### ISSUE TITLE
Secret Sanity

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1000]
Details can be found at https://github.com/equinor/energyvision/wiki/Groups-%E2%80%93-accesses-%E2%80%93-sites

**Comment by SvSven** [comment]
Fixed the issue with the custom actions resolver breaking the i18n plugin in https://github.com/equinor/energyvision/commit/67a7db67499386a387e06ebeeed98be7a6faf166

**Comment by fernandolucchesi** [comment]
@meols
