### ISSUE TITLE
Handle domain level redirects like equinor.co.uk/mariner 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1003]
| Domain  | new |
| ---  | --- |
|equinor.co.uk/mariner	 |	/energy/mariner |
| equinor.co.uk	| /where-we-are/united-kingdom |
| equinorpensjon.no or statoilpensjon.no | /no/om-oss/equinor-pensjon |
| www.equinor.co.tz or www.statoil.co.tz | /en/where-we-are/tanzania |
|www.equinor.co.uk/mariner | /energy/mariner |
| www.equinor.co.uk | /where-we-are/united-kingdom |
| www.equinor.no | /no |
| equinorventures.com or www.equinorventures.com | /energy/ventures |
| www.h2hsaltend.co.uk or www.h2hsaltend.co.uk | /energy/h2h-saltend |

**Comment by nilsml** [comment]
#1015 will verify this
