### ISSUE TITLE
Add a load more button to the filter lists

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1004]
We are currently showing a lot of checkbox options for the newsroom search filters. In the hooks API, we have the option to add a show more button and limit the visible number of checkboxes to some custom value. I think this will make sense for a better UX.

![Skjermbilde 2022-04-19 kl. 12.05.50.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8982e85e-98bc-430b-aecc-18854ad3855e)

### TODO
- See [example for implementation at Algolia](https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-hooks-dom/src/widgets/RefinementList.tsx)
- Decide which values we should use for each filter type
- Remember a11y

**Comment by nilsml** [comment]
Still wanted/needed?

**Comment by fernandolucchesi** [comment]
> Still wanted/needed?

nope :D
