### ISSUE TITLE
Add the option for a title in the cookie consent component

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1009]
In order to avoid to use a separate text block component for the cookie consent title, it should be possible to add a title in the component itself to avoid spacing issues. See /about-us/cookie-policy

![Skjermbilde 2022-04-20 kl. 15.51.38.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/734f6e57-a4d1-4a01-b204-21cfa8af0017)

![Skjermbilde 2022-04-20 kl. 15.56.58.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/cf2911f9-efd2-46e7-bcb1-8189bbb8c459)

**Comment by fernandolucchesi** [comment]
Looking good @bhavi25 ! 👍

**Comment by bhavi25** [comment]
@meols @jorgol This is available in https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com 
Can any of you review this?

**Comment by meols** [comment]
@bhavi25 - thanks, looks good :smile:
