### ISSUE TITLE
Add DNS redirects to middleware

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1015]
```
    {
      from: 'equinor.co.uk/mariner',
      to: '/en/energy/mariner',
    },
    {
      from: 'equinor.co.uk',
      to: '/en/where-we-are/united-kingdom',
    },
    {
      from: 'equinorpensjon.no',
      to: '/no/om-oss/equinor-pensjon',
    },
    {
      from: 'statoilpensjon.no',
      to: '/no/om-oss/equinor-pensjon',
    },
    {
      from: 'equinor.co.tz',
      to: '/en/where-we-are/tanzania',
    },
    {
      from: 'statoil.co.tz',
      to: '/en/where-we-are/tanzania',
    },
    {
      from: 'equinor.no',
      to: '/no',
    },
    {
      from: 'statoil.com',
      to: '/en',
    },
    {
      from: 'equinorventures.com',
      to: '/en/energy/ventures',
    },
    {
      from: 'h2hsaltend.co.uk',
      to: '/en/energy/h2h-saltend',
    },
```

**Comment by SvSven** [comment]
Looks to be working quite nicely 👍

**Comment by nilsml** [comment]
@meols go through the list of urls and verify

**Comment by nilsml** [comment]
Test with http, https and www

**Comment by padms** [comment]
@meols  equinor.ca and equinor.nl are not addressed from this list 
https://statoilsrm-my.sharepoint.com/:x:/g/personal/padms_equinor_com/EWsP-MAxwo1EiGhKjbyPpCIBUTg-FAEbbiaPYAKnmoEixw?e=k72Lbu

**Comment by meols** [comment]
@fernandolucchesi @padms - thanks, I've tested and have some comments:
statoilpensjon.no - is not redirected (to /no/om-oss/equinor-pensjon)
equinor.nl - redirect to home page can be removed
equinor.ca - please create a redirect to /where-we-are/canada

**Comment by padms** [comment]
@meols  Can we ignore statoilpensjon.no?

**Comment by meols** [comment]
@padms - I think we should keep statoilpensjon.no, as I wouldn't be surprised if retired people still think of the company as Statoil.

**Comment by fernandolucchesi** [comment]
> @meols Can we ignore statoilpensjon.no?

It can be ignored.
