### ISSUE TITLE
Allow possibility to choose link style?

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#1017]
Should it be possible to override the button style for a CTA? On some pages there are several text components with download links , one or several. Today it looks a bit weird that some of them are a button (singular) while others a link style. See attached screenshot

![Skjermbilde 2022-04-21 kl. 13.25.30.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/e58701ff-d504-475d-a692-a185e8ed6a7f)

Conclusion: Yes, we need to able to override the style from within Sanity studio. It's not as simple as creating a rule like "If it is a download, it should be displayed as a link" as investigation has showed that the use cases is mixed. However, this should only be used in the cases where several text blocks with links and downloads follow each other to avoid confusion for the end user with different designs for the links.

### Acceptance criteria
- Should be able to override the default style from Sanity studio for the single c2a
- The use case should be described

**Comment by BirteThornquist** [comment]
Also check this page: https://www.equinor.com/sustainability/impact-assessments

**Comment by wenche** [comment]
@BirteThornquist  Available in the dev environment to test. And now we need to solve the challenge for a good and descriptive description text

**Comment by BirteThornquist** [comment]
@wenche What about "You can override the default button style to link style. This can only be done if you have one link, and should be used with caution."

**Comment by nilsml** [comment]
LGTM

**Comment by wenche** [comment]
FYI @meols  New option added for overriding the button style for a single link. Available in preprod

**Comment by meols** [comment]
Thanks @wenche
