### ISSUE TITLE
Too little space around the "Array of text and icon" component

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#1018]
Some places there is not enough space. Like the following screen example:

![Skjermbilde 2022-04-21 kl. 13.54.58.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/2e644cb1-4a4f-485a-9ea7-9ba44f421f98)

**Comment by BirteThornquist** [comment]
@satyendra900 The top/bottom space is set to 3XL for the array of text/icon component. Let's try to increase to 4XL.

**Comment by satyendra900** [comment]
@BirteThornquist Done! Please check.

**Comment by BirteThornquist** [comment]
@satyendra900 Looking good to me!
