### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#102]
We need to figure out which license we should use and if we can do it open source. EDS uses MIT license.

Things to do:

- [x] Discuss, evaluate and agree upon open source or not
- [ ] Add LICENSE.md at root of the repository

**Comment by nilsml** [comment]
Any word from Thorvald @wenche?

**Comment by wenche** [comment]
Thorvald recommend to use [how we work](https://github.com/equinor/it-professional-network/blob/master/doc/open_source/code_of_conduct/how_we_work.md) and name it Code of conduct.
