### ISSUE TITLE
Preview for unpublished news does not work

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1021]
The middleware for redirecting `/news` to `/news/archive` has broken the preview for unpublished news articles - we need to account for draft documents in this function somehow.

**Comment by SvSven** [comment]
Added some checking for preview mode to the logic, and it will now check for draft documents if preview mode is enabled - which should solve the problem.

Interestingly enough this seems to have made it less complex in the process, which is nice.

**Comment by nilsml** [comment]
@jojog007 to retest and confirm this
