### ISSUE TITLE
As a stakeholder I need to be able to view content before it has been published in the web so that I can review it

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1029]
Drafts should not be publicly accessible outside of the studio. How can the editors send links to stakeholders for content that is in draft without exposing all draft content to the public 

## Acceptance criteria
1. Preview should still work for all documents / translations
1. Editors should be able to easily get a shareable link to share with stakeholders

**Comment by meols** [comment]
@padms - please specify which link to unpublished pages we can share with stakeholders (if this is for me to test)

**Comment by padms** [comment]
@meols You can pick any draft document and click on "Preview" tab, there is a button at top right corner like this ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/cf2966dc-51c8-48cd-8e69-bc82cc19d769) which will copy the shareable url to clipboard.

**Comment by fernandolucchesi** [comment]
@meols for example: https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/news;464977d8-9ef2-4e8e-b736-1ecdf8715b55%2Cview%3Dpreview

**Comment by meols** [comment]
Thanks @padms and @fernandolucchesi - happy that this is solved! :smile:

**Comment by fernandolucchesi** [comment]
> Thanks @padms and @fernandolucchesi - happy that this is solved! 😄

As a "bonus" there will be no need to click on the "Open Preview" menu button to make the preview tab work properly ;)
