### ISSUE TITLE
Add missing security headers

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1030]
Add

- [x] X-DNS-Prefetch-Control
- [x] Strict-Transport-Security
- [x] X-XSS-Protection
- [ ] X-Frame-Options
- [x] Permissions-Policy
- [x] X-Content-Type-Options
- [x] Referrer-Policy
- [ ] Content-Security-Policy

**Comment by nilsml** [comment]
Please state in the issue what header we are adding and how to test @fernandolucchesi

**Comment by wenche** [comment]
Since the webs are used for the preview in Sanity it is not possible to add the  `X-Frame-Options`

**Comment by wenche** [comment]
[Google Tag manager](https://developers.google.com/tag-platform/tag-manager/web/csp)
[Algolia](https://www.algolia.com/doc/guides/security/security-best-practices/#content-security-policy)
[Siteimprove](https://help.siteimprove.com/support/solutions/articles/80000448448-adding-siteimprove-analytics-javascript-to-your-website#CSP)
[Cookiebot](https://support.cookiebot.com/hc/en-us/articles/360018907220-Cookiebot-and-Content-Security-Protocol-CSP-)

**Comment by wenche** [comment]
Waiting for feedback from SEO Thomas

**Comment by wenche** [comment]
Perhaps we shouldn't use `style-src-elem` and `script-src-elem` if it's bleeding edge
![Skjermbilde 2022-05-02 kl. 12.30.53.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/60923c79-48bf-422a-93b0-63c58eae420a)

**Comment by wenche** [comment]
Still waiting for feedback from the SEO team and also we decided to move to the new cluster before we actually turn on CSP

**Comment by fernandolucchesi** [comment]
For the issue with the tag manager: https://developers.google.com/tag-platform/tag-manager/web/csp

**Comment by wenche** [comment]
This is now in production.

I have created three new issues for remaining tasks that could be improved at some point (#1110 #1109 #1108) but the work that is already done should be more than enough for the time being.
