### ISSUE TITLE
infinite crash loop when cookiebot script is blocked

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1033]

**Comment by SvSven** [comment]
If Cookiebot was blocked by the client, it would cause an infinite client error loop which crashed the site. This was because every time the path updated, it would attempt to run the Cookiebot script on the window object, which did not exist.

I have added some additional checks/error handling to prevent the crash loop from happening: https://github.com/equinor/energyvision/commit/de55554271b1ebe17a9db04970c16d973f5eefd5

**Comment by SvSven** [comment]
This can be tested by blocking Cookiebot. I did that using the Ghostery extension and pressing the magical "Restrict website" button. Tested it in Vivaldi since we got a bug report form someone using that browser specifically, but it probably behaves the same in other browsers and other extensions that can/do block Cookiebot.

**Comment by wenche** [comment]
LGTM :thumbsup:
