### ISSUE TITLE
Add localization switch and localization head tags to archived news

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1037]
For more context: #994

**Comment by fernandolucchesi** [comment]
Hi @bhavi25, I left some comments for you, please check :)

**Comment by fernandolucchesi** [comment]
Hi @meols @jorgol, can you please check this one?
Now archived news also contain the language switch: https://web-global-test-equinor-web-sites-test.c2.radix.equinor.com/en/news/archive/sale-tommeliten-king-lear

**Comment by meols** [comment]
@fernandolucchesi - thanks, great! :thumbsup:
