### ISSUE TITLE
Issues with news publishing

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1038]

**Comment by meols** [comment]
When publishing the first "real" news today Tor discovered that the visible published time was the created time (06:27) and not the real published time (08:00) as expected. Custom date was not used.

**Comment by fernandolucchesi** [comment]
The problem with custom date being erroneous set was caused by the field rounding the value to 15 minutes intervals. This has now been updated to 1 minute instead. 

As for:

> When publishing the first "real" news today Tor discovered that the visible published time was the created time (06:27) and not the real published time (08:00) as expected. Custom date was not used.

I finally understood the misunderstanding. The created time (06:27) is shown in Preview only, because the news has not yet been published and therefore a "real published time" does not exist yet. However, once the article is published, the correct published time will be used.

**Comment by fernandolucchesi** [comment]
@meols can you take a new look at this issue? :)

**Comment by fernandolucchesi** [comment]
Webhook for newsletter distribution was also updated

**Comment by fernandolucchesi** [comment]
@SvSven can you test this one?

**Comment by padms** [comment]
@fer Please update this in the webhook for news distribution too

**Comment by SvSven** [comment]
https://github.com/equinor/energyvision/commit/edd7549117b2d262c8920504fdab777898c7c5ea#diff-e4a2be1e4cfc7de2ee5357795a66a848a3b78819c23cf736e23ed729e9d4b721R28

Not an important point here, but something to do at one point: we should use a const for the API version, both in the studio as well as in the web.

Other than that it works and looks good to me ✅

**Comment by fernandolucchesi** [comment]
@meols, can you please review this?

**Comment by meols** [comment]
@fernandolucchesi - seems like the Norwegian version gets the same published date as the English one. Is it possible to avoid that? https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/test-16:15

**Comment by fernandolucchesi** [comment]
@SvSven, @nilsml can you check this please?

**Comment by fernandolucchesi** [comment]
@meols can you test this now?

**Comment by jorgol** [comment]
@fernandolucchesi This seems to work now for news, but not for local news (tested on global test site)

**Comment by fernandolucchesi** [comment]
@jorgol the same logic is applied to localNews, can you test it again?

**Comment by fernandolucchesi** [comment]
@meols can you test this one since Jørgen is on holidays?

**Comment by meols** [comment]
@fernandolucchesi - it doesn't seem to be working for either news or local news. Tested with this news (without using custom date): https://web-global-test-equinor-web-sites-test.c2.radix.equinor.com/news/friday-news-test
The English version was published 14:35 and not updated or republished after that. It still got a modified time 14:43, when the Norwegian version was published.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/7ead5a6b-afa7-4c61-9043-8c1a923d81f8)
The Norwegian version was created 14:39 (not 14:35, when the English version was published) and published 14:43 for the first time (and not modified at 14:43).
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/f434f1f4-7881-4ea8-ab54-0032ddcf5b01)

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - it doesn't seem to be working for either news or local news. Tested with this news (without using custom date): https://web-global-test-equinor-web-sites-test.c2.radix.equinor.com/news/friday-news-test The English version was published 14:35 and not updated or republished after that. It still got a modified time 14:43, when the Norwegian version was published. ![image.png](https://camo.githubusercontent.com/7a0a3ed01223c9c3e1836aa8ae92cb5e82221e37ffd0d8887741f43d2881a39a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f37656164356136622d616661372d346336312d393034332d386331613932336438316638) The Norwegian version was created 14:39 (not 14:35, when the English version was published) and published 14:43 for the first time (and not modified at 14:43). ![image.png](https://camo.githubusercontent.com/61476842f7e884fa3abf137744f5903d049fbaaf5903310e1e50b698e8d1fd0a/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f66343334663166342d373838312d346561382d616235342d303033326464636635623031)

I found a problem with the test studio :( have fixed it now, can you please try again?

**Comment by meols** [comment]
@fernandolucchesi I have tested again with this news https://web-global-test-equinor-web-sites-test.c2.radix.equinor.com/news/news-test-tuesday
- The English page was created 09:12 and published 09:15 (and not updated/published after that).
- The Norwegian page was created 09:20 and published 09:27
- When the Norwegian page was published 09:27, the English page got a modified date/time at the same time - that it shouldn't have
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/4c746342-6f68-4690-ad4d-b018d1129a9e)  
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/31d7b7fa-acf2-466e-974a-c222dd03d255)

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi I have tested again with this news https://web-global-test-equinor-web-sites-test.c2.radix.equinor.com/news/news-test-tuesday
> 
> * The English page was created 09:12 and published 09:15 (and not updated/published after that).
> * The Norwegian page was created 09:20 and published 09:27
> * When the Norwegian page was published 09:27, the English page got a modified date/time at the same time - that it shouldn't have
>   ![image.png](https://camo.githubusercontent.com/c1309eb28f98d42b466a7e6bde5fea509c6808eeeb0b852dee28ddf991468c43/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f34633734363334322d366636382d343639302d616434642d623031386431313239613965)
>   ![image.png](https://camo.githubusercontent.com/39bc94b7fff1611642799f9bb056674e70654dc640d83168b56fd1333d6fc920/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f33316437623766612d616366322d343636652d393734612d633232326464303364323535)

I will move this to on hold. Atm there is a limitation with sanity internationalisation plugin to get the updatedAt right: https://equinor.slack.com/archives/C01A4BGNRMJ/p1658924207824719

**Comment by fernandolucchesi** [comment]
@meols, talked to sanity about this and the issue with the "updatedAt" field is already existent as of today, even when we use the custom date. 

The way around it, is to publish the Norwegian document (or any other translation) right after the english document is published for the first time. This issue is not related to the publication date time, but a fault on how sanity deals with translations.

They are aware of this and a fix will come at some point in a future upgrade.

**Comment by meols** [comment]
Thanks @fernandolucchesi - then let's wait and just close this one :smile:
