### ISSUE TITLE
update react & react-dom to v18

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1041]
React v18 has a number of changes we should review before upgrading: https://github.com/facebook/react/releases/tag/v18.0.0

**Comment by nilsml** [comment]
Let's look into this task to see how big it is.

**Comment by SvSven** [comment]
Might be smart to wait until EDS has updated, to avoid any potential conflicts there.

**Comment by SvSven** [comment]
There are some updates we need to do to the testing setup, nothing major: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html

But in addition to that the `next build` fails due to the algolia hooks package:

```
> Build error occurred
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './server.js' is not defined by "exports" in /workspaces/energyvision/web/node_modules/.pnpm/react-instantsearch-hooks-server@6.23.4_f9eac4bda68a2fd42ea7c9e36c9c6077/node_modules/react-dom/package.json imported from /workspaces/energyvision/web/node_modules/.pnpm/react-instantsearch-hooks-server@6.23.4_f9eac4bda68a2fd42ea7c9e36c9c6077/node_modules/react-instantsearch-hooks-server/dist/es/getServerState.js
```

There is an issue for it on the algolia instantsearch repo with a suggested temporary fix: https://github.com/algolia/react-instantsearch/issues/3453

But I would suggest we wait a bit longer for Algolia to push out an update.

**Comment by SvSven** [comment]
Algolia should now be ready for React 18 from version 6.25.0 and above: https://github.com/algolia/react-instantsearch/releases/tag/v6.25.0

**Comment by SvSven** [comment]
Looks to all be fine 👍
All the fragments around the `{children}` is a bit annoying but it is what it is.
