### ISSUE TITLE
Magazine template on Sanity

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1042]
Placeholder for magazines

Topic page schema could be used as for the MVP
Should have it is own menu item
Should include Subscription (to be handled in #1147)

For the future we will need a custom template (designed by an UX)

**Comment by fernandolucchesi** [comment]
@SvSven can you take a look at what has been done here? :)

**Comment by SvSven** [comment]
Missing the preview and 'connected routes' tabs on the Magazine document in the Studio.

I'm also not seeing the Text content rendered in the Magazine landing page.
Similarly the components don't seem to be rendering for the magazine documents:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/e5989fae-949a-4113-9859-e15e0a812c08)

**Comment by jorgol** [comment]
Looks good. But do we have a solution for displaying them on /magazine and /magasin ? Or did we agree to display/promote them manually?

**Comment by fernandolucchesi** [comment]
> Looks good. But do we have a solution for displaying them on /magazine and /magasin ? Or did we agree to display/promote them manually?

Request will be solved on #1148

**Comment by fernandolucchesi** [comment]
Adjust feature flag
