### ISSUE TITLE
Copy/paste functionality in Sanity

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1045]

**Comment by fernandolucchesi** [comment]
#360

**Comment by fernandolucchesi** [comment]
this is finally released on sanity 3.5 o/

**Comment by padms** [comment]
@fernandolucchesi finally!!

**Comment by padms** [comment]
@meols Each field has a menu option that appears on hover. To copy the field click on copy field button, go to the document where you want to paste it, click on paste field from the menu of the corresponding field.
