### ISSUE TITLE
Small text jumping outside margins on news template

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1046]

**Comment by meols** [comment]
@nilsml - forgot to mention this urgent issue in the meeting today - just added it on slack yesterday; When testing a news similar to the quarterly results news article, we seethat small text is jumping outside of margins to full width: https://web-global-development-energyvision-dev.radix.equinor.com/news/equinor-third-quarter-2021-results We will use small text the same way in the news article on Wednesday 4 May. Tested on secret site and dev with both studio and web, and on global site preview with the same result.

**Comment by nilsml** [comment]
@meols  Fixing this will require deploying one more time to production though, and that may include the non-finished friendlycaptcha implementation. Correct me if I am wrong @padms

**Comment by meols** [comment]
@nilsml @padms - if another deploy will be required next week we should avoid it. I have tested a (probably not optimal) workaround with using subscript or superscript to get small text.

**Comment by SvSven** [comment]
I've fixed the issue and is available on https://web-global-development-energyvision-dev.radix.equinor.com/news/equinor-third-quarter-2021-results

It would require another deploy yes, but we may be able to cherry pick which stuff we deploy @nilsml ?

**Comment by meols** [comment]
Thanks @SvSven - looks good :thumbsup:
