### ISSUE TITLE
Crude oil shouldn't display on the front page or in the newsroom

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1049]
The crude oil is a workaround for newsletters.

We need to discuss the solution here, but something like
- Add a switch in Sanity -> only for newsletter/hide from web or something like that
- Delete it from all Algolia indexes
- Update the Sanity query for both the web and the search to not fetch documents with the hide switch set to `true`
- Filter from the promote news card list (and filter from the dropdown of options for selectable news in the Sanity promote news component?)
- Filter from latest news

EDIT: See discussion on Slack https://equinor.slack.com/archives/C01MU3H6G0Y/p1654168566352739

Perhaps we could reuse the crude oil subscription type since the ID for this is something we control in code and not something publishers can change?

**Comment by fernandolucchesi** [comment]
Remove crude oil tags from algolia

**Comment by padms** [comment]
Articles related to crude oil assays are filtered based on the subscription type and not by the tag name. 
The news promotion in front page will not show crude oil assays unless "Crude oil assays " tag is added to the news promotion.

**Comment by fernandolucchesi** [comment]
Left a comment [on latest commit](https://github.com/equinor/energyvision/commit/06208b2b81ff9e3fa950a7fea831da7165ac310e)

**Comment by padms** [comment]
Updated query to index news with no tags defined.

**Comment by fernandolucchesi** [comment]
@meols, if a news has two tags: "Crude Oil" and "General News", should we index it or not?

**Comment by meols** [comment]
@fernandolucchesi - if a news has both these topic tags it should be indexed. Then it will have the general news **subscription** tag, and be an article around crude oil. A news with crude oil subscription tag (for crude oil assay updates) will never have a general news topic tag.

**Comment by padms** [comment]
Reverted.
