### ISSUE TITLE
Issues with Next.js and prefetching with the language switch

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1052]
With next/link, Next.js will always prefetch on hover even with prefetch=false. [See related discussion.](https://github.com/vercel/next.js/discussions/11793) This seems to be causing issues with our localisation switch. Example:

On a Norwegian page, say /no/om-oss, hover the English equivalent. Next.js will then prefetch the content /en/about-us.json but also, for unknown reasons, also prefetch /no/about-us.json. The latter will result in 404 since we use translated URLs.

It's not necessarily a lot we can do with this, but we should at least look more into it and be 100% that it is not something on our end. If this is verified, we should consider to open a bug report on Next.js github.

**Comment by fernandolucchesi** [comment]
This was fixed in newer versions of nextjs. Hence closing it.
