### ISSUE TITLE
Add option to restrict documents from being index by Algolia

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1053]
There are some pages that should not show up in the search results/newsroom. We don't currently have a way of filtering these out.

Suggest approach:
- Add a switch field in Sanity on the documents called `shouldIndex` or `includeInSearch` or similar
- Field should default to true
- Potentially restrict access to this field to specific roles
- Add filtering to search indexing code to skip documents where the value is set to false

We need to also ensure that this is backwards compatible.

**Comment by wenche** [comment]
Use case example #1049

**Comment by SvSven** [comment]
I have added a field `excludeFromSearch` to the schema which defaults to `false` - and have added this field to the `news` and `routes` schemas.
Decided it would make more sense to actively exclude documents instead of what was suggested in the issue description.

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/792a71b2-5da2-4205-955b-5776c30a8556)

Have also updated the groq queries for the search indexer to exclude documents based on this field.
The groq query is set to `&& excludeFromSearch != true` - this is due to backward compatibility as existing documents don't get updated when a new field is added to the schema. For existing documents this value will simply be `null`; so we can't set it to `&& excludeFromSearch == false`

**Comment by fernandolucchesi** [comment]
Looks good to me! 👍

**Comment by fernandolucchesi** [comment]
@jorgol

**Comment by jorgol** [comment]
Doesn't seem to work when I set the Johan Sverdrup route to be excluded. It still shows up in search. Does it only work for new documents?

https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/topicRoutes;englishUkRoutes;topLevelRoutes;b6c76ce4-d4c8-43c9-85f1-05ef639d392a

https://web-global-test-equinor-web-sites-test.c2.radix.equinor.com/search?query=johan+sverdrup

**Comment by SvSven** [comment]
Looks like documents that have already been published (and indexed) won't get removed by this. We made an issue to handle that #1197

For now this will only work when you create a new route or news article then.

**Comment by fernandolucchesi** [comment]
@SvSven, can we close this one?

**Comment by fernandolucchesi** [comment]
Closing it :)
