### ISSUE TITLE
Look into tree shaking with the component folder

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1059]
With `next build` we see that the `First Load JS shared by all` is pretty big, 173kB at the moment of writing. By analysing the client side bundle, it seems like every component from the component folder is added to  the bundle. This might be because of missing tree shaking with the barrel file approach in the component folder. Also [possible related](https://stackoverflow.com/questions/64485105/all-nextjs-pages-have-almost-the-same-js-bundle-size).

We should look into this and see if there's room for improvements.

 ![Skjermbilde 2022-05-04 kl. 09.32.03.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d17853cb-df5d-485d-92a7-f345e70c1f0e)

![Skjermbilde 2022-05-04 kl. 08.27.27.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/efebe7c4-1f2b-40d3-847d-a43ad2958dba)

**Comment by nilsml** [comment]
Related to #1878
