### ISSUE TITLE
Improve search result for editors within in Sanity

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1065]

**Comment by meols** [comment]
When editors search in Sanity search result list contains an unordered (?) list of topic pages, page routes, tags, redirects, files, news, local news. How can that list be improved? Understand that we are dependent on Sanity for this task, but is it possible to at least prioritize topic pages as the top result and group similar content types?

**Comment by fernandolucchesi** [comment]
Tags, Redirects and Files should now be listed at the bottom of the search list

**Comment by wenche** [comment]
LGTM :thumbsup: I guess it's on purpose that we don't add anything explicit for events, landing pages, menu and so on in the searchweight? @fernandolucchesi

**Comment by wenche** [comment]
@meols  You can test this in https://studio-global-equinor-web-sites-preprod.c2.radix.equinor.com/

**Comment by fernandolucchesi** [comment]
> 

that is correct, by doing this we override sanity's magic, I preferred to let sanity sort the way it finds best for these

**Comment by meols** [comment]
Thanks @fernandolucchesi and @wenche :smile:
