### ISSUE TITLE
Home page template

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1067]

**Comment by meols** [comment]
Create a home page template. Discussed briefly with @BirteThornquist

**Comment by fernandolucchesi** [comment]
TBD in the workshop in the 27th

**Comment by fernandolucchesi** [comment]
This issue needs to be its own mini-project. It is not a simple since it involves branding / UX / etcs.

**Comment by meols** [comment]
@fernandolucchesi - closing this one for now. We may revisit the issue at a later point
