### ISSUE TITLE
Update runbook on ghcr images housekeeping

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1070]
In order to clean up images on ghcr we need some way of knowing which images are in use in each environment. All images not in use + a few versions can be deleted.

Need to find a good solution that also works with rollback functionality.

**Comment by fernandolucchesi** [comment]
Include this in the runbook (if not yet)

**Comment by nilsml** [comment]
Not sure how to solve it with rollback. Depends on how many versions you want to go back. For now I believe we are keeping the last three versions.

Runbook probably needs to be updated still.

**Comment by fernandolucchesi** [comment]
Updated ✅ 

> 3.1.7.3 Cleanup of Github Container Registry 
> 
> In the energyvision repository there is a GH action called [ghcr-cleanup.yaml](https://github.com/equinor/energyvision/blob/main/.github/workflows/ghcr-cleanup.yaml). This workflow is run once a day, at midnight, and it will clean up all non-labeled images older than a week from GHCR. To prevent deleting useful images (during rollback scenarios for example) we always keep the latest 5 images regardless of their age. The number of images kept can be configured in the action itself.

https://statoilsrm.sharepoint.com/:w:/r/sites/CCOMEquinor.comCMSevaluation/_layouts/15/Doc.aspx?sourcedoc=%7B70F86F5B-895A-4BFC-8AB8-DF631EC7F881%7D&file=EQUINOR_DOT_COM_Runbook.docx&action=default&mobileredirect=true

**Comment by nilsml** [comment]
Looks good. Closing this issue.
