### ISSUE TITLE
rollback functionality

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1071]
**In order to easily roll back to previous version we need a GH Action where site and version can be selected**

## Acceptance criteria
1. Version can be selected among previous valid versions for site
1. Rolling back will switch to older image for selected site
1. Must work with #1070

**Comment by nilsml** [comment]
There are functions in the API that we can use to list all deployments and extract image names from. We should make feature requests for the features we use that does not exist in the CLI so that we can use that instead in the future. API is not meant for direct usage.

First we need to find out what a first version of the rollback feature is.

**Comment by nilsml** [comment]
Will spend todays playground working on this task 💪

**Comment by nilsml** [comment]
## Proposed MVP

1. Github action that rolls back __one__ site or studio to a previous version
1. Select site using a dropdown (like we do for PROD deployment)
1. Input field for commit sha
1. Action tries to find image for the commit sha and replaces the running pod with a new based on this image

## Future goal
Use CLI (or API) from Radix to find the previous deployment and roll back to that.

**Comment by nilsml** [comment]
Action for web sites implemented. Needs testing.
Studio left to do.

**Comment by nilsml** [comment]
Now both studio and web is implemented, but not tested. Need to figure out a way to test these in a safe manner.

**Comment by SvSven** [comment]
Can we use this on a different environment, for example global-development to test?

**Comment by SvSven** [comment]
We tried out the rollback yesterday for a minor issue; seemed to work for the web, but not for the studio.

```
ERR_PNPM_NOTHING_TO_DEPLOY  No project was selected for deployment 18
```

**Comment by fernandolucchesi** [comment]
Rolling back studios is working now, thus closing this.
