### ISSUE TITLE
Fix og:image for topic content

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1074]
The introduction of `isDecorative` broke the og image selection logic since it's not enough to check for the existence of an openGraphImage when it has default isDecorative.

EDIT: It's just an issue for the topic page template

**Comment by wenche** [comment]
@SvSven  Ref. Slack conversation!

**Comment by SvSven** [comment]
Looks good to me and also works ✅
Need to make sure we keep this initialValue stuff in mind for other places as well
