### ISSUE TITLE
Unexpected token in JSON errors

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1075]
We see a lot of issues with the json reponse in the Radix console. We should look into this issue

```
An error occured while parsing archive news data FetchError: invalid json response body at https://envis-legacy.azureedge.net/equinor-archive-content/no/news/archive/2009/05/19/downloads/StatoilHydros%20generalforsamling%202009_protokoll%20med%20vedlegg.pdf.json reason: Unexpected token  in JSON at position 0
    at /opt/app/web/node_modules/.pnpm/next@12.1.5_react-dom@17.0.2+react@17.0.2/node_modules/next/dist/compiled/node-fetch/index.js:1:49606
    at dynatraceOnServiceExecutionIndicator (/opt/dynatrace/oneagent/agent/bin/1.237.258.20220428-180124/any/nodejs/nodejsagent.js:2916:20)
    at Object.b.safeInvoke (/opt/dynatrace/oneagent/agent/bin/1.237.258.20220428-180124/any/nodejs/nodejsagent.js:2970:41)
    at /opt/dynatrace/oneagent/agent/bin/1.237.258.20220428-180124/any/nodejs/nodejsagent.js:7746:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async parseResponse (/opt/app/web/.next/server/pages/news/archive/[...pagePath].js:349:22)
    at async getStaticProps (/opt/app/web/.next/server/pages/news/archive/[...pagePath].js:363:22)
    at async Object.renderToHTML (/opt/app/web/node_modules/.pnpm/next@12.1.5_react-dom@17.0.2+react@17.0.2/node_modules/next/dist/server/render.js:488:20) {
  type: 'invalid-json'
```

**Comment by SvSven** [comment]
Most of these seem to be request for images; thumbnails in particular. I checked some of the archived news content in Azure and I don't see any links to it, so my theory is that this is something that gets automatically requested by one of the JS libraries for the AEM news.

I've added a simple guard conditional to the `fetchArchiveData` function that checks if the path includes a `.` and then returns false if it does. That should prevent these invalid requests made to Azure as well as an attempt to parse the response (which is what is causing this error). I don't _think_ this should cause any unwanted side-effects.

**Comment by wenche** [comment]
And you did of course double check that none of the legal paths include a `.`? :)

LGTM if that is the case. Not the most elegant piece of code, but whatever floats the boat

**Comment by SvSven** [comment]
I'm not 100% sure on that, so yes that is a concern. Initially I wanted to check specifically for if the path ends with a file extension, but then we need to hard-code a bunch of known file extensions. That could work, but this seemed a bit more "catch-all".

I did have a look in the blob storage before going with this approach, and I _think_ that none of these URLs would contain a period character; this code should only run to fetch archived news from Azure in any case, so in theory if a non-archived news request is made from this function it should return a 404 regardless - this just skips the fetching part for that I guess.

**Comment by wenche** [comment]
OK, nice 👌
