### ISSUE TITLE
Should we add something to monitor uptime of the websites

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1077]
We should discuss with the Radix team if we need some something to monitor the availability of the websites. Examples for such services could be Freshping or Pingdom or another approach

**Comment by fernandolucchesi** [comment]
Probably #1134

**Comment by nilsml** [comment]
I think this should be prioritised, and would also add to create dashboard for monitoring the health of the different sites.

**Comment by nilsml** [comment]
We need to prioritise this issue. I think we should also create a dashboard for monitoring the health of our sites.

**Comment by fernandolucchesi** [comment]
@nilsml I'd say we can close this, for ref: #1357 
What do you think?
