### ISSUE TITLE
Evaluate readme files

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1080]
We haven't looked at/updated our readme files in quite a while. We should go over them and see what needs to be changed.

**Comment by SvSven** [comment]
@nilsml @fernandolucchesi @padms @millianapia @bhavi25 

I have updated the following readme files:

- main: https://github.com/equinor/energyvision/blob/main/README.md
- web: https://github.com/equinor/energyvision/blob/main/web/README.md
- studio: https://github.com/equinor/energyvision/blob/main/studio/README.md
- legacy: https://github.com/equinor/energyvision/tree/main/legacy/README.md

Don't think we have to do an extensive review, but feel free to have a look and see if everything looks ok or if anything is missing.

**Comment by millianapia** [comment]
Looks very good!
