### ISSUE TITLE
Install the Siteimprove CMS plugin

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1083]

**Comment by meols** [comment]
We would like to have the Siteimprove CMS plugin installed, to e.g. enable us to go to the correct page in Sanity from an issue, with a click on one button. We've had that from AEM, so currently it's not working for Sanity. https://help.siteimprove.com/support/solutions/articles/80000863887-how-to-install-the-siteimprove-cms-plugin ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/cfc751b5-126a-4eb8-9262-2ed61c472f8c)

**Comment by wenche** [comment]
Unfortunately Sanity is not on the list for [available CMS plugins on the SiteImprove page](https://www.siteimprove.com/integrations/cms-plugin/), so I don't think that is possible. AEM on the other hand is a premium plugin collaborator @meols

**Comment by meols** [comment]
OK - thanks for checking @wenche
