### ISSUE TITLE
Missing studio preview for menus

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1086]
The preview is important for when deleting routes that are still referenced in the menu:

![image.png](https://images.zenhubusercontent.com/619cb66996a338308e2dd0b8/5d23ae7c-585a-4475-9cbe-0065b68fed8a)

**Comment by wenche** [comment]
It will now look like this instead

![Skjermbilde 2022-05-16 kl. 13.23.38.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ef497627-6650-4479-b99f-9e8b16f23e64)

LGTM :thumbsup:
