### ISSUE TITLE
Upcoming update for the contact us form

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1087]

**Comment by meols** [comment]
We have received a request for an update to the Contact us form.
We need to add a new category for Human rights in the drop down list, and are waiting for the correct text and which assignment group in s@e that shall receive human rights requests. When we have the correct info (text + assignment group), how big a task is this, and is it possible to prioritize it?

**Comment by meols** [comment]
@padms @fernandolucchesi - we will get the new texts (no/en) for the dropdown and a the related link to the right place in serviceNow early next week. This update need to be prioritized.

**Comment by padms** [comment]
Added the "Human Rights Information Request" option to Category dropdown and based on the category the catalog identifier is changed in the service-now URL.

**Comment by wenche** [comment]
@meols you may test, see URL from Padmaja above

**Comment by meols** [comment]
Thanks @wenche - I've tested and submitted a ticket and asked to get a confirmation that it goes to the right assignment group in ServiceNow.
I see that this change is already published in the form on equinor.com - with English text in the Norwegian form. What is this text called in text snippets? I cant find it (immediately).
Also, I don't understand the process of testing and launching updates, @fernandolucchesi @nilsml  
Isn't the process to test, confirm and then launch?

**Comment by wenche** [comment]
@meols Yes, you are completely right, this is far from an optimal process :/ 

We will do a release when everybody is at work, and it will then be available in Sanity. The Sanity change is currently just in preprod

**Comment by meols** [comment]
@wenche - still don't understand the process, as the form update was visible on equinor.com before I had looked at it or tested it anywhere. The reason why I looked at the .com page at all was that my "customer" had noticed the change and closed my task for this in a request in serviceNow with the comment that she saw that the update in the form was done.

**Comment by nilsml** [comment]
@meols this time the reason for deploying to production before you had verified everything was because of serious problem we have been experiencing (#1128). Then bypassed the process to try fixing this.

In the future we should implement feature toggling so that we can turn off new untested functionality if we have to do emergency deployments.

**Comment by meols** [comment]
Thanks for clarifying @nilsml
