### ISSUE TITLE
Add newsroom and search(?) to the sitemap

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1088]
/news and /nyheter are not included in the sitemap.xml

These should be included if the dataset is global.

Question: Should we also include /search? (verify with seo agency - if not, exclude page from robot indexing)

Response from SEO Agency:
`
Google prefer that internal search pages with corresponding results are tagged as noindex - nofollow. They deem it as bad experience to send a user from one search result page to another search result page`

**Comment by nilsml** [comment]
LGTM
