### ISSUE TITLE
Sort promoted event cards by date

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1093]
The promoted events card should be sorted by date. This should be easy enough as we already do this in for example the query for promoted news cards. 

One thing is left to be decided: What should we do about the cards without a date, like the one for not yet scheduled quarterly presentations

### Acceptance criteria
- Cards should be sorted by date, descending order (06.06.2022, 08.09.2022, 01.12.2022)

**Comment by padms** [comment]
Sorted only automatically selected events.
Cards cannot be without a date because event date is required field for events. When the time is not selected the card shows 'to be announced'

**Comment by wenche** [comment]
LGTM :thumbsup:

**Comment by wenche** [comment]
@meols  and Jørgen The events are now sorted by date. This change is not yet available in preprod, but see the attached screenshots to verify
**Before**
![Skjermbilde 2022-05-30 kl. 09.49.23.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/1f632e04-e6c9-4556-98a6-ffe2c91e696e)
**After**
![Skjermbilde 2022-05-30 kl. 09.53.52.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f4c4d1a7-1a6f-446b-afa6-d59227940dd8)

**Comment by meols** [comment]
Thanks @wenche :smile:
