### ISSUE TITLE
Remove polyfill for focus-visible

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1094]
Background: We use a polyfill for focus-visible in the same way as EDS. The focus-visible is a way to solve the problem of adding a visible outline only if you use the keyboard for navigating and not when you click with the mouse.

This feature has a rather [good support by the browsers](https://caniuse.com/?search=focus-visible) now and we should look into to remove it completely and use the browser native solution instead.

**Comment by BorghildSelle** [comment]
Will be done in #2150
