### ISSUE TITLE
Add 50 years celebration page to equinor

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1096]
Should be accessible through /50 slug.
Original project url: https://equinor-50-historier.vercel.app/50
We should not be responsible for its security headers.

**Comment by wenche** [comment]
LGTM :thumbsup: As far I can see :) Nice to do it with rewrite. Do we know for how long this should be available?

**Comment by fernandolucchesi** [comment]
> LGTM 👍 As far I can see :) Nice to do it with rewrite. Do we know for how long this should be available?

About 1 year
