### ISSUE TITLE
MUX integration

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1100]
A MUX component should be created in both studio and the web. 

We can use https://github.com/video-dev/hls.js/ to create our own player component in Next.js

Acceptance criteria:
- [ ] Update documentation in Runbook

**Comment by padms** [comment]
Created Video component in sanity to upload video. 
Created Video component in the web to display the uploaded video ( no tracking).

**Comment by padms** [comment]
@fernandolucchesi Most of the points above are related to the asset being a test asset 

> I wasn't able to delete a video that I have uploaded. ( May be the 
> 
> video you are trying to remove is already deleted after 24 hours.. )
> Video contained this water mark, is this expected? 
> I can't find the video I uploaded in the Mux Interface. (Test asset is deleted after 24 hours)

**Comment by padms** [comment]
@fernandolucchesi Yes it is possible to set up different environments for different datasets.

**Comment by fernandolucchesi** [comment]
Waiting for plan upgrade to continue work

**Comment by fernandolucchesi** [comment]
Discuss with editorial what kind of plan do we need https://www.mux.com/pricing

**Comment by fernandolucchesi** [comment]
Waiting for Terje to come back to proceed with this.

**Comment by fernandolucchesi** [comment]
Contact MUX and investigate how the video count works

**Comment by fernandolucchesi** [comment]
Also waiting for: https://equinor.slack.com/archives/C01A4BGNRMJ/p1659952633026379

**Comment by meols** [comment]
@fernandolucchesi - I have requested youtube numbers from Line: In total 1/8/21 til 1/8/22 = 132,751 views (More than12 sek).
What counts as a view on YouTube? Each time a viewer intentionally initiates the playing of a video on their device and watches for at least 30 seconds, that counts as a view. Pretty simple! If you play your own video, that will be counted as a view.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/201ce25e-596b-4eb3-bf32-415433a4ed37)
