### ISSUE TITLE
Log CSP reports

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1108]
We should add an endpoint for logging CSP reports. If we do this, we will have insights into what potential problems our users are facing. Ideally this should be with a specialised tool like Sentry. Some experiments and an example of this was [removed by this commit](https://github.com/equinor/energyvision/commit/542a05304bd233eabaf9c9eb526b9c88ecb27e49)

**Comment by SvSven** [comment]
We may be able to get a dashboard for this on Dynatrace set up

**Comment by nilsml** [comment]
Dynatrace solves this
