### ISSUE TITLE
Improve CSP headers implementation

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1109]
Look into to further improve the CSP headers. Remember that adding `nounce` might be a rabbit hole, but it could still be worth to look into at some point. The problematic aspects are things like unsafe-inline added because of 3. party tools like cookiebot.

![Skjermbilde 2022-05-23 kl. 12.36.11.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ae0bb965-9409-4a3c-821c-e877f591132e)

**Comment by fernandolucchesi** [comment]
#1108

**Comment by fernandolucchesi** [comment]
Check if still needed

**Comment by nilsml** [comment]
Make a final report on the status. Close this if what we have is good enough.
