### ISSUE TITLE
Events card showing Add to calendar on Norwegian pages

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1111]
### Acceptance criteria

- Should be a text string in text snippets
- Should only be available for the global studio

**Comment by meols** [comment]
The button text Add to calendar is shown in English on Norwegian pages. (I can't find that text in text snippets.)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/a74c67ea-7f6b-49ed-ad98-79c0f8d86496)

**Comment by wenche** [comment]
An improvement would be to group the event related text snippets by a prefix in the title like we do with more or less the rest of the text snippets. And I would have preferred a litte more verbose and descriptive ID for the snippet than `atc` next time. :)

**Comment by fernandolucchesi** [comment]
It should also contain a hidden: !HAS_EVENT logic

**Comment by meols** [comment]
Thanks, looks good @fernandolucchesi @wenche
