### ISSUE TITLE
upgrade rxjs to v7

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1112]
Due to [a problem with the Sanity media plugin](https://github.com/equinor/energyvision/pull/1060#issuecomment-1131589336) we had to downgrade rxjs to v6.

Once this issue has been fixed in the Sanity media plugin, we should upgrade rxjs to v7: https://github.com/robinpyon/sanity-plugin-media/issues/79

**Comment by wenche** [comment]
This is now fixed int the plugin

**Comment by wenche** [comment]
@SvSven I know that I said it worked a couple of weeks ago as well, but now I really think it is OK? I see no runtime crashes on my localhost at least :crossed_fingers:

**Comment by SvSven** [comment]
LGTM 👍

I see they just fixed it by moving it from peerDependency to normal dependency
