### ISSUE TITLE
Fix warning for Algolia SSR with React 18

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1114]
![Skjermbilde 2022-05-25 kl. 10.31.53.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/eb654f1f-6d91-48c1-aca0-e161fed3ec93)

**Comment by wenche** [comment]
I'm unfortunately not able to fix this easily. It also seems to be related to [a reported issue at the Algolia repo. ](https://github.com/algolia/react-instantsearch/issues/3441) The code seems to work fine even with the warning, and the warning is only visible server side, so it will be visible in our Radix logs for the newsroom.

My suggestion will be to move this to `Dependent on others` column, and see if Algolia is able to sort this out. In the meantime, I have changed the code to use `react-instantsearch-hooks-web ` instead of `react-instantsearch-hook` as the newly documented Algolia examples suggest. The main difference is that the web library includes the work in progress React components along with the hooks, so it will create a better foundation for using Algolia components when we continue the work for the newsroom. :)

**Comment by SvSven** [comment]
This is an issue with React 18 and hasn't been fixed upstream yet:

https://github.com/algolia/react-instantsearch/issues/3441

https://github.com/facebook/react/issues/22796

Don't think there's anything we can do on our end with this yet - but it shouldn't cause any issues to have the warning.

**Comment by nilsml** [comment]
Any news about this one @SvSven ?

**Comment by nilsml** [comment]
Someone should have a look to see if it is already fixed

**Comment by fernandolucchesi** [comment]
[InstantSearch] The package `react-instantsearch-hooks` is replaced by `react-instantsearch-core`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
[InstantSearch] The package `react-instantsearch-hooks-router-nextjs` is replaced by `react-instantsearch-router-nextjs`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
[InstantSearch] The package `react-instantsearch-hooks-server` is replaced by `react-instantsearch`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
[InstantSearch] The package `react-instantsearch-hooks-web` is replaced by `react-instantsearch`. The API is the same, but the package name has changed. Please update your dependencies and follow the migration guide: https://www.algolia.com/doc/guides/building-search-ui/upgrade-guides/react/
