### ISSUE TITLE
Commit sha not uniqe enough for images

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1115]
When building Docker images for deployment, the short sha (typically 7 characters) is being used as tag/key. This is unique most of the time, but with a large repository it is no longer unique. We have seen that sometimes image for TEST is tagged with 7 characters and PREPROD with 8 f.ex.

## Proposed solution
Use 12 characters for short commit sha to make unique enough

**Comment by fernandolucchesi** [comment]
LGTM!
