### ISSUE TITLE
50-50 top banner

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#1121]
@fernandolucchesi - these are the specification from @NickHaggerty1  for the first top banner - **50-50 top banner**
FIELDS:
Title H1 (optional)
Subtitle H2 (optional)
Ingress text (optional)
Text link to internal/external pages (optional field) Max 2 links (including download)
Option to download. Editor could have just link. Just download. Nothing (just title and text) or both link and download.
Image: To discuss. Should it be fixed size - set 20 2:1 full width (like Hero image + crop/hotspot) or Fluid like Teaser and adapt to text size.
Background White/slate blue/moss green tint /spruce wood
Phase 2: Should we have option for colour on text? Could editor highlight words or sentences? Rich title/text options

MOBILE:
Should stack with image at the top first and then background
Limit text to just title. (do not display ingress if its featured on desktop)
Link(s) and download options as per desktop

**Comment by fernandolucchesi** [comment]
Moving this back to the backlog since Birte has left the show :(

**Comment by fernandolucchesi** [comment]
Design to be provided soon...

**Comment by SvSven** [comment]
Figma designs: https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=1511%3A0

Notes:
- Drop ingress on mobile
- Imae should always be at the top on mobile

**Comment by NickHaggerty1** [comment]
![50-50 example.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/72ebb33d-3129-47df-841b-bcf489816d5f)

**Comment by NickHaggerty1** [comment]
![50-50 mobile.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/5f757e8e-364e-45a3-b24a-bb33ef0f5533)

**Comment by NickHaggerty1** [comment]
![wide screen 50-50.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/e479b420-8052-4380-b479-5a6d1e83c069)

**Comment by fernandolucchesi** [comment]
Hi @bhavi25, please check my comments

**Comment by fernandolucchesi** [comment]
@bhavi25 left a suggestion for you. Up to you if you want to do it or not :) LGTM ✅

**Comment by bhavi25** [comment]
@NickHaggerty1 50-50 top banner is available for review: 
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/topic-content-test1

**Comment by NickHaggerty1** [comment]
@bhavi25 Looking GREAT. nice work. Tested on desktop and mobile. Just one small comment that we have the image caption and credit fields, but when filled in they dont display on the page (which I think is correct) Should we just hide these two fields? @meols @fernandolucchesi FYI

**Comment by fernandolucchesi** [comment]
> @bhavi25 Looking GREAT. nice work. Tested on desktop and mobile. Just one small comment that we have the image caption and credit fields, but when filled in they dont display on the page (which I think is correct) Should we just hide these two fields? @meols @fernandolucchesi FYI

Fields are now hidden @NickHaggerty1 =)

**Comment by NickHaggerty1** [comment]
@fernandolucchesi I would say this approved... @meols what say you?

**Comment by meols** [comment]
@fernandolucchesi @NickHaggerty1 @bhavi25 - it looks great on topic page, but when testing on magazine, I don't see the Hero title or the Hero ingress - I only see the link (in preview). Tested on [this page](https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/magazine;387294ff-0913-4fdd-8714-bb7c68b02bab)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/e1c859b2-8ba8-438c-a995-d32c932df0d1)

**Comment by NickHaggerty1** [comment]
@meols I didnt test on magazine to be honest, but it should work exactly the same

**Comment by fernandolucchesi** [comment]
Good catch @meols.

@bhavi25, it is also missing the edge case for magazine pages where the tag bar goes in between the component: 
<img width="839" alt="image" src="https://user-images.githubusercontent.com/23337266/195306426-fca30721-4890-4c8c-9687-b234d00388c1.png">
vs 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/23337266/195306500-6e08918e-efc0-40a3-9a91-2ee7c5085614.png">


I also fix this for the full width banner

**Comment by bhavi25** [comment]
@meols @NickHaggerty1 -Hero title and Hero ingress are in place now.

**Comment by NickHaggerty1** [comment]
@meols @bhavi25 Im still seeing the Title before the horziontal bar: 
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine/test1_magazine

**Comment by fernandolucchesi** [comment]
> @meols @bhavi25 Im still seeing the Title before the horziontal bar: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine/test1_magazine

@NickHaggerty1, this will be fixed for this banner and for the full image banner in #1322

**Comment by NickHaggerty1** [comment]
@bhavi25 On topic page it is working as expected, I think the padding between the Title and the text block is a bit too much though![50-50 banner.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/1bb428fd-ad30-41fe-ba6b-30aa9ad78fd5).

**Comment by NickHaggerty1** [comment]
@fernandolucchesi @meols @bhavi25 Im still seeing the Title before the horziontal bar: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine/test1_magazine

@NickHaggerty1, this will be fixed for this banner and for the full image banner in #1322

OK Great

**Comment by meols** [comment]
@NickHaggerty1 - can you please check if your comments are captured here

**Comment by NickHaggerty1** [comment]
@meols @fernandolucchesi @bhavi25 Hi I notice the spacing request for the title text above the first Text component has not been captured on the TOPIC or Magazine templates. Can you please take a look at the request above and lets us know if this captured elsewhere (I don't see the acceptance specified on 1322 either) I think this should be adjusted before deploy...

**Comment by fernandolucchesi** [comment]
Hi @NickHaggerty1, added the request to to #1251
