### ISSUE TITLE
Publishing date preview for News

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1125]
The preview in the list only shows publishing date if the editor has chosen a custom publishing date.

![Skjermbilde 2022-06-03 kl. 12.02.59.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/55322b3b-ce64-4283-beb7-e05460620d04)

**Comment by meols** [comment]
@wenche - does this mean that we need to/should use custom date when publishing news until this is fixed

**Comment by fernandolucchesi** [comment]
Hi @bhavi25, left a couple of comments for you, please check :)

**Comment by bhavi25** [comment]
@meols @jorgol This is available in https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com
Can any of you review this?

**Comment by meols** [comment]
Thanks @bhavi25 - looks great :smile:
