### ISSUE TITLE
Restore scroll position on browser back

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1130]
Next.js is supposed to restore the scroll position on browser back. This has been tested and verified early in the project, but at some point this has stopped working.

### Problem
- Scroll down on a page, like on the front page
- Click on an internal link and navigate to another page
- Click browser back
- Next.js is not able to restore the scroll position, but will take you to the top

**Comment by wenche** [comment]
Ref the browser back issue. On my mobile it almost seems like whats happening is the following: When I press button back, the scroll position is restored on the current side and the the navigation completes and takes you to the top of the prev side.
To see what I mean, test with https://www.equinor.com/investors Scroll down to the Equinor in brief card and click the link. When you push back, you can notice a short glimpse of what seems to be the red icons on the blue background at the middle of the Equinor in brief page

**Comment by wenche** [comment]
Another evidence indicating that this is something with the client side navigation and routing: The link to the /50 page on the frontpage does not have this issue (if you click browser back on /50 page, the scroll position is correct on the frontpage)

**Comment by fernandolucchesi** [comment]
Looks good! :)

**Comment by millianapia** [comment]
@meols and @nicholas-haggerty this is ready to be tested. Testcase:
- Scroll down on a page, like on the front page
- Click on an internal link and navigate to another page
- Click browser back
- You arrive on the same position as you were before you navigated
