### ISSUE TITLE
Fine tune what should be indexed on search

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1131]
1. Discussion on what to index in algolia
2. Implement the changes

- Also consider other improvements like

- [x] Support "" 
- [ ] Disable typo tolerance on certain words like "Helge Lund"
![Skjermbilde 2022-06-10 kl. 12.23.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/347fd508-3a17-46fd-a77a-9e12dc7734ad)

**Comment by nilsml** [comment]
Supporting double quotes and prohibit operator can be achieved by enabling the [advancedSyntax](https://www.algolia.com/doc/api-reference/api-parameters/advancedSyntax/?client=javascript) parameter

**Comment by wenche** [comment]
"" is solved by enabling advanced syntax

**Comment by nilsml** [comment]
In production now 🥳

**Comment by fernandolucchesi** [comment]
Plan a workshop day
