### ISSUE TITLE
Video for hero banner

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1133]
Use MUX with the watermark to create the functionality

**Comment by fernandolucchesi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Energy-Vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/1133?planning-poker) with Zenhub @bhavi25 @SvSven @padms

**Comment by NickHaggerty1** [comment]
Hey, I see this is working well in the testing environment. Obviously depends on when we get the Mux contract in place. We would require some features on this banner that I dont think are in place now. Is this to card to add some acceptance criteria or will we work more on the video banner once we have Mux in place? Im thinking Autoplay (with a muted video) and Looping, would need to be options for editors when using this option.... @fernandolucchesi @SvSven @meols

**Comment by SvSven** [comment]
Getting a lot of errors when trying to browse for videos

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/5c627c70-e90b-4f3b-83d0-0271787c5ca2)

Looks to be related to the thumbnails from Mux - getting lots of 404's on Mux URLs as well.
Might be this is a network issue?

Getting a 404 error on the front end as well, with response:

```
{"error":{"messages":["Invalid Playback ID"],"type":"not_found"}}
```

I just randomly clicked a broken thumbnail in Sanity, so might be the 2 errors are related 😅

**Comment by padms** [comment]
Added toggles for loop and auto play options for hero video.

**Comment by SvSven** [comment]
The errors seem to be gone for me, and I am able to upload a new video. The autoplay and loop seem to work as well. Left a comment on the commit about the `playbackId` which needs to be fixed.

Also - do we want the controls to be visible? Not sure if that was discussed at any point, but it's probably nicest to hide them?

**Comment by padms** [comment]
@SvSven  Fixed the playbackId issue. I tried to hide the controls, but it shows up on hover or focus.

**Comment by padms** [comment]
@SvSven I was able to hide it completely by setting the attribute to undefined. Now if autoplay is enabled controls are hidden otherwise controls are shown.

**Comment by SvSven** [comment]
Perfect! Looks good ✅

**Comment by padms** [comment]
@NickHaggerty1 Please check the new options (Loop and Autoplay). If autoplay is enabled the controls for the video is hidden otherwise it is shown.

**Comment by NickHaggerty1** [comment]
@padms @SvSven Looking really good nice work.  And yes agree to the earlier question about hiding the controls. I uploaded a video here. Obviously as mux is integrated the 'watermark' is visible. Not sure if that is something we can also get rid of? ref the question earlier..... 
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/api/preview?type=magazine&locale=en&slug=%2Fmagazine%2Fmagazine-video-banner&secret=jlskdjfkj4323lk4jlkjlksdf

**Comment by fernandolucchesi** [comment]
@padms, just giving a late review here... these 2 props (from the query) should be fetched inside the video object

```
    "loop": coalesce(heroVideoLoop,false),
    "autoplay": coalesce(heroVideoAutoPlay,false)
```
