### ISSUE TITLE
Enable DynaTrace for the solution

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1134]
**In order to monitor both what happens on the server and for the client, we should enable Dynatrace**

**Comment by nilsml** [comment]
Contact person (as per 9/6-22) Hans-Henrik Kivsmose

**Comment by fernandolucchesi** [comment]
Waiting for needed keys and address. To be provided by Hans-Henrik Kivsmose. Request is being followed up on slack.

Setup: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/docker/set-up-oneagent-on-containers-for-application-only-monitoring

**Comment by fernandolucchesi** [comment]
https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=8c6f32691b73891053382136604bcb16

**Comment by fernandolucchesi** [comment]
Finally ready :) this is going to be hard to review, I will ask the dynatrace people to give access to the whole team, let's keep this on hold for a while

**Comment by padms** [comment]
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/725198ac-d80e-41df-85cf-740e1b9dcd50)Cookies being set by dynatrace.

**Comment by nilsml** [comment]
So we need to include the cookies set by dynaTrace to cookiebot?! @padms @fernandolucchesi

**Comment by fernandolucchesi** [comment]
> So we need to include the cookies set by dynaTrace to cookiebot?! @padms @fernandolucchesi

Yep! Will ask about it in the meeting tomorrow. I did not find a react library to use the functions mentioned in the docs.
