### ISSUE TITLE
Create folder like structure for text snippets

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1135]
Investigate if we can order the text snippets in a folder like structure to make it easier for the publishers to find the relevant text snippets, and to understand where they are used.

**Comment by fernandolucchesi** [comment]
Hi @padms, left some comments for you in your commit.

A very important note is to not forget to use feature flags. We should "revert" this changes to deploy to prod on Monday, otherwise these will be in production before it gets reviewed by Mette.

**Comment by fernandolucchesi** [comment]
I believe having some grouped and others ungroup is very confusing UX-wise:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/23337266/182397799-6cf05043-bdb5-4582-bfee-258235c3afd8.png">


I'd suggest we make the group property mandatory, and create a new group "Others". I would also suggest changing the "text icon" to a "folder icon", since they behave like folders now.

**Comment by padms** [comment]
Done

**Comment by fernandolucchesi** [comment]
@padms, looks good! Possible enhancement is to order items alphabetically.

**Comment by padms** [comment]
Done

**Comment by padms** [comment]
@meols @jorgol https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/settings;textSnippets;snippet-group-Others

Text Snippets are grouped by component or feature. Some misc text snippets are under 'Others' folder.

**Comment by jorgol** [comment]
Great improvement!
