### ISSUE TITLE
Improve presentation for CVs

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1136]
Example https://www.equinor.com/about-us/board-of-directors-cvs

Ideally the publishers would like a way to add an image for each director, but with the current available components that doesn't look good. We should look into if it makes more sense to have a specialised component in Sanity for this, that includes a smaller image like the quote image.

### Acceptance criteri

**Comment by NickHaggerty1** [comment]
solved with #1311 Closing FYI @meols
