### ISSUE TITLE
Remove indexed documents from algolia

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1138]
We need a webhook that will be triggered **on updated** (watches the flag excludeFromSearch) to unindex documents, and triggered **on unpublished**. 

Document a process for that in the runbook

**Acceptance Criteria**
- [x] Update runbook
- [x] Indexes are deleted whenever 'Disable from search results'  is turned on or document is unpublished or deleted.

**Comment by fernandolucchesi** [comment]
we need a webhook that will be triggered **on updated** (watches the flag excludeFromSearch) to unindex documents, and triggered **on unpublished**.

**Comment by nilsml** [comment]
@padms to add more information including acceptence criteria to this issue

**Comment by padms** [comment]
Updated run book.

**Comment by nilsml** [comment]
Isn't this finished @padms?

**Comment by fernandolucchesi** [comment]
@nilsml have you reviewed? Can we deploy this? @padms

**Comment by padms** [comment]
Safe to deploy, webhook for prod is not setup yet

**Comment by padms** [comment]
@Mette This also can be tested on dev. Content previously visible under search, newsroom or magazine index page should not be visible 

- When news, magazine, local news , topic routes are unpublished or deleted.

- When content is updated with "exclude from search" option enabled when it was previously disabled

**Comment by padms** [comment]
@meols This can be tested
