### ISSUE TITLE
H3 has different sizes in different documents

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1140]
H3 is different in news articles compared to topic pages 

Since they are two different templates, the h3 doesn't have to look the same. On the other hand, the ones for the topic pages was updated a while back and we might have forgot to look into the news article h3. Figma does not have any examples for h3 in the news article as far as I can see. :)

### Actions
- Compare the two templates and see if it would make sense to align them
- Update figma sketches accordingly

**Comment by fernandolucchesi** [comment]
@NickHaggerty1 can you assist me on this one?

**Comment by NickHaggerty1** [comment]
Sure @fernandolucchesi I can try. Though this related to the work done by Victor at the start of the year. Im not sure I   this was ever merged back to Figma. I would assume the correct H3 size is on the TOPIC / MAGAZINE / HOME templates. So if the news is different to this, then I think you can just change the News template to match, as there shouldnt be a difference.

**Comment by SvSven** [comment]
Not sure I understand the purpose of the `h2Heading` and `h3Heading` components here - seems to me like the only difference is the `size` attribute on the main `Heading` component?

Admittedly I haven't looked at this part of the code in a long time, so is using these components just bringing it in line with the rest?

**Comment by meols** [comment]
@SvSven - we really don't see a difference, but please make news H3 the same as on other pages if you find some differences in the code. @NickHaggerty1 
Topic page:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/771a65fe-b145-4095-95b7-a3d0aa3c81c4)
News page:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/d02d36c7-80b9-43a7-aba1-4d74c3a4f5b7)

**Comment by fernandolucchesi** [comment]
> Not sure I understand the purpose of the `h2Heading` and `h3Heading` components here - seems to me like the only difference is the `size` attribute on the main `Heading` component?
> 
> Admittedly I haven't looked at this part of the code in a long time, so is using these components just bringing it in line with the rest?

Yes, the other components are using it, so this is to make sure that when we update it in one place, it updates all the components.

**Comment by SvSven** [comment]
Sounds good ✅
