### ISSUE TITLE
Make Search box font size bigger

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1142]
Some feedback about that the font size is too small for the search box

### Acceptance criteria
- Improve readability

**Comment by wenche** [comment]
@BirteThornquist  You may test in development https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/search?query=hel

I did what you suggested, but I didn't change any of the spacings. What do you think?

**Comment by BirteThornquist** [comment]
I think this is good @wenche

**Comment by meols** [comment]
Thanks @wenche @BirteThornquist - looks good :smile:
