### ISSUE TITLE
Magazine subscription

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1147]
Users should be able to subscribe to magazine newsletters.

**Comment by padms** [comment]
Need to confirm from Brandmaster that the data is received correctly

**Comment by fernandolucchesi** [comment]
Looking good! =)

**Comment by fernandolucchesi** [comment]
@padms can you confirm you got the subscription data correctly?

**Comment by fernandolucchesi** [comment]
Person from Brandmaster is on holidays until August 1st

**Comment by fernandolucchesi** [comment]
@padms, can you follow up on this one?

**Comment by padms** [comment]
@meols @jorgol  The magazines need the ingress text ( as it is in the email template). Currently, we dont have a separate text block for ingress in the magazine template. 

We can extract the ingress from the text component added in page section and use it in the mail. Should we look for the ingress in the first texblock on the page and warn if it is missing?

**Comment by jorgol** [comment]
Would it be a better option to add ingress as a separate field like on the news template? Could ask Nick for input as well, but I'm unable to tag him now for some reason.

I think we should also add a warning if it's missing whether we choose the one or the other solution.

**Comment by padms** [comment]
@NickHaggerty1 Need your inputs on this.

**Comment by NickHaggerty1** [comment]
@jorgol @padms I guess the easiest option is to extract the ingress from the first text block, but it does make sense to have a separate ingress field on the Magazine template. This could either be the same text as the first text block ingress or something written independently (and hopefully shorter). the additional advantage would be to use this field to display an ingress on the Magazine landing page (when we create that). Is it a big task to create a separate field Padmaja?

**Comment by padms** [comment]
@NickHaggerty1 Its easy to add a separate field. I will add it

**Comment by meols** [comment]
Sounds good @padms - agree with comments from you and @NickHaggerty1 that it's beneficial to also be able to use the ingress in the cards/on the landing page, and for search.

**Comment by meols** [comment]
@fernandolucchesi - some questions to the subscription, not sure where to add them - so putting them here :smile:
- if I forget to activate (change to green) the send to subscribers when publishing a magazine article, do I then unpublish, activate the "switch" and republish the page - or do I just activate and publish (not needing to unpublish)
- When I do an update after a magazine article is published and sent to subscribers, will a new newsletter be sent out (which we don't want)?

**Comment by fernandolucchesi** [comment]
@padms:
```
I suggest to edit the distribution/subscription text to:
Send to subscribers: Activate (change to green) to send to subscribers when you publish the magazine article.
```

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - some questions to the subscription, not sure where to add them - so putting them here 😄
> 
> * if I forget to activate (change to green) the send to subscribers when publishing a magazine article, do I then unpublish, activate the "switch" and republish the page - or do I just activate and publish (not needing to unpublish)
> * When I do an update after a magazine article is published and sent to subscribers, will a new newsletter be sent out (which we don't want)?

Will work the same way as for the news:

-  Unpublishing -> publishing will (re)distribute. 
- Re-publishing without unpublishing will not distribute.

**Comment by padms** [comment]
I added a separate ingress field which is searchable from global search and magazine index page. But the ingress is itself not visible on the magazine page.

**Comment by meols** [comment]
Thanks @padms - the text in the ingress field should also be added to the newsletter text in the emails to subscribers. Can it be moved to the top (between SEO and title) and renamed to: 
**Description** Shown in newsletters and promotions.
 This field should also be mandatory to fill in.
@NickHaggerty1

**Comment by fernandolucchesi** [comment]
@padms looks good, if needed, could you also add the ingress to the editor's documentation? :)

**Comment by padms** [comment]
Added to the documentation.

**Comment by meols** [comment]
@padms @fernandolucchesi - can you please add some information on the dialogue you have had with brandmaster. 
- Are newsletters triggered, and is the Description text (ingress text) shown in the newsletter?
- I suggested above to change the text for the Ingress field to **Description**, to avoid confusions with the Ingress in the text components. Can you please do that update.

**Comment by padms** [comment]
Attaching the screenshot of the magazine letter attached by brandmaster. ![Screenshot 2022-08-16 at 10.23.03.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/a2d74bcc-35d3-42eb-b1fa-6748469639df)

**Comment by meols** [comment]
Thanks @padms
