### ISSUE TITLE
Magazines should be searchable

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1148]
Magazine content should be indexed in algolia as we do for news.

A newsroom like page, and a link in the Menu is also required.

Accept criteria:
- [ ] Improve search documentation in Runbook 
- [ ] Add documentation for magazines in Runbook
- [x] Verify if sanity roles need to be updated to include magazine, if not already done so

**Comment by SvSven** [comment]
Pending creation of magazine articles.

What's left to do is documentation at least.

**Comment by fernandolucchesi** [comment]
Hi @SvSven, a few points:

There is a 'News' placeholder in the Magazine.
<img width="599" alt="image" src="https://user-images.githubusercontent.com/23337266/180789482-0b7d2346-66f9-4f9c-b201-7108f1467a4d.png">

This would also be nice to be renamed, in MagazineIndexPage.tsx: 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/23337266/180789655-ba963f2b-ec7b-4c7e-930b-262ed7662e4d.png">

For the magasin index file, we should update this from `en` to `no`:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/23337266/180790163-ed734199-3d11-4448-bb63-e66169354c15.png">

**Comment by fernandolucchesi** [comment]
We should also make sure the magazine type is added correctly to the sanity roles before deploying to production. I'll update the acceptance criteria

**Comment by SvSven** [comment]
Good catch on the magasin index page; copy paste error 😅
Have fixed the component names and the heading. It's not perfect yet, we should at some point come back here and refactor things more - the newsroom was never set up to have "shared" code/components so it's a bit of a mess still.

The roles I am not sure of, have not done anything with that yet.

**Comment by fernandolucchesi** [comment]
Magazine Index page is not being displayed in the studio: 
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/23337266/182328321-a1de45b3-dce3-4d1a-bebb-bebccb23bb90.png">

**Comment by fernandolucchesi** [comment]
> Good catch on the magasin index page; copy paste error 😅 Have fixed the component names and the heading. It's not perfect yet, we should at some point come back here and refactor things more - the newsroom was never set up to have "shared" code/components so it's a bit of a mess still.
> 
> The roles I am not sure of, have not done anything with that yet.

I've basically added it to here: 

<img width="619" alt="image" src="https://user-images.githubusercontent.com/23337266/182328620-0908570d-2768-47c0-ba2c-9760a746840f.png">

**Comment by fernandolucchesi** [comment]
Reminder to add exclude from search

**Comment by fernandolucchesi** [comment]
@meols @jorgol, can you please review this one?
https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/misc;magazineIndexPage;magazineIndex

https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/search?query=magazine&tab=magazine

https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine

Please keep in mind that adding a new magazine or updating it, will not automatically index it. I need to run a script to update the indexed magazines in the dev environment.

**Comment by meols** [comment]
@fernandolucchesi - when searching for "second magazine" it looks like I don't get a hit with the text Nothing found showing, but there is a hit in the magazine tab, which isn't easy to see (and probably not good for accessibility)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/f831316c-adaa-4fa3-94e8-47fd836e65e3)
Will we (can we) get the cards/promo look instead of the list look on the index page to make it more visually appealing (as we had in AEM)
Also some comments to the template:
- is it decided (by who) to not have date/custom date, which we had in AEM. Is it a big task to add it?
- I suggest to edit the distribution/subscription text to:
**Subscribers:** Toggle (change to green) to send to subscribers when you publish the magazine article.

**Comment by fernandolucchesi** [comment]
Hi @meols, we can for sure improve UX for search, specially now that @NickHaggerty1 is back. However I'd suggest that these UX improvements are handled by a different issue.

As for the templates, It was agreed before that since we didn't have a custom template (design wise) for Magazine, using the same as Topic Page was a good start, and that is why there is no date/custom date (since topics don't have this field). Adding it is not a big task :)

**Comment by NickHaggerty1** [comment]
@meols Feel like there are quite a few different points you are raising here relating to magazine. There has been no internal chat (as far as I know) on the requirements for magazine so suggest we do that so we cover all the different elements and then create issues relating to Magazine. There are points relating to  Magazine template. Magazine landing page. As well as search display. For me the UX on magazine search is correct (its just not showing the result you expected) and in keeping with the approved and implemented design for News search and Topic search.

**Comment by fernandolucchesi** [comment]
Wait to deploy - do not turn on feature flag 🎏
