### ISSUE TITLE
Documentation for Editors

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1151]
This document should work as the one that exists for AEM, with screenshots and explanation of components / how to use them in Sanity. 

AEM example: [https://statoilsrm.sharepoint.com/sites/EditordocumentationforAEMequinorcom/_layouts/15/Doc.aspx?sourcedoc={8e53650c-64b2-41de-bd94-96204ff172a7}&action=edit&wd=target%28General.one%7Cc6904292-2ef8-408e-802e-26da4408bd77%2FUse%20Google%20Chrome%7Cc3775a1b-1816-4410-a236-fa40febda329%2F%29&wdorigin=NavigationUrl](https://statoilsrm.sharepoint.com/sites/EditordocumentationforAEMequinorcom/_layouts/15/Doc.aspx?sourcedoc=%7B8e53650c-64b2-41de-bd94-96204ff172a7%7D&action=edit&wd=target%28General.one%7Cc6904292-2ef8-408e-802e-26da4408bd77%2FUse%20Google%20Chrome%7Cc3775a1b-1816-4410-a236-fa40febda329%2F%29&wdorigin=NavigationUrl)

**Comment by fernandolucchesi** [comment]
Hi @padms, please add the link on where this can be found :)

**Comment by padms** [comment]
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/editorial-documentation/using-the-sanity-studio

https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/editorial-documentation

All the links can be found under 'Editorial Documentation' menu in dev

**Comment by meols** [comment]
Thanks @padms - this is really great :thumbsup: :smile: I will go through this more thoroughly and share with the editorial team a well, so let's keep the card in the acceptance lane for a while.

**Comment by fernandolucchesi** [comment]
> Thanks @padms - this is really great 👍 😄 I will go through this more thoroughly and share with the editorial team a well, so let's keep the card in the acceptance lane for a while.

As a "bonus" there will be no need to click on the "Open Preview" menu button to make the preview tab work properly ;)

**Comment by fernandolucchesi** [comment]
@meols can we close this one? And create new ones to improve / modify documentation when needed?
