### ISSUE TITLE
Document how images work

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#1156]

**Comment by wenche** [comment]
As a start, we have added two documents in the development dataset
[News](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/images)
[Topic content ](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/images)

**Comment by fernandolucchesi** [comment]
Hi @meols, can you take a look at the documentation that has been written here? If this looks good for you we can also add it to another location (wiki / doc / other dataset etcs).

**Comment by jorgol** [comment]
Thanks. If these URLs are accessible for everyone and/or should be placed somewhere else, this can be closed as completed.
