### ISSUE TITLE
Have a vault with all secrets / environments etcs

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1157]
- [x] SSL Certificates and private keys for all sites 
- [x] Environment Variables

**Comment by SvSven** [comment]
Not sure what there is to review here for us, I guess making sure everyone that needs to have access has access?
I'm happy with the chosen tool at least; it's simple to use and in line with Equinor policy.

**Comment by fernandolucchesi** [comment]
This has been solved ✅
