### ISSUE TITLE
List all missing components in Storybook

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1158]
We should create a list of all missing components in storybook, and later implement them to keep storybook updated

**Comment by fernandolucchesi** [comment]
Do we want to keep using it?

**Comment by SvSven** [comment]
Seems like only the `Form` is missing in terms of the web components listed in `web/components/src`. Should be easy enough to add that.

Makes sense as well since we haven't really added any new base components in quite a while. Most work has been done on Sanity/Next specific components.

**Comment by fernandolucchesi** [comment]
We will need to add banner and banner variations. I'll invite for a meeting next week for us to decide if we keep updating it or not

**Comment by SvSven** [comment]
Decision made on 2022.09.13 to keep storybook going forward and that we should have updating storybook as part of the acceptance criteria for new components.

**Comment by SvSven** [comment]
Issue for adding missing Form components: #1276
