### ISSUE TITLE
'smallText block style not supported' error in server logs

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1162]
The server logs are getting spammed with an error:

`Unknown block style "smallText", specify a component for it in the `components.block` prop`

**Comment by fernandolucchesi** [comment]
Looks good to me. Let's deploy to prod tomorrow and watch if logs are gone, if so we close this.

**Comment by SvSven** [comment]
Found out the error pages do not handle the `smallText` option but did have it enabled in the schema. Seems that despite there not being a value in the block content that actually uses the `smallText`, it being part of the schema and not being handled on the frontend still causes this error message.

Have disabled the `smallText` in the schema, as it's not needed for the error pages at this point - but it's a good learning.

**Comment by SvSven** [comment]
Review pending deploy to production to see if issue is fixed
