### ISSUE TITLE
White space between components with same background in news page 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1164]
See the link https://www.equinor.com/news/20220617-considering-1gw-offshore-wind-farm-off-western-norway

**Comment by fernandolucchesi** [comment]
Extra space at the bottom of the content was also removed: 
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/23337266/187693830-068dc76a-aac0-4910-a583-30d93f6dc109.png">

**Comment by fernandolucchesi** [comment]
@meols @NickHaggerty1, this is ready to be tested on global-development or global-test

**Comment by NickHaggerty1** [comment]
@fernandolucchesi Hey. Thanks, tested and approved

**Comment by NickHaggerty1** [comment]
@meols FYI
