### ISSUE TITLE
Launch SouthKorea Website

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1166]
Technical
- [x] Request DNS change (use the new cluster)
- [x] Add domain to `robots.txt.ts` and `satellitesConfig.js`
- [x] Add missing roles, if any, to sanity.io
- [x] Add GTM to radixconfig
- [x] Redirect equinor.kr to equinor.co.kr (should keep path)
- [x] Add domain url to the Cookie Bot (@padms)
- [x] Add SSL certificates
- [x] Test PREPROD environment
- [x] Push to prod

Editorial
- [ ] Misc pages (404, 500 etcs)
- [ ] Homepage
- [ ] Redirects
- [ ] Cookie Policy
- [ ] Double check links (translations, if any)

Launch date: TBD

**Comment by padms** [comment]
The website equinor.kr should be redirected to equinor.co.kr , redirect should include sub pages as well
