### ISSUE TITLE
Improve on Architecture Contract document

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#117]
- [ ] Add somewhere a comment about the format used by Sanity to expose content (ie. Portable Text)
- [ ] Check out Security Health Check. Is this covered through the Self Assessment?
- [ ] Legal Risk Assessment. There is a link in the contract for this. See if there is something we should do.
- [x] Discuss what parts of the code we write can be open sourced
- [ ] As part of our requirements, certain documents shall be published at a given date and time, and before that date and time, only a few selected people can have access to them. We should point out in the Architecture Contract whether that functionality is offered out of the box from Sanity, or if it's something under our responsibility

**Comment by wenche** [comment]
LGTM, but how about the checklist in the issue description? Is that deprecated? @nilsml

**Comment by nilsml** [comment]
Good point @wenche. Maybe create new tasks for these issues. There are tasks embedded in the document as well, so need to revisit that more often.
