### ISSUE TITLE
SEO Improvements

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1171]
TAGS:

Href lang should not have extra trailing `/` in home page
Href lang for default language should not include `/en`

<img width="556" alt="image" src="https://user-images.githubusercontent.com/23337266/175262239-5ab627ec-f54a-4125-90f8-2482a10e29e3.png">

Scripts:

Do not add SiteImprove scripts to test datasets

**Comment by fernandolucchesi** [comment]
@padms wrote you a comment

**Comment by padms** [comment]
Done..
