### ISSUE TITLE
Statoil external redirect

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1172]
Currently we only redirect statoil.com to equinor.com.
We should redirect every statoil url to equinor.com, example:

statoil.com/123/456 -> equinor.com/123/456

**Comment by SvSven** [comment]
I feel like these things should be handled on a DNS level at the registrar - but I guess that's not going to happen based on previous experiences.

Looks good to me 👍

**Comment by fernandolucchesi** [comment]
> I feel like these things should be handled on a DNS level at the registrar - but I guess that's not going to happen based on previous experiences.
> 
> Looks good to me 👍

Yes agree :/ thought about having it in the next.config.js too but we  still have some assets working with statoil url afaik
