### ISSUE TITLE
Add news for Japan website

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1173]
Possibility of different language using the same slug should be added.

Eg:
```
equinor.jp/news/an-example-slug
equinor.jp/ja/news/an-example-slug

```

**Comment by fernandolucchesi** [comment]
Hi Sven, can you review this one? To make it easier you can modify the languages allowed for the development dataset:

<img width="466" alt="image" src="https://user-images.githubusercontent.com/23337266/176198018-20c7fea6-7a72-4abc-bcab-41e430e917fe.png">

**Comment by fernandolucchesi** [comment]
@SvSven

**Comment by SvSven** [comment]
Looks to be selecting the correct document now 👍

I would be disappointing Nils Magne if I didn't point out that this could be a function: https://github.com/equinor/energyvision/commit/cd28e03aab2831e7842706b9013e3e094cc0264b#diff-da4ce219f31e0775067ad965d2b09e19c33eec51f78ca54f93c04ebc21b0dd88R67-R78

But this approach works as well ✅

**Comment by fernandolucchesi** [comment]
> Looks to be selecting the correct document now 👍
> 
> I would be disappointing Nils Magne if I didn't point out that this could be a function: [cd28e03#diff-da4ce219f31e0775067ad965d2b09e19c33eec51f78ca54f93c04ebc21b0dd88R67-R78](https://github.com/equinor/energyvision/commit/cd28e03aab2831e7842706b9013e3e094cc0264b#diff-da4ce219f31e0775067ad965d2b09e19c33eec51f78ca54f93c04ebc21b0dd88R67-R78) But this approach works as well ✅

good point! Refactored =)

**Comment by jorgol** [comment]
@fernandolucchesi I see that news are available both on the Japan and Korea site - is there anything left for me to test/approve?

**Comment by fernandolucchesi** [comment]
That's all =)
