### ISSUE TITLE
Emergency Website

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1182]
We need an emergency website in case of a black screen scenario.

The emergency website must:

- be independent from external CMSs
- be easily deployable to any cloud provider or server
- contain a built-in CMS with tile, date, text fields
- contain a simple internal log in system independent from external providers
- Have a similar look'n'feel of the main website

Acceptance criteria:
- [ ] Update documentation in Runbook

**Comment by fernandolucchesi** [comment]
Ready to be reviewed: https://github.com/equinor/energyvision-emergency

For the MVP, only "Create" operation has been implemented

**Comment by SvSven** [comment]
The `.vercel.app` domain appears to be blocked by network policy on the Equinor network and managed devices.
We should put in a ticket to have the URL for the emergency website whitelisted.

**Comment by fernandolucchesi** [comment]
> The `.vercel.app` domain appears to be blocked by network policy on the Equinor network and managed devices. We should put in a ticket to have the URL for the demo of the emergency website whitelisted.

lets do it when we are able to host in a different close provider. I will close this issue
