### ISSUE TITLE
Checklist for what to check when upgrading dependencies

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1184]
Setup a github template for this.

**Comment by SvSven** [comment]
Had previously started on a checklist, still a work in progress: https://github.com/equinor/energyvision/wiki/Sanity-Studio-upgrade-testing

**Comment by SvSven** [comment]
@fernandolucchesi @padms @bhavi25 @nilsml 

Have expanded upon my previous checklist draft with a wiki page - let me know what you think: https://github.com/equinor/energyvision/wiki/Guide-to-upgrading-dependencies

**Comment by padms** [comment]
@SvSven I think we can also include webhooks and redirects in this list.
