### ISSUE TITLE
Newsroom centre

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#119]
As a user I need to be able to filter news between types and also by tags on the newsroom centre page

_Less important than the news articles_

## Acceptance criteria
Need to select types of news (General news/stock market announcements/notifiable trading/our stories/local news)
• Filters organised by tag titles (Country/year/topic) with filtering for tags (Norway/UK ++) Tag selection should impact on other tag.
• Investigation task. Do we need separate template for local news type. (To allow access for unique editors to publish local articles)
• Filter button/pop out option specific to general news type
• One type that is needed but not defined on the newsroom page is Crude Oil Assays
• Other types can be filtered with other displays, not under filter button/pop out
• Different visual display for certain types (stories different to the other types)
• Search engine must function for news across Azure and Sanity
• Archive news should at least be filterable by year
• Toggle off tags either in pop out filters or the display in main window. Tag de-selection should impact on other selected tags
• The tags defined should be kept in one list and created first in English and translated to Norwegian (not to allow to create separate NO only or first)
• Possibility to show numbers for tags once selected. EG Norway 77 (nice to have. Investigation, how to apply to articles that haven’t been tagged eg archive news)
• Need to have subscription to some types (General news/stock market/crude oil/stories). Subscribe is selected/defined at the article template level.
1. Ability to hide certain tagged news the news room. For example, today we publish crude oil assays as subscribed news articles (to a different subscriber list), but these news types are hidden in the newsroom.

**Comment by nilsml** [comment]
Perhaps we should consider splitting this up into smaller chunks as well? Not sure what makes sense here.

**Comment by nilsml** [comment]
Only basic version of newsroom to be completed before switching off AEM!

**Comment by nicholas-haggerty** [comment]
@nilsml When we finally get around to discussing how to solve the newsroom, yes we need to define what is basic/like for like replacement.
However this decision also impacts how we solve local news and Magazine (stories) The ultimate plan (call it a phase 2) is to have one landing page to select/filter between. That means we would also need to solve these to a basic level too. It makes sense to assess whether to do the separate basic tasks or build the one landing page.
I also think there is alot of design work to defined for this task and as there isnt much UX tasks, I would like Birte and I to work on this. for both a basic version and phase 2. Then when developers are available we have something to discuss in a workshop

**Comment by NickHaggerty1** [comment]
Think we can close this @meols ? Any future plans for newsroom can be created separately
