### ISSUE TITLE
First publish didn't work as expected

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1199]
`firstPublishedAt` field was erroneous updated between revisions:

https://equinor.sanity.studio/desk/news;4b320f0f-ee49-4d19-a86d-42119521c8a6%2Crev%3D2022-07-12T11%3A59%3A51.496413Z%2FotwEPi8NkWYpA9uLbw6HZ5%2Cinspect%3Don

and:

https://equinor.sanity.studio/desk/news;4b320f0f-ee49-4d19-a86d-42119521c8a6%2Cinspect%3Don%2Crev%3D2022-07-12T12%3A06%3A42.551805Z%2FoPCumSShnmMkQJ90r8mCny

I couldn't replicate it so am assuming the api call has failed.

**Comment by SvSven** [comment]
Wouldn't it be better to use React state here instead of `let`?

**Comment by fernandolucchesi** [comment]
> Wouldn't it be better to use React state here instead of `let`?

Hmm but then the state would be updated only in the next re-rendering, unless logic was moved inside an useEffect. Since the 'error' logic is all inside the "else" block, I don't really see the need of using state here

**Comment by SvSven** [comment]
Seems reasonable enough 👍
