### ISSUE TITLE
add 'sharp' image optimization for production build

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1205]
This warning showed up in the logs:

```
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
```

See: https://nextjs.org/docs/messages/sharp-missing-in-production

We should probably add that if it is recommended.

**Comment by fernandolucchesi** [comment]
done in https://github.com/equinor/energyvision/commit/c764cf78012191c54048464af8dc2cf9df2b9e8d
