### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1209]
⚠ Blocked until after quarterly results release ⚠

We have a couple of Snyk PR's waiting to be merged - and a number of other outdated dependencies waiting. We should always strive to be as up to date as possible to avoid any potential security problems.

Difficult to assign story points for this task since it could be as quick as an hour but it could be as long as a week, it all depends on the (potential) issues relating to upgrades.

---

- [x] Update root project dependencies
- [x] Update web dependencies
- [x] Update Sanity studio and plugins

Separate issues can/should be made for larger/specific dependency updates as they require investigation and testing.

**Comment by fernandolucchesi** [comment]
https://github.com/sanity-io/document-internationalization/issues/59

**Comment by padms** [comment]
Didnt find any issue
