### ISSUE TITLE
Error in order report form

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1212]
There is an error going on in the radix console:

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/23337266/180783561-2ef43052-49e6-4df1-976f-935006870cc4.png">

**Comment by padms** [comment]
There was no check for allowing only 'POST' requests for the forms, which further allowed parsing the JSON body which is null.

**Comment by SvSven** [comment]
Not sure why it was doing GET requests, but looks good to me 👍

**Comment by fernandolucchesi** [comment]
I see some unnecessary code duplication. What about extracting the validation block into a "validateFormRequest.ts" file / method ?

**Comment by fernandolucchesi** [comment]
This is in prod already but waiting for code optimisation to close it

**Comment by padms** [comment]
Done

**Comment by fernandolucchesi** [comment]
Looks good! :)

**Comment by padms** [comment]
Closing this went live with https://github.com/equinor/energyvision/discussions/1227
