### ISSUE TITLE
 Event template contact list ingress not showing

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1213]
Are we using it at all? If not investigate if we can remove it

**Comment by fernandolucchesi** [comment]
Hi @meols, it is being used. You can check a example of it being used at https://equinor.sanity.studio/desk/event;7f18b53e-0a2f-4250-b888-4006533854b9

**Comment by meols** [comment]
@fernandolucchesi - we should display it, and it should be optional. Then we have more options to format the text.

**Comment by padms** [comment]
LGTM

**Comment by fernandolucchesi** [comment]
@meols, can you please test how it looks now? :) https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/

**Comment by meols** [comment]
Thanks @fernandolucchesi - looks great :smile:
