### ISSUE TITLE
Index files in algolia

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1219]
Add the possibility to search for files in the search bar.

**Comment by SvSven** [comment]
If we want to change the URL structure for files from the Sanity CDN (for example https://cdn.equinor.com) we should do that before we index them in Algolia.

**Comment by SvSven** [comment]
We should _probably_ also group the files into a separate tab for the search page.

**Comment by SvSven** [comment]
All relevant files will have a news article or other page attached which is indexed, this is not needed
