### ISSUE TITLE
Create tags for magazines

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1226]
We should have a tag system similar to the tag system we have with news. Magazine tags should be indexed, and added as a filter in the magazine landing page.

Acceptance criteria:
- [ ] Update roles (rules) in sanity

**Comment by fernandolucchesi** [comment]
Hi @bhavi25, a few comments:

## Needs change

1. We have all the files inside newsroom1 folder, even tho some are related to Magazines. I suggest extracting the common files into the "shared" folder. 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/23337266/186165608-02908a3b-2910-416a-90a9-272ea88477cb.png">
Then files related to the magazine should be moved out of the newsroom folder.


2. The magazine tags component should come second in the studio, after SEO and metatag (like we do for local news): 
<img width="744" alt="image" src="https://user-images.githubusercontent.com/23337266/186169679-09b72b3a-7a75-42a1-901d-18f480678667.png">

## Possible enhancements
1. on Filters.tsx, this code: 
<img width="507" alt="image" src="https://user-images.githubusercontent.com/23337266/186167133-7ac7a440-6e76-4cdc-b639-503f970f15e1.png">
could be more readable by refactoring/extracting the whole block of code into 2 other components: < MagazineFilters /> and < NewsroomFilters />. If you extract it to outside of the main function would be even cleaner / better.
 
2. on studio/magazineTag.js: the file could be converted into a typescript (.ts) file

## Neat picking
1. I know you just copied this from the other file, but we don't need to use back quotes if we are not using javascript inside of it:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/23337266/186170256-6221950f-6ae7-444c-a3b3-9dd81aef4c3d.png">

**Comment by fernandolucchesi** [comment]
@bhavi25 left a new comment for you =)

**Comment by fernandolucchesi** [comment]
Left a couple more comments =)

**Comment by meols** [comment]
@fernandolucchesi - we would like to display tags on the magazine template and the magazine landing page. The display should be limited to max 5 tags at any time (5 "promoted" tags). We would like to create a "hierarchy" in the magazine tag list, so that we can have a longer list, but have 5 of them visible/promoted on the pages. Is that possible? Editors should be able to, at any time, to select/deselect which tags are visible. The full tag list will be used in promotion cards, and will have a "limitless" number of tags. @NickHaggerty1

**Comment by fernandolucchesi** [comment]
@meols, I suggest we close this without deploying to prod, and do the requested changes in the other issue. The work that has been done here will work as a base for #1252

**Comment by fernandolucchesi** [comment]
LGTM ✅

**Comment by bhavi25** [comment]
@meols We now have the tag system for magazines similar to that of news.
https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/
Also these tags are indexed and added as a filter in magazine landing page.
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine

**Comment by meols** [comment]
Thanks @bhavi25 and @fernandolucchesi - this looks good :smile:
