### ISSUE TITLE
Improve search results page

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1236]

**Comment by meols** [comment]
When performing a search which give hits/results in only one tab, e.g. magazine, the user see NOT FOUND..... , since it is currently the search results for Topic that is default shown.

- If there is results in only one tab, that tab should be underlined and the search results list should be shown.
- If there are search results in more than one tab, we should see the results from the left-most tab underlined and it's search results list. 

![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/b8a17b54-34da-4689-88aa-b18d012ff7cc)

**Comment by fernandolucchesi** [comment]
@meols @NickHaggerty1, what if the user deliberately clicks on "news", meaning that news is the only type the user is interested in searching for? should we then create a logic that if the user clicks in one of the tabs, the auto switching no longer applies?

**Comment by NickHaggerty1** [comment]
@fernandolucchesi Maybe Im not understanding, but a user doesnt get an option to choose a tab before the results are displayed? So in the example above, the results should show the Magazine (1). If a user **then** clicks on News (0) They should see the message 'Nothing found' Or?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Maybe Im not understanding, but a user doesnt get an option to choose a tab before the results are displayed? So in the example above, the results should show the Magazine (1). If a user **then** clicks on News (0) They should see the message 'Nothing found' Or?

and if they search for a new query after they click on "news"?

**Comment by NickHaggerty1** [comment]
@fernandolucchesi Then it should behave as it does today. So if the NEWS results says nothing found and user starts a new search, the results would display based on tabs and numbers, the highlighted tab (underlined) would still be news.

**Comment by NickHaggerty1** [comment]
![Screenshot 2022-09-15 at 12.24.30.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/ad6c1504-6c7e-40b7-ad12-90ba44a9e7b1)

**Comment by NickHaggerty1** [comment]
![Screenshot 2022-09-15 at 12.24.21.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/a3cdcc4f-d63a-4517-9899-e62e7477e69b)

**Comment by NickHaggerty1** [comment]
![Screenshot 2022-09-15 at 12.24.30.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/408613b8-b211-4b09-8cf6-b90ab88b32d7)

**Comment by fernandolucchesi** [comment]
Hi @NickHaggerty1, can you verify this one on global-development?

Other improvements were also done:
- Glitching when using backspace / typing was fixed
- Results will now take 400ms to update (this is to reduce the usage of algolia quota and consequently our bills - no need to update on every key stroke)

Please also check if the copying + paste of search urls is also working as intended

**Comment by NickHaggerty1** [comment]
@meols @fernandolucchesi Nice work.. All tested and approved
