### ISSUE TITLE
Add Promote magazine to the promotion component

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1237]
As an editor I want to be able to promote other magazine stories and/or topic pages.
Please update the promotion component with the following:

- Add Promote magazine as an option:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/8e784aff-3463-40c4-9245-8b2163937982)

- Editors should then be able to either select magazine tags, or manually select magazine and topic pages to promote

![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/91389553-205f-4ae9-879a-4ead245b2d5f)

![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/ba2ffb6a-2557-40b2-9e19-f99fb4f6d4e3)

**Comment by SvSven** [comment]
@fernandolucchesi @padms @bhavi25 this should be ready for technical review

I've added support for promoting magazine articles using tags and by selecting them individually.
Currently you can only select magazine articles, not both magazine articles and topic pages as I feel we really shouldn't blur the lines between components too much. If we do need to have this mix, I would suggest updating the Topic Page Promotion to make that a more generic "Promote Page" component that allows for selecting individual topic pages, magazine articles, news articles, etc.

**Comment by fernandolucchesi** [comment]
Looks good to me ✅

**Comment by meols** [comment]
Thanks @SvSven and @fernandolucchesi - looks good, but referring to @SvSven's  comment above, 
@NickHaggerty1 - can you please comment on the "not mixing magazine and topic" issue and whether we should change "the Topic Page Promotion to make that a more generic "Promote Page"", as @SvSven suggests .

**Comment by fernandolucchesi** [comment]
@NickHaggerty1

**Comment by NickHaggerty1** [comment]
@SvSven @fernandolucchesi @meols If thats the way you want to solve it, then sure. There still will be a need to only promote TOPICS. But we are adding the option to build a promo that can promote say one Sustainability TOPIC page and two Magazine articles on sustainability. So we need the mix (and I guess adding NEW to that mix makes it super flexible)
