### ISSUE TITLE
As Equinor I want to ensure my content performs as good as possible in search engines so that the pages rank higher in search engines

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#124]
## Acceptance criteria
1. Ensure page SEO requirements are met
1. Content is easily indexable by search engines

## Test
Adding meta data to the correct fields.

**Comment by SvSven** [comment]
Related issue: https://github.com/equinor/energyvision/issues/258

Incomplete list of things to do:
- Add default values for fields such as title, description, etc
- Add relevant links to social media accounts. These should probably be set at a central place in Sanity and used to set the values for the NextSeo plugin / other relevant fields.

**Comment by wenche** [comment]
Title has a fallback to page title if it's not set. Meta description can't have default value since it's so special, but we are waiting for Sanity to fix the validation bug in collapsed fieldset. Might be an idea to have the validation as error if it's empty. :)

**Comment by nilsml** [comment]
Also covered by #189
