### ISSUE TITLE
Create missing Ad.Groups roles in Azure for the satellites

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1243]
## Global:
 - [x] Editor
 - [x] Sub Editor
 - [x] Local News Editor
## Argentina:
 - [x] Editor
 - [x] Sub Editor
## Brazil:
 - [x] Editor
 - [x] Sub Editor
## Fondene:
 - [x] Editor
 - [x] Sub Editor
## Japan:
 - [x] Editor
 - [x] Sub Editor
## South Korea:
 - [x] Editor
 - [x] Sub Editor
## Storage:
 - [x] Editor
 - [x] Sub Editor
## Germany:
 - [x] Editor
 - [x] Sub Editor
## Celtic Sea:
 - [x] Editor
 - [x] Sub Editor

**Comment by nilsml** [comment]
Which groups are missing @fernandolucchesi ?

**Comment by fernandolucchesi** [comment]
> Which groups are missing @fernandolucchesi ?

I've updated the issue description with the groups overview.

**Comment by nilsml** [comment]
Process started. Waiting now for ServiceNow to create necessary groups in AD.
