### ISSUE TITLE
As Equinor I want my content to be sharable links on SoMe so that the content is optimzed/displayed correctly 

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#125]
## Acceptance criteria
1. Ensure the correct image and description
1. [Criteria 2]

## Test
Post a link to an article on SOME

**Comment by wenche** [comment]
@BirteThornquist  We need to talk about the content of the title and description for the og: tags. More often than not we tend to use metaDescription and the metaTitle, but in this case it _might_ make sense to use the title and ingress/lead paragraph/preamble instead? To complicate things, I use a combination of the news title and metaDescription at the moment. Why? Just because. 😎

**Comment by wenche** [comment]
For the og: article publishing and modified times I just use the same as in the timestamps for the web version, but I think we should rethink this and either use Sanity generated timestamps for both or use editable for both. Not a mix as in today's  solution.

**Comment by wenche** [comment]
@BirteThornquist  Will use <title> and meta description to make it the same as in the current version and because the lead paragraph more often than not exceeds 160 chars.

**Comment by BirteThornquist** [comment]
Makes sense to me @wenche 👍

**Comment by wenche** [comment]
Added the large version for twitter
![Skjermbilde 2021-04-22 kl  08 28 57](https://user-images.githubusercontent.com/1568252/115666469-e92bd680-a344-11eb-99bb-ee418f139663.png)

**Comment by petterwildhagen** [comment]
![image.png](https://images.zenhubusercontent.com/60376a60b424c72d28d1572f/b04d5cc9-38c9-4b53-ab63-07f6778132b1)

Shared an article on facebook. The bottom looks like this:
![image.png](https://images.zenhubusercontent.com/60376a60b424c72d28d1572f/edec18d6-7bdc-4819-9de4-44e138e45403)

**Comment by wenche** [comment]
Yup, because you didn't add meta title or description in Sanity, so Facebook is doing it's best to guess 🤷‍♀️

**Comment by petterwildhagen** [comment]
It looks better with that yes:)

**Comment by petterwildhagen** [comment]
Looks good on FB, Twitter, LinkedIn when I add the meta title & description. Should there be a validation that meta title and description is missing when publishing? Is it possible to have required and optional fields in the sanity editor?

**Comment by wenche** [comment]
It does actually have a warning if it's missing, but it seems like there's a Sanity bug here. Will ask them

**Comment by wenche** [comment]
I asked Sanity [on the slack channel](https://equinor.slack.com/archives/C01A4BGNRMJ/p1619087827027900) :)

**Comment by wenche** [comment]
And yes, this could perfectly well be an error as well, but we haven't discussed it with Nick & co yet.

**Comment by petterwildhagen** [comment]
Should we add a task for it @wenche ?
