### ISSUE TITLE
Magazine landing page

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1251]
We need a separate landingpage for the Magazine stories, which is a one off template. This page should be created in two steps, with banner options as version 2. 
**Version 1** will be:

- SEO - as today's topic

- hero banner (as today) at the top 

- #1268: NEW tag list displayed horizontally, including magazine search to the right. This should show the 5 (or fewer) "promoted tags selected by editors ( #1226 ), This tag list should also be implemented to the magazine template page.
- #1268: Tag list should be scrolling horizontally (left to right) on mobile (see behaviour inspiration from [Hydro](https://www.hydro.com/en/about-hydro/stories-by-hydro/greener-cities-with-bicycle-racks-from-kairos-optimized-with-hydro-ecodesign/https://www.hydro.com/en/about-hydro/stories-by-hydro/greener-cities-with-bicycle-racks-from-kairos-optimized-with-hydro-ecodesign/))
- text block, as today, but should this be created as a component or be a feature of the template (so the order can't be changed).
- #1269: Latest magazine stories feed shown in tile cards. The tiles should display the banner image, title and maximum two of the promoted tags. Tags should display alphabetically. If more than two tags are chosen, the first two should be displayed.
- #1269: The latest magazine stories tile cards should be shown as a list of 9, and then use pagination (as newsroom) for the next 9.
- #1290 magazine landing page (and magazine template) should always have a subscribe promotion in place at the bottom of the page (above the footer). _Question_: could this be done by using text snippet, to be able to do a site wide change of the text. See sketches for design. The design would also include an image.
Sketches to come from @NickHaggerty1 :smile:

**Comment by meols** [comment]
We need a separate landingpage for the Magazine stories, which is a one off template. This page should be created in two steps, with banner options as version 2. 
**Version 1** will be:

- SEO - as today's topic

- hero banner (as today) at the top 

- NEW tag list displayed horizontally, including magazine search to the right. This should show the 5 (or fewer) "promoted tags selected by editors ( #1226 ), This tag list should also be implemented to the magazine template page.
- Tag list should be scrolling horizontally (left to right) on mobile (see behaviour inspiration from [Hydro](https://www.hydro.com/en/about-hydro/stories-by-hydro/greener-cities-with-bicycle-racks-from-kairos-optimized-with-hydro-ecodesign/https://www.hydro.com/en/about-hydro/stories-by-hydro/greener-cities-with-bicycle-racks-from-kairos-optimized-with-hydro-ecodesign/))
- text block, as today, but should this be created as a component or be a feature of the template (so the order can't be changed).
- Latest magazine stories feed shown in tile cards. The tiles should display the banner image, title and maximum two of the promoted tags. Tags should display alphabetically. If more than two tags are chosen, the first two should be displayed.
- The latest magazine stories tile cards should be shown as a list of 9, and then use pagination (as newsroom) for the next 9.
- magazine landing page (and magazine template) should always have a subscribe promotion in place at the bottom of the page (above the footer). _Question_: could this be done by using text snippet, to be able to do a site wide change of the text. See sketches for design. The design would also include an image.
Sketches to come from @NickHaggerty1 :smile:

**Comment by NickHaggerty1** [comment]
@SvSven @fernandolucchesi 
Mobile and Desktop sketches in Figma (magazine landing page): https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=5977%3A90557

Reach to discuss if/when needed

**Comment by NickHaggerty1** [comment]
Landing page for is a good example: https://www.hydro.com/en/about-hydro/stories-by-hydro/

**Comment by SvSven** [comment]
All of the relevant magazine issues relating to this are in review/acceptance - we should give the full page a good once-over to see if it's in line with the design and to make sure everything checks out.

**Comment by NickHaggerty1** [comment]
@SvSven @meols @fernandolucchesi  @padms Hey. We are looking into the individual cards relating to this so will accept as we go. In general though we a missing some elements for the landing page. In particular banner image (with all the options that are also being worked on) Text block component between the banner and feed. Is this a separate task/card that hasnt been worked on yet?

**Comment by NickHaggerty1** [comment]
![Screenshot 2022-10-13 at 13.32.37.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/c720bce1-2e60-4f16-a67e-03bc728896a7)

**Comment by NickHaggerty1** [comment]
Dont forget about the issue relating to Header placement on the different banners also ref #1146 #1121

**Comment by NickHaggerty1** [comment]
![Screenshot 2022-10-14 at 11.51.50.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/7a968160-2ccb-4320-9b87-2395f75248f0)

**Comment by NickHaggerty1** [comment]
Hi After some thought and discussion with Fernando. We would like to adjust the order/structure for the Magazine landing page only. We felt that the horizontal bar might be too far away from the feed if we feature Title / Text / link between the two. So, as per the sketch above we would like:

- Banner options as Topic and magazine article templates
- Title (H1)
- Text options for H2 / H3 / paragraph -normal/ small (could feature in the dropdown as they do today)
- Option for link as per TEXT block options
- Option for background colour to cover the space between the bottom of the banner and the top of the horizontal bar.
- Horizontal bar as today
- Feed
As we dont have many articles yet have we looked into pagination? We should use the same set up we have in Search / Newsroom

Sorry about the slight adjustment to the order here.

**Comment by NickHaggerty1** [comment]
@meols @fernandolucchesi @SvSven @padms FYI

**Comment by SvSven** [comment]
You should be able to see/test the pagination, I added a bunch of dummy articles: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine

**Comment by nilsml** [comment]
Can we move this to acceptance @fernandolucchesi ?

**Comment by fernandolucchesi** [comment]
@nilsml, nobody has technical reviewed it yet, but if your comment is a "this looks good", yes we can :D

**Comment by nilsml** [comment]
I thought this was more of a collection of tasks where all of these are done

**Comment by NickHaggerty1** [comment]
@nilsml this is something that Mette and I should look - along with the epic - to just ensure all elements have been covered in other issues. Once we are done, we can close this

**Comment by NickHaggerty1** [comment]
@fernandolucchesi @nilsml Hey, we think this is good to close. But there is one issue that hasnt been looked or captured in a separate issue (its not on #1268 for example). That is the comment in the above description: T**ag list should be scrolling horizontally (left to right) on mobile (see behaviour inspiration from Hydro)**  Now on Mobile the tags just stack. Should you create a separate card for this issue? Then I think we can close this one.

**Comment by fernandolucchesi** [comment]
Hi @NickHaggerty1, I will add it to #1268

**Comment by NickHaggerty1** [comment]
Nice. Closing this one then. @meols
