### ISSUE TITLE
Magazine template version 2

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1252]

**Comment by meols** [comment]
The MVP magazine template has been set up, and this is a description of the the next update for it.
Additional requirements for the magazine template:

1. Horizontal tag list, as described in #1251. If users select All stories, they should go to the Magazine landing page, down to the tile list of all stories. If they select a specific tag, they should go to the magazine landing page, down to the tile list of all stories, which should be filtered with the selected tag.

2. Subscribe promotion as part of the template, at the bottom, as described in #1251

Sketches to come from @NickHaggerty1

**Comment by fernandolucchesi** [comment]
@meols, I suggest we close this without deploying to prod, and do the requested changes in the other issue. The work that has been done here will work as a base for #1251.

**Comment by NickHaggerty1** [comment]
Hydro magazine article is a good example of the behaviour for selecting the tab from the bar and going back to Mag landing page: https://www.hydro.com/en/about-hydro/stories-by-hydro/hydro-continues-to-support-youth-and-adolescent-together-with-unicef/

**Comment by fernandolucchesi** [comment]
If I understood correctly, this will be automatically done when #1251 and #1121 are completed. If so, can we close this @meols ?

**Comment by NickHaggerty1** [comment]
@fernandolucchesi No these are additional tasks that need to be added to the Magazine **article** template. Even though its the same horizontal tag bar as mapped out on 1251, That is a unique template for the magazine **landing page**, so the task will need to be added to the article template. This also goes for the Subscribe issue. Same task, but needs to be captured on both templates.

**Comment by fernandolucchesi** [comment]
https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=5977%3A90557

**Comment by NickHaggerty1** [comment]
@fernandolucchesi @padms I know it is still work in progress, so feel free to roll your eyes and tell me ' WE KNOW OK' But I noticed the HEADER/TITLE comes between the full width banner and the horizontal tab bar on the magazine template. I would expect the order to be IMAGE / HORIZONTAL BAR / TITLE![magazine title above tabs.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/0477660e-f3f2-4444-9f76-303e9ed2bf08)
