### ISSUE TITLE
Draft events getting indexed 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1253]

**Comment by padms** [comment]
Fixed in this commit 06d7d4fa0b4001b0c9b6af188d3b534dd7ea5045

**Comment by SvSven** [comment]
Looks good to me ✅
Wish there was a simple setting or something for this with Sanity/GROQ

**Comment by fernandolucchesi** [comment]
@padms, feel free to close this when cleanup in algolia is done :)

**Comment by padms** [comment]
Deleted draft event indexes from algolia.
