### ISSUE TITLE
Add localNews and magazine types to redirects

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1255]

**Comment by padms** [comment]
LGTM, I was able to create redirect for local news and magazine which I needed for linking in menu for the editorial documentation (earlier I was using static links :P).

**Comment by fernandolucchesi** [comment]
Hi @meols, this is ready to be tested at https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/

**Comment by meols** [comment]
Thanks @fernandolucchesi - looks great :smile:
