### ISSUE TITLE
Disable search auto deployment to prod

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1257]

**Comment by SvSven** [comment]
Search is currently automatically deployed on commits. We should disable this for the time being so as to avoid features being deployed that should not be deployed yet.

**Comment by SvSven** [comment]
Should we remove the 

```yaml
on:
  workflow_dispatch:
```

part as well? Not sure if this will cause any syntax errors or anything.

**Comment by fernandolucchesi** [comment]
> 

I am actually unsure. But I know like this works due to other scripts being done this way (PROD and TEST).

I can experiment without when I get some time

**Comment by fernandolucchesi** [comment]
@SvSven we actually need this. Without we get a syntax error:

Missing property "on".yaml-schema: GitHub Workflow

and without workflow_dispatch we get incorrect path error

**Comment by SvSven** [comment]
Weird, but then the whole syntax is a bit weird 😬
We can probably just close this one ✅
