### ISSUE TITLE
Add an option to display two column to the TEXT BLOCK for links and downloads

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1258]
Occasionally we will have a need to display alot of links. This could be solved by having an option to choose to display with two columns. Suggestion for how it should look for editors attached (although if you have a better idea please advise) And sketch of expected outcome

**Comment by NickHaggerty1** [comment]
![link component two column.png](https://ima![text block 2 column links.jpg](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/3a2cb2ba-524e-4ef9-905d-159116e39613)ges.zenhubusercontent.com/62e8c66dc59ea7c87816be13/1254cf2c-f249-4f1c-b199-f55df87f607b)

**Comment by NickHaggerty1** [comment]
![text block 2 column links.jpg](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/9c8e2bbf-44a1-4bd3-883b-ed16fb136b1d)

**Comment by NickHaggerty1** [comment]
![link component two column.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/b2213e0a-149c-4a57-93e0-f215b3c5e37a)

**Comment by SvSven** [comment]
What should the logic here be with regards to number of items per column? Just divide the total amount of items by 2?

Also how should the items be placed?

```
1 - 2
3 - 4
5 - 6
```

or

```
1 - 4
2 - 5 
3 - 6
```

**Comment by NickHaggerty1** [comment]
Yes, divide by two and if there is an odd one, eg 7. The 7th would be on one line, all alone... And placed 1-2, 3-4, 5-6

**Comment by NickHaggerty1** [comment]
![two column odd number.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/3401e3bb-7e94-48e6-9eb4-ea79d21435a2)

**Comment by fernandolucchesi** [comment]
Hi @bhavi25, left some comments for you

**Comment by fernandolucchesi** [comment]
Looks good @bhavi25 ✅

**Comment by bhavi25** [comment]
@NickHaggerty1 Text block for links and downloads has an option for displaying in two columns 
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine/test1_magazine

**Comment by NickHaggerty1** [comment]
@bhavi25 @meols @fernandolucchesi Hey, looks great. thanks. Approved
