### ISSUE TITLE
Improve DNS-processes documentation

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1259]
We should have the documents written in a format / language that both the COM team and the technical team understands.

- [x] Remove old external domain
- [x] Create a new external domain
- [x] Add a CNAME for an existing domain
- [x] Create a SSL certificate for a new domain
- [x] Renew a SSL certificate for an existing domain
- [x] Abbreviations
- [x] Basic DNS knowledge
- [x] Contact information
- [x] Add powerpoint diagram to the document
- [x] Remove old KB document about DNS
- [x] Runbook Update

**Comment by meols** [comment]
@fernandolucchesi - can you please add a link to the documentation?

**Comment by nilsml** [comment]
We need to figure out where to put this documentation.

**Comment by fernandolucchesi** [comment]
[KB0050096](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.service-now.com%2Fselfservice%3Fid%3Dkb_article%26sys_id%3D1a242fe78747d510c83765390cbb35bc&data=05%7C01%7CPADMS%40equinor.com%7Cf85a4eb62458420309cd08dac7eaeebd%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C638042109091736927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iAqL2Iv%2BiJKx75EybVByOUUUJxeLkqgeuVmWdGepFik%3D&reserved=0)  Creating an Equinor Website
[KB0050097](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.service-now.com%2Fselfservice%3Fid%3Dkb_article%26sysparm_article%3DKB0050097%26sys_kb_id%3D88d9fe1e87c7dd907d95eb990cbb358e%26spa%3D1&data=05%7C01%7CPADMS%40equinor.com%7Cf85a4eb62458420309cd08dac7eaeebd%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C638042109091736927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AcDVc%2FnHFL27itpbTyvY6RiNZhEkrWQWjw%2F%2BlwmAM%2B4%3D&reserved=0)  Equinor DNS for Dummies
[KB0050098 ](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.service-now.com%2Fselfservice%3Fid%3Dkb_article%26sysparm_article%3DKB0050098%26sys_kb_id%3Dc24b76d6870bdd907d95eb990cbb352e%26spa%3D1&data=05%7C01%7CPADMS%40equinor.com%7Cf85a4eb62458420309cd08dac7eaeebd%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C638042109091736927%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hGIappSELhZXtAaWtzTrFJB8WEvw70e%2FmiVW8XFIvc4%3D&reserved=0)Requesting DNS mapping
