### ISSUE TITLE
Re-activate equinor.com.au

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1260]
- [ ] Create service-now ticket
- [x] Add redirect inside middleware
- [x] Modify yaml file to add ssl. 
- [x] Once deployed add the ssl certificate in radix

**Comment by meols** [comment]
Can you please reactivate equinor.com.au and point it to the Australia page, that we now have updated and published: https://www.equinor.com/where-we-are/australia

**Comment by padms** [comment]
[RITM2592520](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.service-now.com%2Fselfservice%3Fid%3Dticket%26table%3Dsc_req_item%26sys_id%3D9c36fdc68739dd14ea1854673cbb3535&data=05%7C01%7Cpadms%40equinor.com%7Cf5877461ac874c470fc708da9232d31f%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C637983044240364820%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vMgsMeiB4XCA2sIdOjHyhNspgX2LHCGiz5gyZHSDFF4%3D&reserved=0)
[RITM2592520](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.service-now.com%2Fselfservice%3Fid%3Dticket%26table%3Dsc_req_item%26sys_id%3D9c36fdc68739dd14ea1854673cbb3535&data=05%7C01%7Cpadms%40equinor.com%7C096816350ee14b922e5908da9231eb73%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C637983040338921834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1c%2FwXLPYkcr17wdwp0e5%2BhGjinTeIpuI%2BdtrYfukYVo%3D&reserved=0)

**Comment by padms** [comment]
equinor.co.au is redirecting now. Hence closing
