### ISSUE TITLE
Review Cookiebot reports. 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1261]
Cookiebot scans equinor.com and other satellite sites every month and generates a report. The report contains the cookies scanned for that website and highlights if a cookie is set with out the user's consent.

These reports must be reviewed and mitigate any violations. 

-

- [x] We should let the COM team aware in case settings are missing inside the CMS
- [ ] Verify if code is installed correctly

**Comment by padms** [comment]
@fernandolucchesi @sven please review this. I modified code to block siteimprove script until consent for statistics is given

**Comment by SvSven** [comment]
I don't have permissions to change my hosts file on my Equinor device, so hard to test cookiebot locally.

However I don't see the `https://siteimproveanalytics.com/js/siteanalyze_6003171.js` anywhere in the DOM anywhere on global-dev at radix 🤔

That being said, the commented out condition `&& window?.Cookiebot.consent.statistics` should fix prevent the cookies from being injected prior to consent I think?

**Comment by nilsml** [comment]
@padms will review this together with @fernandolucchesi

**Comment by padms** [comment]
Created a hook for this.

**Comment by fernandolucchesi** [comment]
Left a few comments, please check =)

**Comment by padms** [comment]
@fernandolucchesi  Please check now..

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Please check now..

still missing a dependency in the dependency array:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/23337266/195609754-41347bbd-2baa-401d-86d4-70ffc4ca788e.png">

**Comment by padms** [comment]
Missed that one. Done now

**Comment by fernandolucchesi** [comment]
LGTM ✅
