### ISSUE TITLE
Delete CDN Purge from Azure

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1262]

**Comment by fernandolucchesi** [comment]
Ref #553

Deleted:
https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/a8b981a0-f92f-452c-90dc-d1226778e182/resourceGroups/EnvisRGDev/providers/Microsoft.Storage/storageAccounts/envisstoragedev/eventgrid

https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/a8b981a0-f92f-452c-90dc-d1226778e182/resourceGroups/EnvisRGDev/providers/Microsoft.Automation/automationAccounts/EnergyVisionAutomation/webhooks/CDNPurgeWebhook


https://portal.azure.com/#@StatoilSRM.onmicrosoft.com/resource/subscriptions/a8b981a0-f92f-452c-90dc-d1226778e182/resourceGroups/EnvisRGDev/providers/Microsoft.Automation/automationAccounts/EnergyVisionAutomation/runbooks/CDNPurge/overview

**Comment by fernandolucchesi** [comment]
@nilsml, is there logs in azure where I can see these deletions?

**Comment by nilsml** [comment]
Hmm, not exactly sure. Azure monitoring/insights perhaps, but doubt it.

**Comment by fernandolucchesi** [comment]
> Hmm, not exactly sure. Azure monitoring/insights perhaps, but doubt it.

I see. Not so sure how this can be reviewed. Should I just close it?
