### ISSUE TITLE
Add documentation for Editors about shareable link

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1265]

**Comment by padms** [comment]
LGTM

**Comment by fernandolucchesi** [comment]
hi @bhavi25, can you provide the link so we move this to acceptance?

**Comment by bhavi25** [comment]
@meols  Documentation for sharable preview link can be found here :
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/editorial-documentation/using-the-sanity-studio

**Comment by meols** [comment]
Thanks @bhavi25
