### ISSUE TITLE
Full width image no text top banner

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1266]
Figma: https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=1511%3A0

**Comment by NickHaggerty1** [comment]
![50-50 example.png](https://ima![50-50 mobile.png](https://ima[Uploading... wide screen 50-50.png]ges.zenhubusercontent.com/62e8c66dc59ea7c87816be13/ff1da6b3-5434-4407-9cb9-1d607666e627)ges.zenhubusercontent.com/62e8c66dc59ea7c87816be13/7e7f7b7b-8cd3-4d31-b2e5-7e52a02eba2d)

**Comment by NickHaggerty1** [comment]
Sketches can be found in Figma on TOP BANNERS tab

**Comment by fernandolucchesi** [comment]
@NickHaggerty1 the 2:1 and full screen looks almost the same, is there any other preset you want rather than the ones listed?

**Comment by NickHaggerty1** [comment]
@fernandolucchesi On the sketch you mean right? Bit hard to sketch full screen for all screen sizes. I assume thats something that will be set in the code? to be responsive to screen sizes? The priority would be the 10:3 (like the full width image component) and a full width 2:1.  Full width is less priority as this would be used rarely I think. Be great to see how a full screen could look if thats something you could demo though? :)

**Comment by NickHaggerty1** [comment]
Yup @fernandolucchesi  Topic and Magazine. Obrigado!

**Comment by padms** [comment]
LGTM

**Comment by fernandolucchesi** [comment]
@NickHaggerty1 can you please check this one? :)

**Comment by fernandolucchesi** [comment]
Available at https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk

**Comment by fernandolucchesi** [comment]
If "designer" role is required to modify these banners more work has to be done (design permissions conversation we had a while back)

**Comment by NickHaggerty1** [comment]
[Uploading... banner - title.png]

**Comment by NickHaggerty1** [comment]
@fernandolucchesi @meols hey, as discussed on Friday I have added title / image text to the banner sketch. The spacing would follow the logic/grid for the default banner [banner - title.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/6c7723ad-74f5-4797-afed-ad9b3943c5fc)

**Comment by NickHaggerty1** [comment]
![banner - title.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/300ddff3-586d-4409-ad7e-db3360941505)

**Comment by fernandolucchesi** [comment]
@padms, can you review the latest changes?

**Comment by padms** [comment]
@fernandolucchesi  The full screen image is not working as expected. The image is not taking full height of the screen.

**Comment by fernandolucchesi** [comment]
Hi @padms, thanks :) can you please check again?

**Comment by padms** [comment]
@fernandolucchesi  Left a comment here https://github.com/equinor/energyvision/commit/2895d894881301cc6ab31e49c2329ee1a95e8b5d#r86410264

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Left a comment here [2895d89#r86410264](https://github.com/equinor/energyvision/commit/2895d894881301cc6ab31e49c2329ee1a95e8b5d#r86410264)

Fixed the image src and left a reply about the width, please check

**Comment by padms** [comment]
@fernandolucchesi Sorry for not adding all the comments at once.. Full screen image is not respecting hotspot. Not sure if this is intended.

**Comment by NickHaggerty1** [comment]
@padms @fernandolucchesi the screengrab attached highlights the issue with the title coming after the banner but before the horizontal bar

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Sorry for not adding all the comments at once.. Full screen image is not respecting hotspot. Not sure if this is intended. Otherwise LGTM

Hi @padms, I've just tested and it looks correct to me

**Comment by meols** [comment]
@NickHaggerty1 - can you please check if your comments are captured
