### ISSUE TITLE
Latest magazine stories feed component

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1269]
Latest magazine stories feed shown in tile cards. The tiles should display the banner image, title and maximum two of the promoted tags. Tags should display alphabetically. If more than two tags are chosen, the first two should be displayed.

For reference: https://github.com/equinor/energyvision/issues/1251 https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=5977%3A90557

**Comment by SvSven** [comment]
In order to display the magazine thumbnail, we need to index the hero image in Algolia. Relates to #1153

**Comment by SvSven** [comment]
Took a while longer than expected, but this should be ready for review now.

For the image, I decided to go with indexing the actual `heroImage` object in Algolia and using the `Image` component the way we do everywhere else - this seems like the simplest approach and is in line with the rest of the project.

**Comment by fernandolucchesi** [comment]
HI @SvSven, left some comments in your commits

**Comment by SvSven** [comment]
Fixed the import and left some counter comments 😬

**Comment by fernandolucchesi** [comment]
@NickHaggerty1 should the view on tablet display two columns?

If not then this LGTM! 👍

**Comment by padms** [comment]
@SvSven  @fernandolucchesi  With the new video banner option, the thumbnail image should look for alternative image from seo image I guess.

**Comment by SvSven** [comment]
That's actually a very good point, and will go for topic pages as well. We should have a fallback image for cards in that case - the open graph image for social media could be an option, but not sure how well that is used by the editorial team 🤔

**Comment by NickHaggerty1** [comment]
@fernandolucchesi  Ipad/tablet 2 column display, yes.

**Comment by NickHaggerty1** [comment]
@padms @SvSven @fernandolucchesi Yes good point on thumbnail image. Editorially then we should always use a back up image in addition, if using a video in the top banner. Think that is a good idea to use the SoMe open graph image as that place. I imagine the video top banner will only be used to solve certain pages (yes, on topic and magazine templates) so will be easy to manage on the editors site. @meols fyi

**Comment by padms** [comment]
There is an option in Mux to get thumbnail image from video using the playback id, we can make use of that thumbnail as well. 
https://image.mux.com/WmGkrZ2jgfOfGuUHgKqUY7JZp021LitnPSqlRidZ1z8w/thumbnail.jpg

**Comment by SvSven** [comment]
I've added the opengraph image as a fallback in #1306

@fernandolucchesi has also nicely fixed the columns layout; so I think this is ready to be moved to acceptance?

**Comment by fernandolucchesi** [comment]
@SvSven Yass! ✅

**Comment by NickHaggerty1** [comment]
@fernandolucchesi @SvSven Hey.. Looks good. One small issue we have noticed - and it may be user error here - we added a tag to already published magazine articles and re published. The tag doesnt show on the landing page feed display. And also doesnt get captured as a filter (EG we added innovation to Mettes second magazine and it doesnt show)

**Comment by SvSven** [comment]
Not user error - we don't automatically index things on the global-development dataset, and since the magazine landing page is generated with Algolia content those changes won't show there until we manually trigger the indexing.

Coincidentally I just did that as you posted this comment; since I made some more dummy articles to ensure that we would see/be able to test the pagination as well - so they should be showing now 😁
