### ISSUE TITLE
SEO issue: missing structured data markup

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1270]
To start with we can add this type for all https://jsonld.com/website/ 

The following are based on JSON LD generated by next-seo 
- [x] **News Article / Article type JSON LD for news and local news pages** Required attributes are URL, title, images, date published, date modified, author name ( can be left empty), publisher name, publisher logo, description and body.  
- [x] **Article type JSON LD for magazines** Required attributes are URL, title, images, date published, author name ( can be left empty), publisher name, publisher logo, description.  Good example here https://jsonld.com/article/
- [x] **Web Page type JSON LD for topic pages** https://jsonld.com/website/
- [x] **Event type JSON LD for event page** Required attributes are location (required), start date (required) and end date(required), name and description can be added as basic. This can also be further improved by adding the type of event (virtual or physical), if virtual specify the URL of the online event, if physical specify the location address in detail (but the improvements need some modification in event schema).

Could also look in to adding 
 - [x] Person type for pages having People promotion card. 
 - [ ] Site links search box JSON LD
 - [x] FAQs

Schema validator https://validator.schema.org/
Rich results https://search.google.com/test/rich-results

**Comment by meols** [comment]
This seems to affect all our pages. See description in siteimprove:
https://my2.siteimprove.com/SEOv2/550893/52537632527/Recommendations/StructuredDataMarkupPages

**Comment by fernandolucchesi** [comment]
https://github.com/garmeeh/next-seo

**Comment by fernandolucchesi** [comment]
Hi @padms, looks good! I think FAQ is very important, can you also add it to this issue? And create a separate issue in the backlog for the ones that you are not looking into now?

**Comment by padms** [comment]
@fernandolucchesi I guess Q&A type is not applicable to the content in our site, see here https://developers.google.com/search/docs/appearance/structured-data/qapage#content-guidelines

**Comment by padms** [comment]
@fernandolucchesi  I also added the PersonJsonLd and FAQJsonLd. Only thing left is the sitesearch
