### ISSUE TITLE
As an editor I would like to work in the CMS in a clear and easy to navigate structure so that I can easily find the page I want to work on

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#128]
## Acceptance criteria
1. _Find criteria for easily navigatable structure_

**Comment by nilsml** [comment]
So this one concerns the navigation structure within Sanity Studio. Perhaps this one is what is referred to in item 8. in #270 @wenche? When does it make sense to have a look at it?

**Comment by nilsml** [comment]
Where does this fit? 🤔

**Comment by wenche** [comment]
I think we should have an epic for Sanity

**Comment by nilsml** [comment]
🤔 Wouldn't that be an epic that would exist like forever?

**Comment by wenche** [comment]
Closing this issue in favour of #491
