### ISSUE TITLE
Statoil redirects are 307 (temporary) instead of 301

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1289]
This is probably done in a domain level since we are not doing any temporary redirects inside our code. Investigate where this is being done, and how to fix it.

**Comment by padms** [comment]
NextResponse.redirect uses 307 by default. So, added 301 in the redirect params for DNS redirects.

**Comment by padms** [comment]
@fernandolucchesi  Done

**Comment by SvSven** [comment]
Looks good to me 👍
