### ISSUE TITLE
Review Magazine/Event roles in Sanity

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1291]
Editors should be the only one with access to Magazines.

**Comment by fernandolucchesi** [comment]
Types "eventTag", "event", "magazine" and "magazineTag" were added to the missing content resourcers in the project:

![image](https://user-images.githubusercontent.com/23337266/204516141-b55e7ae3-ed8a-4020-9ed0-2facab2ea5d0.png)

**Comment by SvSven** [comment]
We should probably have this as a standard acceptance criteria whenever we make a new document type - I had not thought of this before 🤔
