### ISSUE TITLE
Add new IP address in whitelist in siteimprove

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1292]
There is a mail from siteimprove to add new IP address in the list of whitelisted IPs 
https://help.siteimprove.com/support/solutions/articles/80001011038

**Comment by fernandolucchesi** [comment]
Investigate if we need it

**Comment by padms** [comment]
> Is there something I need to do?
For most customers, nothing will change. However, if you've previously been advised by Siteimprove to include our service's IP addresses to your allow list, you will now also need to add our new IP addresses. The new IP addresses are listed below.

Based on this, if someone can confirm that we were not asked by siteimprove to add the IP addresses, we can consider to close this issue.

**Comment by SvSven** [comment]
@meols see comment above

**Comment by meols** [comment]
@SvSven - I have read the article, but don't know if it is neccessary or not. Can you please check with Siteimprove Support <help@siteimprove.com>?

**Comment by padms** [comment]
Sent mail to support ..

**Comment by padms** [comment]
Closing this for now. We are not very sure that we need to whitelist IP addresses. We can reopen this if needed.
