### ISSUE TITLE
crude oil update articles should not appear in "latest news" list on news articles

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1293]
The query here: https://github.com/equinor/energyvision/blob/main/web/lib/queries/news.ts#L93-L102

Should be updated to exclude the crude oil news tag.

**Comment by SvSven** [comment]
It's a bit hard-coded with the tag name like that, but we'd have the same thing if we use the `_id` 😅

Looks good to me otherwise ✅

**Comment by fernandolucchesi** [comment]
> It's a bit hard-coded with the tag name like that, but we'd have the same thing if we use the `_id` 😅
> 
> Looks good to me otherwise ✅

Yes, we can add this logic to the sanity component itself instead of harding coding it. Sounds clever I believe.

**Comment by fernandolucchesi** [comment]
@meols, can you please test this on the dev studio?

News tagged with 'crude-oil-assays' will not show up in the component anymore

**Comment by meols** [comment]
@fernandolucchesi  - works at it should now - thanks! :smile:
