### ISSUE TITLE
Review secret website for the quarterly publication 28.10

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1295]
Acceptance criteria:
- [x] Duplication should work
- [x] Newsletter should work

**Comment by SvSven** [comment]
To be handled by @fernandolucchesi and/or @padms

**Comment by fernandolucchesi** [comment]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/23337266/196406377-891a6e49-a0f5-44f8-b2bd-af9ec90d7429.png">

everything working as it should =)

**Comment by fernandolucchesi** [comment]
@meols everything seems to be working fine, can you please test it by duplicating into the dev dataset?

**Comment by meols** [comment]
@fernandolucchesi - I have tested with this page - with some issues: https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/news;01fbe898-9f55-45f8-959e-8c0652d359ee
- Duplication worked
- It took 11-12 minutes for it to show in the news promotion on the front pages
- After 20 minutes it is still not visible on the Newsroom pages

Please look into this - this gives some uncertainties for Friday...

**Comment by meols** [comment]
@fernandolucchesi - my test news are still not visible on the dev newsroom pages (after 3,5 hours). Are newsroom pages set up differently on dev - shouldn't they be visible there almost immediately?

**Comment by SvSven** [comment]
Hi @meols - the newsroom is dependent on Algolia data, and we don't automatically update that in the development environment; we need to do that manually, so that explains why it isn't showing in the newsroom.

The news promotion is (to me) the concerning one that we need to resolve.

**Comment by meols** [comment]
Thanks @SvSven
