### ISSUE TITLE
Issue with people promotion's card

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1296]
Validation of internal link is not working as intended: 

https://equinor.sanity.studio/desk/topicContent;9129713f-25d2-4b22-8c01-6ddfeed19e76

![image.png](https://images.zenhubusercontent.com/619cb66996a338308e2dd0b8/6460461f-d66d-46a1-a5d1-183d50beb75b)

**Comment by SvSven** [comment]
Looks good, bit of an oversight that we didn't think of this when we implemented the link stuff.

Also you missed a refactoring of `parent?.isLink === true` on line 96

**Comment by fernandolucchesi** [comment]
Hi @meols, can you test this on the test environment?

https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/

**Comment by meols** [comment]
Thanks @fernandolucchesi - this looks good :thumbsup:
