### ISSUE TITLE
add magazine as option to topic promotion

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1299]
Relates to #1237

Editorial team should have the option to promote magazine articles alongside topic pages in the same promotion

---

## Acceptance criteria

- [ ] Can select topic pages in Sanity
- [ ] Can select magazine articles in Sanity
- [ ] Cards for magazine articles and topic pages are rendered in the same promotion on the web

**Comment by SvSven** [comment]
The document preview in Sanity for the topic promotion might look rather convoluted, but because of the (incredibly bad) way that Sanity handles references in that function I was forced to do it this way, since the structure of the reference is different between magazine articles and topic pages (topic pages use routes, magazine articles do not).

**Comment by padms** [comment]
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/a240916a-03d9-49f3-889d-8cafc512e09f)

**Comment by SvSven** [comment]
Yeah that probably would be a good idea, good catch 😅
Though I see that @fernandolucchesi already fixed it.

**Comment by SvSven** [comment]
@meols @NickHaggerty1 

This is the change to the promotions discussed in (Add Promote magazine to the promotion component #1237), which was to add the magazine articles to the topic page promotion as an option - it's a small but probably nice change.
