### ISSUE TITLE
Create English + Welsh satellite site

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1302]
Acceptance criteria:

- [x] Add domain to cookiebot
- [x] Create Sanity Roles
- [x] Create Ad Group roles

**Comment by meols** [comment]
Can you please create a new English + Welsh satellite site for Celtic sea? They are in a process with Anne Grete Ellingsen of securing domain(s), and will let us know as soon as possible which domain is the main domain, and if there are additional ones to redirect as well.

**Comment by meols** [comment]
@fernandolucchesi @padms - this will be the domain for this site: **www.equinorcelticsea.co.uk** and they are in dialogue with Anne Grete Ellingsen on it. Can you please start "the process" needed for the domain.

**Comment by padms** [comment]
@meols We need translations for Cookiebot dialog text. I have listed the text[ here ](https://statoilsrm-my.sharepoint.com/:x:/g/personal/padms_equinor_com/EfBIFgfOkdFGmqGzju0hVUoBWc-bZAf9c0NGAUBYnCfCwg?email=meols%40equinor.com&e=fXzzmf)

**Comment by meols** [comment]
Thanks @padms for the file - I'll look into this together with Trude on Monday and send for translations. I hope (and assume :wink: ) that this isn't holding up anything in the process for setting up the site. We will start with the English content (as usual), and someone in the stakeholder end will handle content translations to Welsh afterwards.

**Comment by fernandolucchesi** [comment]
> Thanks @padms for the file - I'll look into this together with Trude on Monday and send for translations. I hope (and assume 😉 ) that this isn't holding up anything in the process for setting up the site. We will start with the English content (as usual), and someone in the stakeholder end will handle content translations to Welsh afterwards.

hi @meols , studio and web are ready to use:
https://studio-celticsea-equinor-web-sites-prod.c2.radix.equinor.com/
https://web-celticsea-equinor-web-sites-prod.c2.radix.equinor.com/

the mapping to the correct domain / ssl takes a bit longer since it is not dependent on us. @padms can you raise service now tickets for these?

**Comment by fernandolucchesi** [comment]
it is already possible to start creating content

**Comment by meols** [comment]
Great! :clap:
Thanks for the urls :smile:
@NickHaggerty1

**Comment by meols** [comment]
@padms - when raising a ticket for it, please note that the planned go-live date for this is 7 November. Can you please ask them to confirm if they are able to deliver for that date.
@fernandolucchesi

**Comment by padms** [comment]
https://equinor.service-now.com/nav_to.do?uri=sc_req_item.do%3Fsys_id=b9c3295a872ad194e70032e83cbb3597

**Comment by meols** [comment]
@padms - please find the translation here: [https://app.zenhub.com/files/224120954/9fbf804a-a57a-448c-a3d3-782fe1a02ce6/download](https://app.zenhub.com/files/224120954/9fbf804a-a57a-448c-a3d3-782fe1a02ce6/download)

**Comment by meols** [comment]
@padms @fernandolucchesi - was the domain in place for this one, and shouldn't a redirect be set up for it? I didn't see a redirect in the Settings for the site.

**Comment by fernandolucchesi** [comment]
> @padms @fernandolucchesi - was the domain in place for this one, and shouldn't a redirect be set up for it? I didn't see a redirect in the Settings for the site.

This is a dns redirect, so should be done in the code. That is also the reason why it is not working, because we need to deploy it and we are on a deployment freeze. Too risky to release it now since other issues would also be released together with this one.

**Comment by meols** [comment]
@fernandolucchesi - thanks for reminding me - and of course agree to wait :smile:
