### ISSUE TITLE
Update Contact us form

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1304]

**Comment by meols** [comment]
We need to update the Contact us form with a new category, **Login issues**.
Request using this category should go to _Service desk IT_ assignment group in ServiceNow: https://equinor.service-now.com/nav_to.do?uri=%2Fsys_user_group.do%3Fsys_id%3Da4ed15756fdc1d00b2cbd6426e3ee4f4%26sysparm_view%3D
Do you need any additional information for this task @padms - assuming it will be a task for you :smile:

**Comment by meols** [comment]
@padms - any other clarifications I should track down before we can prioritize this task?

**Comment by padms** [comment]
This would be a new endpoint for this category:
https://equinor.service-now.com/api/stasa/statoildotcomproject/ContactUs/e8139ed7db2a6200aa5ff1eabf961987/49f29a93dbb2ac10f42b2208059619a7


 


This will assign the ticket to the following CI: SWITCHBOARD IT, which will set Service Offering and Assignment Group(SERVICE DESK IT)

**Comment by padms** [comment]
@meols We are good to go

**Comment by meols** [comment]
Thanks @padms :smile:
@fernandolucchesi - can we please prioritize this (hopefully not to big) task?

**Comment by SvSven** [comment]
Left a comment about the catelog identifier. I'm not very familiar with the forms, but code wise it looks good I think?

**Comment by padms** [comment]
@SvSven  The catalog identifier is same for all environments, so I hardcoded them

**Comment by SvSven** [comment]
@padms Makes sense, looks good to me ✅

**Comment by padms** [comment]
@meols Added new option " Login issues". You can use this page to test https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/contact-equinor

**Comment by meols** [comment]
Thanks @padms - looks great :thumbsup:
I didn't receive an email (Equinor or private email). Should I expect that when in test/dev,, and have we confirmed that tests are received by the correct assignment group?

**Comment by meols** [comment]
Thanks @padms - looks great :thumbsup:
I didn't receive an email (Equinor or private email). Should I expect that when in test/dev,, and have we confirmed that tests are received by the correct assignment group?

**Comment by meols** [comment]
Thanks @padms - looks great :thumbsup:
I didn't receive an email (Equinor or private email). Should I expect that when in test/dev,, and have we confirmed that tests are received by the correct assignment group?

**Comment by padms** [comment]
@meols Yes, I could verify it was assigned to service desk it ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/f9038945-85e5-4e4a-abbe-2af8176ef6ba)

**Comment by meols** [comment]
Great @padms - then this is approved and moved :smile:

**Comment by meols** [comment]
@padms @fernandolucchesi - when will this one be deployed?
