### ISSUE TITLE
Renew ssl certificate for equinor.com

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1305]
Certificate for equinor.com expires on Nov 6, 2022

**Comment by padms** [comment]
https://equinor.service-now.com/nav_to.do?uri=sc_req_item.do%3Fsys_id=d08e0a1587e611d4e06962090cbb3518

**Comment by fernandolucchesi** [comment]
Please escalate to knut 😬

**Comment by fernandolucchesi** [comment]
https://equinor.service-now.com/nav_to.do?uri=sc_req_item.do%3Fsys_id=a38786a987b61150a9faa9383cbb3598
