### ISSUE TITLE
Remove experimental search from studio

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1307]
Feature is buggy and breaks the search bar. 

https://equinor.slack.com/archives/C01A4BGNRMJ/p1664192569467379

**Comment by fernandolucchesi** [comment]
Ideally to be done with upgrading studio, since newest studio version has a search bar that removes the need for the experimental feature.

When upgrading studio we should downgrade rxjs to ^6, follow 🧵 : https://equinor.slack.com/archives/C01A4BGNRMJ/p1665678355962029

**Comment by fernandolucchesi** [comment]
Hi @millianapia! Changes look good, however, I can see that your `.prettierrc.js` configuration file is not being applied. That justifies the number of changes to the yarn.lock file and not add a new line at the end of the files on your changes:

![image](https://user-images.githubusercontent.com/23337266/199709662-299b3664-7c7f-4f94-be03-87cecf2a2431.png)
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/23337266/199709812-a1f5520d-e00d-4c41-81ac-c199dc4812bf.png">
<img width="433" alt="image" src="https://user-images.githubusercontent.com/23337266/199709926-ec87ce8d-3913-48ef-bd5a-9863b413f764.png">

Could you please check? :)

**Comment by fernandolucchesi** [comment]
Looks good!

**Comment by millianapia** [comment]
@meols  @NickHaggerty1  Can you please test this?
Should be able to search for content in sanity:
https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/homePage;homepage-english

before:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/21845545/199733671-3bf5cdf6-ddac-48a8-b6c6-74bb727b38e8.png">

how it should work:
![Screenshot 2022-11-02 at 13 55 50](https://user-images.githubusercontent.com/21845545/199733731-92488e2f-c795-47a8-bb07-aaa06c827765.png)
