### ISSUE TITLE
Improve Dynatrace Installation

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1309]
Move everything to DT PRODUCTION environment / add it to the cookie bot with dtrum.enable()

~

Discuss if needed at all

**Comment by SvSven** [comment]
Left a comment in the code: https://github.com/equinor/energyvision/commit/f7f88cff79182a171c510c83232bba3d5e581345#comments

**Comment by fernandolucchesi** [comment]
> Left a comment in the code: [f7f88cf#comments](https://github.com/equinor/energyvision/commit/f7f88cff79182a171c510c83232bba3d5e581345#comments)

I like the suggestion! Just refactored =)

**Comment by SvSven** [comment]
Looks good, it now also doesn't crash anymore with adblock enabled ✅
