### ISSUE TITLE
As an editor I want the content to be fully responsive so that my content is displayed correctly on popular devices and screen sizes

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#131]
This issue is about testing the solution and verify that everything works good on most popular devices and screen sizes.

## Test
Test content on all pre-defined devices.
Automated testing should be considered.

**Consider this to be an epic**

**Comment by nilsml** [comment]
Another one on responsive design. Should we define devices and screen sizes in the wiki perhaps? Then the requirement will be that we support these. Comments @vnys?

**Comment by wenche** [comment]
Let's just close this one it's way to general

**Comment by vnys** [comment]
In the storybook there’s a shortcut to changing the width of the preview. I added the 10 most used screen resolutions to that list, so all the components can be tested manually based on that. 

![image](https://user-images.githubusercontent.com/2081882/152497615-67b6e296-7e19-44d5-b7c5-a5c31d0f4f60.png)

**Comment by vnys** [comment]
That list could be updated on a semi-regular basis. And perhaps we should also write something about it in the wiki. Not sure this is something everyone remembers, or that new additions to the team know anything about.
