### ISSUE TITLE
Big text component

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1310]

**Comment by meols** [comment]
To be further discussed and detailed out

**Comment by NickHaggerty1** [comment]
![Screenshot 2022-10-13 at 12.40.49.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/a62fcd4d-dca7-437e-8011-a95e916848cc)

**Comment by NickHaggerty1** [comment]
![Screenshot 2022-10-13 at 12.40.49.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/45448473-20ef-4b49-9487-d9aaadb2a65b)
