### ISSUE TITLE
Add Caption and credit fields to Full Width Image component

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1311]
We see the need to have optional caption and credit fields on the wide image also. This should be same as the Image component in terms of style.

Example to follow for placement of where the text should start from will be supplied.

**Comment by SvSven** [comment]
Main question is where to place it in the layout, which column width should it follow

**Comment by NickHaggerty1** [comment]
@SvSven  Lets use the same column placement as the full width top banner image text.....![Screenshot 2022-11-16 at 12.06.20.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/242c8a6e-2a7d-46df-8440-98896c3cd225).

**Comment by SvSven** [comment]
I hereby acknowledge the snake drone arrow 🐍 😂
Also those drones are cool!

**Comment by fernandolucchesi** [comment]
Left some suggestions =)

**Comment by padms** [comment]
Hi @fernandolucchesi this is done, please check.

**Comment by fernandolucchesi** [comment]
Looks good! ✅

**Comment by padms** [comment]
@meols This can be tested
