### ISSUE TITLE
Horizontal scroll for PROMOTION component on Mobile view

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1312]
We would like to have the option to display ALL VARIANTS of the Promotion component to be scrollable/swipeable on mobile view.

Should this be set to default ON? or will this impact on existing promotion examples?  And have the option to toggle off?

This should also include the News template example of promotion that pulls in the last 3 at the bottom.

**Comment by SvSven** [comment]
Relates to #1373

**Comment by SvSven** [comment]
Will be partially solved in #1373

**Comment by NickHaggerty1** [comment]
Agreed with Sven that horizontal scroll should be default setting on mobile for all PROMOTION settings. No need to have a toggle option for editors. 
This goes for:
(Topic / Magazine / News /  - not sure about: People? / Events?)

**Comment by SvSven** [comment]
Handled in #1373

**Comment by NickHaggerty1** [comment]
Approved @fernandolucchesi @meols
