### ISSUE TITLE
Remove Stock text snippet from satellite sites

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1316]

**Comment by meols** [comment]
Can we please remove the "Stock API: NYSE time delay message" text snippet' from satellite sites. It is only relevant for the stock graphs, which only is in use on our investors page (in the global site).

**Comment by SvSven** [comment]
@fernandolucchesi @padms @millianapia 

This is ready for review. I could have solved this with existing flags like `IS_GLOBAL_PROD || IS_DEV` - but this seemed more elegant and may be useful in the future.

**Comment by fernandolucchesi** [comment]
left a comment :d

**Comment by SvSven** [comment]
Fixed!

**Comment by fernandolucchesi** [comment]
Looks good! :)
