### ISSUE TITLE
pagination should scroll to the top of the page when changing page

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1318]
Currently when clicking on a different page in the pagination, it stays at the bottom of the screen - the UX should be that it scrolls to the top when navigating the pagination

**Comment by SvSven** [comment]
I added a `scrollTo` to the pagination code. Unfortunately the `refine()` function from Algolia returns void, so we can't do a promise chain or anything like that; so instead I used a `useEffect`. Initially I was just running it immediately after `refine()` but then it scrolled up while in the background the list changed, which looked confusing and weird.

Might even be an idea to add a short 300ms to 500ms delay before calling it just so it's clear to the user that the list has actually updated. I did hear a good comment that we should consider if this is actually what we want, since we are hijacking the scroll with this behaviour and not everyone always likes that.

**Comment by fernandolucchesi** [comment]
> I added a `scrollTo` to the pagination code. Unfortunately the `refine()` function from Algolia returns void, so we can't do a promise chain or anything like that; so instead I used a `useEffect`. Initially I was just running it immediately after `refine()` but then it scrolled up while in the background the list changed, which looked confusing and weird.
> 
> Might even be an idea to add a short 300ms to 500ms delay before calling it just so it's clear to the user that the list has actually updated. I did hear a good comment that we should consider if this is actually what we want, since we are hijacking the scroll with this behaviour and not everyone always likes that.

Hmm I think adding the delay is nice. Tbh I don't like the scroll to the top, specially because we will probably have a big banner. Can we scroll to an #id and use the magazine tag bar as anchor point instead?

**Comment by fernandolucchesi** [comment]
https://dev.to/dagasatvik10/react-usescrollto-hook-3263

**Comment by SvSven** [comment]
@fernandolucchesi now using React context ✨ 

This is quickly becoming quite over-engineered but yeah 😅
Tried adding the ref to an element a bit above the actual results to compensate for the `position: fixed` topbar, but we can tweak that if necessary.

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi now using React context ✨
> 
> This is quickly becoming quite over-engineered but yeah 😅 Tried adding the ref to an element a bit above the actual results to compensate for the `position: fixed` topbar, but we can tweak that if necessary.

Hi @SvSven, thought about a really simple solution that worked like a charm:
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/23337266/197416793-b9bf673b-6ecc-4208-80e4-d8a847bea519.png">

maybe we should go with this instead of over-engineering? 😅

**Comment by SvSven** [comment]
I considered that, but have always been told that DOM selectors should be avoided in favor of using a `ref` in React 🤷‍♂️
The newsroom is also SSR, not sure if it would work there because of that?

Having a context in place for the pagination specifically might also not be a bad thing either since we can use it to store some other values as well; like the previous refinement (currently use a ref for that)

**Comment by fernandolucchesi** [comment]
Good point. If we are going with use context I believe the ref used should be the one from MagazineTagBar. Also, the context provider is exposing ref and setRef which are never being used, only defaultRef is being used

**Comment by SvSven** [comment]
Ah yeah, I forgot to remove those - I had initially done it different with a pre-made context that included that setRef function; but then I would have had to put the ContextProvider 1 level up for it to work. I'll get rid of the unnecessary leftovers.

**Comment by SvSven** [comment]
@fernandolucchesi have removed the setter function and moved the ref to the magazine tag bar

**Comment by fernandolucchesi** [comment]
Noice! Looks good!

**Comment by SvSven** [comment]
@meols @NickHaggerty1 

You should not automatically scroll to the top of the list when navigating between pagination in the newsroom, search, and magazine index page

**Comment by NickHaggerty1** [comment]
@SvSven thanks, tested on the search in stage at least and looks great. I would say approved
