### ISSUE TITLE
Temporarily redirect celticsea radix url to equinor.com

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1319]

**Comment by SvSven** [comment]
Looks good to me ✅

We should make a note to remove this once the celticsea site is launched.

**Comment by fernandolucchesi** [comment]
@padms, if I understood correctly you raised a service now ticket pointing the equinorcelticsea.co.uk domain to equinor.com. So this logic is not needed... This would be needed in case it were pointing to https://web-celticsea-equinor-web-sites-prod.c2.radix.equinor.com/. But it as good thing that the request is pointing to equinor.com since we are on a deployment freeze and wouldn't be able to handle this logic through middleware redirect

**Comment by fernandolucchesi** [comment]
ref https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=9fde9e9287e25594e70032e83cbb3524
