### ISSUE TITLE
Cleanup and Reindex algolia content

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1321]
- [ ] Fix typo before reindexing content in search/IndexSanityContent/topic/mapper.ts
<img width="722" alt="image" src="https://user-images.githubusercontent.com/23337266/196924850-e373af90-d4fd-4e34-82ed-b607870bc3dc.png">

**Comment by fernandolucchesi** [comment]
I assume this will happen automatically due to the webhook @padms?

**Comment by padms** [comment]
This task is to clean up stale data once before going forward with the webhook solution.
