### ISSUE TITLE
Display magazine tag bar in between header components 

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1322]
#1266 #1121

- [x] Improve title margin #1121

**Comment by fernandolucchesi** [comment]
Hi @bhavi25 left some comments for you, please check :)

**Comment by fernandolucchesi** [comment]
Hi @bhavi25, left a comment

**Comment by fernandolucchesi** [comment]
LGTM!

**Comment by bhavi25** [comment]
@meols @NickHaggerty1 Can you please test this?
Magazine Tag bar in no more in between header components.

https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/magazine/test1_magazine

**Comment by NickHaggerty1** [comment]
@bhavi25 thanks. Looks good. One issue though, if the first component after the banner is set to have a coloured background the Title above it doesnt reflect that colour choice (as its not part of the component) so the colour extends a little behind the title. I have tested on the page you provided so please take a look... Is there a way an editor can adjust the colour/spacing behind the title also to match the first component choice? @meols

**Comment by NickHaggerty1** [comment]
@meols @fernandolucchesi @bhavi25 I guess we could also create a bug for the above issue? And push the deploy with this card included? Dont want this issue to hold up getting the magazine changes published. It can be controlled / Managed by editors not selecting a background in the first text component. But should be looked at.

**Comment by fernandolucchesi** [comment]
> @bhavi25 thanks. Looks good. One issue though, if the first component after the banner is set to have a coloured background the Title above it doesnt reflect that colour choice (as its not part of the component) so the colour extends a little behind the title. I have tested on the page you provided so please take a look... Is there a way an editor can adjust the colour/spacing behind the title also to match the first component choice? @meols

Hi Nick, I thought this would be a requirement just for the magazineIndexPage, I will extend the functionality
