### ISSUE TITLE
Link to another languages feature

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1323]
Add linking to another language support to different components:
- [x] CTA
- [x] Text Link
- [x] Promo sections in menu
- [x] Text Block
- [x] Teaser
- [x] Accordion
- [x] Promo tiles
- [x] Promotion
- [x] Table

**Comment by meols** [comment]
@fernandolucchesi - we'd like the option in all components with link options:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/45da7ae9-cc9b-417b-9e98-f8c210a70092)

**Comment by SvSven** [comment]
Currently the internal link can only reference documents of the same language. We should have an additional option that allows for cross-language referencing.
