### ISSUE TITLE
Mechanism to find unused assets

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1324]
### Feature Flagged 

- [x] studio\src\lib\structure\items\AssetLibrary.js

**Comment by SvSven** [comment]
Looks good to me! Nice and simple ✅

**Comment by padms** [comment]
@meols This is ready for test

**Comment by fernandolucchesi** [comment]
There seems to be an edge case:

![image](https://user-images.githubusercontent.com/23337266/211318620-b460f76f-9245-4d6c-bf8b-c6e6b3d5871f.png)

Displays as unused because it is the draft., but the original is being used. I believe if the original is being used, we should not list the draft: 
![image](https://user-images.githubusercontent.com/23337266/211318808-5a069824-7ab0-4795-ba39-2174f0ee20e2.png)
![image](https://user-images.githubusercontent.com/23337266/211318850-66297537-f06c-4e6a-906e-4c83e86d0ed0.png)


As for the deskStructure, I think:

```
.                                              Unused assets   
.                            ->                Unused videos
____________ 
Unused files                        

```

Has a better UX

**Comment by meols** [comment]
@fernandolucchesi - any acceptance criteria for this?

**Comment by padms** [comment]
@fernandolucchesi  Can I further split this in to published unused assets and new unused assets .. This would simplify the query and will not give "Operation timed out" error..

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Can I further split this in to published unused assets and new unused assets .. This would simplify the query and will not give "Operation timed out" error..

I think it is the best option

**Comment by padms** [comment]
@fernandolucchesi done. Please check now.

**Comment by fernandolucchesi** [comment]
Great! Approved ✅

**Comment by padms** [comment]
@meols This can be tested now. A new folder called "Unused Files" is added under Asset Library, which has four sub folders showing list of published files which are not referenced anywhere, and list of assets which are unpublished drafts.

**Comment by meols** [comment]
@padms - I have struggled a bit with testing this – and also taken a long time, sorry! :smile: Can this functionality only be used for files (mostly pdf and xls) that are created with an “asset container” and not all file formats (images included) that are in media?
If I upload a new file to media it isn’t visible in the new Drafts assets folder, but it needs to be linked to an asset container as well to be shown.
If I replaced a file in an asset container without going to media to delete the old version of it, the old version isn’t showing in any of the Unused files folders when it’s no longer attached to an asset container.
But what I noticed when testing was that in Media we can Browse assets and add a filter for “In use” and choose True or False and then search for e.g. “.xls” to find unused .xls and .xlsx files.
What are the benefits with using the Unused files” folder compared with this search in Media?

**Comment by padms** [comment]
@meols  -  
<img width="539" alt="image" src="https://user-images.githubusercontent.com/52911293/218670890-09091f9e-04e1-49bd-9765-aab156c7b654.png">


If you see the above image, there are some assets that are not used on the actual page. If you filter for unused assets under media, you might see them as being used. 

In order to find which assets are actual used on the page, you have to look for unused asset references. This newly created 'Unused Files' will show the list of all such files.

**Comment by meols** [comment]
OK, thanks @padms - Then we have two ways to find files :smile:
