### ISSUE TITLE
Malin onboarding

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1326]
Let's give Malin a nice and welcoming onboarding! 🥳

--------
# Onboarding
 
- [x] Let's get productive!
    - [x] Add to slack channels
    - [x] Prepare list of nice first issues
    - [x] Setup and run code locally

---

- [ ] Meet the team!
    - [ ] 20 min 1-1 call with @SvSven 
    - [ ] 20 min 1-1 call with @fernandolucchesi 
    - [ ] 20 min 1-1 call with @padms 
    - [ ] 20 min 1-1 call with @nilsml 
    - [ ] 20 min 1-1 call with @bhavi25 

---

- [x] Overview of code practices and development flow
    - [x] ZenHub
    - [x] Agile methodology (Sprint / Meetings)
    - [x] Prettier / Gitmoji
    - [x] How we do code review
    - [x] How we deploy to prod
    - [x] Environments
    - [x] Feature Flags

---

- [x] Overview of documentation and repositories
    - [x] Wiki / Runbook
    - [x] GitHub
    - [x] Azure

---

- [x] Overview of tech stack
    - [x] Architecture
    - [x] Next
    - [x] Sanity
    - [x] Radix
    - [x] Azure
    - [x] Algolia
    - [x] Styled Components

---

- [x] Overview of Equinor process
    - [x] Service now
    - [x] AccessIT
        - [x] LastPass
    - [x] Team structure

---

## Topics suggestions for knowledge sharing

- [x] Satellites setup
- [ ] Roles and permissions
- [ ] CI/CD
- [ ] Azure
- [ ] Brandmaster /  Fotoware
- [ ] Routing in Sanity
- [x] Search (Algolia)
- [ ] Forms / FriendlyCaptcha
- [ ] Webhook / Newsletter

**Comment by nilsml** [comment]
This is a great list!
