### ISSUE TITLE
Investigate if we can index text with striketrough in algolia

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1327]
#741

**Comment by fernandolucchesi** [comment]
Test if this works as intended or not before doing something here

**Comment by padms** [comment]
@meols Title text with strikethrough part should not appear in search results. If you search for struck through text, it should not give any matching results.

**Comment by meols** [comment]
@padms - does this mean that we can't index text with strikethrough should we want to, or that you recommend that we shouldn't do it?

**Comment by padms** [comment]
@meols - We are skipping to index only that part of the text that is struck through. This is only to avoid showing struck through text in the search results. Otherwise, this has no impact.

**Comment by meols** [comment]
Thanks @padms - this is approved :smile:
