### ISSUE TITLE
inform IE users that browser is not supported

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1329]
Internet Explorer is currently not supported on equinor.com - and the experience when trying to access equinor.com with IE11 is pretty shitty:

![image(1).png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/5d4a0905-ca54-43a0-ac83-8b6f37814258)

Despite IE officially no longer being supported, we still get the occasional visitor using IE (6235 in 2022 at the time of writing according to SiteImprove).

We should add a simple redirect/message telling these visitors that their browser is not supported

This can be done using the redirects in next.config: https://infinum.com/handbook/frontend/react/recipes/unsupported-browser-redirection

**Comment by SvSven** [comment]
Created a page with some basic styling informing users that their browser is not supported and to use a more up to date one. 

It works on my end for localhost when trying to view the site using IE11

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/dfe25c05-d345-4378-b0c2-c3edd30be892)

**Comment by SvSven** [comment]
Right, forgot about the security headers. Should be fixed now.

**Comment by fernandolucchesi** [comment]
LGTM!
