### ISSUE TITLE
display list of documents using selected tag in Studio

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1330]
Add the "connected routes" tab to the different tags in the Studio.

I needed a quick way to see which documents were using specific tags while working on something else, and noticed this tab was missing. Figured we should enable it for these documents since it adds value.

**Comment by SvSven** [comment]
@fernandolucchesi this is a minor thing, but I wanted to capture it in an issue so that we can include it in the release log

**Comment by padms** [comment]
Looks good to me, but Settings can be accessible only by editors but not sub-editors (who have access to local news, news, magazine and events ) so they cannot use this feature which might help them.

**Comment by meols** [comment]
Good idea @SvSven - and good comment @padms 
So far I don't think we have any sub-editors, so I don't think we need to handle this for them (at this point at least)
Approved :smile:
