### ISSUE TITLE
upgrade Sanity Studio

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1336]
We have some pending issues that should be fixed in the most recent version of the Studio according to Sanity.
It's been a while since we upgraded, so we should do that.

**Comment by fernandolucchesi** [comment]
related to #1307

**Comment by millianapia** [comment]
@meols @NickHaggerty1 can you also test this. Sanity was updated, and it should not have any breaking changes, just check that it still works as usual. It was updated due to #1307

**Comment by meols** [comment]
@millianapia - haven't seen anything unusual, so if there's nothing specific to test this is OK
