### ISSUE TITLE
As editors we see a need to a simple image carousel component to communicate a image story or timeline

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1339]
## Acceptance criteria
1. Editor can add images (with same upload settings as Image component - fotoware/upload etc)
1. Size should display 2:1 same as default banner on topic page
1. Editor can add SVGs
1. Editor can Crop/hotspot on images
1. Editor can add optional image text per image added in same style as image component
1. Carousel should auto rotate, editor can set transition speed in seconds
1. Carousel should also have options for users to click through.
1. Carousel should indicate amount of transitions for user
1. Optional title for component (Not per transition)
1. Options on colour background as per other components
1. Component should be available for use on Magazine and topic templates

**Comment by NickHaggerty1** [comment]
@meols fyi, and please add any acceptance criteria

**Comment by meols** [comment]
Looks good @NickHaggerty1 - nothing to add :smile:

**Comment by fernandolucchesi** [comment]
#1313

**Comment by NickHaggerty1** [comment]
I have made some sketches in Figma. The page TOP BANNER has a carousel ++ artboard. Im open for input in how best to solve the scroll left and right and display how many options there are. I have some different design options. We have to consider that the same functionality needs to be applied to horizontal scroll on promotion components etc too.

**Comment by SvSven** [comment]
Will be partially solved in #1373

**Comment by NickHaggerty1** [comment]
For design of left and right arrows @SvSven will use the examples in TOP BANNER on figma as a basis and we will look at options to confirm the design once in Sanity. 
[Uploading... carosuel-image-text.png]
We will go for a number indicator display to tell user which slide they are on and how many..... 1 / 6 for example

**Comment by NickHaggerty1** [comment]
![carosuel-image-text.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/7ae066b1-9b3d-4d21-b38b-81bc484d8324)

**Comment by SvSven** [comment]
Some work here was done alongside #1373 - however there are some differences between the 2 components. We can (and should) use the same library for both solutions: https://swiperjs.com/swiper-api

Examples of some customization/implementation can be found in the horizontal scroll component for #1373

**Comment by SvSven** [comment]
@fernandolucchesi @millianapia @padms This is ready for technical review

**Comment by millianapia** [comment]
added a few comments, but looks very good otherwise!

**Comment by SvSven** [comment]
Actually forgot to make the autoplay dependent on the chosen value in Sanity - should be fixed now 😅

**Comment by NickHaggerty1** [comment]
@fernandolucchesi @meols @SvSven. I say approved!
