### ISSUE TITLE
As a user I would like to be able to switch language so that I can access the preferred language easily

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#134]
## Acceptance criteria
1. User can find language switch and  easily change language

## Test
User testing is required

**Comment by nilsml** [comment]
Can we close this one @wtol?

**Comment by wenche** [comment]
This is @SvSven 's baby. We can probably close this, but the news archive doesn't have the language switch yet. But I mentioned that in the issue #449 as well

**Comment by nilsml** [comment]
@SvSven

**Comment by SvSven** [comment]
The functionality is there but the design and UX is not.
Though that can be part of the menu in general I suppose.

**Comment by wenche** [comment]
Close. No longer relevant as this is already done and the only remaining issue of wether we should show the switch or not if a page doesn't have translation is covered by #743
