### ISSUE TITLE
We would like to make some visual adjustments the news template ´feed´

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1340]
Particularly on desktop the news template ´news feed´ at the bottom of the page, the promo card display is quite large compared to our other promo cards. We would like to refine the presentation of these and also add some elements to make the content scrollable on desktop and mobile instead of stacking (on mobile)

**Acceptance Criteria:**
1. Reduce the column width promotion cards (currently its almost full screen width)
1. Set a character limit on the title or ingress to reduce the height of the promotion card. Solve with ... at the end.
1. Have scrollable function to show more news articles (ref apple site at bottom of https://www.apple.com/environment/)
1. Feature 6 news articles
1. Should be scrollable via arrows/click on desktop and swipe and arrows/click on mobile

**Comment by NickHaggerty1** [comment]
![newsroom scroll.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/79c200f7-18f0-4c3f-b786-4df6453d414e)

**Comment by fernandolucchesi** [comment]
@NickHaggerty1 can we close this? I believe this has been covered in other issues already?
