### ISSUE TITLE
Update prompt text for unpublish

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1343]

**Comment by meols** [comment]
When editors want to unpublish a page, the prompt/warning text is a bit misleading. Can we please replace "delete" with "unpublish". ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/589acd81-79d5-4d0e-9880-5f9275e3e643)

**Comment by padms** [comment]
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/c1d442a9-a2ed-4e0c-b4eb-475231798ead)

**Comment by padms** [comment]
@meols I see this is updated in dev and test. No action is needed. :)

**Comment by meols** [comment]
Great! Thanks @padms

**Comment by padms** [comment]
Closing this as this is verified.
