### ISSUE TITLE
As an (end) user I want to be able to navigate to different Equinor sites so that I can explore them

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#135]
## Acceptance criteria
1. User can find site overview and  easily change. Unique editorial access. _(needs refinement)_

**Comment by nilsml** [comment]
I guess this is about the satellite pages and how to reach them

**Comment by nilsml** [comment]
We need to have a discussion about this and how the UX should be.
Technical solution, UX for the user and for the editors.

**Comment by wenche** [comment]
Bonus issue: It's a bug on hover in the main menu
![Skjermbilde 2022-04-04 kl. 13.50.10.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ba9d0f51-2687-4bb6-a6b5-34d3353baa01)

**Comment by wenche** [comment]
What's the simplest solution for fixing this on short term?

We need a way to create the content. Use a topic page?

**Comment by SvSven** [comment]
Suggested (and accepted) solution was to use a topic page with the promotion tile component to recreate this page in Sanity

**Comment by SvSven** [comment]
The URL for this page has changed from `/languages` to `/about-us/all-sites`
I have added the missing href to the `SiteMenu` and used the old URL which is currently used on equinor.com

We can set up a redirect in Sanity to point it in the right direction, and then update it in code after we have gone live.
