### ISSUE TITLE
upgrade to Next 13

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1350]
Next 13 has a lot of nice new features, we should upgrade 🎉

https://nextjs.org/blog/next-13

**Comment by fernandolucchesi** [comment]
Looks good!

**Comment by millianapia** [comment]
@meols @NickHaggerty1 FYI we recently upgraded to next 13, it has been active in our dev/test environment the last week and has not shown any breaking changes; as we are aware of. So if there are some new unexplainable issues that starts to appear, this might be the reason why. So if either of you can verify that nothing unusual has started to appear, that would be great:)
