### ISSUE TITLE
As an editor I'd like to have a  clear definition of text settings to easily display text content

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#136]
## Acceptance criteria
1. Text component delivers design requirements (Semantic HTML/W3 standards are met)

**Comment by nilsml** [comment]
What is the status on this one? Is it taken care of?

**Comment by wenche** [comment]
I have no idea about what this guy, Nils Magne, is talking about 🤷‍♀️

**Comment by nicholas-haggerty** [comment]
Isn't this in place? Think we can close this

**Comment by wenche** [comment]
Closing.
