### ISSUE TITLE
fix check-code CodeQL warnings for web & studio

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1365]
We're getting some warnings in the check-code action in the CI. We should have a look at them and fix the ones we can (e.g. unused imports, unexpected any, etc).

**Comment by SvSven** [comment]
@equinor/envis-devs fixed a number of different warnings that were popping up from the `check-code` action. Unfortunately that action ignores the `@typescript-eslint/no-explicit-any` comments, so it will keep showing this warning in a number of places where we can't or don't want to add explicit types

**Comment by fernandolucchesi** [comment]
Looks good!
