### ISSUE TITLE
fix padding on search button in topbar

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1366]
The padding around the icon for the search button in the topbar is not correct:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/0d52b440-8b00-489d-b5fb-0350e27fe335)

The padding should look like this according to EDS:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/65993a7f-5d8e-49ca-9214-3b168420f462)

https://eds-storybook-react.azurewebsites.net/?path=/docs/inputs-button-button--icon-button

**Comment by millianapia** [comment]
its on the closing button too

![Screenshot 2022-11-10 at 13 22 28](https://user-images.githubusercontent.com/21845545/201090558-9517f805-4d0d-436b-9a27-4b690ad86f0c.png)

**Comment by SvSven** [comment]
Looks good to ✅

**Comment by millianapia** [comment]
can either @meols or @NickHaggerty1 verify if the buttons looks good and centered?

**Comment by NickHaggerty1** [comment]
@millianapia Thanks Malin Looks good on both. Approved. Good catch on seeing this too.. FYI @SvSven
