### ISSUE TITLE
fix duplicate route indexing in search

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1367]
Because of our routing system in Sanity, some routes may get indexed in Algolia multiple times whenever the referenced topic content gets changed. This is because the `objectID` used in Algolia is based on both the route document ID and its referenced content. One of the pages where this can and has happened is the homepage, since the editors will prepare a new topic content to use as homepage ahead of time.

We should update the indexer to only use the `_id` of the route document so that we don't get "duplicate" content in Algolia.

**Comment by SvSven** [comment]
I'm gonna go ahead and tag @nilsml to have a look at this since he understands the functional code much better than me 😅

**Comment by millianapia** [comment]
Commented on someplaces where the code could be reused - if that is possible

**Comment by nilsml** [comment]
Isn't this what we discussed last week at the office @SvSven? If we should use the slug instead. This `_id`, is that some new field we've added?

**Comment by nilsml** [comment]
I had a look at the code. I think @padms has done a great job with the functional code! A couple of small improvements suggested in comments. One being to extract some of the code that is common .

To get the bugfix out, we could create a new issue to refactor this a little bit later on.

**Comment by fernandolucchesi** [comment]
@padms

**Comment by padms** [comment]
No.. @nilsml did some refactoring... and this can be improved later.

**Comment by fernandolucchesi** [comment]
@padms can we move this to acceptance or close this then?

**Comment by padms** [comment]
We can close this as this is tested in #833.
