### ISSUE TITLE
Rewrite how we use Next/link to avoid using LegacyBehaviour

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1369]
When upgrading to next 13, we added LegacyBehaviour on each NextLink so we could continue to pass <a>-links that are styled inside of the nextlinks without triggering an error. This needs to be rewritten in the future, adding LegacyBehaviour gives us some time.

**Comment by meols** [comment]
@padms - hopefully nothing I should approve for this one, since I don't understand much/anything of it :grin:

**Comment by padms** [comment]
@meols  This is a refactoring to use latest code, we have to just verify that the links work as expected.
