### ISSUE TITLE
fix alignment of promotion cards

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1371]
For certain screen sizes, the event promotion cards are aligned to the left even when there are less than 3 cards being rendered. 

See example below:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/73656d02-0e62-446d-a670-08f7a69049a4)

We should fix this so that the cards are always center aligned regardless of the number of cards.

**Comment by SvSven** [comment]
Problem is visible on this page https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/event-promotion

**Comment by millianapia** [comment]
> I'm not sure if this was an issue before, or if it's new - but there is some weird behaviour between 990px and 1176px where the cards go to a centered 1 column width when there are 2 present.

super weird, will look at that

**Comment by millianapia** [comment]
@SvSven should be working correctly now

**Comment by SvSven** [comment]
That fixed it, yes! However the cards are no longer all the same size 🤔 I remember having issues with that before as well; not sure how we ended up fixing it.

@NickHaggerty1 what do you think? This page has a bunch of event promotion cards to test with: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/event-promotion

**Comment by NickHaggerty1** [comment]
@SvSven looks good to me... One small issue I noticed, on Safari browser and full screen, the CTA buttons increase in height. This does not happen on chrome![Screenshot 2022-11-16 at 11.11.50.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/f4f3ffaa-5679-47ad-aea8-313b30cc3f41).

**Comment by millianapia** [comment]
found new weird bug with the same components. They start to left align themselves between the width of 1901-1969, and only between those. Will look at this and the weird increase of button heights. Might separate the button bug into a new issue if it is a larger task 

![Screenshot 2022-11-16 at 12 30 45](https://user-images.githubusercontent.com/21845545/202169341-212ae89d-a95b-45a6-ae35-f0fc2509b8ba.png)

**Comment by millianapia** [comment]
The button issue is present on other browsers as well

**Comment by NickHaggerty1** [comment]
Sounds good, thanks Malin

**Comment by millianapia** [comment]
in need of a new technical review

**Comment by SvSven** [comment]
LGTM ✔

**Comment by meols** [comment]
Thanks @millianapia - looks great :smile:
