### ISSUE TITLE
As editors we see a need to promote images when using the Accordion component for CVs

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1372]
## Acceptance criteria
1. Add an optional image component to Accordion component
1. Design / sizing / options would be based on the Quote component image options
1. Image would need to appear first in order (image / title / ingress / accordion element)

**Comment by NickHaggerty1** [comment]
![image-to-accordion.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/f6428192-fc20-4bc7-91e7-9b6010726bde)

**Comment by SvSven** [comment]
Should not be in the accordion content, but with the title and ingress

**Comment by fernandolucchesi** [comment]
Hi @padms, left a comment

**Comment by padms** [comment]
@fernandolucchesi  Please check now

**Comment by fernandolucchesi** [comment]
Looks good!

**Comment by padms** [comment]
@meols Ready to be tested

**Comment by meols** [comment]
@padms Looks good to me :thumbsup:
