### ISSUE TITLE
As editors we would like to use a horizontal scroll for our promotion components on desktop and mobile to promote more content and take up less vertical real estate

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1373]
## Acceptance criteria
1. Optional horizontal scroll option for all Promotion component options (NEWS / PEOPLE / TOPIC / MAGAZINE / EVENTS)
1. Also should be used for NEWS article template newsfeed (at bottom of the page) #1340
1. Horizontal should work on all devices / screen sizes.
1. Explore whether same implementation should apply to PROMO TILES components....
1. Discussion/meeting required on best way to solve the Users interaction with the left / right navigation. Use of horizontal bar to indicate location in the scroll (ref Ikea) arrows left / right. Other ideas/inspiration?
 
Inspiration:
https://www.ikea.com/no/no/ (third module down)
https://www.apple.com/environment/ (bottom of page)

**Comment by NickHaggerty1** [comment]
As discussed with @SvSven. FYI @meols 

- Mobile horizontal scroll will be default ( #1312)

- Editor can choose to display horizontally for Desktop
- If editor **does not** select to display horizontally. The usual 3 are displayed and no option for horizontal scroll
- If editor **does** select to display horizontally. They have additional options to add/display more cards. Then Left right arrows (same solution as carousel component) would appear on Desktop and also bar underneath to indicate where user is in the scroll.
- For each choice (Topic / News / Magazine) we need to define unique options for amount of cards to display.

**Comment by SvSven** [comment]
For future post-Christmas self:

- Horizontal scroll currently works for Topic, News, Magazine, People, and Event promotions.
- Navigation arrows are hidden at start/end respectively.
- A toggle has been added to the Promotion component in Sanity to always have the horizontal scroll enabled (if content is greater than allowed space)
- By default, all promotions will show horizontal scroll on smaller screens
- Scrollbar and navigation arrows have been added

Left to do:
- Styling of navigation buttons is currently EDS styling; does not conform to Figma yet
- Update validation for promotion to allow user to select more than 3 cards if the horizontal scroll is enabled manually
- Add horizontal scroll to "latest news" at the bottom of news articles per acceptance criteria 
- Placement of navigation arrows looks weird on larger screens; should ideally not overlap cards
- Figure out why navigation buttons show if horizontal scroll manually enabled but not initialized (enough width for content)

For testing: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/carousel

**Comment by SvSven** [comment]
@equinor/envis-devs this is ready for technical review - I'm fully expecting some problems/comments here given how long this has been worked on 😅

This also solves #1312 - horizontal scroll should always be default on smaller screens for promotions

The idea was that the horizontal scroll component would handle more content/cases than cards (used in promotions) but I'm not 100% sure if that's needed.

**Comment by NickHaggerty1** [comment]
@SvSven Firstly, great job, this is looking very good on the components it has been created for.. Small comment from me, Can the Left arrow button display as soon as the Right button been clicked. Currently it only appears when the user reaches the end of the scroll (you can see this on your TOPIC promotion test page)

**Comment by SvSven** [comment]
Yeah I think those arrows are going to be the death of me.

@NickHaggerty1 I'll have a look to see if I can tweak the showing/hiding of the navigation arrows a bit, currently it's doing some automagic things for it.

Also the difference in card image; that's weird, they should all be the same size 🤔

**Comment by SvSven** [comment]
@fernandolucchesi @NickHaggerty1 navigation arrows should now properly show/hide and the cards should all be the same width as well

**Comment by NickHaggerty1** [comment]
@SvSven You have shown them buttons who's boss thats for sure! Nice work

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi @NickHaggerty1 navigation arrows should now properly show/hide and the cards should all be the same width as well

I think the width should vary accordingly to the carousel type:

![image](https://user-images.githubusercontent.com/23337266/214054357-f68b6478-71a4-4dd1-ae8e-be654b1992a3.png)
![image](https://user-images.githubusercontent.com/23337266/214054458-672d7d1b-7174-4d82-9b0a-a9fa0ddf0385.png)

**Comment by SvSven** [comment]
@fernandolucchesi the issue with the people promotion card width should be fixed now. We might want to refactor the implementation slightly when we add support for iframes in a horizontal scroll, but for now it should be fine.

@NickHaggerty1 To try and move things along a bit better, I made a separate issue for adding the horizontal scroll the to promo tile component, see: #1485

**Comment by fernandolucchesi** [comment]
looks good! approved! ✅

**Comment by NickHaggerty1** [comment]
Approved. @fernandolucchesi @meols But there is a small bug that maybe is only on Stage? The EVENTS promotion comes with a warning to select a tag. Even through I have selected to manually choose my events.

https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;a353cb14-028f-45dd-bbea-4010d6968d3e

**Comment by NickHaggerty1** [comment]
![events promo error manual select.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/22c70b7b-cdd4-425f-bee0-7f4a3a3f87a8)

**Comment by millianapia** [comment]
@NickHaggerty1 currently looking into this

**Comment by millianapia** [comment]
@NickHaggerty1 this happens when you toggle manually choose events, when select by tag toggle is still toggled - even though it is hidden. I will try to make a quick fix for this

**Comment by NickHaggerty1** [comment]
Nice thanks @millianapia

**Comment by millianapia** [comment]
@NickHaggerty1 should work as expected, could you verify before we move this issue to the deploy column

**Comment by NickHaggerty1** [comment]
@millianapia Good stuff. Approved, works as expected. Thanks

**Comment by millianapia** [comment]
@NickHaggerty1 i also made it so the navigation buttons now are hidden when used on a phone size, hope it looks ok

**Comment by NickHaggerty1** [comment]
Yeah thats great. Lets go for that @millianapia until someone complains about the lack of arrows! Thanks for fixing. Approved
