### ISSUE TITLE
Refactor how news and localNews are fetched

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1374]
The way news is currently being fetched is not optimal because it always require an extra check and additional logic to manipulate the news data.

We should standardise the way different documents are fetched to simplify our code and make it easier to understand.

**Comment by millianapia** [comment]
Looks good! love the refactoring, easier to follow how it is fetched

**Comment by meols** [comment]
@fernandolucchesi - today I am at the office, and preview doesn't work:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/9d1471fb-a33e-403f-9e6d-da415752158a) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/22df8776-5422-482e-b27f-9059d3d744d6) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/6a9105e7-b765-46bc-af3d-1a0f594e3c85)

**Comment by meols** [comment]
And FYI @fernandolucchesi Knut Jarle will escalate the ticket in ServiceNow (RITM2624670)

**Comment by fernandolucchesi** [comment]
> And FYI @fernandolucchesi Knut Jarle will escalate the ticket in ServiceNow (RITM2624670)

these are not working from the office because of #1244 😅

**Comment by meols** [comment]
@fernandolucchesi - there is preview (tab) and then there is preview (image) :smile: - but neither are working. Assuming this was related to the preview tab then (and #1379)
