### ISSUE TITLE
Bug when updating time/date on an event page

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1376]

**Comment by meols** [comment]
When changing the time from 16:30 to 16:15 (on a published event page for the autumn conference), the new time (and date) disappears when changing to Norwegian, and the updated Norwegian time/date changes when changing back to English. But if we publish the English page and then change to Norwegian and publish that it works as expected.

**Comment by SvSven** [comment]
Seems like you don't have to change anything in the time - just switching between the different languages seems to reset the date and time fields to blank...

**Comment by SvSven** [comment]
@fernandolucchesi @padms @millianapia 

Should be fixed now, can't really feature flag it but everything looks to work again

**Comment by SvSven** [comment]
@meols Should be fixed on the dev dataset now https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk

**Comment by meols** [comment]
Thanks @SvSven - looks great!
