### ISSUE TITLE
Rich text title for promotile component. 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1377]
Title for Promo tile component should have rich text options.

**Comment by fernandolucchesi** [comment]
Hi @padms, keeping 2 fields for the title doesn't sound like the best solution here. We should migrate the string to text blocks using a script. I found this one for textblock that might be interesting looking into: https://www.sanity.io/schemas/migrate-plain-text-field-to-portable-text-a05f0300

**Comment by padms** [comment]
@fer Please check the migration script

**Comment by fernandolucchesi** [comment]
Hi @padms, left new comments =)

**Comment by padms** [comment]
Please check now..

**Comment by padms** [comment]
Please check now..

**Comment by fernandolucchesi** [comment]
Looks good! ✅

**Comment by padms** [comment]
@meols Ready for testing

**Comment by meols** [comment]
Thanks @padms - looks great :thumbsup:
