### ISSUE TITLE
Replace Reach UI components with something maintained 

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1378]
[Reach UI is currently not maintained](https://github.com/reach/reach-ui/issues/972), they suggest using one of the following libraries instead:
- Radix UI
- Ariakit
- React Aria

The following components needs to be refactored to a new library:

- [x] Accordion
- [x] Skip-nav
- [x] tabs
- [x] window-size

**Comment by fernandolucchesi** [comment]
Hey @millianapia, left some comments in your commits =)

**Comment by millianapia** [comment]
@fernandolucchesi have now refactored and fixed the UI changes after your recommendations :) ready to be reviewed again

**Comment by fernandolucchesi** [comment]
Hi @millianapia , left a couple more comments :P

**Comment by millianapia** [comment]
@fernandolucchesi fixed some things, added a couple of TODO and an explanation for the styling choices

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi fixed some things, added a couple of TODO and an explanation for the styling choices

Nice! @millianapia I've replied to the thread about the stylings

**Comment by fernandolucchesi** [comment]
Looks good!

**Comment by millianapia** [comment]
Hi @meols @NickHaggerty1 , we have replaced a library that we used for a few components. There should not be any difference from your part, only from a code perspective. So the testcase is to check if these components are working like before:
- Accordion
- Tabs
- Skip Nav/skip to content

![Screenshot 2023-01-18 at 09 12 02](https://user-images.githubusercontent.com/21845545/213117957-d883a982-4f8d-4615-ab5a-e951454463b2.png)

![Screenshot 2023-01-18 at 09 12 46](https://user-images.githubusercontent.com/21845545/213118083-400329eb-7dcd-48de-93db-7ea501e479d4.png)

![Screenshot 2023-01-18 at 09 13 21](https://user-images.githubusercontent.com/21845545/213118229-b72e364c-a625-4195-8dcf-e1e71a81b9c1.png)

**Comment by millianapia** [comment]
@meols @nicholas-haggerty

**Comment by meols** [comment]
Works like before as far as I can see :thumbsup: Thanks @millianapia
