### ISSUE TITLE
Preview for algolia pages

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1379]
Newsroom preview and Magazine Index preview do not work when opening in a new tab, and cannot be shared.

**Comment by SvSven** [comment]
I like the refactoring, especially with the `sameLang` and `noDrafts`, and the preview for the magazine index and newsroom now work - but the magazine preview problem from #1344 is now back 😅

**Comment by fernandolucchesi** [comment]
@SvSven, can you please check it again?

**Comment by SvSven** [comment]
Issue still persists for unpublished magazine article with a slug. It is however now saying it needs a slug to preview when it doesn't have one yet

https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/magazine;6c1c14fe-b728-4082-8a8d-dfa5e64a6c77%2Ctemplate%3Dmagazine

**Comment by fernandolucchesi** [comment]
Found the error. Should be fixed now 😬 @SvSven

**Comment by SvSven** [comment]
Perfect, that fixed it! Can't say I fully understand _why_ that fixed it; but it works 😬

**Comment by fernandolucchesi** [comment]
@meols can you review this one please?

**Comment by meols** [comment]
@fernandolucchesi - preview without a slug doesn't seem to work for news or magazine. (tested at the Fornebu office) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/8ee2eb88-8868-44f8-a203-f60a01a42250) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/f51d34ba-2de8-4dc1-a08c-d3c8050ac046) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/5109fac5-c0fd-4013-9833-3cf7ab339ae4)

**Comment by fernandolucchesi** [comment]
Hi @meols, the magazine, news, and local news will need a slug to be previewed properly (no need to publish it)

**Comment by meols** [comment]
@fernandolucchesi - then it's OK. Not crystal clear what should be tested and what the acceptance criteria were for this one (at least not to me).

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - then it's OK. Not crystal clear what should be tested and what the acceptance criteria were for this one (at least not to me).

this is the preview for misc > newsroom and magazineIndex

**Comment by fernandolucchesi** [comment]
it didn't exist before
