### ISSUE TITLE
Horizontal scroll for MAGAZINE TAGS component on Mobile view

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1380]

**Comment by fernandolucchesi** [comment]
Hi @millianapia, looks like everything works as it should! So nice job!  However, I also think that we could use this issue as an opportunity to refactor the whole Image.tsx file, since the logic there is very old and looks like Frankenstein. 

From what I can understand of our code, our component only uses two layout options: fill and responsive. I would suggest we create a new Image wrapper for the Next 13 images, and make sure we are using only what is really needed for each layout.

For example, in the `NewImg` component you created, the prop "sizes" is being used when the layout is 'fill'. From [the docs](https://github.com/bundlesandbatches/next-sanity-image), looks like we can omit that, but hard to make sure nothing else will break.

My suggestion is to have a component that takes the layout as a prop, and conditionally checks if other props are required by typescript, something like:

```
type ImageType = ...
type = {
    layout: 'fill'
} & ImageType | {
   layout: 'responsive',
   sizes: string
 } & ImageType etcs 
```

It would also be nice to have a switch statement for the returning of the images to make it more readable, and comments explaining the differences between each layout, as they provide in the docs:
```
switch (layout) { 
   ...
}
```

Annnd, looks like your prettier has stopped working 😅

**Comment by padms** [comment]
@millianapia This issue is related to the Horizontal Tag Bar component. See https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/gh/equinor/energyvision/1251

**Comment by NickHaggerty1** [comment]
@millianapia Hey. Think you have had some dialogue with @meols on this. Its ok to keep the horizontal scroll for tags in the card promos (though hopefully most stories would only have 1 or 2).
Its the actual bar that would need to scroll on mobile as current the tags stack (poorly)
Adding an image of the sketch in Figma....![mobile horizontal scroll bar.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/e8c89585-86c0-4dda-bcdc-a8168f7c6036).

**Comment by millianapia** [comment]
@padms now it includes for the top tags too, can you do a quick code review?

**Comment by padms** [comment]
Looks good to me

**Comment by millianapia** [comment]
@meols and @NickHaggerty1, it is now ready to be tested. I have added a horizontal scroll for both the tags under each card and for the top tag component. As it is magazine related, it would be great to have it reviewed before deploy tomorrow

**Comment by NickHaggerty1** [comment]
@millianapia Great job! Looks good to me. I say approved!
