### ISSUE TITLE
Encode pathname in middleware for redirects

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1381]
When a slug is added using special characters in the redirect tab, the middleware captures it as utf8. So special characters such as åøæ will be replaced by their respective codes. This should not happen otherwise the redirect path will not be found.

**Comment by fernandolucchesi** [comment]
Left a comment @padms

**Comment by padms** [comment]
@fernandolucchesi Done

**Comment by fernandolucchesi** [comment]
@padms looks good!

**Comment by padms** [comment]
@meols This is ready to be tested in dev

**Comment by meols** [comment]
Thanks @padms - this looks good :thumbsup: But I wonder why we get the red warning at the same time as it is published?

**Comment by padms** [comment]
@meols I am not able to replicate the above issue.

**Comment by fernandolucchesi** [comment]
> Thanks @padms - this looks good 👍 But I wonder why we get the red warning at the same time as it is published?

Hi @meols, there was a tiny bug in the validation. I have just fixed it, can you please test again?

**Comment by meols** [comment]
Thanks @fernandolucchesi for fixing the bug
