### ISSUE TITLE
create functionality to index dev dataset in Algolia

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1383]
Currently we need to build and run the search indexers locally with the correct env variables, and then manually trigger the function in order to index the dev dataset. We should set something up to make this easier and robust

**Comment by fernandolucchesi** [comment]
I believe the Algolia webhooks fix this. @padms

**Comment by padms** [comment]
@fer Currently there is only production environment, dev indexing happens based on the payload from webhook. Environments are not isolated.

**Comment by SvSven** [comment]
We don't have anything set up to index the dev dataset, no. The AzureFunction needs environment variables during build time for this as far as I know. cc @nilsml
