### ISSUE TITLE
Improve menu links performance

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1384]
All menu links are prefetched when menu is opened. This impacts performance considerably. We should disable prefetching for menu links in order to provide better user experience.

**Comment by nilsml** [comment]
Are we using latest link component? We don't see this issue in Data Marketplace as far as I know. Or is it actually a bug in the new Next version?

**Comment by fernandolucchesi** [comment]
> Are we using latest link component? We don't see this issue in Data Marketplace as far as I know. Or is it actually a bug in the new Next version?

We are using next 12 link
