### ISSUE TITLE
Fix preview by id

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1386]
When previewing documents by ID the locale is not being set.

(Fixes problem with promotion cards preview)

**Comment by millianapia** [comment]
LGTM!

**Comment by fernandolucchesi** [comment]
@meols can you test this on dev environment? =)

**Comment by fernandolucchesi** [comment]
@meols can you test this on dev environment?

**Comment by meols** [comment]
@fernandolucchesi - if the Norwegian versions of the promoted pages should show automatically in preview after duplicating to Norwegian without relinking to the Norwegian pages, I don't see them on the Norwegian page. Tested on [this page](https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;d17dc252-5deb-402e-b513-b59ac78bafc2%2Ctype%3Dpage).  ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/c3b21274-022c-4112-8dc2-402423fcf33b) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/19e3dbfc-31d6-451d-8f0e-1f54e1db67c4)

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - if the Norwegian versions of the promoted pages should show automatically in the preview after duplicating to Norwegian without relinking to the Norwegian pages, I don't see them on the Norwegian page. Tested on [this page](https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;d17dc252-5deb-402e-b513-b59ac78bafc2%2Ctype%3Dpage). ![image.png](https://camo.githubusercontent.com/696942945867610d2e897b139c97414d820c7c7d7de3e4d1e7c8dd0a702042fd/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f63336232313237342d303232632d343131322d386463322d343032343233666366333362) ![image.png](https://camo.githubusercontent.com/6916b018ed4b8e495884e61facb04b6fd4f2c4ee9d6302828727582132c4961c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f31396533646266632d333164362d343531642d386630652d316635346531646236376334)

When you asked during the meeting I misunderstood you. It should not show it in Norwegian because these are direct links to english pages: 
<img width="841" alt="image" src="https://user-images.githubusercontent.com/23337266/207304347-d724a18b-9570-4a46-b2c5-80db415c5b07.png">

**Comment by fernandolucchesi** [comment]
This issues fixes this: https://equinor.slack.com/archives/C01MU3H6G0Y/p1669213390059189
It is currently happening for unpublished topic content and events
