### ISSUE TITLE
Remove content archiver azure function

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1387]
We need to remove equinor-content-archiver function, as this is no longer used.

**Comment by fernandolucchesi** [comment]
I can still see 
https://portal.azure.com/#view/Microsoft_AAD_IAM/ManagedAppMenuBlade/~/Overview/objectId/0aa39907-b312-4837-8309-4db426f1a946/appId/1c21e0b4-4c08-4cc8-a17a-074ff0840957 and https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/Overview/appId/1c21e0b4-4c08-4cc8-a17a-074ff0840957, we might need @nilsml to delete it?

**Comment by nilsml** [comment]
They are now gone!
