### ISSUE TITLE
Improve rollback scripts

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1389]
There is room for improvement in our actions:

- [x] Validate if image SHA really exists (and has the same amount of characters)
- [x] Rollback all at once (no need for rolling back each at a time)
- [ ] Optimize repo installation when rolling back global and secret studios (yarn install only /studio, sparse checkout) 
- [x] Investigate with sanity if they have a rollback solution for their hosted studios

**Comment by fernandolucchesi** [comment]
For #2, it is already the current behavior, I believe we should get rid of the input for datasets since it is making the GHA confusing (picking a dataset but rolling back all of them). 

As for #3, optimizing installation, I think we should discuss having the global studios hosted by us instead of by sanity as part of the Disaster Recover mitigation. 

Any thoughts?

**Comment by fernandolucchesi** [comment]
@nilsml

**Comment by nilsml** [comment]
For #3 I think we need to be careful. We may have a duplicate Sanity instance in Radix, but there are good reasons for having  Sanity running the main one. The most important beeing SLA.

**Comment by fernandolucchesi** [comment]
> For #2 I agree with having one rollback for all instead of or in additioin to selecting each dataset.
> 
> For #3 I think we need to be careful. We may have a duplicate Sanity instance in Radix, but there are good reasons for having  Sanity running the main one. The most important beeing SLA.

I see. If we were hosting it ourselves, we could rollback all of them with satellites instead. Since Sanity is hosting it we need to re-install everything and go through the build process. I don't think it is a big deal to optimize it, and I'd say we postpone it until we move to Sanity v3 at least. 

Other than that, this is ready to be reviewed.

**Comment by padms** [comment]
@nilsml
