### ISSUE TITLE
Make static pages accessible through menu

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#139]
**In order to view the static pages, we must make them accessible through a menu**

## Acceptance criteria
1. It is possible to locate the static pages on the site
1. The link is available through the menu

## Sub-tasks
1. Add a field in Sanity to make it possible to add link to static page
1. In the web we need to query for this information and create the actual link

**Comment by wenche** [comment]
Update @nicholas-haggerty (and everybody else)

- We have created some new fields in the menu builder tool for the top level link and the sub item links for each menu item. The idea is to make it very explicit by using a switch for static pages (in lack of a better term). This switch uses the new conditional field features Sanity recently launched, and if the switch is on, you'll have a text field where you add/copy-paste the URL as it is in the current CMS, except for the lang part and .html extension. There is currently no validation here, just a placeholder text for some guidance
![Skjermbilde 2021-09-03 kl. 13.16.27.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d2b52d92-52dd-4635-8b26-4f2cbfa22453)
![Skjermbilde 2021-09-03 kl. 13.16.42.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/68c7ed96-8777-4943-8d9c-f5d27922036f)
- By doing this, you are able to register the URL needed for the static pages Plan B to work. I've registered quite a few for testing purposes already
![Skjermbilde 2021-09-03 kl. 13.18.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8cf4e419-f0fd-456b-9c3c-9987bc5e06e6)
![Skjermbilde 2021-09-03 kl. 13.18.47.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/91932179-dbd9-43d3-b003-2333cb1e07a6)
![Skjermbilde 2021-09-03 kl. 13.19.13.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/3214eced-6ec8-49f4-b8c2-f93dbc6cf265)
![Skjermbilde 2021-09-03 kl. 13.19.40.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/227573a0-2aeb-4185-b065-6e235d1bef05)
![Skjermbilde 2021-09-03 kl. 13.20.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/1a2253fd-8c04-4e66-8007-a52b35a7b4d8)
![Skjermbilde 2021-09-03 kl. 13.20.20.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/0c7debf7-60b8-415b-956b-78bbfdce8cc0)
![Skjermbilde 2021-09-03 kl. 13.20.42.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/589e7011-23e5-4489-8723-8112624044dc)
![Skjermbilde 2021-09-03 kl. 13.21.01.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2965be35-232b-4f30-8742-962ffec88584)

I don't think you should register something yet. This is still bleeding edge. :) Still, it solves one part of the puzzle. 

We need to make this more robust by adding more validation and safety guards, but we need to wait until the web and the blob storage is in place and we have verified that this is the way to go.
