### ISSUE TITLE
CSR Generator

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1391]
This issue aims to create a tool that facilitates requesting an SSL certificate. Currently, we need to create a conf file and run a bash command to generate two other files (process described on 'user story 4' [on this doc](https://statoilsrm.sharepoint.com/:w:/r/sites/DNSrequestsfromCommunication/_layouts/15/Doc.aspx?sourcedoc=%7B8A580D7C-E09C-4AE1-95F8-7C86E8A93ADD%7D&file=DNS-requests-general.docx&action=default&mobileredirect=true)). We could find a way to simplify this process to avoid other teams requesting us to do the job for them all the time.

PS: This is not something our team is responsible for, we are just trying to help other Equinor teams here.

**Comment by fernandolucchesi** [comment]
Repo: https://github.com/equinor/csr-generator
URL: https://app-csr-generator-prod.radix.equinor.com/

**Comment by fernandolucchesi** [comment]
This tool can be used to validate the CSR created: https://www.sslshopper.com/csr-decoder.html

I don't know how to validate the .key file but would assume it just works since the .csr works.

**Comment by padms** [comment]
Looks good to me 	✅
