### ISSUE TITLE
Enhance alerts and logging about the health of our apps

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1395]
- [x] can we make Dynatrace alert slack?
- [ ] Persist logs in radix

**Comment by fernandolucchesi** [comment]
https://www.dynatrace.com/support/help/how-to-use-dynatrace/problem-detection-and-analysis/notifications-and-alerting/problem-notifications/slack-integration

**Comment by fernandolucchesi** [comment]
@nilsml, we need to create a slack webhook for DT. I don't have permissions to do so, how can we approach this?

**Comment by nilsml** [comment]
I will have a look

**Comment by fernandolucchesi** [comment]
> 

I think it is a good idea!

**Comment by nilsml** [comment]
Persist logs for Radix is a feature that has been communicated to the Radix team. It is high on their backlog.

Also as discussed in the team we could have automated scripts using Brwoser Stack to do smoke tests in Preprod before we deploy.

**Comment by millianapia** [comment]
is split into two issues #1578 and #1579
