### ISSUE TITLE
Document DDoS protection setup

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1398]
DDoS protection service is enabled for our cluster in Radix.
This should be stated in the Archtecture contract as well as the Runbook.

## Tasks
- [ ]  Add note about DDoS protection in archtecture contract
- [ ] Add note about DDoS protection in Runbook for energyvision

**Comment by nilsml** [comment]
Relates to #1550

**Comment by fernandolucchesi** [comment]
We already have this documented in the runbook. Under the "Network security" subitem. @nilsml can we close this?

**Comment by nilsml** [comment]
Agree, we can close this
