### ISSUE TITLE
404s on archived-archived news downloads 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1399]

**Comment by fernandolucchesi** [comment]
Hi @padms , left a suggestion

**Comment by padms** [comment]
@fernandolucchesi Done

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Done

Looks good! However `Flags.IS_DEV && Flags.IS_GLOBAL_PROD` will always be false. Should use IS_DEV during test and then IS_DEV || IS_GLOBAL_PROD when going to prod

**Comment by padms** [comment]
@fernandolucchesi Done

**Comment by fernandolucchesi** [comment]
LGTM!

**Comment by fernandolucchesi** [comment]
LGTM!

**Comment by padms** [comment]
@meols This can be tested.

**Comment by fernandolucchesi** [comment]
@padms, can you provide a link for mette to test, that is 404 on prod and now works?

**Comment by padms** [comment]
https://www.equinor.com/news/archive/2011/02/24/24FebEGAF

https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/archive/2011/02/24/24FebEGAF

https://www.equinor.com/news/archive/2013/09/03/03SepAberdeen
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/archive/2013/09/03/03SepAberdeen

**Comment by meols** [comment]
Thanks @padms - works well :thumbsup:

@fernandolucchesi - How soon can we have this deployed? There is an upcoming article on the In Amenas terrorist attack 10 years ago where they would like to link to [this news article](https://www.equinor.com/news/archive/2013/09/12/12SepInAmenasreport) (or maybe straight to the report, not sure) so the pdf report should be working.
