### ISSUE TITLE
event promotion query does not account for "undefined" value in toggles

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1402]
When we released #628, we did some work on the "select events from tags" toggle and added some logic to determine which events to pick based on the toggle states. This logic counts on the toggles being either `true` or `false`. This broke the event promotion in production since the already added components had some toggles which had `undefined` as value.

**Comment by millianapia** [comment]
As it does take the toggle value is defined or not into account, we hope this issue will be fixed in v3 of sanity

**Comment by SvSven** [comment]
will be handled in #1617
