### ISSUE TITLE
Upgrade Sanity Studio to v3

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1403]
https://www.sanity.io/docs/migrating-from-v2

## Custom plugins

- `asset-source-brandmaster`
- `asset-source-fotoware`

https://www.sanity.io/docs/migrating-plugins#7bd52dc2439e

_Should_ be straightforward, with only having to update it to use `definePlugin`.
Note that these are local custom plugins, they are not published to NPM.

## Migration plan
1. Create Epic Issue
1. Create a separate folder in the monorepo
1. Check if all plugins we are using in the studio support v3
1. Migrate the Sanity Setup
1. Create an issue for custom component migrations
1. Deploy it to a new URL

**Comment by nilsml** [comment]
All tasks are done
