### ISSUE TITLE
Add line clamp to promoted news

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1418]
![image.png](https://images.zenhubusercontent.com/619cb66996a338308e2dd0b8/0e8631f8-3e46-487e-accc-918326c77494)

**Comment by fernandolucchesi** [comment]
#1340

**Comment by meols** [comment]
@millianapia - for the news article bottom promotions, is it possible to have 7 lines in total for title + ingress + 3 dots at the end of the ingress (e.g. 1 line title + 6 lines ingress or 3 lines title + 4 lines ingress)?

**Comment by meols** [comment]
@millianapia - that's perfectly fine :smile:

**Comment by meols** [comment]
Could we try e.g. 300 characters (including spacing)?

**Comment by millianapia** [comment]
Perhaps clamping title with 2, and text with 5? looks like this
![image (6)](https://user-images.githubusercontent.com/21845545/211844421-55533d95-04cc-46bf-ac74-529198ff5697.png)


vs this
![image (7)](https://user-images.githubusercontent.com/21845545/211844407-87cd2267-3d9f-4450-86f8-2f7153165da2.png)

**Comment by fernandolucchesi** [comment]
Hi @millianapia, left a couple of comments, please check

**Comment by millianapia** [comment]
Ty for the feedback! should be fixed now @fernandolucchesi

**Comment by fernandolucchesi** [comment]
LGTM!

**Comment by millianapia** [comment]
@meols @nicholas-haggerty added lineclamping on the cards, the title restricts at 2, while the main content is restricted at 5 lines

**Comment by millianapia** [comment]
@NickHaggerty1 @meols

**Comment by NickHaggerty1** [comment]
@millianapia @meol 
Approved thanks

**Comment by fernandolucchesi** [comment]
I just tested this from my mobile (IOS) and there is a tiny bug (tested both in chrome and safari)

Maybe the ellipse CSS property I asked you to remove is actually needed? @millianapia  

![image](https://user-images.githubusercontent.com/23337266/216617932-7166511c-30b3-46d5-b9c8-41449afb8e68.png)

**Comment by millianapia** [comment]
had to add lineheight due to a bug on phones, ready to be re-reviewed

**Comment by nilsml** [comment]
Done. Looking good.

**Comment by meols** [comment]
@millianapia - we should probably consider horizontal mobile as well, or?![horizontal.jpeg](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/3c0c0f0d-31c6-466d-aa61-fc63c8642390)

**Comment by millianapia** [comment]
@meols that should have been covered, really weird. Will take this back to in progress

**Comment by fernandolucchesi** [comment]
@millianapia left a comment

**Comment by fernandolucchesi** [comment]
Looks good!

**Comment by millianapia** [comment]
@meols could you verify that this works with the new changes?

**Comment by millianapia** [comment]
@meols @NickHaggerty1 could you verify this :)

**Comment by millianapia** [comment]
i cant seem to replicate this, can you verify @NickHaggerty1

**Comment by millianapia** [comment]
@meols after some investigation, i see that this bug is actually not due to the line clamp. The bug can be found in the live version of the web page. So i will be creating a new issue for this, for fixing that.

**Comment by millianapia** [comment]
@meols can you confirm that the line clamp itself is working, then i will move this along and work on the bug itself?

**Comment by NickHaggerty1** [comment]
@millianapia Clamping looks good and we see the issue raised is in prod too so this needs to be looked separately. This one can be deployed. Thanks.
