### ISSUE TITLE
Bullet list/numbered list shows incorrect on published pages

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1422]

**Comment by meols** [comment]
@fernandolucchesi - The bullets/numbers in the lists shows with an outdent, outside of the left margin, instead of with an indent.
https://www.equinor.com/about-us
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/76b90fc4-f72f-43c6-9919-80d506a62a88)

**Comment by fernandolucchesi** [comment]
@millianapia left a small comment, LGTM after fixing it

**Comment by millianapia** [comment]
@meols @nicholas-haggerty numbered and dotted list should now be aligned with the rest of the text content

**Comment by meols** [comment]
Great @millianapia - thanks for fixing :smile:
