### ISSUE TITLE
CTA component - link to another language

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1432]

**Comment by SvSven** [comment]
Looks good to me ✅

**Comment by meols** [comment]
@padms - by CTA component I assume we mean that it is CTA in text component I should test? If so it works as expected :thumbsup:

**Comment by padms** [comment]
@meols This refers to related content links on the news, local news and events pages.

**Comment by meols** [comment]
Thanks for clarifying @padms :smile:
Works as expected.
