### ISSUE TITLE
Promotion component - link to another language

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1439]

**Comment by millianapia** [comment]
the promo-component itself has link to another language through the text editor, the underlying promotion components does not - so this can be closed

**Comment by SvSven** [comment]
Can confirm, linking to different language in the ingress works. 

We can't however add a promotions to a different language when manually selecting cards (topic, event, magazine) - is that something we want/need? Would be a bit more involved than most of these other "link to another language" issues.

**Comment by millianapia** [comment]
closing this as agreed upon in standup
