### ISSUE TITLE
Table component - link to another language

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1440]

**Comment by fernandolucchesi** [comment]
left a comment :)

**Comment by fernandolucchesi** [comment]
LGTM!

**Comment by meols** [comment]
@millianapia @fernandolucchesi - I have added 4 different links (2 Norwegian, 2 English) in the table at the bottom of this page: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/mette-test-1 - https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;d0b57050-7f22-434d-97b3-ceb8324719e1 
but they all go to the English homepage - which isn't expected
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/9903d56e-cfa8-4a8e-a261-81be7b3eced3)

**Comment by fernandolucchesi** [comment]
> @millianapia @fernandolucchesi - I have added 4 different links (2 Norwegian, 2 English) in the table at the bottom of this page: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/mette-test-1 - https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;d0b57050-7f22-434d-97b3-ceb8324719e1 but they all go to the English homepage - which isn't expected ![image.png](https://camo.githubusercontent.com/1852a0dad0be3fba5db2cf5e9c6a975a8a30211f0fea878b985faba2b75e4a47/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f39393033643536652d636661382d346138652d613236312d383162653762336563656433)

You are right, there is a bug in the code

**Comment by fernandolucchesi** [comment]
@meols thanks for checking...

**Comment by fernandolucchesi** [comment]
@millianapia code introduced in #1437 was buggy, I fixed it, but it still lacks changes to the Link component in the Table cell (we are currently not passing the locale). So I moved it back to in progress

**Comment by millianapia** [comment]
@fernandolucchesi now it applies the locale to the link, is ready for second technical review:)

**Comment by fernandolucchesi** [comment]
Looks good! ✅

**Comment by meols** [comment]
Great and thanks @millianapia
