### ISSUE TITLE
Chakra ui adds cookies prior consent

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1444]
chakra-ui-color-mode  is added to local storage before consent

More information is available in the attachments in the email from cookie bot

**Comment by fernandolucchesi** [comment]
Could be as easy as removing the ChrakraProvider, or as complicated as adding chakra to consent

**Comment by millianapia** [comment]
I rewrote _app so it uses baseprovider instead of the standard chakraprovider, is it any way of verifying this in test if it helped regarding the cookies and accessability issues  @fernandolucchesi

**Comment by fernandolucchesi** [comment]
> I rewrote _app so it uses baseprovider instead of the standard chakraprovider, is it any way of verifying this in test if it helped regarding the cookies and accessability issues @fernandolucchesi

@padms can you check for the cookiebot? I am not sure how to test it.

As for the accessibility, problem still exists. Basically the context is creating a chakra-portal that we are not using/has incorrect accessibility props, you can read more on #1415 
![image](https://user-images.githubusercontent.com/23337266/212320700-2c1b5e0a-5fa2-420c-8a51-b5916555b419.png)

**Comment by padms** [comment]
I see cookie in the local storage. ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/50582d3f-aa75-4488-a2cd-2a0d6521bcae)

**Comment by millianapia** [comment]
as baseprovider did not live up to expectations, i will try removing the chakraprovider all-together from the _app file.

**Comment by millianapia** [comment]
did not get any local cookies when removing the baseprovider, will check in global dev when it is finished building

**Comment by millianapia** [comment]
@fernandolucchesi @padms could either of you verify the new changes

**Comment by padms** [comment]
Could verify that no cookie is added now

**Comment by millianapia** [comment]
this is a very technical issue so there is no other test to be made than checking if cookie is added which @padms did, it is connected to the #1378 so i will move it to the other column
