### ISSUE TITLE
Expand/Collapse button on accordion is misplaced. See on hover.

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1445]

**Comment by millianapia** [comment]
The icon was styled like this, so i removed the hoverstyling. If this was intentional, we can revert

**Comment by fernandolucchesi** [comment]
I have no clue on how this should look but looks good to me 😂

**Comment by millianapia** [comment]
How it is now:
![new](https://user-images.githubusercontent.com/21845545/212329073-2a3764ff-ded6-4b1f-9db0-fbea3ea27b00.gif)

Old misplaced icon:
![old](https://user-images.githubusercontent.com/21845545/212329078-62b857b8-3e56-4f80-86bf-d6b69bcf50ae.gif)

**Comment by meols** [comment]
@NickHaggerty1 - can you please comment on this one?

**Comment by NickHaggerty1** [comment]
Hey @millianapia We would still need the hoverstyling (so reverses to red with white x) Great if you can add that back. But you have fixed the movement of the circle between natural and selected. Nice!

**Comment by fernandolucchesi** [comment]
Also looks like this line is not perfectly aligned with the circle: 
![image](https://user-images.githubusercontent.com/23337266/212685506-c8bd21bf-5383-4d9b-bd64-9f5db9787f85.png)

**Comment by millianapia** [comment]
hoverstyles are back @NickHaggerty1 ! but i cant replicate the not-aligned thing you posted @fernandolucchesi  ![Jan-18-2023 13-36-11](https://user-images.githubusercontent.com/21845545/213173125-c95adcca-a982-4f3f-bee6-92dc6b9fcdac.gif)

**Comment by NickHaggerty1** [comment]
@millianapia I couldn't replicate the alignment issue either? All good from my perspective unless the line issues shows up!
