### ISSUE TITLE
Preview for promo tiles component

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1447]
We run a script to upgrade titles from string to textblock, but we forgot to update the previewing. 

![image.png](https://images.zenhubusercontent.com/619cb66996a338308e2dd0b8/d884f907-d719-4267-a8b3-b79a79cd470d)

**Comment by padms** [comment]
@fernandolucchesi Removed the feature flag.

**Comment by fernandolucchesi** [comment]
LGTM

**Comment by meols** [comment]
@fernandolucchesi - I see that [object Object] is added to the title (if a title is missing?) on some occasions (both on [Mette's test page](https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;d0b57050-7f22-434d-97b3-ceb8324719e1) and [Fields and platforms](https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;64874433-f6f3-4b91-94b2-a82a5b9d7cee)
 ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/5231f29c-9deb-4151-a820-37d5260bff4d)

**Comment by padms** [comment]
@meols This is expected. I was testing my migration script and as a result this happened ( only in global-development dataset, should not be a problem in other datasets).

**Comment by meols** [comment]
@padms - I trust you on this one then :smile:, since it still looks wrong to me ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/8e1fb222-121f-4afc-8a1c-36b95bbfdd5e)

**Comment by padms** [comment]
@meols You can also verify the actual promo title in the rich text and the the title shown in the preview. In global-developement , the title in the rich text and preview will be "[object][object]" , in other datasets, though the title in preview shows "[object][object]", the actual title in the rich text is not changed.
