### ISSUE TITLE
Full width image does not preview when added.

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1450]
**Describe the bug**
Making changes to an already published page. Adding new content to the page but not publishing until approved. Issue seems to be to display a full width image when previewing or opening the link in a new browser window.
**To Reproduce**
I have added two images of a drone, one using the normal width and one with the full width to the digitalisation page in PRODUCTION The full width does not display:
https://equinor.sanity.studio/desk/topicContent;a1e8e187-e70b-4fcd-823f-ba7d9f04f093%2Cview%3Dpreview

**Expected behavior**
The full width image should display.

Tested on Chrome and safari browser

**Comment by padms** [comment]
Fixed with #1451

**Comment by fernandolucchesi** [comment]
Moving this to ready to deploy
