### ISSUE TITLE
As editors we would like to have additional display options for showing videos in the IFRAME component

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1455]
## Acceptance criteria
1. Allow options to add two column display (two videos side by side). Use the wider column width to accomodate the two column. For desktop. For mobile horizontal scroll should be in place.
1. Allow option to add 3 or more videos horizontally on desktop. This would then mean horizontal scroll would be required for desktop (and mobile) - do we have an established column width for the horizontal scroll elements now? If so lets use that for the iframe component also.

![iframe improvements.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/4195fef8-1a06-410c-9a46-b518ca150caa)

**Comment by SvSven** [comment]
Depends on technical review of #1373

**Comment by NickHaggerty1** [comment]
I notice the iframe carousel component in in Stage which is great. One comment on naming though. Should this component be called iframe horizontal scroll instead? as it has the behaviour of the horizontal scroll elements more?
@meols fyi

**Comment by NickHaggerty1** [comment]
![spacing width for scroll.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/3ee08b3e-3c04-43d5-a027-9e2819b9e0c0)

**Comment by NickHaggerty1** [comment]
For the title on the iframe horizontal scroll. Maybe better to centre place to align with promotion components. 
Width is in between the image carousel and the promotion components. I would suggest increasing the width to same as the carousel module.

**Comment by millianapia** [comment]
lgtm!

**Comment by NickHaggerty1** [comment]
@millianapia @fernandolucchesi Great. lgtm to me too! @meols any comments?

**Comment by meols** [comment]
Looks great!
