### ISSUE TITLE
Improve pagination looks on mobile

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1466]

**Comment by fernandolucchesi** [comment]
Using ready to deploy flag bc there is no feature flag here :P

**Comment by millianapia** [comment]
Looks good to me!

**Comment by SvSven** [comment]
I'm guessing all the changes in imports are just caused by auto-formatting on save?

Anyway, looks good!

**Comment by fernandolucchesi** [comment]
> I'm guessing all the changes in imports are just caused by auto-formatting on save?
> 
> Anyway, looks good!

you are correct
