### ISSUE TITLE
Statoil redirect

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1468]
https://www.statoil.com/content/dam/statoil/documents/supply-chain/statoil-deposit-enrollment-form.pdf should be redirected to https://www.equinor.com/where-we-are/us-owner-relations

**Comment by fernandolucchesi** [comment]
left a comment @padms

**Comment by padms** [comment]
@fernandolucchesi Done

**Comment by meols** [comment]
@padms @fernandolucchesi - anything to test for this before it is deployed?

**Comment by padms** [comment]
@meols You can test the redirect by verifying this link
 https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/content/dam/statoil/documents/supply-chain/statoil-deposit-enrollment-form.pdf

**Comment by fernandolucchesi** [comment]
> @padms @fernandolucchesi - anything to test for this before it is deployed?

no, we are good to go
