### ISSUE TITLE
Text in bullet lists should always be indented

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1471]

**Comment by meols** [comment]
#1422 wasn't tested with longer texts pr list item, and now I've noticed that only the first line and not the complete text for each list item is indented. Texts should be indented as in word and on the Sanity page on the screen shots below ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/528d81ab-1e74-4d80-9099-8c4ba3fade42) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/29ebe618-d720-4686-aa1e-e0c11ded71e8)

**Comment by padms** [comment]
LGTM

**Comment by millianapia** [comment]
@meols should work as intended now, can you verify

**Comment by meols** [comment]
Works well - Great and thanks @millianapia :smile:
