### ISSUE TITLE
Use ES6 instead of common JS modules for monorepo config

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1483]
Next 12 allows es6 in next.config.js, therefore we can replace the CommonJS setup with ES6. This is needed to make it work with sanity v3.

**Comment by fernandolucchesi** [comment]
Created this on a PR so that we only release it after the quarterly publication, since this is not feature flaggable.

**Comment by fernandolucchesi** [comment]
to review:

Web, Studio, Sanity v3, Search and Lint should still work the same as they used to

**Comment by millianapia** [comment]
lgtm! everything works as they used to
