### ISSUE TITLE
Implement horizontal scroll to Promo Tiles component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1485]
Relates to #1373

The horizontal scroll feature implemented in #1373 should be added to the promo tiles component as well, with the same settings;

- Default for smaller screens should always be horizontal scroll (regardless of settings in Sanity)
- Add option in Sanity for editors to explicitly enable horizontal scroll

**Comment by SvSven** [comment]
Depends on technical review of #1373

**Comment by millianapia** [comment]
already on promotiles component - adding this in the same column as #1373

**Comment by NickHaggerty1** [comment]
@millianapia Hey. Not sure if this ready to test yet? I dont see an option for editors to choose to display as '2 4 6' or as horizontal scroll?

**Comment by SvSven** [comment]
@NickHaggerty1 do we want the same validation logic here as with the promotion component? That if the horizontal scroll is enabled editors can add more tiles?

**Comment by NickHaggerty1** [comment]
@SvSven I think that works yup. And how you have in stage is great so editor can choose either horizontal scroll or to stack 2 by 2

**Comment by SvSven** [comment]
@NickHaggerty1 Looks like the promo tiles component already allows for this actually - the only validation it has now is that it needs a minimum of 2 tiles - so we should be good on the validation front.

**Comment by millianapia** [comment]
looks good! remember to add this to v3 as well

**Comment by NickHaggerty1** [comment]
@SvSven Looking good. Only issue now is if editor selects option to have title and button/CTA. The button is kissing the bottom of the component. I have a few examples on my topic test page:
https://studio-global-development-equinor-web-sites-dev.c2.radix.equinor.com/desk/topicContent;a353cb14-028f-45dd-bbea-4010d6968d3e

**Comment by SvSven** [comment]
@NickHaggerty1 Should be fixed now!

**Comment by NickHaggerty1** [comment]
@SvSven The button is correctly placed but this seems to have caused the issues regarding spacing and image placement that were there yesterday? See same page as above.

**Comment by SvSven** [comment]
I'm not seeing any issues with the spacing... I'll check some different browsers, might be on my end.
With regards to the size discrepancies; due to the way the carousel/horizontal scroll and the flexible width of all of the cards in general works, they'll never all be the same width unfortunately. You'll notice that the tiles in the horizontal scroll will also be bigger than the 2x2 layout on smaller screens.

I do see this one though, that's a weird one - will investigate:
![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/c960f19f-e923-4ae4-a302-e2565438e2fb)

**Comment by NickHaggerty1** [comment]
![Screenshot 2023-02-22 at 13.27.54.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/5832f3c3-9d8d-4104-854f-5c35629fb7d2)

**Comment by NickHaggerty1** [comment]
@SvSven Preview on my stage test page. Chrome.. Had this spacing issue a couple of days ago too but you had fixed this yesterday. Only cam back when you worked on the button placement.

**Comment by NickHaggerty1** [comment]
same issue in Safari

**Comment by SvSven** [comment]
@NickHaggerty1 I was able to reproduce it on smaller resolutions. Have made some changes that should hopefully fix it. Not 100% satisfied with the whole thing, but I think all of the horizontal scroll code could use an overhaul to make it a bit more robust.

cc @millianapia @padms

**Comment by NickHaggerty1** [comment]
@SvSven Looking good now. Nice. Approved from my side, your gang knows best on the code side!
