### ISSUE TITLE
Promo tile adjustments

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1500]
The promo tile is used to promote to other content throughout the site. We see there is duplication quite often in the title and the button CTA text (see example on careers)

We would like to make some options to the component to choose between the current set up (which should remain) and an option where its just a title and arrow link instead of button.

Is it possible for editor to toggle between choices? **Title/button** or **title/arrow** for example?

For tittle/arrow route I suggested H3 instead of H2. Open for input on this.
Add shadow to component (for both options) as per other promotion elements) 
Arrow behaviour should replicate the arrow featured on other CTA components
Two design suggestions arrow to the right of title and arrow below. Open for input. Should we just follow logic of other promotions and have arrow below?

**Comment by NickHaggerty1** [comment]
![promo tile-same-same.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/db0a7c7e-0922-449c-97d0-e30748a21ed8)

**Comment by NickHaggerty1** [comment]
![alt-arrow-promo-carosuel-example.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/f90e5967-56c6-476a-9e89-bb01c3f3cfde)![promo-carosuel-example.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/a43ac283-2052-4f54-b7c1-473beb9fda49)![twoxtwo-display.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/d86656cd-4b54-4d9b-90bb-5939290f4669)

**Comment by fernandolucchesi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Energy-Vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/1500?planning-poker) with Zenhub @millianapia @padms

**Comment by millianapia** [comment]
looks good! love the refactoring as well:)

**Comment by fernandolucchesi** [comment]
Hi @millianapia, I pushed new changes to this component, can you please review it again?

**Comment by millianapia** [comment]
looks good! just comment on style preference

**Comment by NickHaggerty1** [comment]
@fernandolucchesi Couple of comments on the styling (maybe Im too early to comment so ignore if its in progress)
1. The padding for the title and arrow runs full width to the component on the example I added in.
2. I mentioned above about replicating the shadow as per other promotion components. Doable?

**Comment by NickHaggerty1** [comment]
[Uploading... Screenshot 2023-02-16 at 13.37.35.png]

**Comment by NickHaggerty1** [comment]
![Screenshot 2023-02-16 at 13.37.35.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/bcd6aead-337f-4fb3-bc2e-36b10064e3f1)

**Comment by SvSven** [comment]
@NickHaggerty1 I'll have a look at the padding. The drop shadow should be the same as the news/promotion cards I assume? That should be doable.

**Comment by SvSven** [comment]
@NickHaggerty1 Never mind! I see that Fernando already fixed it - can you have another look?

**Comment by NickHaggerty1** [comment]
@SvSven Yup padding and shadow good/approved.. An issue on the horizontal scroll display which I will describe there....
