### ISSUE TITLE
Convert TimeInput custom component to v3

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1503]

**Comment by fernandolucchesi** [comment]
@padms I believe you tagged the commit to another issue?

**Comment by padms** [comment]
I tagged it to 1053 .. Here is the commit beea07b

**Comment by fernandolucchesi** [comment]
Couple of comments regarding cleaning up otherwise looks good!

**Comment by padms** [comment]
Cleaned up
