### ISSUE TITLE
Screen9 widget Implementation

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1510]

**Comment by fernandolucchesi** [comment]
Waiting for Screen9 access

**Comment by nilsml** [comment]
@fernandolucchesi to add proper description to the task so that it is possible to know when it is done

**Comment by nilsml** [comment]
Meeting scheduled with Screen9

**Comment by SvSven** [comment]
When creating a new video asset document, I choose import from media bank - BrandMaster loads fine, I successfully import the asset but then get a validation issue on the "Video" field: 

![image](https://user-images.githubusercontent.com/7661362/229128552-4c006d1f-c49f-46ec-86cf-444b396eb773.png)


Similarly on a video asset I created earlier (before Screen9 was added), I import the asset from BrandMaster successfully, but the web prioritizes the existing video field (which was uploaded manually as file).
