### ISSUE TITLE
Find a way to order and re-order magazines

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1511]

**Comment by fernandolucchesi** [comment]
blocked by #1514

**Comment by fernandolucchesi** [comment]
LGTM!

**Comment by meols** [comment]
This is great @padms :thumbsup: - one question: are we able to manipulate the list other than unpublish and republish to move an article to the top? Would we e.g. need a date picker to do so?

**Comment by fernandolucchesi** [comment]
> This is great @padms 👍 - one question: are we able to manipulate the list other than unpublish and republish to move an article to the top? Would we e.g. need a date picker to do so?

This is ordering by firstPublishedAt, so even publishing and unpublishing wouldn't allow you to get what you want... if we want it 100% customizable we need to do more work on this issue
