### ISSUE TITLE
Convert titleandmeta custom component to v3 

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1516]

**Comment by fernandolucchesi** [comment]
The component is not working as it should:
![image](https://user-images.githubusercontent.com/23337266/222136171-50fcad0a-9104-4c29-a14a-9de57ba5fe64.png)
vs
![image](https://user-images.githubusercontent.com/23337266/222136351-743a4f1e-f809-4f4f-9ae4-34d973846e9b.png)

**Comment by millianapia** [comment]
@fernandolucchesi should be working now, ready for another review

**Comment by fernandolucchesi** [comment]
> 

The default component is not including the char count: 
<img width="124" alt="image" src="https://user-images.githubusercontent.com/23337266/223385978-5ae04b7e-4725-4768-a61e-476616c8cbad.png">

**Comment by millianapia** [comment]
@fernandolucchesi it works now with a char count and an input field

**Comment by fernandolucchesi** [comment]
Looks nice now! Approved ✅  Also left a comment regarding the looks of it
