### ISSUE TITLE
Architecture diagram for azure

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1518]

**Comment by padms** [comment]
https://miro.com/app/board/uXjVPpaKJ1c=/

**Comment by nilsml** [comment]
It is ✅ for Dev, but prod is missing. Either create a new issue for prod or update this one.

**Comment by padms** [comment]
Added architecture diagram for prod

**Comment by padms** [comment]
@nilsml

**Comment by nilsml** [comment]
I have been through it. Looks good!
One minor thing we could improve would be to have a separate storage account for storybook, but it is not so important. This setup works too. We just have to make sure we do not clear or delete the SA if static content is removed OR the storybook is removed.
