### ISSUE TITLE
Magazine footer is always shown in english

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1521]

**Comment by millianapia** [comment]
lgtm!

**Comment by padms** [comment]
@fernandolucchesi you could also add the noDrafts condition on the magazine tags too .

**Comment by meols** [comment]
@fernandolucchesi - the footer is (and was) visible in English, but still isn't visible in Norwegian magazine articles

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - the footer is (and was) visible in English, but still isn't visible in Norwegian magazine articles

Hi @meols, I forgot to paste the link, this has to be tested in the dev environment: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/no/magasin/test-english-16-aug

**Comment by meols** [comment]
@fernandolucchesi - I tested several pages on DEV and didn't see it, but now it's there and all is good :smile:

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - I tested several pages on DEV and didn't see it, but now it's there and all is good 😄

Oh I see! It is because we were lacking the Misc > MagazineIndex in Norwegian page... so it was not showing anything... I created it after you did the first round of testing
