### ISSUE TITLE
Fix storybook

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1522]
In order to make Sanity v3 work, we had to set the type of our app as "module", and this is causing problems to start/run storybook

**Comment by fernandolucchesi** [comment]
Like magic, adding an empty package.json file to the storybook folder fixed it. The idea of doing it is that it would not use the package.json doc from the parent folder, and instead use its own. Surprisingly, it worked.

**Comment by padms** [comment]
Works now.
