### ISSUE TITLE
Scroller bar is showing on header component

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1523]
![Screenshot 2023-02-15 at 14.43.10.png](https://images.zenhubusercontent.com/635f91c1e030510524915bc3/367b4f67-20b1-4d20-964a-29ae3a4921ce)

**Comment by SvSven** [comment]
Looks good to me
It's also already in production now that we have the horizontal scroll/carousel stuff deployed - but that's fine, it's just a minor issue in CSS anyway.
