### ISSUE TITLE
Remove MUX from our codebase

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1525]

**Comment by padms** [comment]
@millianapia I guess this can also be removed ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/d0e5734c-30ac-4813-b553-9359fa36a394)

**Comment by millianapia** [comment]
@padms that is now removed, ty!

**Comment by padms** [comment]
Except for the HAS_MUX flag in featureflags file, everthing is removed now :)

**Comment by millianapia** [comment]
woo! i had that and checksum locally for last, i pushed it now @padms

**Comment by padms** [comment]
LGTM

**Comment by millianapia** [comment]
@meols @NickHaggerty1 testcase is verifying that you can not add a mux video in sanity, and that places where you had mux videos earlier is removed

**Comment by millianapia** [comment]
@meols @NickHaggerty1

**Comment by meols** [comment]
Thanks @millianapia - MUX is gone :smile:
