### ISSUE TITLE
allow for TextBlock to render if it only has a CTA

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1530]
In some cases the editorial team needs to display just a link. Currently, the TextBlock component does not render if it does not have a title, ingress, and text.

We should update this to allow for only links to be rendered.

**Comment by SvSven** [comment]
@padms @millianapia ready for testing 🎉

**Comment by millianapia** [comment]
looks good, and it works!

**Comment by SvSven** [comment]
@NickHaggerty1 @meols This should fix the issue with the text block not appearing when it only has a link.

**Comment by NickHaggerty1** [comment]
Nice, thanks @SvSven. Approved....
