### ISSUE TITLE
Adding links below iframe horizontal component

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1534]
1. In the Iframe component we have the option to add CTA.
The iframe horizontal component doesnt have this options so editor is forced to use Text component to add CTA.
This creates a large gap between video and CTA.

So should we add CTA option to Iframe horizontal component? As per the iframe component

2. On occasion more than one link is also needed. Editor SHOUD use text component CTAs for this, however there seems to be extra space here also. The top / bottom padding seems to be in place even with the same background colour in place on both components.

**Comment by NickHaggerty1** [comment]
![Screenshot 2023-02-21 at 14.57.38 (2).png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/bab863ff-a300-4b3d-a57c-897f8956978d)

**Comment by NickHaggerty1** [comment]
Example with iframe horizontal and text component - several CTAs![Screenshot 2023-02-21 at 15.05.05 (2).png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/1f3f8b09-7db2-45c6-bd12-b020f1ae3d89):
https://www.equinor.com/careers/graduates

**Comment by NickHaggerty1** [comment]
@SvSven ref the chat on Slack around text component for just CTAs

**Comment by fernandolucchesi** [comment]
approved! left a comment tho, up to you if you wanna change

**Comment by meols** [comment]
@NickHaggerty1 - can you please check (and approve) this one? :smile:

**Comment by NickHaggerty1** [comment]
@padms @fernandolucchesi @meols 
To have a link/button under each video was not the request. Instead the request was to have a button under the component/scroll bar. So for example we could have 5 videos for careers and then link to their YT channel to see more. 
However, it looks the spacing has been improved if we use a text component under the horizontal iframe to have links, so I suggest we do that to solve the need.
Lets also keep the button under each video. It may be required at some point. One point though, should the links/buttons be aligned to the bottom if there is descriptive texts added with differing lengths of text? If possible I suggest we do this.

**Comment by NickHaggerty1** [comment]
looks good @padms approved
