### ISSUE TITLE
Separate environments with resource groups 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1536]
- [x] Add env variable to radix config ARCHIVE_CONTENT_LINK while going live. requires deploy 
- [x] Create prod resource group in azure
- [x] Update webhook endpoint in sanity for algolia indexers for prod
- [x] Update fotoware url and code in github secrets .. requires deploy. 
- [x] Update fotoware redirect url in fotoware console
- [x] Copy archive content to prod container
- [x] Add secrets in keyvault
- [x] Add env variables to function app config for algolia

**Comment by padms** [comment]
I skipped creating dashboard resource that are there now. I believe we are not using it.

**Comment by padms** [comment]
- Changed Algolia url for the webhook in sanity and enabled dev dataset indexing.
- Added env variable for archive link url.

**Comment by nilsml** [comment]
Har to say if this one is 100% done. We do have the dev RG, but prod is not yet created. What do ya think @padms?

**Comment by nilsml** [comment]
We are ready to schedule a switch-over @padms

**Comment by SvSven** [comment]
I believe this can be closed now that we have moved to the new resource groups? @nilsml @padms

**Comment by padms** [comment]
Clean up task #1618 created. So closing this
