### ISSUE TITLE
Screen 9 Video player

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1538]
Suggested scope of component/development for discussion workshop in March:
Components:
**Video player New component (Similar to Iframe)**
play button
	video controls (what is out of the box?)
	Thumbnail upload
	Full screen option
	Title field
	Text field below
	CTA button below
	autoplay
	loop
	mute

**Video player horizontal scroll/carousel. New component (Similar to Iframe horizontal)**
	Title (for the whole carousel?) - Optional.
	autoplay
	loop
	mute
	Full screen option
	Text below each video
	CTA button under?

**Teaser component Addition to existing component. ‘Moving image’**
	autoplay
	loop
	mute
	Set a minimum - max height? Not based on the text length

**Banner (Similar to current interim player)**
	Autoplay
	Loop
	mute
	Title on video (H1) optional either on video or below banner
	Optional text over
	CTA?
	Thumbnail image

**50 / 50 Banner New/addition to current 50 / 50**
	Autoplay
	Loop
	mute
	Set a minimum - max height? Not based on the text length
	Thumbnail image
	Text side should be the same as image. 

**All encompassing, Full width. Scrolling. New component**  (see https://www.apple.com/careers/us/work-at-apple.html example)
	Background video or just image?
		loop
		autoplay
		mute
		Add transparency colour for text legibility
Text overlay on scroll? Needs to be limited in characters. Size to be specced. Left or right placement. Colour options? Dark or white?
	CTA link to other content
	CTA Play the video which launches the video player.
	Timing of scroll

**Carousel /multiple display** see https://orsted.com/en/careers example)
	Background video or image
		loop
		autoplay
		mute
		Add transparency colour for text legibility
	Intro text (or quote) to each video. With play video
	Timing display for each carousel transition
	Maximum on screen number?

**Comment by nilsml** [comment]
A lot of good suggestions on this task, but I would like the team to be involved in finding the best way to incorporate Screen9 as well. The description of the epic is very solution oriented. Would it be possible to state more the What than the How in the issues? By doing that it makes it easier for the team to discuss different  ways of achieving it.

**Comment by NickHaggerty1** [comment]
@nilsml Not really sure what you mean. This is meant as starting point for discussion for the workshop (as stated in the first sentence and mentioned in a couple of meetings) The overview is also pulling some of the earlier plans for how to use a video solution. I HOPE the team inputs in both how and what during the workshop relating to video and many other aspects :-) By the end of the workshop we should aim to define this epic and related issues.

**Comment by nilsml** [comment]
Great, then we are aligned. I think I read this issue on an empty stomach and interpreted this as more of a spec than a starting point for a discussion.

**Comment by nilsml** [comment]
Suggestion to create on user story for creating the component, and then separate user stories for each feature to be added
