### ISSUE TITLE
Adding a 'thumbnail' (small) image option to text component in order to solve certain specific requirements

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1540]
We need an option to have a smaller image. Question. Should we add an image to the text component or make changes to the image component? We are unsure how the spacing between elements will help or hinder on this.

**Comment by NickHaggerty1** [comment]
![podcast links-mobile.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/b5fd12a2-5f71-47ce-ae04-c30c29c20547)

**Comment by NickHaggerty1** [comment]
![podcast links-2.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/3ff44b33-b7b8-4982-940f-900585ad4c90)

**Comment by SvSven** [comment]
LGTM ✅

**Comment by NickHaggerty1** [comment]
@padms Approved great job.
