### ISSUE TITLE
Call to action component that allows editors to place images (jpg/png/svg) as buttons

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1541]
## Acceptance criteria
1. Look into creating a unique PODCAST component (list) similar to the SOME component in the footer.
1. Options to add multiple links, and display reflects sketch in terms pf placement
1. Limit width on all displays
1. How to resolve spacing/padding top and bottom to correctly place with other components (particularly text component)
1. All call to action options should be available to editor (Internal / external / anchor link)
1. Alt text on image to ensure accessibility

**Comment by padms** [comment]
https://www.apple.com/itunes/marketing-on-podcasts/identity-guidelines.html#listen-on-apple-podcasts-badge

**Comment by fernandolucchesi** [comment]
won't be needed anymore
