### ISSUE TITLE
add icons for documents in Studio

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1543]
We should add some icons for each document type that can be created in the studio

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/73291b44-abe0-4659-ac2a-835f6bf88445)

**Comment by NickHaggerty1** [comment]
![icons-for-studio.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/51a39bc4-236f-42a0-9009-aca3d6df933f)

**Comment by NickHaggerty1** [comment]
@fernandolucchesi @SvSven Hey added a new page on the figma board called Icons for studio and added these examples to represent the respective titles

**Comment by padms** [comment]
Sanity V3 has list to pick a document type , not sure where the icons for the documents will be helpful ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/11f96587-f191-49e2-a473-5ade385f5826)

**Comment by padms** [comment]
@meols This can be tested here...  https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk

**Comment by NickHaggerty1** [comment]
@padms Not sure how to test this?

**Comment by padms** [comment]
@NickHaggerty1 Click on the create new document icon to the left of the search bar in the top left corner.

**Comment by NickHaggerty1** [comment]
Ahh got it. I tried with the event and saw it hadnt changed (but that is ok to leave the calender)

Approved
