### ISSUE TITLE
Investigate a new subscription solution

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1544]

**Comment by meols** [comment]
We should look into finding a new out of the box subscription/send to subscribers solution. The Papirfly/Brandmaster solution is a custom made for us several years ago. 
GDPR and where personal date are stored will be important when looking into this.

**Comment by fernandolucchesi** [comment]
@meols I investigated these platforms and it doesn't look like they are any helpful for sending newsletters. I asked my friend (chatgpt) for EU GDPR complient services and got some recommendation:

Sendinblue: Sendinblue is a popular email marketing service that is based in France and is compliant with GDPR. They offer various features including email campaigns, transactional emails, SMS, and marketing automation.

MailerLite: MailerLite is an email marketing tool that offers GDPR compliant features, and they have data centers in the EU.

Moosend: Based in the UK and Greece, Moosend offers a range of email marketing tools and services, and they comply with GDPR regulations.

Mailjet: Mailjet is a French company that specializes in email marketing and transactional emails. They are GDPR compliant and have data centers in the EU.

GetResponse: GetResponse is a popular email marketing platform that offers various tools including newsletters, landing pages, and webinars. They comply with GDPR and have data centers in the European Union.

CleverReach: Based in Germany, CleverReach is specifically geared towards compliance with European data protection regulations, including GDPR.

-

But I would imagine there is another team within Equinor already using a similar service, we should aim to go for one of these.

**Comment by meols** [comment]
Thanks @fernandolucchesi - could you try to find out more if there are any relevant tools already in use in Equinor by other areas than COM? Maybe check in the IT software inventory?

**Comment by fernandolucchesi** [comment]
Brandmaster will continue supporting our current solution, and might come up with a more robust solution in the near future.
