### ISSUE TITLE
Create Architecture Contract for Screen9

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1550]

**Comment by SvSven** [comment]
Potentially incorporate into existing contract, replacing Mux

**Comment by nilsml** [comment]
Include DDoS info as per #1398

**Comment by fernandolucchesi** [comment]
https://github.com/equinor/architecturecontract/pull/1654

**Comment by SvSven** [comment]
Looks good I think? Not entirely sure what should be in the contract, but since this is part of Brandmaster/Papirfly it's probably not as big of an issue?

**Comment by fernandolucchesi** [comment]
@nilsml any idea about who should we nudge to get this approved?

**Comment by nilsml** [comment]
Merged
