### ISSUE TITLE
Embedded video player component in Sanity

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1562]
Acceptanace criteria (based on settings for iframe also)

Play button
video controls (what is out of the box?)
Thumbnail upload in Sanity for promotion cards
Full screen option
Format options for display: 16 / 9 is default. Optional 9 / 16. 1 / 1. Custom pixel height (as per iframe)
Title field above
Text field below
CTA below

Autoplay
Loop
Mute
Colour background options

**Comment by padms** [comment]
Looks very good to me :)

**Comment by NickHaggerty1** [comment]
@fernandolucchesi all the video aspects are working great. One issue though. When we tested a published dev page on mobile the videos dont play. Just thumbnail for the autoplay examples, and on the play button, when we press play nothing happens. Hopefully a small fix?
Tested on this page and open on mobile:
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/sustainability/video-player

**Comment by padms** [comment]
It works correctly on android with chrome

**Comment by fernandolucchesi** [comment]
> Also the loop option is not enabled for the video, might be the case where it plays once and stops before we scroll to that video.

took me ages to find out what was going on with ios, but should be fixed now :)

**Comment by NickHaggerty1** [comment]
@fernandolucchesi looks good on ios now. approved. FYI @meols
