### ISSUE TITLE
Add the video player component to horizontal scroll

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1563]
Acceptance criteria
As per set for iframe:
Allow options to add two column display (two videos side by side). Use the wider column width to accomodate the two column. For desktop. For mobile horizontal scroll should be in place.
Allow option to add 3 or more videos horizontally on desktop. This would then mean horizontal scroll would be required for desktop (and mobile) - do we have an established column width for the horizontal scroll elements now? If so lets use that for the iframe component also.
9 / 16 display would be 3 videos viewed on large desktop. Scroll bar appears at responsive break points. Horizontal scroll on mobile.

**Comment by NickHaggerty1** [comment]
[Uploading... 9-16-example x 3.png]

**Comment by NickHaggerty1** [comment]
![9-16-example x 3.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/c0fe3dc2-1bcc-4b61-9a45-90312eac6636)

**Comment by fernandolucchesi** [comment]
> @fer , The thumbnail for video is not a required field. A video with out a thumbnail is breaking the video components

fixed =) good catch

**Comment by NickHaggerty1** [comment]
@fernandolucchesi approved.
