### ISSUE TITLE
Ensure critical pages are statically prebuilt during deployment

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1566]
Due to the amount of content we have as well as limitations in the CI process, we can't prebuild the entire website as it would simply take too long. That being said, we should ensure that in the event of downtime with the Sanity API our most critical pages are still accessible and do not render an error page. 

1. Identify which pages should always be prebuilt
2. Set up prebuilding for said pages

**Comment by nilsml** [comment]
Need to do some testing as caching can be a challenge for pages that change after being prebuilt.

**Comment by fernandolucchesi** [comment]
What is prevent all pages from being statically built is the missing SANITY_API_TOKEN in the dockerfile. It is commented out on purpose (otherwise built time would be too long). To select what has to be generated, we need to modify the getStaticPaths

**Comment by BorghildSelle** [comment]
Possible and resolved in #2111
