### ISSUE TITLE
Improve hardcoded cors setup for bicep

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1573]
In order to fix Fotoware, CORS had to be enabled for all our studios. 

This has been achieved by hardcoding all the URLs. We should improve the setup: https://github.com/equinor/energyvision-internal/commit/09b548a7d1bb0c9d97c2ee2c6bcdcf170841b6d1

If no good solution is found, we should add this extra setup to the docs https://github.com/equinor/energyvision/wiki/satellite-sites

**Comment by padms** [comment]
Added to the wiki...

**Comment by SvSven** [comment]
LGTM ✅

I tried looking for better ways of adding it to the bicep file when I originally added them, but couldn't find a good way unfortunately.
