### ISSUE TITLE
Magazine tags are not displayed correctly depending on screen size

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1574]
![image.png](https://images.zenhubusercontent.com/619cb66996a338308e2dd0b8/9c8c7233-161a-47a4-8b32-edfd9155636f)

**Comment by millianapia** [comment]
what is the correct display? it should be a breakpoint for phones or at least tablets to be horizontal-scrollable ref #1380

**Comment by fernandolucchesi** [comment]
It is a scrollable component, let's leave it as it is for now...

**Comment by NickHaggerty1** [comment]
![Screenshot 2023-05-16 at 13.19.43.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/826ba042-1010-4ec9-b417-65232be3b4ac)

**Comment by NickHaggerty1** [comment]
![Screenshot 2023-05-16 at 13.19.50.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/af911bca-66a5-4597-89d2-8d4880d8859a)

**Comment by NickHaggerty1** [comment]
We could also explore a couple of the above options to make it clearer there is more to read and a user can scroll.

**Comment by BorghildSelle** [comment]
Agreed to update the magazine cards to use new card component, similar to promotions
where arrow is at the bottom right and hover on title shows underline
the tags can be a comma-separated list
![image](https://github.com/equinor/energyvision/assets/104756130/34e7b553-bed0-4118-8e04-071345e20686)

**Comment by millianapia** [comment]
@NickHaggerty1 changed after revised design, can you confirm

**Comment by millianapia** [comment]
@meols bump
