### ISSUE TITLE
Depoyment failing after release of new radix version

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1576]
Because Radix has implemented new ways of enabling/disabling components in each environment, and also a new validation rule, our old way of doing this is no longer possible.

## TODO
- Short term: use `enabled:false` for components that are not being used
- Short term: replace our dynamic imageTagName logic with the new way of setting imageTagName through cli

**Comment by meols** [comment]
@nilsml - can you please add some details on this issue?

**Comment by meols** [comment]
:smile:

**Comment by nilsml** [comment]
Related: https://radix.equinor.com/guides/enable-and-disable-components/

**Comment by padms** [comment]
Fixed..
