### ISSUE TITLE
Create redirects for the /50 site

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1577]

**Comment by meols** [comment]
We have started the dialogue with internal stakeholders to shut down the /50/ site. We would like to set an "overall" redirect per language.

Norwegian
- Redirect **from** the Norwegian https://www.equinor.com/50/any url (for urls that don't contain /en/) **to** https://www.equinor.com/no/magasin 

English: 
- Redirect **from** https://www.equinor.com/50/en/any url **to** https://www.equinor.com/magazine

Let's discuss before implementing to ensure that we haven't received any comments from stakeholders.

**Comment by fernandolucchesi** [comment]
#1096

**Comment by fernandolucchesi** [comment]
Hi @meols, I would like to confirm. Should we redirect specific articles, such as 50/carbon-knut to magazine/carbon-knut for example? 

Or should every article from 50 go to /magazine as you said? 

We can also redirect to the magazine page with the tag @50 filtered by default: https://www.equinor.com/magazine?tag=Equinor+%4050

**Comment by fernandolucchesi** [comment]
@padms let's wait for mette's confirmation, but your solution would be better if done in the next.config.js, and should apply only to the global dataset

**Comment by meols** [comment]
@fernandolucchesi @padms - we prefer if  every article from /50/ go to /magazine (or /no/magasin) as described.

**Comment by fernandolucchesi** [comment]
Looks good! ✅

**Comment by meols** [comment]
@padms @fernandolucchesi - what/how should I test to approve this this?
I just checked two random articles that aren't redirected (yet): https://www.equinor.com/50/en/article/this-can-be-a-starting-point-for-norway-s-new-industrial-chapter and https://www.equinor.com/50/artikkel/nordsjoen-har-energi-europa-trenger-og-plass-til-utslipp-vi-ma-bli-kvitt

**Comment by fernandolucchesi** [comment]
> @padms @fernandolucchesi - what/how should I test to approve this this? I just checked two random articles that aren't redirected (yet): https://www.equinor.com/50/en/article/this-can-be-a-starting-point-for-norway-s-new-industrial-chapter and https://www.equinor.com/50/artikkel/nordsjoen-har-energi-europa-trenger-og-plass-til-utslipp-vi-ma-bli-kvitt

did not work because it is not deployed it, we will deploy soon
