### ISSUE TITLE
Missing href in SimpleMenuGroup's 'read more' link causes crash

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1588]
It's currently possible to leave the connected route on the "Read more link" for the SimpleMenuGroup empty - which causes a crash due to a missing `href` on a `<Link>` component. We should add validation in the web and/or Studio in order to prevent this from happening.

Relevant code for web:

https://github.com/equinor/energyvision/blob/main/web/pageComponents/shared/siteMenu/simple/SimpleMenuItem.tsx#L46-L50

Relevant code for Studio:

https://github.com/equinor/energyvision/blob/main/studio/schemas/objects/simpleMenuGroup.tsx#L45-L55

Note: if changes are made to the Studio, remember to also update it for v3

**Comment by millianapia** [comment]
lgtm!
