### ISSUE TITLE
Fork sanity-plugin-color-list and make compatible for v3

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1603]
We use this plugin for selecting background colors, but the plugin has not been updated in 10 months and is not compatible with version 3 of Sanity, and no ETA for when it will be.

We should either fork this plugin and make it compatible ourselves, or create our own custom input component to replace it (while maintaining backward compatibility with the data format already in our datasets)

**Comment by SvSven** [comment]
@fernandolucchesi @millianapia @padms 

Ready for review - it's in a PR because it's a lot of changes (mostly just uncommenting/updating schemas)

**Comment by fernandolucchesi** [comment]
Looking good ✅
