### ISSUE TITLE
Add video player and video player carousel to v3

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1609]

**Comment by fernandolucchesi** [comment]
This will only work when videoFile and hlsVideo are also migrated. Should we create a new issue for it? IMO it should be handled on this one.

**Comment by padms** [comment]
Its handled in #1542

**Comment by padms** [comment]
Its handled in #1542

**Comment by fernandolucchesi** [comment]
review ok for this then ✅
