### ISSUE TITLE
ensure Studio icons are compatible with both light & dark theme

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#1615]
![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/90c4bd1c-956b-423c-9079-4ba033d24a8d)

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/6df2ffe0-b6df-42cb-a448-c0e76792a3e2)

**Comment by fernandolucchesi** [comment]
✅
