### ISSUE TITLE
Bullet indent isn't working as it should in the news template

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1632]

**Comment by meols** [comment]
When publishing the quarterly results I discovered that indented bullets doesn't work as expected (and as on a topic page) - see the attached image: ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/7773eb7d-f457-4ee5-a1fb-272ea7873e7f)

**Comment by millianapia** [comment]
With this we can delete the newstext component and use richtext directly, less code for the same result ✨

**Comment by padms** [comment]
@millianapia  The news text block has options to insert image, quote and factbox which is not there in a RichText. So, NewsText cannot be replaced with RichText.

**Comment by millianapia** [comment]
@padms those options are still there

**Comment by padms** [comment]
@millianapia I tested using this page by adding a quote and an image in the content block. Image and quote are not shown on the page.
https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/testing-news-article

**Comment by fernandolucchesi** [comment]
@millianapia what is the status here?

**Comment by millianapia** [comment]
@fernandolucchesi me and @padms had a discussion regarding this, and i created a fix which was approved by @padms

**Comment by meols** [comment]
@millianapia @padms @fernandolucchesi - the bullets in the news text component looks good - but the quote, image and factbox need some fixing: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/test-08-06
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/3c081111-d04f-4258-be79-9bce1d2d27b5)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/be33c42f-bf6b-410d-bd29-8f576c55a916)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/99325313-b083-41a6-aaae-efe1217f75c9)

**Comment by millianapia** [comment]
Hi @meols, should be working now. About the space between the indents, that has always been there. It has the same space in magazine as well. Is this something you want changed? if so, to what

**Comment by NickHaggerty1** [comment]
@millianapia @meols I think we should removing spacing on ALL templates (Topic / News / Magazine) between Bullets and indented bullets. Must admit I have never indented anything before so had not noticed this.

**Comment by NickHaggerty1** [comment]
![bullets and indented bullets.png](https://images.zenhubusercontent.com/62e8c66dc59ea7c87816be13/ca84cf90-a95a-47d1-86f9-85d157668a81)

**Comment by NickHaggerty1** [comment]
Something similar to this @millianapia (this is in word but just for to show the lack of spacing)

**Comment by millianapia** [comment]
new round of technical review, but i just removed the vertical spacing on list items, will give you a heads up when it is ready to be reviewed again @NickHaggerty1

**Comment by NickHaggerty1** [comment]
@millianapia @fernandolucchesi. Thanks. Approved
