### ISSUE TITLE
New SlugInput for Sanity v3

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1651]
Sanity v3 does not allow async calls in the components' options anymore. This means we cannot prefetch the slug prefix outside the SlugInput component. In order to fix it for Route types, the logic was moved inside the custom component (#1634). However, this is getting pretty ugly and is not scalable. Also, local news logic is broken and the fix done for routes is useless for local news.

In order to fix it we can choose two approaches:

1. Extend the current component to deal with localNews logic (quicker fix, but no non generic and ugly code)
2. Build a fancy component that accepts prefix logic as option. (elegant solution but requires more refactoring). Looks like this library could be an option: https://github.com/hdoro/sanity-plugin-prefixed-slug, or at least fork it and adapt to our needs.

**Comment by fernandolucchesi** [comment]
Hi @padms, left some minor comments =)

**Comment by padms** [comment]
@fernandolucchesi  Fixed the types

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Fixed the types

Looks good! ✅
