### ISSUE TITLE
Update runbook

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1652]
- [x] @fernandolucchesi to update secret site architecture diagram
- [x] @fernandolucchesi to create and add secret site publication routine
- [x] @fernandolucchesi review secret site info with v3
- [x] @fernandolucchesi to add information about where to find info when website is down
- [x] @nilsml to add link to affiliate users' service now ticket
- [x] @nilsml to write about decommissioning of team members
- [x] @millianapia to write about the branching strategy
- [x] @millianapia to update CI info with new Branching Strategy
- [x] @padms to change envs related to v3 (once v3 is live)
- [x] @padms to write about decommissioning of satellites
- [x] @SvSven to write about Security logging (PIM, Sanity History etcs)

**Comment by nilsml** [comment]
Looks good!
I wonder if we should also copy the SLA part from Sanity into the document. There is an SLA section.

**Comment by nilsml** [comment]
Did we add a section for SLA?

**Comment by fernandolucchesi** [comment]
Runbook and architecture contract were updated with new secret info.

https://github.com/equinor/architecturecontract/pull/1767
