### ISSUE TITLE
Accessibility issue with"scrolling arrow"

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1653]

**Comment by meols** [comment]
Can you please add an alt text to the scrolling arrow(s), as pointed out in siteimprove:
https://my2.siteimprove.com/Accessibility/550893/52537632527/NextGen/Issue/1?ruleId=12&pageSegments=&issueKind=1&exceptTags=1,2&conformance=&siteTarget.conformanceLevels=0,1,3
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/1318ecc6-651d-404a-aff3-fa05dd6da51f)

**Comment by SvSven** [comment]
LGTM ✅
