### ISSUE TITLE
Wrong url for Cookie policy in Cookiebot banner

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1656]

**Comment by meols** [comment]
Please update the link to the cookie policy page in the cookie banner to https://www.equinor.com/about-us/cookie-policy
Currently it is redirected to https://www.equinor.com/cookie-policy and gives a 404.
The same change is needed for the Norwegian site/cookie banner, where the link should go to https://www.equinor.com/no/om-oss/informasjonskapsler
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/4b1244f1-e2fc-4c93-83ab-71c2de7d941f)

**Comment by padms** [comment]
@meols This is changed in production.

**Comment by meols** [comment]
@padms @fernandolucchesi  - I see that the cookie banner text showing on the Norwegian site is also in English, and not in Norwegian. I thought we have translations to all relevant languages and showed a cookie banner in the site's language - is that wrong? 

Some more comments:
- On satellite sites the cookie policy link is also wrong/old (ending with .html), and for sites with two languages only one language is used in the cookie banner - so that the Argentina site shows Spanish text for both Spanish and English site, the Japanese site shows Japanese for both the Japanese and the English site and so on.
- The text on the linked word website is smaller (in all cookie banners) - see attachment.
- Do you need an overview from me for the correct link for all sites, or is it OK for you to find the Cookie policy link in each site footer?

![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/cfb15f34-bca7-46eb-992f-d86f7eb66f24)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/d28f3609-5145-43cb-89b7-67353631dc6a)

**Comment by padms** [comment]
@meols 

> On satellite sites the cookie policy link is also wrong/old (ending with .html), and for sites with two languages only one language is used in the cookie banner - so that the Argentina site shows Spanish text for both Spanish and English site, the Japanese site shows Japanese for both the Japanese and the English site and so on.

This happens when you try to switch language before the dialog shows. You can try refreshing the page and it shows correctly. 

> Do you need an overview from me for the correct link for all sites, or is it OK for you to find the Cookie policy link in each site footer?

I found an issue here for english language, we use common text for english content in all the sites, currently the website link is set to "/about-us/cookie-policy" which works for main site, but the other satellite sites have their own cookie-policy url. Foe ex for https://www.equinor.co.kr/en/cookie-policy.  So, in these sites website link is wrong. To fix this you can create another route called "cookie-policy" to the cookie policy page on the main site. I would then change the website link to "/en/cookie-policy"

**Comment by meols** [comment]
@padms - regarding "This happens when you try to switch language before the dialog shows. You can try refreshing the page and it shows correctly."
If I enter the Argentina site in Spanish and accept necessary cookies only, and then change the language to English, I get the Accept cookies/Cookie settings in English for the YouTube film. 
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/c4c3b00b-dbea-46ee-85d4-1921f53e108f)
When I click Cookie settings (on the English page) I get the Spanish Cookie settings box.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/e40a461b-947a-4d29-9edc-241080f13554)
If I refresh the (English) page the Spanish cookie settings box disappears, and I see the Accept cookies box again. If I then click on the same button that gave Spanish text it now gives the English text.

This isn't very intuitive for the end users. Can we have a "process" where we don't expect users to know that they need to refresh and do the same choice again/click the same button to get a different result = the site language, for the cookie settings?

Regarding the Cookie policy pages for the Website link in the cookie banner, all local languages should go to the local language page in the site, not the Global site/English one.

I will share an overview of the correct link to use per site.

**Comment by meols** [comment]
@padms - we have (hopefully) done what you suggested:
- created the top level route /cookie-policy (en site)
- created the top level route for /no/informasjonskapsler (no site)
- created a redirect from /about-us/cookie-policy to /cookie-policy (in case anybody else in Equinor has used the link)
- created a redirect from /no/om-oss/informasjonskapsler to /no/informasjonskapsler (in case anybody else in Equinor has used the link)
- deleted redirect from /en/cookie-policy.html to /about-us/cookie-policy (to avoid redirect chain)
- deleted redirect from /no/cookie-policy.html to /no/om-oss/informasjonskapsler (to avoid redirect chain)
- deleted the old routes and relinked in footer and other referenced pages (both languages)

Please confirm if this is what you wanted us to do :smile: and do any necessary updates for the cookie messages/banner on the satellite sites

**Comment by padms** [comment]
@meols 

- Please also create a route for Equinor Fondene "/informasjonskapsler" and create a redirect from "/om-oss/cookie-policy" to "/informasjonskapsler".

 Rest of them looks good.

**Comment by meols** [comment]
@padms - Trude and I have fixed this now :smile:

**Comment by padms** [comment]
@meols This is working as it should now. I created #1701 to handle the language issue and the font.

**Comment by meols** [comment]
Thanks Padmaja - this is approved :smile:
