### ISSUE TITLE
Add Equinor font

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#166]
Part of #97

Find [the best way](https://leerob.io/blog/fonts) to add the Equinor font to the Next.js and Storybook. 

What about variable font, should we use that/do we need that?

**Comment by wenche** [comment]
This issue might be covered by #165?

**Comment by SvSven** [comment]
Equinor font has been added using CDN provided by EDS: https://github.com/equinor/energyvision/commit/0602f14ae688e2427f6b870ec729da65bf7b36c7

We may want to revisit this at a later point to optimize it as described in the article @wenche linked as the current approach just links to a css file with @font-face
