### ISSUE TITLE
Friendlycaptcha license moving to Atea - take action

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#1664]

**Comment by padms** [comment]
After deploy update the api key in radix console

**Comment by padms** [comment]
https://github.com/equinor/energyvision/pull/1708
https://github.com/equinor/energyvision-internal/pull/77

**Comment by fernandolucchesi** [comment]
❗REMEMBER TO UPDATE API KEY IN RADIX DURING THE NEXT DEPLOYMENT
