### ISSUE TITLE
As Equinor I want to ensure accessibility so that the web pages are easy to use for every audience

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#167]
This task is about testing for a11y. Team to discuss what is needed.

## Acceptance criteria
1. Editors receive guidance within Sanity Studio on a11y 
2. Code is somehow tested for accessibility errors (axe or similar tools?)
3. Code is linted with a11y focus

## In order to ensure good quality we should
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test

**Comment by nilsml** [comment]
I guess this will be more about the testing. Will keep it until further notice.
