### ISSUE TITLE
Update the contact us form

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1677]
We have two updates for the Contact us form:

1. Can you please remove the field **Who are you trying to reach?** (en)/**Hvem er det du prøver å nå?** (no) 
2. Also please add the placeholder text below (in the same way as Jane Doe in name field) in the **What is your request?** (en)/**Hva ønsker du å spørre om?** (no) fields:
_English form:_
Please don't enter any personal information
_Norwegian form:_
Ikke legg inn personlige opplysninger

Question: Is it possible to create a link to the form where a category is preselected or have the form on a page with a category preselected - instead of having to choose a category? This is for the humans rights category, where we have a request/discussion to either having the form on a human rights page, or to have a link to the form. For either option they would like to have the category preselected.

**Comment by padms** [comment]
@meols It is possible to preselect the option and mark it disabled like this.
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/c94cb60e-2fa4-4dff-9340-d3cd5ed7255b)

**Comment by padms** [comment]
branch padms/1677

**Comment by padms** [comment]
@NickHaggerty1 This is ready to be tested. 
https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/topicContent;39d13acb-e07f-4559-bf6b-6e8c6b3dd562

**Comment by NickHaggerty1** [comment]
@padms @fernandolucchesi I would say this is approved. Mette might need a final say as it was her request.

**Comment by meols** [comment]
Thanks @padms - this is approved
