### ISSUE TITLE
Add /magasin/xxx and /magazine/xxx to the options in Featured content in the menu.

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1689]
Currently it isn't possible to promote magazine articles in the menu
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/41ec8e3c-a059-4513-9ada-16b973ef35d8)

**Comment by fernandolucchesi** [comment]
@meols can you check this one? :)

**Comment by meols** [comment]
@fernandolucchesi - it doesn't seem to work. I searched for "looping video" which should give two magazine articles to choose from, but they are not found: ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/d058f8da-35f6-496a-8653-7d54768b71fc) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/2779b200-4d8e-4829-8e0d-088b49e7638a)

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - it doesn't seem to work. I searched for "looping video" which should give two magazine articles to choose from, but they are not found: ![image.png](https://camo.githubusercontent.com/987ff603384b8575e51302b9ed470371b826011875e76462bb036f9fd9f7cc4c/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f64303538663864612d333566362d343936612d383635332d376435343736386237316663) ![image.png](https://camo.githubusercontent.com/d415a665767ec620d41c8c093fd68111de043e152f0e0fd6111b0f2c9b852630/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566626266346632626162386165373434636236353630662f32373739623230302d346438652d343832392d386530642d303838623439653736333861)

Hi @meols, just noticed that you are using the old studio and changes were only deployed to the new one: https://studiov3-global-development-equinor-web-sites-dev.c2.radix.equinor.com/global-development/desk/menu;menu-english;subMenuTest;80234d84-08f2-4a2c-8ea2-23c93a4a4512

**Comment by meols** [comment]
Thanks @fernandolucchesi - then it worked, and is approved :smile: Does that mean that this change (and other updates we do) now only is applied to v3, and won't show until August when we do the switch?

**Comment by fernandolucchesi** [comment]
> Thanks @fernandolucchesi - then it worked, and is approved 😄 Does that mean that this change (and other updates we do) now only is applied to v3, and won't show until August when we do the switch?

No, it will be applied to both. =)
