### ISSUE TITLE
Find out why  "Javascript not enabled" is picked up by google as relevant to our share page?

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1690]

**Comment by meols** [comment]
Also, how can we avoid this? :smile:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/c369d200-1032-4cf9-9aaa-fb87437a1225)

**Comment by millianapia** [comment]
@meols it is the euroland iframe that is used that has a text "javascript is not enabled". If Euroland adds a meta tag telling bots not to index (like <meta name="robots" content="noindex, nofollow"> ) then it might be excluded, but it has to be on their end

**Comment by meols** [comment]
Thanks @millianapia :smile: - I've forwarded info to the graph/iframe vendor, so this ticket can be closed.
