### ISSUE TITLE
Issue in siteimprove: Pages with low text-to-code ratio

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1692]
We see in Siteimprove that almost all our pages have a low text-to-code ratio: https://my2.siteimprove.com/SEOv2/550893/Recommendations/CodeTextRatio. It is probably true for some pages, but e.g. the HSE page has a lot of text and is still flagged with the issue: https://my2.siteimprove.com/Inspector/550893/SeoV2New/Page?pageId=49862221899&impmd=EFD4B031A902A9835A39E9F85FFF6A77&pageMode=Content#/issue/codetextratio/73

Can you please look into it, as it seems to us that it could be more the code that is an issue that the content, even if it is categorized as a content issue?

**Comment by padms** [comment]
https://validator.w3.org/nu/?doc=https%3A%2F%2Fwww.equinor.com%2Fsustainability%2Fhealth-safety-and-security

**Comment by padms** [comment]
Technical changes
