### ISSUE TITLE
Fix cookie dialog language when switching between languages.

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1701]
Also fix the font size of links in cookie dialog content.
https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/d28f3609-5145-43cb-89b7-67353631dc6a
https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/cfb15f34-bca7-46eb-992f-d86f7eb66f24

**Comment by padms** [comment]
LGTM

**Comment by fernandolucchesi** [comment]
@meols, can you test this on https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/

**Comment by meols** [comment]
@fernandolucchesi - looks good - approved :thumbsup:
