### ISSUE TITLE
statoil.com is not redirecting to equinor.com

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1718]
Missing redirect on the load balancer, for non-www url

**Comment by padms** [comment]
Ticket created https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fequinor.service-now.com%2Fselfservice%3Fid%3Dticket%26table%3Dsc_req_item%26sys_id%3D0ffbc99047e3e95041bad352e36d437b&data=05%7C01%7Cpadms%40equinor.com%7C432c34b49dc747fab0cb08db7304689f%7C3aa4a235b6e248d591957fcf05b459b0%7C0%7C0%7C638230235002452072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rXTwJSyIZKsW1pugIHD5ksXXNVEl0ScmM8m1hBgsKHw%3D&reserved=0

**Comment by fernandolucchesi** [comment]
Requested knut to escalate

**Comment by fernandolucchesi** [comment]
Done!
