### ISSUE TITLE
Define color styles in Figma 

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#173]
## Acceptance criteria
1. Define a "pool" of colors with corresponding variable names
2. The same names should be used both in Figma and as CSS variables
3. No states and no usage related information in the names

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Extra focus on usability
- [ ] Test for accessibility

**Comment by wenche** [comment]
I added most of the colours from Figma as CSS variables
![Skjermbilde 2021-03-08 kl. 14.42.29.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2039e3b3-df29-44d4-afe6-941af7ed6ae5)
But the colours in this picture don't match this pattern, as they have state and usage information in their names:
![Skjermbilde 2021-03-08 kl. 14.30.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a56d23e9-7284-4b82-bb1d-5e17f59cbb9a)

@BirteThornquist Should we see if we find an even better way of naming the colors?

**Comment by BirteThornquist** [comment]
@wenche I have changed the color naming to only include the color name and then numbers from 100 -> for the individual colors. So no contextual names at this stage.
