### ISSUE TITLE
Create a document explaining what is being indexed in Algolia

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1751]
We need a document showing what is currently being indexed in Algolia.
This document will be the baseline for discussions within team (including COM) on what we will/should/would index, and what we deliberately don't want to index.

**Comment by padms** [comment]
Created this document. https://statoilsrm-my.sharepoint.com/:w:/g/personal/padms_equinor_com/EWiAWygoRcRLvxOB25Nv5DgBThzsfHP123Un8UQh2T394A?email=fg_envis%40equinor.com&e=JQbLZC

**Comment by fernandolucchesi** [comment]
> Created this document. https://statoilsrm-my.sharepoint.com/:w:/g/personal/padms_equinor_com/EWiAWygoRcRLvxOB25Nv5DgBThzsfHP123Un8UQh2T394A?email=fg_envis%40equinor.com&e=JQbLZC

Moving it to acceptance @meols @NickHaggerty1

**Comment by meols** [comment]
@padms - Thanks for explaining, but when you say "As of now, text blocks and accordions are indexed for a topic page.", do you mean that only content in text blocks and accordions are indexed (and not content in any other components)? We wonder which components have their text content indexed.
E.g. if I search for "CV Anders Opedal" I get no hits, even if it is the same text as on a people promotion button. ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/e02bef8a-747d-4ddb-b279-25059f05becf)
or if I search for "current job vacancies", that is used in a top banner I also get no hits.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/8a9155df-344e-4d78-9cec-369d2237868f)

**Comment by padms** [comment]
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/412ffcbd-fee5-4daf-a5de-258e5d8ac3a8)

**Comment by padms** [comment]
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/40e70e92-f784-4627-bd6a-596156c8d825)

**Comment by padms** [comment]
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/0081d625-6a9d-4df6-b87e-08f1c6196f7b)

**Comment by padms** [comment]
@meols Only Page title , Texblock component (title, ingress,text) and accordion component ( title, ingress) are indexed. No other components are indexed. ![indexed1.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/0474786b-6368-4b6b-9903-497ded66e8bc)![index3.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/50dd1c6e-1de4-4182-b3b1-0f867334ee46)![indexed2.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/c9c06a93-c733-4703-8407-022248005d8e)![indexed4.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/7b0b8ec1-0df9-4422-b75e-ec7d407f0f80)

**Comment by meols** [comment]
Thanks for a good explanation @padms. Is it possible to index more components, what will doing that affect? If we want to index more components, what/which components can we index and what input do you need from us (name of component/name of text field/name of other fields etc.)

**Comment by meols** [comment]
And one additonal question @padms  - what about the news template; will the text content in a fact box be indexed?

**Comment by meols** [comment]
@padms - especially the accordion items would we like to index. Can that be done?

**Comment by meols** [comment]
@padms - yet another question :smile: is it correct then that people will get better search results in google than on our site, and does our not indexing everything setup affect anything in google?
