### ISSUE TITLE
Adjustments to the the image component

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1752]
Currently the image components height is defined by the image choice. For consistency on the pages we would like to include an option to have a defined height/size of 16/9 when using the image component.

1. Add option for editor to toggle between 16/9 or original (as it is today)
2. Set default to be 16/9
3. This applies to the image component on Topic / Magazine / Event / News article template
4. 

Use script from issue-1756 folder to migrate ...

**Comment by meols** [comment]
@padms - 16:9 needs to be preselected/default, otherwise we will need to edit all image components.

**Comment by padms** [comment]
@meols Ran a script which sets aspect ratio of all existing image components to original. Newly created image components will have 16:9 as default.

**Comment by meols** [comment]
Thanks @padms - I have one question to the crop/hotspot: shouldn't the crop hotspot I have used for the picture below look like the 16:9 below the crop tool? Now it looks like it's been cropped a bit at the top and the bottom whithout considering the crop/hotspot. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWxTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ca3f19dff18f8f7618cc9d7db0fa97a29fc33630/image.png)

**Comment by padms** [comment]
@meols Image component does not respect crop and hotspot https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/images#image

**Comment by padms** [comment]
Related  https://github.com/equinor/energyvision/issues/775

**Comment by millianapia** [comment]
waiting on migration script

**Comment by padms** [comment]
Lets move this to acceptance. Looks good to me.

**Comment by meols** [comment]
@millianapia - not really sure what to expect here. Please describe what has changed and/or the acceptance criteria. Should I expect 16:9 to be default or available as an option? Shouldn't the guy to the right disappear on the preview with the crop and hotspot I used on it (still as a portrait image)? Also tried to crop the portrait image to a landscape format, which still doesn't work. Screenshots below from Mette's testpage (bottom).
<img width="1798" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBendYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c507b646a977f36481e631fc1f1b83e27f3d6bb8/image.png" alt="image.png" />

Also this crop doesn't work:
<img width="1646" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFYQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e09eb9b4dd6e73ab793f0bfbf74723d7070678b/image.png" alt="image.png" />

**Comment by millianapia** [comment]
@meols

**Comment by meols** [comment]
@millianapia - a few comments;
- we don't see a toggle between 16:9 or original
- it seems like we can't revert to an "uncropped" image
- no matter what kind of crop we do, the result is 16:9 (centered?)
- we need to keep original format for e.g. maps that are in use
- what will happen with images that are in use today if this crop is impelemented? We want to keep images that are in use on a page as they are

**Comment by meols** [comment]
@millianapia - this looks good. Please confirm the last point "what will happen with images that are in use today if this crop is implemented? We want to keep images that are in use on a page as they are". I assume that no selection is made for Aspect ratio - that the selection is blank (neither 16:9 or Original), and that all images appear as they currently are shown?
