### ISSUE TITLE
Spacing on News article template needs addressing

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1753]
Looking at the news article the spacing between components and components within the text module seems to be duplicated or even trebled. The spacing needs to reflect the spacing reference on TOPIC page template between components. 
Reference page link below:

1. Double space between Ingress and text module.
2. Seems to be triple spacing Text module and Iframe and iframe to Links.
3. Seems to be double spacing within the text module between text and factbox. The correct spacing is shown between text and image.

https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/api/preview?type=news&locale=en&slug=%2Fnews%2Fnick-testing-the-layout&secret=jlskdjfkj4323lk4jlkjlksdf

**Comment by padms** [comment]
@NickHaggerty1 @meols This is ready for a second review.

**Comment by meols** [comment]
@NickHaggerty1 - can you please check this one?

**Comment by NickHaggerty1** [comment]
@padms Looks better. thanks
