### ISSUE TITLE
Improve docker image cleanup script

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1770]
We are cleaning up the latest 5 images every day. The images are the ones generated when we deploy to pre-prod, meaning that if merge to main 5 times without releasing to prod, the image will be gone and radix won't be able to pull it.

Plus: make images private

**Comment by fernandolucchesi** [comment]
https://github.com/snok/container-retention-policy/issues/66

**Comment by fernandolucchesi** [comment]
Not in the PR but requires review (already in main):
https://github.com/equinor/energyvision-internal/blob/main/ci/storeImageTags.js
and changes to PROD actions for both studios and webs

**Comment by padms** [comment]
Looks good to me.
