### ISSUE TITLE
Carousel buttons should have a marked focus area

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1776]
Issue notified in siteimprove:
https://my2.siteimprove.com/Accessibility/550893/52537632527/NextGen/Issue/1?ruleId=65&pageSegments=&issueKind=2&exceptTags=1,2&conformance=&siteTarget.conformanceLevels=0,1,3

https://my2.siteimprove.com/Inspector/550893/A11Y/Page?pageId=49866725245&impmd=EFD4B031A902A9835A39E9F85FFF6A77&expand=potential&conf=a+aa+aria#/sia-r65/cantTell/YWJ3VnFkSS8=;ZGU3NmZlYjA=

![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/93e5e8c8-c5b3-48d3-901c-a9221a3e33d6)

**Comment by padms** [comment]
@meols The arrow buttons should have dotted circle when focused.

**Comment by NickHaggerty1** [comment]
Think this is good @meols. Not sure if you need to check in siteimprove

**Comment by meols** [comment]
@padms @NickHaggerty1 - looks good :thumbsup: We'll see the effect in Sitemprove after it's deployed
