### ISSUE TITLE
 Home text in Norwegian site breadcrumbs should be "Hjem" instead of "Home"

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1778]
Please update the code to Norwegian "Hjem" for the Norwegian site:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/cf0ec2c8-07ab-4ca5-ae72-9e1cf7526c94)

**Comment by padms** [comment]
@meols A textsnippet for "Home" is added in Others folder, which is used on the breadcrumb.

**Comment by meols** [comment]
Thanks @padms - this is approved :thumbsup:
(I only found it in dev v3, should it be in dev v2 as well?)

**Comment by padms** [comment]
> Thanks @padms - this is approved 👍
(I only found it in dev v3, should it be in dev v2 as well?)

@meols The change is done for v2 as well but it is not deployed.
