### ISSUE TITLE
As an editor I need to be able to add anchor points to pages and name/show these points in a menu so users can navigate the content on the page.

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#178]
## Acceptance criteria
1. Anchor point needs to feature in a URL too, so editors can point a user directly to that piece of content in the URL
1. If anchor links are added to the page by editor, an additional menu appears on the page for users to jump to the points of the page where the anchor(s) is added
1. Anchor link menu points should be highlighted/animated as user scrolls through/past each anchor point.
1. Anchor links menu hides when user scrolls up (short delay)
1. _Investigate/discuss: Should anchor link menu also include links to other pages of interest or be restricted to anchor links for that page? Currently AEM is set up this way (https://www.equinor.com/en/careers.html)_

## In order to ensure good quality we should
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test

**Comment by nilsml** [comment]
Perhaps stick to anchor links within the page itself. Otherwise we might get ourselves into trouble 😱

**Comment by nicholas-haggerty** [comment]
Closing as this is a duplicate. Defined on #346
