### ISSUE TITLE
Error in static website script deployment -Azure setup 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1828]

**Comment by fernandolucchesi** [comment]
links to what has been changed?

**Comment by padms** [comment]
@fernandolucchesi https://github.com/equinor/energyvision-internal/commit/8c3f52143b8f27cda9afbed742f3be7fb08bed9a

**Comment by fernandolucchesi** [comment]
Oh sure, ill close this since already released

**Comment by fernandolucchesi** [comment]
✅
