### ISSUE TITLE
Disable time trigger function

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1829]

**Comment by fernandolucchesi** [comment]
not sure how to test it but sounds good... thought it was disabled already

**Comment by padms** [comment]
@fernandolucchesi , this sets AzureWebJobs. <FUNCTION_NAME>. Disabled = 1 in the app settings of the function app. This is the standard setting to diable a function in a function app for all runtime envs... the disabled attribute in function.json does not work for Azure functions > 1

**Comment by fernandolucchesi** [comment]
approved! you forgot to create the PR =p
