### ISSUE TITLE
Do not auto start downloading screen9 videos until play button is clicked

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1830]

**Comment by fernandolucchesi** [comment]
@meols @NickHaggerty1 can you please review if the looping hero banner/video component / and carousel video component still work as it should? there were significant changes to the code that touches videos in order to increase performance, but the behaviour should be the same.

**Comment by meols** [comment]
@fernandolucchesi - I tested from home yesterday, and then the top banner became blurry for a bit and then fine again (see attached video). I also asked Trude to test (from home) and she experienced the same thing.
[Uploading... video top banner.mp4]

 Testing at the office today I see no blurring and it looks good.

@NickHaggerty1 - can you also test this
