### ISSUE TITLE
Table component in v3

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1832]

**Comment by meols** [comment]
Can we have a table component in v3?
https://github.com/sanity-io/table
![alt text](https://user-images.githubusercontent.com/8467307/48703530-e369be00-ebeb-11e8-8299-14812461aee8.gif)
Questions: 
- Will copy-paste from excel across the table work in such a table? 
- Can we style the text (bold, italic, header row, possibly also colors etc) and give rows a background colour?

**Comment by nilsml** [comment]
Remember accessibility!!

**Comment by fernandolucchesi** [comment]
Investigate what solutions are there

**Comment by fernandolucchesi** [comment]
investigate if we can improve our current setup by adding italic, bold, and color for headers and rows

**Comment by fernandolucchesi** [comment]
@meols, the table plugin from sanity is very basic, and we can not simply plug and play it for our needs. It also doesn't allow pasting from Excel (there is an open request from the community https://github.com/sanity-io/table/issues/26 for this same feature though).

So I suggest we go for the low-hanging fruit improvement of our current setup and work on a fancy table component later.

**Comment by fernandolucchesi** [comment]
As for the colours, I believe we should have a pre-set allowed values, to avoid bad design decisions by editors. What is the use case for these colors? @NickHaggerty1 any input?

**Comment by NickHaggerty1** [comment]
@fernandolucchesi  No idea what the options are on colour. Currently we only have option to change the colour on background which I think is fine. Im not sure there would be a need for any other colour options on a table?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi No idea what the options are on colour. Currently we only have option to change the colour on background which I think is fine. Im not sure there would be a need for any other colour options on a table?

Hmm the colours was a request from @meols, we can discuss this further when she is back from holidays

**Comment by NickHaggerty1** [comment]
She was asking what the options are yes for various things. Didnt see anywhere that described what the options were! Until we know, hard to know what to suggest (if anything at all)

**Comment by fernandolucchesi** [comment]
> She was asking what the options are yes for various things. Didnt see anywhere that described what the options were! Until we know, hard to know what to suggest (if anything at all)

We can add all text decorators' requests in the current setup we have.

**Comment by NickHaggerty1** [comment]
Design tweaks:
1. Add white key lines for column separation
2. Add themes for editor to choose colour
3. Add colour to headers
4. Add colour to alternate rows

Blue theme:
Header background = A8C3DB
Header band/separator = 7294BB
Row background = D6EBF6
Remove mist blue from background choice.

Green theme:
Header background = C2D4D6
Header band/separator = B5C7C9
Row background = E3EDEA
Remove green from background choice.

**Comment by NickHaggerty1** [comment]
<img width="1358" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVd0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f114f23c5739282c48d1e22b76769e2629567530/Screenshot%202024-01-09%20at%2012.40.51.png" alt="Screenshot 2024-01-09 at 12.40.51.png" />

**Comment by NickHaggerty1** [comment]
<img width="1356" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWV0QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39071588d30bc1e0704f34600d1cd1c2aa0617ed/Screenshot%202024-01-09%20at%2012.41.24.png" alt="Screenshot 2024-01-09 at 12.41.24.png" />

**Comment by fernandolucchesi** [comment]
Hi @NickHaggerty1, can you review this on dev environment?

**Comment by NickHaggerty1** [comment]
Hey @fernandolucchesi looking good. One small thing, for blue theme the mist blue is still an option for background colour and Green theme the green background also available. Need to hide these.

**Comment by NickHaggerty1** [comment]
<img width="1523" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0xlQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8eafd1873586bd9b283efb72c3db5b9d35cb2861/Screenshot%202024-01-19%20at%2008.04.29.png" alt="Screenshot 2024-01-19 at 08.04.29.png" />

**Comment by NickHaggerty1** [comment]
@fernandolucchesi nice! approved

**Comment by guzmancarlosal** [comment]
@fernandolucchesi 
can we copy/paste tables from excel or google doc to sanity block now? You closed this as completed last week. I want to know if I can copy/paste tables. Following is my schema definition. can you revise me?

import {defineType, defineArrayMember} from 'sanity';

export default defineType({
  title: 'Block Content',
  name: 'blockContent',
  type: 'array',
  of: [
    defineArrayMember({
      title: 'Block',
      type: 'block',
      styles: [
        {title: 'Normal', value: 'normal'},
        {title: 'H1', value: 'h1'},
        {title: 'H2', value: 'h2'},
        {title: 'H3', value: 'h3'},
        {title: 'H4', value: 'h4'},
        {title: 'Quote', value: 'blockquote'},
      ],
      lists: [
        {title: 'Bullet', value: 'bullet'},
        {title: 'Number', value: 'number'},
      ],
      marks: {
        decorators: [
          {title: 'Strong', value: 'strong'},
          {title: 'Emphasis', value: 'em'},
          {title: 'Underline', value: 'underline'},
        ],
        annotations: [
          {
            title: 'URL',
            name: 'link',
            type: 'object',
            fields: [
              {
                title: 'URL',
                name: 'href',
                type: 'url',
              },
              {
                title: 'Open in new tab',
                name: 'blank',
                type: 'boolean',
              },
            ],
          },
        ],
      },
    }),
    defineArrayMember({
      title: 'Table',
      name: 'inlineTable',
      type: 'object',
      fields: [
        {
          name: 'table',
          title: 'Table',
          type: 'table', // Specify 'table' type
        },
        {
          name: 'caption',
          type: 'string',
          title: 'Caption',
        },
      ],
    }),
    defineArrayMember({
      type: 'image',
      options: {hotspot: true},
    }),
  ],
});

**Comment by guzmancarlosal** [comment]
@fernandolucchesi Following is the table I want to copy and paste. It includes hyperlinks.
![image](https://github.com/equinor/energyvision/assets/17786145/70b572d4-83d7-4173-8701-94c86d879299)
Can you let me know if I can copy/paste this table into sanity studio?

**Comment by fernandolucchesi** [comment]
Hi @guzmancarlosal, unfortunately not. This feature is something we also need in our project, but we haven't implemented it yet :/
