### ISSUE TITLE
How to handle accessibility issues for videos?

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1834]

**Comment by meols** [comment]
Currently the streaming video component isn't optimal for screenreaders.

Ref. Slack discussion https://app.slack.com/client/T02JL00JU/C01MU3H6G0Y/thread/C01MU3H6G0Y-1689857111.343759
and 
https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/gh/equinor/energyvision/1638

For discussion:
- title - invisible on page, for accessibility
- caption or not - visible or not?
- description/alt text?
- mark as decorative?
- same options as for iFrame component?

**Comment by fernandolucchesi** [comment]
setup a meeting with siteimprove clarifying how to handle these

**Comment by fernandolucchesi** [comment]
suggestion from siteimprove is adding a simple caption:

`  <span class="visually-hidden">Captions: This is a beautiful video showcasing our products.</span>`

**Comment by meols** [comment]
Thanks @padms - Let's give this a try :smile: Could the explanation be changed to "Use the alt text below to describe the video content (for screenreaders)."

**Comment by padms** [comment]
@meols I have changed the description.
