### ISSUE TITLE
Background colour picker in components should have mouseover colour names, as in v2

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1837]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVFMIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--68e460968c5b55db0cb302eefe9bf0099d4f2ef9/image.png)

**Comment by meols** [comment]
Thanks @padms - can we add it for these components as well?
- Image carousel
- Horizontal scroll iFrame
- Video player
- Horizontal scroll video player

**Comment by padms** [comment]
@meols Can you check this again on https://studiov3-global-development-equinor-web-sites-dev.c2.radix.equinor.com/ ? I can see the tooltip for all the components above

**Comment by meols** [comment]
You are absolutely right @padms - sorry! Then this is perfect and approved :smile:
