### ISSUE TITLE
As a Equinor I want certain content to be treated confidentially in the solution so that it doesn't fall into the wrong hands

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#184]
## Acceptance criteria
1. It is possible to limit access to the data to certain persons within the company
1. Data can be made public when possible

## In order to ensure good quality we should
- [ ] Perform security testing
- [ ] Perform integration testing
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test

**Comment by nilsml** [comment]
I guess #1000 is a duplicate of this @fernandolucchesi?

**Comment by fernandolucchesi** [comment]
You are correct, closing it
