### ISSUE TITLE
Index more components

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1864]
Let's discuss which components to start indexing. I suggest to discuss in a planning meeting to get input on what the dev team needs as input from Mette. Accordion item is a good component/content candidate to discuss.
Ref. discussion in #1751

**Comment by NickHaggerty1** [comment]
Is factbox on News template indexed?

**Comment by padms** [comment]
@meols This is ready to be reviewed. 

- Factboxes in news articles are searchable. 
- Accordions in topic and magazines are searchable. 

Also, I found that local news articles stopped getting indexed, this is fixed in #1970

**Comment by meols** [comment]
Thanks @padms - this is great, and approved :smile:
