### ISSUE TITLE
9:16 videos in full screen are shown as 16:9, should be 9:16

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1865]
See examples on this page: https://www.equinor.com/energy/techstars

**Comment by fernandolucchesi** [comment]
Hi @millianapia, when working on the dependencies upgrade of hls.js  #1854 I had to do a small tweak in the video code. So I also ended up looking into this issue and am pushing a fix :) hope you don't mind.

**Comment by fernandolucchesi** [comment]
@meols @NickHaggerty1, this is ready to be tested on global-dev

**Comment by NickHaggerty1** [comment]
Nice. Approved @fernandolucchesi
