### ISSUE TITLE
Upgrade internationalization plugin

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1868]
- [ ] Modify the _lang field in webhook
- [ ] Run migration scripts createMetadata and renameLangField
- [ ] Update documentation

## Migration plan

1.  Content freeze for the dataset to be migrated. 
2.  Take backup of the dataset. 
3.  Push code to production for studio and web.  ( At this point both studio and web breaks.) 
4.  Run migration script createMetadata.mjs until no documents are found that is not migrated. 
5.  Run migration script renameLangField.mjs until no documents are found that is not migrated.
6.  Modify the _lang field in the webhook. 
6.  Rebuild web if necessary.

**Comment by padms** [comment]
Putting on hold, to discuss with sanity to see if there is a way to hide create option with out a language.

**Comment by padms** [comment]
On hold, because we want to hide the manage translations option

**Comment by meols** [comment]
@fernandolucchesi @padms - any updates from Sanity on this issue?

**Comment by fernandolucchesi** [comment]
@padms that could work, we would then need to refactor all the custom roles we have and replace the default "Editor" role, since the default one cannot be edited. Afterwards, change the SSO role mapping so people don't need to re-apply on accessIT
<img width="895" alt="image" src="https://github.com/equinor/energyvision/assets/23337266/a70186e2-d33e-46e2-9a6d-209a5701b0d6">
<img width="888" alt="image" src="https://github.com/equinor/energyvision/assets/23337266/4d836f61-6465-41a4-bf8d-e3bac1261fda">

**Comment by BorghildSelle** [comment]
#2140 Testing custom role to restrict and have a ticket with sanity regarding delete document when unset translation references

**Comment by BorghildSelle** [comment]
Have to modify plugin to hide the manage translation button

**Comment by padms** [comment]
## Migration plan

1.  Content freeze for the dataset to be migrated. 
2.  Take backup of the dataset. 
3.  Push code to production for studio and web.  ( At this point both studio and web breaks.) 
4.  Run migration script createMetadata.mjs until no documents are found that is not migrated. 
5.  Run migration script renameLangField.mjs until no documents are found that is not migrated.
6.  Rebuild web if necessary.

**Comment by padms** [comment]
@meols This is ready for testing. This upgrade affects all the documents. Hence, every aspect of creating, updating, deleting, duplicating a document and/or it translations has to be tested. 

Actions like linking a reference document, allowing same slug etc has to be tested. 
Algolia indexing, redirects, routes are to be tested.

**Comment by meols** [comment]
Some comments on this - will test further today, but we have more or less completed testing.

- Do we need to implement the extra click with “Translations”? We prefer to continue to visually see which language we are on immediately. 
- Can we continue to have the flags to indicate language?
- When toggle is on (e.g. image is decorative), can the active toggle continue to be green?
- Can active publish button continue to be blue (published status OK with light grey)?
- What is the “Vision” menu option in the top for? (Beside Schedule) Can it be hidden for editors?
<img width="1606" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM05xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f8a798e97bed34cc1154054c9bb1a778d3485189/image.png" alt="image.png" />

**Comment by padms** [comment]
@meols 

- Do we need to implement the extra click with “Translations”? We prefer to continue to visually see which language we are on immediately.
  _The current language of the document is at the bottom of the page. I will see if we can add a more prominent badge at the bottom of the document or within the document with the flag._

-  Can we continue to have the flags to indicate language?
    _I will check this_
- When toggle is on (e.g. image is decorative), can the active toggle continue to be green?
   _Its possible. Will fix this too._
- Can active publish button continue to be blue (published status OK with light grey)?
   _Will fix this too._
- What is the “Vision” menu option in the top for? (Beside Schedule) Can it be hidden for editors?
   _This is enabled only in the staging environment, hidden in all other environments._

**Comment by meols** [comment]
Thanks Padmaja! I'll do some more testing today.
Here is a suggested order of sites to update:
- Poland - one language, not much activity
- Japan – two languages, not much activity
- Celtic sea - two languages, not much activity
- Argentina - two languages, not much activity
- Storage - two languages, not much activity (has an [iframe ](https://www.equinorstorage.de/en/maintenance)that is important to them)
- Germany – one language, updates/publishing done by agency (we don’t know their plans)
- Equinorfondene – one language, some activity
- South-Korea – two languages, some activity
- Brazil – one language, more activity (doing updates/publishing themselves as well as getting support from us)
- Global site
- Secret site

**Comment by padms** [comment]
@meols  Added the flag and the language on the document as well as at the bottom of the document. I am still working on the colors and I haven't figured out the stable fix yet, if its ok, can we take the colors fix in a new card?
