### ISSUE TITLE
As an editor I want to promote certain content in the menu

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#187]
Menu contextual promotion

## Acceptance criteria
1. Editor can select which content to be displayed
1. Clicking the content takes the user to the correct content

## In order to ensure good quality we should
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility

**Comment by BirteThornquist** [comment]
We have to solve the lack of ingress text for promo card of topic pages in a separate issue.

**Comment by wenche** [comment]
Will be hidden on small devices.
