### ISSUE TITLE
H3 subtitle can't be selected in expanded text box

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1873]
When the text component content field is expanded we can't choose H3. When minimizing the text field we can choose H3.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ040IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--06cc356a247072befb00c20289fd28e1077f777c/expand%20view%20-%20no%20H3%20option.mp4)

**Comment by fernandolucchesi** [comment]
Fix: upgrade sanity to latest

**Comment by meols** [comment]
@fernandolucchesi - H3 doesn't work in expanded textbox on dev (see video on slack)

**Comment by meols** [comment]
@fernandolucchesi - Duplicating a topic page doesn't work on dev (it is on dev I should test, right?)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzNvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8d611e06683155125a29120d9141fb6d1cbc8271/image.png)

**Comment by meols** [comment]
@fernandolucchesi - thanks for the tip, it worked after a few refresh, sign out and clear history (all to be sure :smile:) Approved
