### ISSUE TITLE
Paragraph after bullet list not working as expected

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1880]
Something has happened with the spacing after a bullet list (seen in both text component and accordion) for the next paragraph. Currently there is no extra spacing:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcjJHIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--112ef427fe2f287c51678ab12b2c3c806879c847/image.png)
Se description in **#1632** for how it should be

**Comment by meols** [comment]
@fernandolucchesi Please note that this is correct in the news template:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFFEQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12d07b24882bb0b6721db99e56200a2469a14a99/image.png)

**Comment by millianapia** [comment]
hi @NickHaggerty1 @meols now there should be spacing after a list, can either of you verify that it works as expected

**Comment by NickHaggerty1** [comment]
@millianapia Doesnt seem to be fixed yet. I tested here:
https://studiov3-global-development-equinor-web-sites-dev.c2.radix.equinor.com/global-development/desk/topicContent;a353cb14-028f-45dd-bbea-4010d6968d3e

**Comment by NickHaggerty1** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3a29c8e5e70e9953e5fa46ebe701614cc53b854d/Screenshot%202023-11-15%20at%2010.14.33.png)

**Comment by NickHaggerty1** [comment]
@millianapia Working now. Approved
