### ISSUE TITLE
 As editors we want to create an additional 50/50 banner option to communicate certain messages to meet our brand positioning strategy

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1887]
New banner designs 2. Create an option in 50/50  banner for editors to place big text.
1. Add choice for editors to select Big text.
2. Rich text Element. Use all options in current rich text element (bold / Subscript etc)
3. The sketch for desktop should indicate a rough size but please loop Nick in once set up to finalise the pixel sizes and spacing.
4. Consider how to name the font size in terms of H numbers. 
5. Remove link option.
5. Banner addition should be available on TOPIC and MAGAZINE templates.
6. Banner should be available on ALL SITES
8. Text should follow accessibility as per rich text component.
9. Background and text colour should follow current set up.
10. New background colours will come soon[Uploading... 50-50 + big text banner.png
11. Follow current banner component behaviour for mobile: Image first. Colour box and big statement under.

Sketches available on CMS Figma board on BIG TEXT page.

**Comment by NickHaggerty1** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzJsIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8a2a9cbc5023bcc384caca864ec2a7daa9188d99/50-50%20%2B%20big%20text%20banner.png)

**Comment by padms** [comment]
@NickHaggerty1 @meols  This is ready to be reviewed. 

This includes the big title for default banner as well. #1886

**Comment by NickHaggerty1** [comment]
@padms @fernandolucchesi Sorry for late reply on this. Approved. Nice job
