### ISSUE TITLE
Issues with the table component

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1893]
When we try to add table rows to the table component we are not able to select the options. Adding headers works fine.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanl5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--db490b974b205b111c206fd4236d5ca1cfc487b3/table-issue.mp4)

**Comment by meols** [comment]
@fernandolucchesi - is this also related to  #1868?

**Comment by fernandolucchesi** [comment]
@meols no, probably related to the v3 migration

**Comment by fernandolucchesi** [comment]
this is fixed
