### ISSUE TITLE
Issues with adding components

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1900]
When trying to add components from the bottom of the components list (e.g. anchor link) I can't click to use vertical scroll to select the component, and need to use the up/down arrow keys + enter to be able to select and add the component.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa25aIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fc7971d5371fba31c83d6d0e20752e50ade8e0f1/add-component-issue.mp4)

**Comment by fernandolucchesi** [comment]
Not an issue anymore
