### ISSUE TITLE
Promote magazine error when using tagged articles

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1904]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZy9nIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--950587eff92bacb071be62e38c8026787add96ed/Screenshot%202023-09-27%20at%2014.21.18.png)

**Comment by meols** [comment]
@fernandolucchesi @millianapia - thanks, works now and is approved :thumbsup:
