### ISSUE TITLE
As a developer I want to use Typescript inside the studio folder

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#191]
## Acceptance criteria
1. Set up Typescript

**Comment by nilsml** [comment]
What is needed in terms of CI setup for Sanity?
Publish new stuff for Sanity Studio to Sanity's cloud?

**Comment by wenche** [comment]
CI setup is covered by #177. This issue doesn't actually make sense.  I'll  change it. :)

**Comment by wenche** [comment]
I think we have covered the Typescript setup for now. There will probably be adjustments as we start writing more code.

I was thinking of testing the [sanity-codegen plugin](https://www.npmjs.com/package/sanity-codegen), but let's do so when we have something in Sanity as well as in Next.js
