### ISSUE TITLE
Add big text option to Text component

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#1917]
As editors we would like to have the option to display larger text elements. This can be created as part of the current text component, and allow the user to toggle a "big text option" instead of the TITLE field.

The Big text option should have rich text options
Title should be hidden
Eyebrow should be hidden
All other options remain the same (ingress/body/colour background/links etc)
The attached sketch is a guide for the size. Contact Nick to discuss the final responsive display.
Consider spacing to the ingress and or body text also looks correct once big text option is place
Option should be available on TOPIC and MAGAZINE templates.
Option should be available on ALL SITES

**Comment by NickHaggerty1** [comment]
@fernandolucchesi FYI

**Comment by fernandolucchesi** [comment]
Hi Nick, I assumed the image also has to be hidden, is that correct? I fixed this together with #1890 to make it easier.

**Comment by fernandolucchesi** [comment]
Closing this as it is fixed on #1890
