### ISSUE TITLE
As an end user I want the news articles to have a nice design regardless of device and monitor size

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#192]
## Acceptance criteria
1. Nice looking design sketches in Figma in several screen widths
2. The content itself should be the main focus, not the exact devices

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test

**Comment by wenche** [comment]
Sorry @BirteThornquist I'll once again change your work in progress :grimacing: let's make it more appropriate for the work you actually are doing.

**Comment by vnys** [comment]
@BirteThornquist Looking at the design in Figma I think there’s a potential to simplify things a bit. Perhaps two margin variants instead of three, and fewer spacing variations between the elements?

**Comment by BirteThornquist** [comment]
Could well be that it is too complicated @vnys. Do you mean the hero image is at one margin and the main column should be the second one? For vertical spacing I use the type size as the guide....
