### ISSUE TITLE
Issue with /news-and-media/news and /presserom/nyheter pages

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1925]

**Comment by meols** [comment]
On search in google we find two pages per language for news on our websites.
The two showing the news list: https://www.equinor.com/news and https://www.equinor.com/no/nyheter/ 
In addition we find two "empty" pages with title only and no language switch: https://www.equinor.com/news-and-media/news and https://www.equinor.com/no/presserom/nyheter

We actually can't find these pages with title only, even if we find the route.
Do these pages serve a purpose or can they be deleted - if so, please delete them or send us the page links from Studio :smile:

Both the "empty" pages are found by google:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFFRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a6422495278cf63f8d8fda89448005a981f8995f/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFVRQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8eb4794c51eb34c8b896f6f5a5720ab088ccb34e/image.png)

**Comment by fernandolucchesi** [comment]
You can delete these, these routes are useless

**Comment by meols** [comment]
Thanks @fernandolucchesi - we have deleted the useless routes :smile:
