### ISSUE TITLE
Issue with external links in promo tiles

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1926]
We see that using external links (both page links and mailto links) in **promotiles** causes the link click to go to equinor.com home page, and not the correct external page or open an empty email.
Reported in siteimprove here: https://my2.siteimprove.com/Accessibility/550893/NextGen/Issue/1?ruleId=81&pageSegments=&issueKind=2&exceptTags=1,2&conformance=&siteTarget.conformanceLevels=0,1,3
(we understand that for the three pages United Kingdom and Carbon, capture and storage (no and en) the issue is different and related to read more/les mer)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVFXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--994e1d36714bf470ca5b17f5ed7916adb0eaa01d/image.png)

**Comment by fernandolucchesi** [comment]
Fixed on #1919
