### ISSUE TITLE
Renew SSL certificate for equinor websites

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1927]

**Comment by padms** [comment]
https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=fafe7011977179d09ccfb06de053af15

**Comment by fernandolucchesi** [comment]
https://equinor.service-now.com/now/nav/ui/classic/params/target/sc_req_item.do%3Fsys_id%3De5518def97393d109ccfb06de053afb9
