### ISSUE TITLE
Carousel is not aligning correctly when less than 3 cards

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1928]
<img width="1146" alt="Screenshot 2023-10-09 at 12 19 28" src="https://github.com/equinor/energyvision/assets/21845545/4cdda6a9-81c9-4f72-b009-ec4887c59955">

**Comment by padms** [comment]
@meols This is fixed and can be tested on this [page](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/padms)

**Comment by NickHaggerty1** [comment]
@padms @meols was this for the image carousel? (if so, approved) 
Or was it referencing an issue with the Horizontal scroll option on promotions?

**Comment by padms** [comment]
@NickHaggerty1 This affects all the components that have the horizontal scroll option. This issue is particularly reproducible when the no of cards in the components is less than 3, which happens with automatically picked events, news.

**Comment by NickHaggerty1** [comment]
@padms approved
