### ISSUE TITLE
Issue with Event promotion

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1929]
On the https://www.equinor.com/investors page we see an issue with events promotion, showing the two cards visible for events with different width. Could this be related to using Horisontal scroll? We have the same two promotions visible on this page https://www.equinor.com/investors/events-and-presentations as well, with what looks like the correct width on the cards and horisontal scroll isn't used.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN1lYQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d4c726191af3a619cc00f210801c811c881c76a2/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN29YQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ad702dfcc21732b49f43b6ffcf052b6b542f0c7/image.png)

We also have events on this page: https://www.equinor.com/news-and-media/events where Current and upcoming events have horisontal scroll on and shows the wrong width - but the past events below also have horisontal scroll on, but shows the correct width.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG9YQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b797d8cd0e82c5ffa0cc4376a8b2e1574d242c8d/image.png)

**Comment by fernandolucchesi** [comment]
seems related to #1928

**Comment by padms** [comment]
@meols This is fixed and can be tested on this [page](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/padms)

**Comment by padms** [comment]
@meols  The issue with upcoming events was that " select events from tags" was neither disabled nor enabled. When set to disabled, the upcoming events are shown. 

 "select events from tags"  is selected by default now. So, this isn't an issue anymore.
