### ISSUE TITLE
Image on thumbnail of magazine cards & quote has very low quality

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1941]
Investigate if proper resolution and sizes are being used. images are being displayed with bad quality 
<img width="447" alt="image" src="https://github.com/equinor/energyvision/assets/23337266/ed412bb5-c8fc-4b9a-9b26-fc99bd0f8eaf">

<img width="262" alt="image" src="https://github.com/equinor/energyvision/assets/23337266/78700f42-bbe1-4476-aa97-81a134253d36">

**Comment by padms** [comment]
@fernandolucchesi @millianapia I used dpr here to improve the image quality.
