### ISSUE TITLE
Update from twitter to x logo

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#1959]

**Comment by millianapia** [comment]
@meols hi! can you verify that the twitter logo is changed from the bird to the x?

**Comment by meols** [comment]
Thanks @millianapia - looks good (and is approved) :smile:

**Comment by NickHaggerty1** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXFrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--79bc27e7fd4b68c762c67c2abe443544a71face3/Twitter%20X%20Icon-equinor.svg)

**Comment by NickHaggerty1** [comment]
@millianapia Hey. Sorry, is it ok to replace the logo with the file above? I noticed the X was in black and a little thin when the icon goes so small, so I have increased the thickness and changed the colour to the footer background.

**Comment by millianapia** [comment]
hi @NickHaggerty1, i updated with the new logo you provided, can you verify :)

**Comment by NickHaggerty1** [comment]
Tusen takk @millianapia Approved
