### ISSUE TITLE
Image crop doesn't work on windows

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1969]

**Comment by meols** [comment]
@fernandolucchesi - this still doesn't work. I have cleared browser history, refreshed the page several times and also signed out a few times. Tested in both Edge and Chrome (on this page: https://studiov3-global-development-equinor-web-sites-dev.c2.radix.equinor.com/global-development/desk/topicContent;d0b57050-7f22-434d-97b3-ceb8324719e1)

**Comment by meols** [comment]
@fernandolucchesi - any updates from Sanity on this?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - there's nothing new to test here? It still doesn't work. Should it be moved away from Acceptance?

latest update from 5 days ago was "we filed a bug report and will keep you updated on the progression". lets move it to dependent on others while we wait for sanity's feedback.

**Comment by meols** [comment]
@fernandolucchesi - can you please check with Sanity if there is a solution for this coming up soon. We've had this issue for more than 5 weeks now.

**Comment by fernandolucchesi** [comment]
Hi! can you test on the studio dev if it works now @meols?

**Comment by meols** [comment]
YES! I works :clap: :smile:
What was the fix for it?
