### ISSUE TITLE
Local news not indexed

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#1970]
Localnews document schema does not have "excludeFromSearch" field. 

When a local news is published, the webhook filters checks if excludeFromSearch field is defined, since it was never defined the webhook never triggered the indexers.

**Comment by padms** [comment]
@meols  Exclude from search option is added to local news articles. You can test indexing local news article, by enabling and disabling this option.

**Comment by meols** [comment]
@padms - I am not able to find a local news article I published 15 November, either in global search or on the News index page (on dev). I have not activated exclude from search:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk1LQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c80e8e2e408a91419c58cd755016d1aa002febc2/image.png)

**Comment by padms** [comment]
@meols Could you please try now? I modified the webhook, should be working fine now.

**Comment by meols** [comment]
Thanks @padms - now it worked, and is approved :smile:
