### ISSUE TITLE
Create a new satellite site for Sheringham Shoal

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#1994]
We are going to move (most of) the content from this site https://sheringhamshoal.co.uk/ into our system.
At this point we don't know who owns the domain, but will leave that for the stakeholder to clarify for now.
It will be in English only.

**Comment by padms** [comment]
@meols Should this satellite have news?

**Comment by meols** [comment]
@padms - yes, please include news - thanks for reminding me :smile:

**Comment by meols** [comment]
@padms - can you please share the link?

**Comment by padms** [comment]
@meols https://studio-sheringham-equinor-web-sites-preprod.c2.radix.equinor.com/sheringham/desk/topicContent

**Comment by meols** [comment]
Thanks @padms - the site looks good and is approved :smile:
We will add data when we have agreed upon it from the stakeholder, so I assume this site will be deployed at a later stage, but that it now is ready to add content.
