### ISSUE TITLE
Teaser component image is not optmized

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#1997]
<img width="1512" alt="image" src="https://github.com/equinor/energyvision/assets/23337266/176b885c-1704-4d44-9abe-aa8f1d161951">

**Comment by millianapia** [comment]
@meols @NickHaggerty1 the test case is to check that the image for the teaser component looks like before, and that the warning in console from the screenshot is removed

**Comment by meols** [comment]
@millianapia - the teaser image looks good to me, but maybe you could check also @NickHaggerty1? I don't see the warning in console, but struggle to see if I should have made some selections apart from selecting console as there are many other error messages and warnings (?!)

**Comment by NickHaggerty1** [comment]
@millianapia same as Mette, so guess approved
