### ISSUE TITLE
Add new background colours 

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2008]

**Comment by NickHaggerty1** [comment]
Equinor has made some revisions to its branded colour palette so the editorial team those colours reflected on equinor.com. 

Figma board = TOPIC PAGE TEMPLATES

1. All colours need to be added to **all** components that have background colour options
2. New colour one: #FFF5B8. Name: mid yellow
3. New colour two: #F8D1AF. Name: mid orange
4. Replacement new colour: #49709C. TEXTS / CTA need to be white. **Replacing the** SLATE BLUE. Name: mid blue
5. Replacement new colour: #C3E4CE. **Replacing the** moss green. Name: mid green

**Comment by NickHaggerty1** [comment]
<img width="1438" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE1xQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b750804b738f98f7a06b860e7ae0b781878bf073/Screenshot%202023-12-04%20at%2010.01.24.png" alt="Screenshot 2023-12-04 at 10.01.24.png" />

**Comment by padms** [comment]
@NickHaggerty1  The following components have selected background colors : 

1. Promotion : ['White', 'Moss Green', 'Moss Green Light', 'Spruce Wood', 'Mist Blue'] ( slate blue excluded) 
2. Fact box : ['White', 'Moss Green', 'Spruce Wood']
3. Table : ['White', 'Moss Green', 'Moss Green Light', 'Spruce Wood', 'Mist Blue'] ( slate blue excluded)

Should I include new colors to all these components?

**Comment by padms** [comment]
@NickHaggerty1 @meols New colors are ready for test.

**Comment by NickHaggerty1** [comment]
@padms @meols This is excellent and fast work Padmaja. Mette, I have made a new page just to test colours so feel free to add to this. 

One small issue is the new promo card component which isnt approved yet. The blue background option needs a white arrow.

For now colours have been made to all components that had colour, the only question is Mette should we exclude any colour options in certain components?. Have a play and lets discuss when you are back.

**Comment by NickHaggerty1** [comment]
@meols looks like the studio is updated now so can be tested.

**Comment by meols** [comment]
@NickHaggerty1 - looks great, and as discussed I agree that we don't need to exclude any colour options in any components (and rather discuss it later if we experience any issues).
Great work @padms
