### ISSUE TITLE
Text improvements to the teaser component

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2009]
We would like to have a few more options on the text within the teaser component. 

1. Bullet points/Numbers
2. Spacing enhancements so when enter spacing is reduced.<img width="1546" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2tyQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--591063e5f78a8e8cdae9b8eacac984a81c635104/Screenshot%202023-12-04%20at%2014.40.03.png" alt="Screenshot 2023-12-04 at 14.40.03.png" />

**Comment by NickHaggerty1** [comment]
[Uploading... Screenshot 2023-12-04 at 15.00.28.png]

**Comment by millianapia** [comment]
@NickHaggerty1 added more options, could you verify it works as expected

**Comment by NickHaggerty1** [comment]
Hey @millianapia looks good. Approved. 
One issue connected to this component. The spacing between the big text and the link when selecting the BIG text option is different/wrong. Is this something quick to fix on this card or do we need to make a new issue?

**Comment by NickHaggerty1** [comment]
<img width="957" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeGwzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88a53b6c989e7a21fa9fc88a6bf57b7814b1efb0/spacing%20on%20teaser-link.png" alt="spacing on teaser-link.png" />

**Comment by millianapia** [comment]
@NickHaggerty1 it is now fixed

**Comment by NickHaggerty1** [comment]
@millianapia NICE :) thanks for fixing. Card is approved
