### ISSUE TITLE
As editors we would like a new text teaser component to promote Equinors key messaging

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2010]
Figma board: Big text

## Acceptance criteria
1. Based on current teaser component without image
2. Editor can toggle Title left or right displaying text on opposite side (title displays above on Ipad vertical/mobile)
2. Agree on font size for title
3. Editor can bold key words in Title
4. All background colours 
5. Specific background colours could have themed options for editor to select colours:
6. (New) Mid blue background #49709C. White text default. Option to choose yellow theme #FFF5B8 or Mid orange theme #F8D1AF (note link arrow should also be white for this background)
7. (new) Mid orange #F8D1AF . Black text default. Option to choose red theme (energy red)
8. Link should be optional
9. Word limit for text as per teaser
10.  Can this component be hidden for users except "designer" role?

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by NickHaggerty1** [comment]
<img width="355" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEFzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--59b3e04738045e2a9c190862b1c25dc42756a0d3/Screenshot%202023-12-04%20at%2015.16.40.png" alt="Screenshot 2023-12-04 at 15.16.40.png" />

**Comment by padms** [comment]
On hold to discuss the color highlight option.

**Comment by padms** [comment]
https://www.sanity.io/answers/how-to-get-the-currently-logged-in-user-inside-a-sanity-schema

**Comment by NickHaggerty1** [comment]
@padms The new colour set up as you have created for the other components is approved to apply for this component too. Thanks

**Comment by padms** [comment]
@NickHaggerty1 This is ready for review.

**Comment by NickHaggerty1** [comment]
Hi @padms great work. This looks very good and interesting to see some new elements to play with in the theme setup. As there is a new way to do thingsI think we need to be super clear with the explanations for editors:

When user hovers over highlight. Can text say: Highlight text selected from theme below

Can the theme description text say:

Theme (for title)
When you have selected highlight in the title, choose colour combination for the title text/background. If no highlighted is selected colour will be black or white (on blue background) If no theme is selected the default is white background with black text.

**Comment by NickHaggerty1** [comment]
@padms Only other comment, on mobile the title spacing is quite big to the text. Is this something thats easy to adjust? If you look at the screen grab below, the spacing for the Teaser should match the Text component.<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW5lQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dad8d4f8d1bf59dbcb155ad248a26f3a425d581c/Image.jpeg" alt="Image.jpeg" />

**Comment by NickHaggerty1** [comment]
@padms @fernandolucchesi approved
