### ISSUE TITLE
Long text is overflowing on portraitcards

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#2037]
<img width="714" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBME9nQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fea993307eac89b8acfec016bc3230302db0aa93/Screenshot%202024-01-05%20at%2013.47.33.png" alt="Screenshot 2024-01-05 at 13.47.33.png" />

**Comment by millianapia** [comment]
@meols @NickHaggerty1 the test is to check if the long links or words will break and go to the next line instead of overflowing the card

**Comment by meols** [comment]
@millianapia - is the issue fixed? See screenshot <img width="1658" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEFJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--15848abae8ca8575f6a24119296eed41603ebeed/image.png" alt="image.png" />

At the bottom of this page: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/mette-test-1

**Comment by meols** [comment]
Nå ser det bra ut @millianapia :smile:
