### ISSUE TITLE
Create a quote component

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#204]
The quote is a "pull quote" meaning it is duplicated from else in the text for a visual stand out effect. 
It shall be possible to add an author.
For the MVP it will not be possible to add a picture.
The length of the text is not limited (max/min).
The quote can be placed anywhere in the paragraph text of the article, but not split a sentence.
It can be more than one quote text within an article.

**Comment by wenche** [comment]
@BirteThornquist @nicholas-haggerty  I think it's hard to see if this quote is supposed to be a pull quote or a "real" quote aka blockquote?

A pull quote is a duplicated snippet from the text that stands out from the rest of the article as a visual effect. There's no dedicated html element for this, so we'll probably use the `<aside>` element.

A block quote on the other hand is content quoted from an _external_ source and it's common practice to link to the url or at least write the name of the author.

**Comment by BirteThornquist** [comment]
Ok. I guess originally this was a pull quote - but I changed it a bit where I pulled out the name as an author. So I have mixed it....Keep it as a pull quote or use a block quote @nicholas-haggerty ?

**Comment by nicholas-haggerty** [comment]
Not sure its either based on the descriptions. The quote probably would come from the text - so a duplication for visual referrence, but would need to have control over if an editor can add Name/role text underneath and have option to combine with image.
Example here quite far down: https://www.equinor.com/en/magazine/weldar-the-welding-robot.html

**Comment by nilsml** [comment]
Who is actively working on this task?

**Comment by wenche** [comment]
Need to improve the design for this (with or without title/Vice president blablabla). And what about the left side "drop"?

**Comment by SvSven** [comment]
- Align width of quote component to title of article
- Author name & title should be `text-align: right` and positioned on the rightmost side of the article body text

**Comment by wenche** [comment]
This is OK for the MVP.

See #251 for follow up on the quote.
