### ISSUE TITLE
As editors we need a component to display key numbers 

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2048]
## Acceptance criteria
1. Rich text components for title (h2) and Ingress (h3) both elements optional
2. Content has same width as top banner image
3. New text size for big number (figma set to 75px) Option to add small abbreviated text alongside number
4. Optional description text under number.
5. Option to add several rows of numbers
6. Minimum 2 numbers. Justified left to align with title. 
7. 3 per row on desktop. 
8. 2 per row vertical ipad/tablet. 
9. 1 per row mobile default - option to horizontal scroll for mobile.
7. Optional text option below to add disclaimers (small text font size)
8. Optional link / download option 
9. Coloured backgrounds (full screen width) Applying same logic as per other components (eg white text on blue background)

Sketchs in figma: KEY NUMBERS board

**Comment by NickHaggerty1** [comment]
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHl1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--976a8300627708f7b4415c94cc5e8dc568f796e6/Screenshot%202024-01-09%20at%2015.04.23%20%282%29.png" alt="Screenshot 2024-01-09 at 15.04.23 (2).png" />

**Comment by padms** [comment]
@NickHaggerty1 This can be reviewed.

**Comment by padms** [comment]
@NickHaggerty1 This is ready for one more round of review with the horizontal scroll option.

**Comment by NickHaggerty1** [comment]
Hi @padms Thanks for fixing. Looking good. Approved
