### ISSUE TITLE
Duplicate page option missing

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2056]
We no longer have the option to duplicate a page. Can we have it back? :smile:
<img width="710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVRBQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71e3ede6a5744121287c74e61e64814e75f56062/image.png" alt="image.png" />

**Comment by padms** [comment]
This will be done along with i18n plugin upgrade.

**Comment by padms** [comment]
@meols  Duplicate page option is included with the i18n plugin upgrade.

**Comment by meols** [comment]
Thanks Padmaja - this is approved :smile:
