### ISSUE TITLE
Create "More on this topic" component

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#206]

**Comment by wenche** [comment]
@BirteThornquist  We need to discuss the title for the component, should this be editable or not.

This component is also used for links of type PDF, images and links to videos in addition to internal and external links

**Comment by wenche** [comment]
Discussing with Birte.

What about a few, predefined options for the header? E.g.

- More on this topic
- Related content
- ??? :)

**Comment by wenche** [comment]
We need to look into what we do with long links

![Skjermbilde 2021-04-07 kl. 10.25.45.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/0447ca14-cf37-42c8-acd2-78e9c7ecc462)

**Comment by SvSven** [comment]
In discussion between @BirteThornquist @nicholas-haggerty and myself we agreed to keep a text input field for the title with a default value for the time being. We will investigate having a dropdown with predefined options as an alternative.

**Comment by wenche** [comment]
See #250
