### ISSUE TITLE
H3 text option displays as paragraph text.

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2061]
When editor selects "subtitle H3" in the text component the font on the webpage is displayed as paragraph text (and has option to bold)

We need to have a distinction between the font sizes to visually indicate a subtitle.

Im not sure of the font scale set up now in the solution, but in Figma I feel like the defined H3 size (34.6pt for medium desktop) is too large for this purpose. I would suggest the size should be around 30pt for H3 (medium desktop). Happy to have a chat on this when the task is being looked at.

**Comment by NickHaggerty1** [comment]
<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9TQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b0112152408de8420e5d2eb92bd9d076cc0ffb6c/Screenshot%202024-01-17%20at%2011.03.12.png" alt="Screenshot 2024-01-17 at 11.03.12.png" />

**Comment by millianapia** [comment]
the H3 text option should work as requested, please verify @NickHaggerty1
