### ISSUE TITLE
Spacing after indent in bullet list needs adjustments

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2064]
Please adjust the text block so that when using indent within a bullet list, there is no spacing until you change from bullet list to text (bullet list ends), as it is in Word.

See #1632 and #1880

<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVhaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2044bbcbaec26a769d059b72ac71930bfcc16e6f/image.png" alt="image.png" />

From Word:
<img width="983" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZaQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eac38d0aaafc3ae1aa10b60cae12a9a85ad5928c/image.png" alt="image.png" />

**Comment by millianapia** [comment]
Spacing after indent in bullet list is adjusted, please verify @meols

**Comment by meols** [comment]
Great @millianapia - thanks and approved :smile:
