### ISSUE TITLE
Add the text "Search" ("Søk" in Norwegian) to the search icon in the top menu

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2072]
Comprend has suggested that we add the text Search/Søk to the search icon, and we would like to implement that. 
@NickHaggerty1 can you please specify the details?

**Comment by BorghildSelle** [comment]
Also suggest when at this, take a look at making the other actions in the top bar have similar interactive states.
With visible Search text in a ghost button the hover is rounded rectangle;
1. the Localization button links should have rounded ghost button styling

**Comment by BorghildSelle** [comment]
Review if this ControlChild is necessary around the topbar search icon and the comment:
This div is needed because of the grid layout to wrap focus lock panes. We might look into to improve this at some point.

**Comment by BorghildSelle** [comment]
Done in #2148

**Comment by padms** [comment]
@meols This is ready for review.

**Comment by NickHaggerty1** [comment]
@padms great. Approved @meols FYI
