### ISSUE TITLE
Small changes to the 404 page

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2081]
We would like to add a link "to the home page" on the 404 page.
Also seems to be an issue with changing text and image. Preview does not show updates to either image selected or text change. Not sure if this needs to be done by developer?

- edit
Also fix preview for misc pages (404 etcs) 

<img width="1019" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdBQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72b44352d778a94f144dfe7d79231b58c185e1aa/Screenshot%202024-01-26%20at%2009.13.11.png" alt="Screenshot 2024-01-26 at 09.13.11.png" />

**Comment by padms** [comment]
@NickHaggerty1 This is ready for review

**Comment by NickHaggerty1** [comment]
@padms No options to add link
