### ISSUE TITLE
Spacing issues on the event template below the iframe

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2087]
The spacing below the iFrame on the event template looks to big - should be as on topic page with iframe (search for Autumn coference f.ex).
See this page with UNPUBLISHED updates for the quarterly result:

<img width="860" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2tPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1c98af2191a99c1c264085e87fcbb6ac780acc9e/image.png" alt="image.png" />

**Comment by millianapia** [comment]
Awaiting on feedback regarding the spacing on event template from @NickHaggerty1 @meols

**Comment by NickHaggerty1** [comment]
@millianapia @BorghildSelle Hi. Looking a bit more into this, I think we should have a little revision on the design of the event template which I can make as a new card. Tighten up spacing issues and maybe some design improvements to add. However for this issue.... Is it the deprecated iframe component that has some "hidden" padding which is causing the spacing issue above? Is it possible to remove this deprecated iframe element entirely from the event template? Any consequences on doing this?

**Comment by NickHaggerty1** [comment]
@BorghildSelle Not sure this is dependant on us. Can the team confirm on the above questions?

**Comment by BorghildSelle** [comment]
The reason the deprecated field hasn't been removed is that is has not been migrated and cleaned up from sanity.
We will use this issue to clean up the "old" deprecated iframe field, and you, @NickHaggerty1, can create a new issue to revise the event template with new design improvements and structure.

Firstly w need to update the following event from using the deprecated iframe field to the "new way", which is in the content field above in Sanity Studio.
We found the "old way" on these pages:
- [ ] https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/event;40e81149-c23c-4834-847e-9a9ffb927e74
- [ ] https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/event;d532b08e-0ab8-4084-ac81-e2c0cbc4f761
- [ ] https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/event;87a8f340-76c7-4956-9d44-2853fced0609
- [ ] https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/event;20c2e6c5-8edf-4646-8bf5-c71079284ae5
- [ ] https://studio-global-test-equinor-web-sites-test.c2.radix.equinor.com/desk/event;7f18b53e-0a2f-4250-b888-4006533854b9

Can you, @NickHaggerty1  or Mette, @meols,   update these and let us know when that is done?

Then the "old" iframe field should be safe to remove from Sanity.

**Comment by meols** [comment]
Sounds good @BorghildSelle :smile: Can you add the list with which event pages to update?

**Comment by millianapia** [comment]
the fix is moved to #2203
