### ISSUE TITLE
Search in header should not wrap anchor around button semantically

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2088]
A Next link is wrapped around Button component to seemingly accomplish a "button"-look for the link.
But semantically a anchor tag should not contain an button element. Button should be used with onClick event.

This results in an blue outline for the anchor when tabbing to the search, instead of the focus design meant for button( that you get when tabbing one more time into the button element)

Should implement as suggested in eds;

A special note about **nextLink**: The `href` type from this component conflicts with the native href type, therefore it is recommended to use the legacy behavior in this case, or alternatively ts-ignore.
```tsx
import NextLink from 'next/link'
import { Button } from '@equinor/eds-core-react'

<NextLink href="/about" passHref legacyBehavior>
  <Button as="a">About</Button>
</NextLink>

**Comment by BorghildSelle** [comment]
This issue also applies to the portrait cards, should maybe run a search for nextlink wrappers with button look

**Comment by meols** [comment]
Thanks @BorghildSelle - this is approved :smile:
