### ISSUE TITLE
Adjust spacing on news template

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2098]

**Comment by meols** [comment]
The spacing on the news template is different/smaller between the content field when it ends with text and the title field for More on this topic compared with if the content field ends with an image or a fact box.
<img width="1862" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lwQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abd287a77220e753b57d411b861f13c88170d299/image.png" alt="image.png" />

**Comment by millianapia** [comment]
Awaiting on feedback regarding the spacing on news template from @NickHaggerty1 @meols

**Comment by millianapia** [comment]
This will be fixed with #2204
