### ISSUE TITLE
Update to the Careers contact us form

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2105]
1. 
We want to add a category to the **Careers** contact form: https://www.equinor.com/careers/careers-contact-form
Please add the category **Suspected recruitment scam** (English form)/**Mistanke om rekrutteringssvindel** (Norwegian form) as the last option in the drop down list.
In addition please add the tickbox that currently as it is on the form on https://www.equinor.com/careers/career-fairs-and-visits:
<img width="1033" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXcvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--caea54c8979a6ab80c1238fb25464e28557a78eb/image.png" alt="image.png" />
<img width="1037" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTAvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d6d66aac76a49a344f9a6f9d25536a613ecbc34/image.png" alt="image.png" />

When users select this new category, the request should go to the **Service desk PO** assignment group.

**Comment by padms** [comment]
Waiting for ServiceNow teams https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=cfe4cbb98359c218347af830feaad36c

**Comment by BorghildSelle** [comment]
Waiting for ServiceNow to get back on the assignment group,
Birte Garvik

**Comment by meols** [comment]
@BorghildSelle - are you still waiting for input from Birte Garvik? If yes, please remind her, as it was requested to be live 1 May at the latest (without us promising it :wink:)

**Comment by padms** [comment]
@meols We are back on it.. Testing on staging..

**Comment by padms** [comment]
@meols Of course!

**Comment by padms** [comment]
@meols This is ready to test. When recruiment scam is selected from category the request goes to Service Desk PO as shown below <img width="1395" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2wrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee13e66c2c769b98cba15de2735833968fad2b0b/image.png" alt="image.png" />

**Comment by padms** [comment]
@meols Can you take a look at this and let me know? I can confirm with service-now to have a deploy tomorrow.

**Comment by meols** [comment]
Thanks @padms. This is approved. And thanks for being so good at following up on this - much appreciated :thumbsup:
