### ISSUE TITLE
News article - final version

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#213]
## Should contain
1. Tagging
1. Subscription option
1. Remaining components

**Comment by nicholas-haggerty** [comment]
Tagging has been added.

**Comment by nicholas-haggerty** [comment]
Comment from Mette on another issue but flagging on the epic....
adding a comment for the future news template work after testing a news today; editors need to be able to prepare a news article sometimes days before it is published, and to be able to add internal links we have to publish the news article. We need to ensure that we are not showing the "published to be able to add links date" but have the real "published to the world date" as the published date (and not as the modified date).
