### ISSUE TITLE
Review Algolia upgrade with report findings

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2132]
Should quota be increased?

**Comment by padms** [comment]
@meols @BorghildSelle We might run out of quota by 3-4%.

**Comment by meols** [comment]
Thanks @padms - our contract responsible has had a dialogue with Algolia on this.
@BorghildSelle - we should look into how to decrease the Algolia "spend", ref what Fernando showed on the almost linear increase month by month. Please create a separate card for that, if needed.

**Comment by meols** [comment]
@BorghildSelle - have you done a review that you are happy with? Seems like we are back to spending about 2% of the Algolia quota per week (as it was before summer), having spent 57% in today's report. If this trend continues we will end up on ca. 115% (31 weeks left x 2% weekly increase). Did the things we have implemented affect the quota usage (both not indexing news on dev and the searching before user press enter)? 
For news we still have ca 70% empty search - are we happy with that?
<img width="1521" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGZEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--febe2fe8a99476a553dd248f387abe7bf78a9fdb/image.png" alt="image.png" />
<img width="1461" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHJEQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0b757310cf20c7703ea544f02348bd92c3ba6007/image.png" alt="image.png" />
