### ISSUE TITLE
Events template - revise spacing between components

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2141]
As editors we see the Event template follows spacing as per other templates that allow for background colour. As we dont separate modules by colour background we would like to reduce the space/padding between the separate elements.
Not quite sure what the pixel gaps are between elements and text fields but they should be consistent through the layout:
1. Space between H2 titles to next element (links or ingress or text for example) should be consistent with other templates.
2. Space between all modules (eg People and contacts) should be reduced by half - 80 pixels? as suggestion. so all have equal spacing.<img width="1237" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkZ4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--437d41f98da62f9f35ef2cf19a67ab60d594218a/Screenshot%202024-02-20%20at%2011.31.05.png" alt="Screenshot 2024-02-20 at 11.31.05.png" />

**Comment by meols** [comment]
@millianapia - still doesn't look consistent - tested on this page: https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/test/mettes-event-test
Let's discuss in the workshop.

**Comment by meols** [comment]
@millianapia - the colored top banner is now bigger, looks too big to me (unless it is agreed with @NickHaggerty1 ). The ingress at the top looks smaller than the ingress in contacts, header color still looks too black (maybe on another card?), the spacing doesn't look consistent. I have added a green box on screenshots to illustrate the difference in spacing. Please consult Nick/Borghild/Figma for the correct spacing. I'm not all into the details on it.
<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWQ1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9e73bc61b84fab718205d2d59c75f4767686768c/image.png" alt="image.png" />

<img width="913" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWw1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f671c50c430dd0d4accc1376888c8fc488cb69d/image.png" alt="image.png" />

<img width="980" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXA1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd0a0a89990f371e1e2132f43ece00b362ff64b1/image.png" alt="image.png" />

**Comment by millianapia** [comment]
@meols a new round of review is needed :) spacing and sizing regarding the h2 and h3 directly in the content should be discussed in a new issue, this is only for spacing within the event template with the spacing between the components
