### ISSUE TITLE
Based on feedback from our reporting agencies we would like to make some minor menu adjustments

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2148]
1. When users open menu from a specific page, indicate in the menu where they are. EG menu opens with ENERGY section and indicates that user is on WIND PROJECTS.
2. Use vertical 100% green line and hover colour to indicate this (as per sketch)
3. Adjust colour of non clickable menu categories to 100% moss green to create a greater distinction between menu items and non clickable menu catagories.
4. Remove ingress text option. Moving all content to move up in the menu window. (its ok to make the ingress optional rather than required? But if editor leaves blank then menu content must move up)<img width="1237" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDkvQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8b7c75c9e6e6d5025c94e401cdef7ecd4541bece/Screenshot%202024-02-22%20at%2011.27.23.png" alt="Screenshot 2024-02-22 at 11.27.23.png" />

**Comment by NickHaggerty1** [comment]
@BorghildSelle Thanks for chat earlier. Card created based on our conclusions. Just reach out with anything if needed once the issue is in to do. @meols FYI

**Comment by BorghildSelle** [comment]
Doing #2072 as that one relates to the topbar, menu improvement

**Comment by padms** [comment]
@NickHaggerty1 This is ready for review.

**Comment by NickHaggerty1** [comment]
@padms Looks good for all. Approved @meols FYI
