### ISSUE TITLE
As a editor I want an additional component to display in-depth content overlaying a topic page

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#217]
We will no longer continue with the PANEL page option, and resolve those pages using other templates. One additional element to provide more indepth content is an overlay component within the TOPIC template.

## Acceptance criteria
1. Component should overlay  the topic content promotes it, with option to close so user is back to where they activated the overlay
2. Does not require a URL
3. Pages would not show in the menu structure
5. Sticky close button
6. On desktop with would be constrained to a grid (not full width)
7. On mobile, display should be full width.
9. Component should be limited to a few elements:
-Title
- Text block (ingress/body)
- CTA (optional)
-Downloads (optional)

Good overlay example
https://www.apple.com/environment/

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nicholas-haggerty** [comment]
@BirteThornquist Yo. Lets discuss this when you have time

**Comment by nilsml** [comment]
Check with @nicholas-haggerty if this is still relevant

**Comment by nicholas-haggerty** [comment]
@nilsml I think we have moved away from this design option, we can close. Maaay be something needed in the future but not part of project delivery.
