### ISSUE TITLE
Coherent topbar ux styling

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2177]
![image](https://github.com/equinor/energyvision/assets/104756130/35e14a9e-c3ae-466c-aded-44de8fda7f76)

The groups doesn't seem to me "together"
Each has its own height, width, hover and focus styling.

Maybe the languages could be in a select dropdown?

**Comment by BorghildSelle** [comment]
![image](https://github.com/equinor/energyvision/assets/104756130/9716ce95-fbd5-4d11-a864-9ae7351af343)

Maybe something like this for languages?

**Comment by NickHaggerty1** [comment]
Hry @BorghildSelle No I dont want to change this

**Comment by BorghildSelle** [comment]
@NickHaggerty1  No to just changing the language or no to change the hover/focus styling and language?

**Comment by NickHaggerty1** [comment]
@BorghildSelle No to the dropdown for language select. We only have max two languages and on the global site some pages are only one. I see this as an additional click for users and harder to see immediately whats available.

With the change to the search button is fine to align the hover/focus styling across the three options.

**Comment by BorghildSelle** [comment]
@NickHaggerty1  I agree, when there are so few options as you say :)

**Comment by BorghildSelle** [comment]
@NickHaggerty1 Do you want to look at a common hover/focus/active styling for these or should we make a suggestion?

**Comment by NickHaggerty1** [comment]
@BorghildSelle great if you can suggest something. Dont have a strong opinion on this.
