### ISSUE TITLE
Upgrade carusel

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2190]
the items should be in an list, as list items.
the button to scroll left or right should have better labels.
the items should be article with li role button? or li role link?
Liste av article, som egentlig er lenker til andre sider, men høyre og venstre artikkel er knapper som roterer karusellen

**Comment by meols** [comment]
@BorghildSelle - please add acceptance criteria and I'll look into it immediately.

**Comment by BorghildSelle** [comment]
Check if you can navigate in the carousels with the buttons, that it looks ok

**Comment by meols** [comment]
Yes, it looks OK :smile:

**Comment by meols** [comment]
Moving comment to this card:  we see that for event promotion the Add to calendar button isn't showing if you haven't added location - which is optional. It is like this in production/live as well.
 <img width="1405" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDFpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7f18f2e6c687151d15a6a96086eab1f1b8d21f76/image.png" alt="image.png" />

**Comment by BorghildSelle** [comment]
@meols i created new issue for the add to calendar issue, #2453 
and i will remove ingress from the past events as mentioned in the other comment
