### ISSUE TITLE
Remove old iframe component

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#2204]

**Comment by meols** [comment]
@millianapia - (I think) I have removed the old/deprecated iFrames in use on the Event pages.

**Comment by meols** [comment]
@millianapia - not sure if you're waiting for feedback related to removing the old iframe component on the news template on this card as well. If we will need to remove/replace iframes in news articles this is not something we need to prioritize (discussed with Tor as well)

**Comment by millianapia** [comment]
@meols this is only regarding the event page, if it looks good from your end i will move this along
