### ISSUE TITLE
Align eventcardcontent 

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#2208]
<img width="690" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1Q4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--038e5d00dca7eb5f60d89807396a9a93d093d49f/Screenshot%202024-03-20%20at%2013.05.36.png" alt="Screenshot 2024-03-20 at 13.05.36.png" />

**Comment by meols** [comment]
@millianapia - not sure what to test as there is no description/criteria - but assuming you have bottom aligned the horizontal lines, which looks good. But currently in prod we can have three event cards horizontally without activating horizontal scroll, but on dev both two and three cards are now stacked on top of each other.
<img width="1548" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM211QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--feb54e9cda65935806ba2f2d4cee0da1e6895594/image.png" alt="image.png" />

<img width="1164" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMyt1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9c666d51889a9a1e61221cd8ce3051f17b78d458/image.png" alt="image.png" />

<img width="1203" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEt1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66e1e1b4709d120928c3e69c84442515410a4c13/image.png" alt="image.png" />

**Comment by millianapia** [comment]
@meols sorry for not writing up the test case, this was only so the lines were horizontally aligned. Regarding the cards stackinng, i will create a separate issue for this and look into this today

**Comment by meols** [comment]
Thanks @millianapia
