### ISSUE TITLE
Editors cannot find the home page when using internal link function.

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2210]
Particularly applies to 404 page where we are trying to add a hyperlink to the home page for users. But the problem may also exist in general when trying to add internal link back to the home page.

The slug is for the home page / only and this doesnt show in the list of pages. Also tried to find by using the title page but again this doesnt find the page.

**Comment by padms** [comment]
@NickHaggerty1 @meols Found the home page when I search for "home",
<img width="760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUVCQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0edc5b45b3014b8257965a7ce8bec7abf45c0dfb/image.png" alt="image.png" />

**Comment by NickHaggerty1** [comment]
@padms Great Ive published! will close.
