### ISSUE TITLE
Sanity video player play button is now justifying to the left instead of the center of the player

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2216]
Example of issue can be seen here:
https://www.equinor.com/energy/techstars

**Comment by padms** [comment]
@NickHaggerty1 This is fixed and ready to be tested in staging.

**Comment by NickHaggerty1** [comment]
@padms ahh ignore that, Its because I had it under the scroll component (which raises another issue but not contected to the video player!
