### ISSUE TITLE
Renew ssl certificate for equinor.ar

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2217]

**Comment by BorghildSelle** [comment]
Waiting for more information from Radix team, regarding certificate automation.
Dont enable for other domains yet

**Comment by padms** [comment]
Request created for renewing SSL for Load balancer https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=515d79ee975542d448ecb166f053af2b

**Comment by padms** [comment]
Certificate renewed.
