### ISSUE TITLE
Remove GTM cookie

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2224]
Ref. [discussion on Slack](https://equinor.slack.com/archives/C01MU3H6G0Y/p1706527745402989) and comment from SEO agency in the SEO board it seems like the GTM cookie isn't needed and can be removed. Please confirm if you agree - and remove it if yes :smile:

**Comment by millianapia** [comment]
@meols we have been in a meeting with the SEO team, where we concluded to contact cookiebot directly to get to the bottom of this. As the cookie should not be present, and it still appears when we rerun the scan.

**Comment by BorghildSelle** [comment]
Also look into, talk to CookieBot about the injections of html in our source code when using their cookie banner.

#2228

**Comment by padms** [comment]
Submitted a ticket to Cookiebot support.

**Comment by BorghildSelle** [comment]
A process has been started to see if an alternative provider is better.

**Comment by BorghildSelle** [comment]
Closing this since it was discussed in SEO meeting as not an issue, and the alternative has been laid on ice
