### ISSUE TITLE
Visible label and accessible name do not match - søk vs. search - reported in Siteimprove

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2225]
In Norwegian both the visible label and accessible name should be **søk** - and then we can gain 1.16 points :smile:

https://my2.siteimprove.com/Accessibility/550893/NextGen/Issue/1?ruleId=14&pageSegments=&issueKind=1&exceptTags=1,2&conformance=&siteTarget.conformanceLevels=0,1,3

<img width="1630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEErQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--67616586f4f7d1177fd5f436abf3ab71f96963a5/image.png" alt="image.png" />

**Comment by padms** [comment]
@meols This is fixed with video accessibility.

**Comment by meols** [comment]
Thanks @padms - I see that the Aria label says search, so without understanding it all I assume that it's all good :thumbsup:
<img width="579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK09SQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a839afbbd3423cef6010cdaa7b38da48b3d99d0e/image.png" alt="image.png" />
