### ISSUE TITLE
Event template - choosing bullets doesn't give bullets

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2226]
On the event template, choosing bullets looks good in editor but isn't showing on preview or live page:
<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWsrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6bc09bb8726c57736a7201a3bf939415dc74c85/image.png" alt="image.png" />

**Comment by millianapia** [comment]
will be fixed by #2203
