### ISSUE TITLE
Look into script and html code regarding CookieBot

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2228]
From the SEO team they have asked us if there are any unnecessary coding in regards to the cookie banner, they highlighted code related to ids starting with CybotCookiebotDialog....
If there are possibilities to Reduce the amount of code?

And if we can impact the rendered html for the cookie banner, for the next phase which is to simplify the banner

**Comment by padms** [comment]
We can try this custom banner here https://support.cookiebot.com/hc/en-us/articles/360003921454-Can-I-build-my-own-fully-customized-cookie-consent-banner

**Comment by padms** [comment]
The dialog shows all the content as shown in the cookie declaration including all the cookies found so there is a lot of code. We can create custom banner using our own css, html and javascript, but the question is should we skip showing the list of cookies inside the banner?

**Comment by BorghildSelle** [comment]
A process is started to look into alternatives to CookieBot and pros/cons

**Comment by meols** [comment]
@padms @BorghildSelle - we have learned that the cookiebot issue is considered temporary, and that cookiebot is working on a solution. We will ask the SEO agency to hold the process of looking into a new tool, and continue with Cookiebot  and hope they will solve the issues. It would be good to avoid starting both a procurement process for a new tool, and an implementation for the website
https://support.cookiebot.com/hc/en-us/articles/360020501579-Google-Core-Web-Vitals-and-Cookiebot-CMP
