### ISSUE TITLE
Design improvements to the Corporate news room

### ISSUE THREAD

**Issue by NickHaggerty1** [equinor/energyvision#2235]
Based on workshop discussion and decisions, we can move ahead with tasks to improve the UX and visual appearance of the newsroom.

Sketch in Figma "Newsportal revised design"

**Comment by NickHaggerty1** [comment]
@BorghildSelle @meols Please advise how to handle this task(s) Create an epic with all elements listed up? Or? Not sure how it makes sense to break down into separate tasks

**Comment by meols** [comment]
@BorghildSelle - looks good :smile:
Filters work, search works, but should I expect to see the actual news article from the news archive (2021) when testing search on dev?
<img width="1454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVZkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--09e186d500659d998124894c9a611c5714e723b6/image.png" alt="image.png" />
<img width="821" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVpkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e3bc13963bee54681d91a43f7b799a403a16dce/image.png" alt="image.png" />
