### ISSUE TITLE
Create DNS redirects from  EU2NSEA.COM, EU2NSEA.EU to equinor.com/energy/eu2nsea

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2257]
https://github.com/equinor/energyvision-internal/pull/90

**Comment by meols** [comment]
@padms - thanks for starting on this. Do we have an estimate for when it will be ready?

**Comment by BorghildSelle** [comment]
Radix team have asked Jon Ole Nome if the domain names can be added. Waiting on his answer
