### ISSUE TITLE
Spacing on H3

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2259]
Is the spacing below H3 on topic page correct? Looks to big below. Do we need to specify per template, or are changes and updates done site wide?
<img width="1114" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBem1YQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1d23d1e5f27dfb2fafda56d8afb0d15c3710f079/image.png" alt="image.png" />

**Comment by BorghildSelle** [comment]
@meols Can you test the spacing for h3 now in staging? Have reduced it to half of the h2 spacing. It was a bug before, as it was the same as h2.
