### ISSUE TITLE
Don't respect header formatting when copying text into a text editor in Sanity if that's not an option to format

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#226]
**Describe the bug**
Can copy'n paste formatted content into e.g. the Ingress rich text editor and the text editor will respect the header level formatting even if you are not allowed to change the text size in the editor. That means the h3 formatting is used by the web as well.

**To Reproduce**

**Expected behavior**

**Screenshots**

![Skjermbilde 2021-04-07 kl. 14.50.43.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ac43830c-1b09-4d76-8a51-f804a68ee2fa)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wenche** [comment]
Look into how we can make it as easy as possible to copy and paste without formatting, if that's what a publisher want. (Help text, setting in the editor)

**Comment by adneforslund** [comment]
Should be closed for now?
