### ISSUE TITLE
Padding bug

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#2267]
![Screenshot 2024-04-30 at 10 31 28](https://github.com/equinor/energyvision/assets/21845545/ff03a8be-f930-436b-b29b-7dda2a23c3a4)

https://www.equinor.com/magazine/techstars-2023-norsjor

**Comment by BorghildSelle** [comment]
![image](https://github.com/equinor/energyvision/assets/104756130/90b40eb0-642c-422a-a648-0fa822ff57fe)

**Comment by BorghildSelle** [comment]
![image](https://github.com/equinor/energyvision/assets/104756130/49c476cc-1930-44d8-8e1d-06cf0f5f9d63)
