### ISSUE TITLE
add styling for figcaption

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#227]
Image captions in Figma have a specific font size and colour that do not currently fit in with the typescale system in code.

We need to either create a styled component specifically for captions or add support for this styling in the css variables system.

**Comment by nilsml** [comment]
Is needed for what we defined as the initial News article, or should we add this to the scope of News article  version 2? @SvSven

**Comment by SvSven** [comment]
We can just add it to the scope for v2 since we need to wait for the typography scaling and variables.
This isn't a major issue either, so should be fine.

**Comment by wenche** [comment]
We still miss styles for the heroImage
