### ISSUE TITLE
Capital letters on breadcrumbs

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2272]

**Comment by BorghildSelle** [comment]
@meols Can you verify that the custom breadcrumbs work on dev/staging? Then its ready to go to preprod

**Comment by meols** [comment]
@BorghildSelle - looks like the capital letter issue is fixed. We get a capital letter at the start and if we write it. But the other issue we had fixed for breadcrumbs, that we sometimes need to have a hyphen in the breadcrumbs to have correct grammar is not in place now. See earlier discussion on Slack, with discussion and examples and screenshot below: https://equinor.slack.com/archives/C01MU3H6G0Y/p1683826370196819
<img width="1708" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3V0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--69f24c5f3c2278372b08fd7207bf257c5985f9fb/image.png" alt="image.png" />
<img width="1602" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKyt0QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e903079a2dced781de38681c1b23996a81fecbf/image.png" alt="image.png" />

**Comment by BorghildSelle** [comment]
@meols ah, hm, i took back the old one as it was just made underline on hover. But will look into it

**Comment by meols** [comment]
Thanks @BorghildSelle :slightly_smiling_face:

**Comment by BorghildSelle** [comment]
@meols Can you check again now?

**Comment by meols** [comment]
Thanks @BorghildSelle :thumbsup: - looks great! :clap:

**Comment by meols** [comment]
Thanks for the link @BorghildSelle - looks great also on preprod :smile: I even found some editorial errors for breadcrumbs to correct when testing :wink:
