### ISSUE TITLE
Different highlight/outline for page elements regarding accessibility

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2285]
We see that we have different line weights on the dotted line around the element in focus when tabbing through pages. Is there a reason why we have different line weights, and could we have only the thickest one? This is tested with Trude, who is visually impaired, and e.g. around the back/forth arrows, that also have a shadow, the thinnest line isn't visible to her. Please evaluate if we should use the heaviest line weight everywhere.
<img width="1579" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2E4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c23213afd679a123aec2f0175f51108a10e44fc/image.png" alt="image.png" />
<img width="1706" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2k4QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ada90b40cca53a5414b68aa4a79170855e8db2c/image.png" alt="image.png" />
<img width="1560" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK204QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1fc7c5d625a4ea943f82325abd928041b67616bc/image.png" alt="image.png" />

**Comment by BorghildSelle** [comment]
@meols The header is another task to make styling the same,#2177, but we can apply the thickest one when doing it. 
Also there is an ongoing update to the focus styling to get rid of a third party library. And here we can also apply the thickest 
#1094
