### ISSUE TITLE
Assess the board and make necessary adjustments to ensure a smooth process

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#230]
Somewhat connected to #229.
Need to make adjustments to the board after feedback from the team.
Right now it is not working as good as it should.

PS: talk to the team about filters and other snacks that we can use to make the board easier to reason about.

**Comment by SvSven** [comment]
Is this still relevant? Or better asked, is this ever _not_ relevant?

**Comment by nilsml** [comment]
Asking myself the same question. Continous improvements? 🤷‍♂️ Perhaps close for now
