### ISSUE TITLE
Teaser link with long text not wrapping 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2312]
<img width="1894" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2I1QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2dcdaded67f332ebce3fb6293c11947648bc152/image.png" alt="image.png" />

**Comment by BorghildSelle** [comment]
Think this gets fixed in #2254
