### ISSUE TITLE
Mark required fields in form

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2334]
Career contact form and possible all
Should have a line saying "All fields with * is required" and * at the end of each required fields label
Introduce meta text under label for describing country code and formats

Career fair and events form - phone with or without country code?

**Comment by millianapia** [comment]
TODO: 
- Change text directly in sanity when we deploy

**Comment by millianapia** [comment]
when codefreeze is over, i will add * to required fields in sanity 
![Screenshot 2024-07-09 at 13 33 47](https://github.com/equinor/energyvision/assets/21845545/a65ed07d-2879-4d28-8dfc-288bf09f8390)

**Comment by meols** [comment]
Then we will see it in dev/stage first I assume? Should the explanatory text "All fields with* is mandatory" look more different from the form field texts (italic, smaller...)? The text should say "All fields with * are mandatory" (add a space in front of the asterix, and are instead of is)

**Comment by millianapia** [comment]
@meols It is merged now, staging was reset to main. The text has now been rewritten, added another space after *, and made it smaller and in italics 

![Screenshot 2024-07-15 at 13 13 24](https://github.com/user-attachments/assets/b4e98a64-0a56-4281-9b7b-bdde057be71e)
