### ISSUE TITLE
Update to the Careers contact us form

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2338]
We have been asked by the stakeholder to implement a change to the form as described by @padms below:
As of now, any request on career form except the 'Recruitment scam' category goes to 'NOR-Recruitment-All queries' what ever the candidate type might be.

The new requirements are:
- All requests on category 'Recruitment scam' irrespective of candidate type selected will go to 'Recruitment scam CI'
- All requests on categories except 'Recruitment scam' will go to 'Emerging Talent - Recruitment - All queries' if the candidate type is one of Greduates, Interns and Apprentices.
- If above two does not match, it will go to 'NOR-Recruitment-All queries'

**Comment by padms** [comment]
@meols This is ready to test.

**Comment by meols** [comment]
Thanks Padmaja - I have asked the stakeholders to test and will get back to you with their comments.

**Comment by meols** [comment]
Thanks again Padmaja - this is now tested and approved by the stakeholder (and therefor also of course approved by me) :smile:
