### ISSUE TITLE
Activate forms for the Brazil site

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2343]
Can you please activate forms for the Brazil site.
They only need the Career fair form (but I guess all are activated?), and have confirmed that it doesn't need any changes - only Portuguese translations (that they will do themselves) - and that it should be received by the same assignment group as the Career fair form on the global site.

**Comment by padms** [comment]
@meols We will not be able to test this in staging environment. But I have enabled "Career contact form " alone  for the Brazilian site.

**Comment by meols** [comment]
Sound very good Padmaja. I'll test it when it's in the live Brazil site before informing the stakeholder.

**Comment by padms** [comment]
@meols This is in prod now.
