### ISSUE TITLE
Improve layout for news article

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#235]
Implement a concept of fluid design/grid for the news article template across screen sizes

**Comment by wenche** [comment]
We need to find a clever way to do this for the serializers. My initial idea was ofc to just use some styled component woo aka parent selector, but that didn't work server side. Seems like the serializers run before that's initialized... @TODO: Look more into this to avoid duplication of serializers.

**Comment by wenche** [comment]
![Skjermbilde 2021-04-15 kl. 14.23.41.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/3a29e0b2-f769-4473-bcf0-54c9dfab2dcd)

Needs alignments: who owns the margins, the component or the container

**Comment by SvSven** [comment]
My vote goes to the container implementing the component owning the margins around the component - since we may use the component in multiple places, each with different needs.

**Comment by wenche** [comment]
Let's take a look at the remaining issues on Monday (add the correct spacers)
