### ISSUE TITLE
Improve "More on this topic" for narrow screen sizes

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#236]
Find the best way to present the more on this topic/card listings on narrow screens
** UX **
- Scroll?
- Parallax effects?
- Animation?
- Infinite?
- Dot indicators?

** Dev **
- Carousel?
- Horizontal scroll?

Don't forget a11y aspects for this task.

** Inspiration **

NRK
![Skjermbilde 2021-04-08 kl. 10.26.10.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/653f5799-60f7-4b34-a83f-d8ec019da8c1)
Flickity (used that in the past) or other carousel libs
https://flickity.metafizzy.co/
Code it ourself like
```
.scrollcontainer {
  display: inline-flex;
  align-items: stretch;
  padding: 1rem;
  max-width: 100%;
  overflow: auto;
  scroll-snap-type: x mandatory;
}
```

**Comment by vnys** [comment]
Here’s [the NRK component in isolation](https://codepen.io/vnys/pen/zYNMzKL) for closer inspection.

**Comment by fernandolucchesi** [comment]
#664

**Comment by fernandolucchesi** [comment]
I'll close this as duplicate for carousel component #1312
