### ISSUE TITLE
Newslist not aligned 

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#2363]
<img width="1004" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGxUQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f56016258a205ff0d00da27985abb4cd7e3de16f/Screenshot%202024-06-11%20at%2018.06.41.png" alt="Screenshot 2024-06-11 at 18.06.41.png" />

**Comment by meols** [comment]
Please add acceptance criteria.

**Comment by millianapia** [comment]
@meols the newslist component was aligned left, but now it should be centered 
![Screenshot 2024-07-09 at 13 38 03](https://github.com/equinor/energyvision/assets/21845545/93e58681-69ec-46a4-a266-8b5b0e21a570)

**Comment by meols** [comment]
Thanks and approved.
