### ISSUE TITLE
Some iframes need consent for both marketing and statistics. Allow option to set that. 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2376]

**Comment by padms** [comment]
@meols This is ready to test, some iframes may need consent for multiple cookies. This will also fix some cookies set even before consent.

**Comment by meols** [comment]
Thanks Padmaja. Two questions to this - will we then see the red warning and need to confirm or change the selected cookie on existing pages?change the

**Comment by padms** [comment]
@meols You are right missed it for events and news will fix it

**Comment by padms** [comment]
@meols The same update has been done for the news and events templates. Old iframes continue to work on the web page as expected. In studio, it shows error if you edit a news/event/page with iframe, the cookie policy can be reset and published at the time of publishing.

**Comment by meols** [comment]
A few comments:
- For the news template I get the warning even if there is no video in the iFrame. Can that be avoided? It isn't logic to select "something" for iFrames when no iFrame is in use on the page.
- Also, is there a way to make it more visible that there is an iFrame error (when you need to reselect cookie) for the news template? The only place it is visible that there is something wrong is the red dot in the top right corner, and you need to know that you can click there to see the error description (which satellite editors may not be aware of). For iFrames nothing on the page immediately shows "something red".
- Can we edit the error messages for this? For satellite site editors it is not obvious that they should click the red and scary Reset value button, and the error messages probably doesn't make sense to them.
- <img width="1549" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0ExQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9eae83e401abfd3a64764a46a800292ca0160573/image.png" alt="image.png" />

<img width="1574" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzQwQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d820c8ded7e1e26548174923f13468d404b568c9/image.png" alt="image.png" />

**Comment by padms** [comment]
@meols  
I have run a script which resets the cookie policy on old iframes, so the red reset button will be gone. 
Made none as the default value for iframes.
The warning on the fieldset is similar to the issue #2442, could be addressed along with that.

**Comment by meols** [comment]
Looks good @padms :thumbsup: Approved.
