### ISSUE TITLE
Fix latest news list card at 1280 width of the screen. 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2385]
https://equinor.slack.com/files/U024NDF8FLM/F07918WLMD2/image.png

**Comment by meols** [comment]
Please add acceptance criteria.

**Comment by millianapia** [comment]
@meols there was a bug regarding a breakpoint with the latest news component, can you verify that the it does not look like this when you adjust the screen size
![image (16)](https://github.com/user-attachments/assets/ea686020-c62c-4f46-98a6-d0d4e40000f1)

**Comment by meols** [comment]
Thanks Malin - looks good - is approved :smile:
