### ISSUE TITLE
Improvise reference filters

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2386]
Sometimes it is hard to find the internal link that we want to use when using the link selector. 

- Investigate why the required page fails to show up in the list. 
- Try improving link selector by adding a filter by type to narrow down the search results in the filter.

**Comment by padms** [comment]
I digged in to this and found that the title that appears on the page route is not a content in itself but its coming from the topic content title.. hence when searching with the title you will not be able to find the exact match for the routes and less relevant news, localnews or magazine appear... When searching for a route, you could trying searching it with the topic slug field, it should quickly show the exact match.

**Comment by padms** [comment]
I digged in to this and found that the title that appears on the page route is not a content in itself but its coming from the topic content title.. hence when searching with the title you will not be able to find the exact match for the routes and less relevant news, localnews or magazine appear... When searching for a route, you could trying searching it with the topic slug field, it should quickly show the exact match.

**Comment by meols** [comment]
@padms - so there is no fix for this? 
(If so, I guess we can close this card.)

**Comment by padms** [comment]
@meols No solution at the moment, but I have a ticket to sanity. Will bring this back when we get a solution from them. I am closing this for now.
