### ISSUE TITLE
Stop that the Algolia quota usage is rapidly increasing

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2416]
In this week's Algolia report it says that "As of July 9th, you have used 37% of your committed units." In the previous Algolia report emails you can see that from 24 June to 1 July there was a jump from 15% to 27%, and from 1 July to today (9 July) there was a jump from 27% to 37%. Previous weeks had around a 2% increase per week. Understand that it is related to newsroom. This needs to be prioritized.

**Comment by meols** [comment]
Pasting in the number from this week's report as a reminder to prioritize this: "As of August 5th, you have used 46% of your committed units."

**Comment by BorghildSelle** [comment]
@meols @nicholas-haggerty  I have changed global search and news search to not search as you type with delay, but on submit. 
So an algolia request should not be sent until user has written and pressed Enter or clicked on submit button.
This should reduce the number of request a bit and also not send an empty request on page load i think.
