### ISSUE TITLE
Create custom field for tracking lastUpdated time for news and localNews

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2418]
https://equinor.slack.com/archives/C01A4BGNRMJ/p1720690169328049?thread_ts=1720511418.101329&cid=C01A4BGNRMJ

**Comment by padms** [comment]
@meols I have added the custom field for the lastModifiedAt, this works similar to the firstPublishedAt field, which gets updated everytime someone publishes a news, localNews, magazine.

**Comment by meols** [comment]
Great Padmaja! There isn't anything I can test for this - or?

**Comment by padms** [comment]
@meols There isn't much to test here except that you will find an extra property called "lastModifiedAt" when you inspect in studio ( similarly how to find the _lang field). While we migrate, we run the script to populate this property based on the _updatedAt property for all the existing news. For the new ones it will be set everytime you publish

**Comment by meols** [comment]
Sounds good, Padmaja :thumbsup:
