### ISSUE TITLE
Topic and event page promotion giving different widths on the same page

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2420]
On prod on the [Our locations page](https://www.equinor.com/where-we-are) and on dev on the [events page](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news-and-media/events) we see different widths on the promotions. 
<img width="1386" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2JjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9677299579182e406fbfa6147dfceecfbd88c41a/image.png" alt="image.png" />
<img width="1216" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2ZjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6e5f5318506625e2199a93385941445d9a6b9cc/image.png" alt="image.png" />
<img width="1190" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2pjQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aec56251033c36f888cc6be2e79b355e88f54239/image.png" alt="image.png" />

**Comment by millianapia** [comment]
@meols  fixed the events not toggling to a singlepromotion, but i still can not recreate the topic promotions that you found in prod at /where-we-are. Will take a look tomorrow as well

**Comment by meols** [comment]
@millianapia - should the widths be different with or without coloured background?
(lagt inn langt nede på denne siden. https://studiov3-global-development-equinor-web-sites-dev.c2.radix.equinor.com/global-development/desk/topicContent;d0b57050-7f22-434d-97b3-ceb8324719e1)
<img width="1532" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek5qQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6712ff1e0b7699cf25297dc2b360f0a004a4fb94/image.png" alt="image.png" />

**Comment by millianapia** [comment]
at this moment, this is not a bug, as the width changes with the content. Other than that, you can test if the text inverts color for title
