### ISSUE TITLE
Bug: Single link with link style option showing don't have the full width underline

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2431]
When choosing link style on a single link in a text block component the underline isn't full width/like in a link list
<img width="1265" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMDhnQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e6a12a32e382cf7aa63acb776acb335e6ad96d0/image.png" alt="image.png" />

**Comment by millianapia** [comment]
closing this after discussion from last sprint status meeting.
