### ISSUE TITLE
Issue with font size on grid theme title

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2432]
The Grid THEME title option doesn't appear large when you set it.
Tested on this page:
https://web-equinor-web-sites-prod.c2.radix.equinor.com/api/preview?type=page&locale=en&id=drafts.1d99a1c1-b3e1-4327-82df-67bc93e24e4e&secret=CMdXeGRwn2JUuwEYVhBb

**Comment by meols** [comment]
@BorghildSelle - is it possible to fast track this for the next deploy (today?). This is a bug and already in use on pages.

**Comment by NickHaggerty1** [comment]
In production:
When selecting THEME title in the Text block. The title does not display large. And for some reason sometimes doesnt show at all?
When using title without theme selected, the title does display large and works with other background colours. But not red.
