### ISSUE TITLE
Upgrade newsroom 

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2433]

**Comment by NickHaggerty1** [comment]
@BorghildSelle @meols The latest version is looking great. No major comments. 
One small thing on the filters, we talked about a CLEAR ALL option if a user has gone crazy with the filter options. 
Otherwise good from the design side.

**Comment by NickHaggerty1** [comment]
[Uploading... 35a7f87d47454941b3706b9c59545e8e.jpg]

**Comment by NickHaggerty1** [comment]
<img width="1200" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenVCQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05b0139e3093d2d288eb13ea520a361f8c7378d7/35a7f87d47454941b3706b9c59545e8e.jpg" alt="35a7f87d47454941b3706b9c59545e8e.jpg" />

**Comment by BorghildSelle** [comment]
@NickHaggerty1  Will do!

**Comment by BorghildSelle** [comment]
@meols @NickHaggerty1 The newsroom is updated now and can be tested.
Criterias:

- [ ] Possible to filter news on different tags
- [ ] Can remove filters and clear all
- [ ] Can quick search on keyword
- [ ] Looks good in mobile and desktop
- [ ] Can tab through newsroom with access to all interactive elements
- [ ] all news have thumbnail images

**Comment by NickHaggerty1** [comment]
@BorghildSelle @meols Hey, tested on the above and looks good to me. Little repetitive with the images when filtering to older news items but dont think we need to worry about this too much.

**Comment by meols** [comment]
@BorghildSelle - looks good with regards to the test cases listed - but I don't see the image update on the top news. Even tried to republish it again today. Also I don't see the two latest articles I published today, neither on the new/English newsroom or the old/Norwegian news room. Only one of the articles is visible in the three articles at the bottom of each article. Also I created a new tag (Test) and used it as a topic tag, but it isn't added to the topic filters.
(Not sure how/if custom date and tags plays a part in this)
<img width="1688" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--05b9961f83a2e5f27f8abb781a51137d308de43c/image.png" alt="image.png" />

<img width="1586" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNS9DQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e6b31bc69ee0d9f616746b8b271122b6dbb808b/image.png" alt="image.png" />

**Comment by meols** [comment]
I get the more or less the same look when filtering on Ireland as a topic. Is it relevant that both have "No relevant content..." for Country - which probably can happen in "real life use" as well.
<img width="1419" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1BPQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--889f321d829a2f0d782439f9ac26c5edbe2b77ed/image.png" alt="image.png" />

**Comment by meols** [comment]
Assuming we will have the new newsroom in Norwegian as well, even if it isn't "activated" on dev/stage?

**Comment by BorghildSelle** [comment]
@meols I will look into these :)

**Comment by padms** [comment]
<img width="406" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGRkQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7738a4af5219c32fdfea11a225b963f14f014cf/image.png" alt="image.png" />
Only the above archived news links (only in en) work in dev, all others give 404.
