### ISSUE TITLE
As an editor I want the option to wrap my text around images

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#244]
## Acceptance criteria
1. Possible to wrap text around images in the rich text editor
1. An option to choose 50% or 100% image width
a. An option to choose left or right alignment if 50%

## Related issues
#224

## In order to ensure good quality we should
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform user testing

**Comment by wenche** [comment]
We're experimenting with custom fields in Sanity for the image positioning.
![Skjermbilde 2021-04-14 kl. 15.45.24.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b40de4e2-e0e2-4d0b-820c-511e974cef42)
Started out with the Radio component from sanity-ui, but with the design without visible radio inputs that made it hard for focus and checked states as sanity-ui wraps the radio in a div and we don't have parent selectors in CSS. I'm not quite sure what we miss by just using a plain input type radio, but let's test it and see.

**Comment by wenche** [comment]
For the custom component, I just added some styles by using CSS modules as this is the way Sanity do it in examples. We should probably look into how we could style custom stuffs and benefit from Sanity's CSS variables ++

**Comment by SvSven** [comment]
Seems to work fine from what I can see.
It may cause some chaos on some screen sizes in articles where this is used a lot - but we should probably trust that the publishers know what they are doing and/or test it properly? (famous last words)

**Comment by BirteThornquist** [comment]
Looking good to me.
