### ISSUE TITLE
Promote single upcoming event does not always work 

### ISSUE THREAD

**Issue by millianapia** [equinor/energyvision#2440]

**Comment by millianapia** [comment]
this is fixed locally, will create pr and merge when #2402 is merged to main

**Comment by millianapia** [comment]
testcase: check if promoting single upcoming event works @meols

**Comment by meols** [comment]
@millianapia - is it supposed to look different with or without promote single page toggled on (bottom of dev web homepage)
<img width="1179" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTVpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b95f9460a9fa919680b7585c84ba8760b67d6d2/image.png" alt="image.png" />

**Comment by millianapia** [comment]
making it so it should not be possible to choose 1 in the amount of future events, minimum 2 @meols, so this should be ok
