### ISSUE TITLE
Connect email newsletter subscription from to StoneShot Api

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2441]
Test newsletter subscription with StoneShot by connecting our subscription form to their api.
Padmaja has gotten access to their test account

**Comment by meols** [comment]
@BorghildSelle - great if you could check with Matthew if we (in theory) could also have a subscription solution for local news and satellite site news in addition to those we currently have.

**Comment by BorghildSelle** [comment]
Check if firstname/lastname is required for contact

**Comment by BorghildSelle** [comment]
@meols Putting this on hold until we find out if Stoneshot can meet our requirement of triggering newsletter distribution

**Comment by BorghildSelle** [comment]
Closing this as we are not going to use vendor
