### ISSUE TITLE
When publishing without hero, add warning to add seo image when using campain

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2443]
When creating/editing a topic page and setting the isCampaign to true, the editors might not add a heroimage in the header fieldset as they might use the content component campain banner instead.
In this case, a warning should appear to tell editors to add a Open Graph Image under SEO& Metadata fieldset in the top.
"Please add an image to Open Graph Image when not using an header image"

**Comment by millianapia** [comment]
closing this until it is needed again. Editors should have this in the task list to consider when toggling campaign mode
