### ISSUE TITLE
Error message shows duplicate text

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2463]
The error message is showing the same text twice:
<img width="411" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGhuQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--117d69b13ca9251cb06457155869570def88f977/image.png" alt="image.png" />

**Comment by millianapia** [comment]
have investigated this, it is a bug from sanity, nothing we can do @meols

**Comment by meols** [comment]
@millianapia - have you brought it up with Sanity as a reminder to fix it, do we know if there is a planned fix for it?

**Comment by millianapia** [comment]
yes, they did not know it was a bug, but it is now reported. No known timeline regarding when it will be fixed. @meols

**Comment by meols** [comment]
Great! Thanks @millianapia
