### ISSUE TITLE
Issue in siteimprove: Scrollable element is not keyboard accessible

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2478]
Please see this report in Siteimprove, where we can gain 1,5 points for fixing the issue:
https://my2.siteimprove.com/Accessibility/550893/NextGen/Issue/1?conformance=&pageSegments=&ruleName=sia-r84&ruleId=84&issueKind=1&exceptTags=1,2&siteTarget.conformanceLevels=0,1,3

**Comment by BorghildSelle** [comment]
Search for elements with overflow and set tabindex 0 on them

**Comment by meols** [comment]
@BorghildSelle - anything to test for this?

**Comment by BorghildSelle** [comment]
@meols No, more techincal and have verified in staging :)
