### ISSUE TITLE
As an editor I want different background colors for the top of the news article to vary the expression

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#249]
## Acceptance criteria
1. Could change background colors blue | white, blue is default

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nilsml** [comment]
Needs to be discussed with designer. Why do we need this? How should it work?

**Comment by wenche** [comment]
Update: Nick and Birte no longer want the option to change color for the top. They want the blue color on every news article if it's not too hard to create an inverted version of the top bar. Hopefully we can solve that when we make the top bar.
