### ISSUE TITLE
New image carousel component - title should not be required

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2492]
Can we change the mandatory/required (red warning) title of the component to Recommend (yellow warning)

**Comment by BorghildSelle** [comment]
@padms @meols @nicholas-haggerty  From W3: "Every carousel should be enclosed in a labeled region, to allow users to find the carousel easily."
So could we hide the title if the issue is maybe more that a visible title is not wanted?

**Comment by NickHaggerty1** [comment]
@BorghildSelle Option for editors to hide the title for users would be great. Only issue/consideration might then be spacing?

**Comment by BorghildSelle** [comment]
@NickHaggerty1 @meols Image carousel already have option to hide title, and is demonstrated on the test/bonanza page.

**Comment by NickHaggerty1** [comment]
Hey. The image carousel doesnt seem to? The title area is set up differently
