### ISSUE TITLE
Issue in siteimprove - low text to code ratio

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2493]
We see in this report in siteimprove https://my2.siteimprove.com/SEOv2/550893/Recommendations/CodeTextRatio that we have 845 pages and 780  (92.31%) of them have this issue. It also says that "Having a low text-to-code ratio also impacts the page speed", and we have issues both with [mobile speed](https://my2.siteimprove.com/SEOv2/550893/Recommendations/MobileSpeed) (68%) and [desktop speed](https://my2.siteimprove.com/SEOv2/550893/Recommendations/DesktopSpeed) (40%).
We can gain 5.70 points for these two issues - is there anything we can do to improve the score?

<img width="1565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMitOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9997e90bd670d81afe18955986e5380a8fdd1c55/image.png" alt="image.png" />

Also we would like to understand what is perceived as content (text) on a page. Is e.g. accordions perceived as code? Is it only text block components that are perceived as text? Will a CTA list in a text component add a lot of code and impact the text to code ratio?
We understand that this page, which basically is a pdf archive, is perceived as having a lot of code (0.1% text): https://www.equinor.com/investors/annual-reports-archive
but we don't understand why this page https://www.equinor.com/no/energi/flytende-havvind has only 4.09% text.
Also we see that 130 /news articles and 48 /nyheter articles are listed as having issues. Are there any isues with the news template that should be looked into?

**Comment by padms** [comment]
Could also be because we are using tailwind class names..

**Comment by BorghildSelle** [comment]
@meols @padms According to my research this low text-to-code ratio is not something to consider, many forums call the ratio made up by seo tool manufacturers.

The one thing we have been trying to do and are going to improve is to reduce the number of DOM nodes as Google can give an warning about too large DOM tree.

**Comment by BorghildSelle** [comment]
Closing this after talk in SEO meeting that this is not a relevant issue.
