### ISSUE TITLE
As a user I want "related to" topics to be only one column wide.

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#250]
Updated in Figma.

## Acceptance criteria
1. "Related to" should only be one column wide

## In order to ensure good quality we should
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Create automated acceptance test/smoke test
- [ ] Perform user testing

## Screenshots
![image.png](https://images.zenhubusercontent.com/5f899bfbf74e6d6928f0f80f/bcd79eb2-1316-47d7-a561-3d2436b52708)

**Comment by SvSven** [comment]
Looks good to me 👍
