### ISSUE TITLE
Default 16:9 aspect ratio in image component is no longer working

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2501]
Check the bottom of this page:
https://equinor.sanity.studio/global/desk/topicContent;a3180c05-7e7b-4c6d-807f-76bea24ba44b
16:9 (default) and selected Original aspect ratio gives the same result.
https://equinor.sanity.studio/global/desk/topicContent;a3180c05-7e7b-4c6d-807f-76bea24ba44b
(We've had #1752 for this earlier)

**Comment by BorghildSelle** [comment]
@meols Can you take another look now?

**Comment by meols** [comment]
Thanks @BorghildSelle - looks good, and approved :smile:
