### ISSUE TITLE
Put required * for label into form

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2505]
The * in label for required field should not be in default value for sanity as this can be overwritten and ignored.
Should be added after in the form component

**Comment by BorghildSelle** [comment]
Keep firstname or drop?

**Comment by BorghildSelle** [comment]
@meols  
Acceptance criteria is that:
-  the form still works, hehe
- shows the All fields are required text at the top
- shows the * for required fields
- gives error if you try to submit without filling out required fields
- gives error if you have filled all fields but not completed the human robot check
- gives good information with the new meta text below the label of fields (for instance in the test/career-contact form with country/city)

**Comment by meols** [comment]
@BorghildSelle - some comments, without having tested all forms
- we would prefer to have the * and text below the form as described in [#2334](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/gh/equinor/energyvision/2334) - and also where can we edit the text (we have just received a request for some edits)
- Couldn't the added meta texts be "leading text/ledetekst" as we have done it for the existing fields. Looks strange with some texts within and some outside of the fields (and I prefer within)
- Where do we edit the Tick the box if you would like to send....

**Comment by meols** [comment]
Thanks @BorghildSelle 
- Okay with moving the text above the form - could it be in small text?
- We are fine with following standards/recommendations, but shouldn't all input text fields be handled the same way?
- For the Supporting documents checkbox, is there a reason why the text snippet for the Careers contact form is located within the Career fair form/folder? Shouldn't it be in the Careers contact folder? We have tried to update text for the Careers contact form tick box (and added/removed a dot and published several times), but it still shows the same text as for the Career fair, which is wrong.
- <img width="1425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1p1Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--36ce42c55f3dc391941e49ac4c8c7aaae0ab374c/image.png" alt="image.png" />
- Thanks for explaining the minor Captcha change, which is fine of course

**Comment by BorghildSelle** [comment]
@meols 
Have made the text small now,
Also there was textsnippet that was in wrong group.
For have moved careers_contact_form_supporting_documents to group careerContactForm now.
In the forms they were both using the career fair textsnippet, and should now use the correct one.

On its way to staging
