### ISSUE TITLE
As an editor I want quotes that stand out

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#251]
## Acceptance criteria
1. If quote/text less than a certain amount of characters (50), use larger font
1. If quote/text is less than a certain amount of characters (160), use bold font

## Screenshots (illustration)
![image.png](https://images.zenhubusercontent.com/5f899bfbf74e6d6928f0f80f/b6a6b000-fa91-44a7-9a1c-d01c43a4f89b)

**Comment by wenche** [comment]
![Skjermbilde 2021-04-15 kl. 11.37.49.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c703cd49-502e-4644-a578-3d164163e9d3)

Looks good as far as I can see. We'll need to do the final adjustments for the quote when the article layout is finished. I think that the image is too big @SvSven  @BirteThornquist ?

**Comment by SvSven** [comment]
The image is currently a bit too big yes, but there is no point in trying to resize it before we have the news article layout finished since it will depend on that.

**Comment by wenche** [comment]
Lot's of good work, but will rewrite it slightly to better conform to the compound component pattern :)

**Comment by BirteThornquist** [comment]
Added an example of using quote mark as a graphical element [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=1131%3A49050). What do you think?

**Comment by wenche** [comment]
I've done a couple of things on this issue:

- [Added more examples in the Storybook](https://envis-storybook.azureedge.net/?path=/docs/components-quote--default)
- Refactored the code for better use of compound component pattern
- Added missing `alt` text in Sanity studio
- Added the quote symbol

Perhaps you could taken another round on this @SvSven ?

**Comment by SvSven** [comment]
@BirteThornquist how should the author name and title be positioned on mobile if no image is added to the quote?
Should it be like below, or does the author align to the left?

![image](https://user-images.githubusercontent.com/7661362/115227386-b0a3b700-a110-11eb-8386-0ae994ba8514.png)

![image](https://user-images.githubusercontent.com/7661362/115227418-bac5b580-a110-11eb-903a-fb8d36ff577c.png)

**Comment by BirteThornquist** [comment]
The name should be left aligned positioned and under the quote text for no image quotes 
![Skjermbilde 2021-04-19 kl  13 29 19](https://user-images.githubusercontent.com/74531659/115229413-4fc9ae00-a113-11eb-8346-1a5d1e39f4f4.png)

**Comment by SvSven** [comment]
The author and title should now display below the quote, aligned to the left, on mobile when there is no image present.
If that was the only issue then we can move this to done?

**Comment by petterwildhagen** [comment]
Text sizes are OK, but the pictures added to the quotes are changed.
![image.png](https://images.zenhubusercontent.com/60376a60b424c72d28d1572f/66bea73e-776e-4f67-bd01-4206099b811b)

**Comment by petterwildhagen** [comment]
@SvSven (and @BirteThornquist) for quote with no image the author and title are aligned to the right
![image.png](https://images.zenhubusercontent.com/60376a60b424c72d28d1572f/a5c43c62-e447-4c0d-8851-0e891fd5ee2a)

**Comment by SvSven** [comment]
From what I understood the author should be aligned on the left (and below the quote text) only on mobile if no image is present, and stay on the right on larger screens - but maybe I was wrong?

**Comment by wenche** [comment]
The image didn't have sizes attribute and loaded far too large images as a result. Will fix.

**Comment by BirteThornquist** [comment]
The text color for the quote should be the same as elsewhere #3D3D3D. I have not made a separate text color style but used the EDS token. I will crate text color styles.

**Comment by wenche** [comment]
Good catch @BirteThornquist ! Fixed it (locally at least)

![Skjermbilde 2021-04-30 kl. 10.07.49.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f52cf80b-39d6-4ec8-87e0-8dbaec34e8c9)
