### ISSUE TITLE
News template: if adding custom date when preparing an unpublished news article, the "status" shown is Published when it should be unpublished

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2524]
Showing published "status" when the page is not yet published is confusing for editors and could potentially lead to someone publishing a confidential article because of a text update when it is still on hold.
<img width="705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKy9YQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f92ec2534fb58f680363a4516463ed932360565c/image.png" alt="image.png" />

**Comment by meols** [comment]
I also see the same on dev
<img width="1302" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0RYQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4dae6287533db7db53ed264bd5dd27a8d1f50ae1/image.png" alt="image.png" />

**Comment by meols** [comment]
@millianapia - I still see some issues with news and dates.
- If I add a custom date for tomorrow by mistake, the text below title says Published date: Not published, while the mouseover says that it is published (1), and it is visible on the /news page with a published date tomorrow (26 Sept)
- If I test publishing a different unpublished news, the publishing is "hanging" while the text change to Published date: 25 Sept 2024 (2). If I then assume it is published since the text changed to publish, and then refresh to stop the "hanging" after a few minutes, it turns out that it isn't published after all - even if it now has a published date (see video)
So we have issues with news hanging when publishing (have seen it several times) and wonder if it shouldn't be possible to publish a page with a date in the future - unless it is set up with scheduling?

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXI5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--55deb0639b20e39e39a1ea4199f744bea4031a40/2024-09-25_10-05-34.mp4)

<img width="1372" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVg5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9d513f8aff30b495b8ded4b69f7cf7db7f70de80/image.png" alt="image.png" />
<img width="1643" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWI5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eea0fe78f09b0ba4929dce97b517c578006113fe/image.png" alt="image.png" />

**Comment by meols** [comment]
Adding a video from today as well

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ece6b84c313826571a4b05a43706bb6e8ccaf951/2024-09-26_13-29-24.mp4)

**Comment by millianapia** [comment]
adjustments has been made, so the time is ignored and only the date is compared @meols

**Comment by meols** [comment]
I just noticed that if i don't add a custom date I get a validation error
<img width="1571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtFQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1ab9372d4371697437b22c80fd7b4e575bae4696/image.png" alt="image.png" />

**Comment by meols** [comment]
@millianapia - today I also remembered that local new are also news :wink: and tested that - and there are some issues with local news and date also.
It says **Published date: Ikke oppgitt** (in Norwegian) for published pages. I think it is when custom date isn't used.
<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTRJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a4f75bf4275525720f1a3454fc5bc867cb3690d1/image.png" alt="image.png" />

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXdJQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e2b370ab38064863a8ee23bcdf0ef783a563edd0/2024-09-27_09-17-22.mp4)
