### ISSUE TITLE
Issues with anchor links

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2533]
We see that not all anchor links are working. E.g. on the UK page (https://www.equinor.com/where-we-are/united-kingdom) some of the anchor links at the top works and some don't, for some of them "back" takes you to the top an some not. On the impact assessment page (https://www.equinor.com/sustainability/impact-assessments) we see the same, and e.g. #krafla was added with the previous solution for anchors within components, but doesn't work - and also it it suggested to remove the anchor from within the component.
Please look into this, and also confirm how "old" anchors within components are handled. Do we need to add new anchor link components for them? Is it an issue if the pages have anchors from both old (within components) and new (anchor link component) ways of handling anchors.?

<img width="1301" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3J5Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc60efc7f9fdbad258ff9a23bde553f494228825/image.png" alt="image.png" />

**Comment by BorghildSelle** [comment]
Should find the old deprecated anchorlinks in no/en and replace them with anchorlink component in dev and prod.
Then lastly remove the field from schema

**Comment by meols** [comment]
@BorghildSelle - please note that also our Privacy Policy page https://www.equinor.com/about-us/privacy-policy isn't working well when anchor links now aren't working (the only one working is 8., which has been created with an anchor link component)

**Comment by padms** [comment]
@meols Anchor links were not working for text block component with image background. This is fixed now. 
Also, I created a migration script to replace the deprecated anchors with the anchor link component.

**Comment by meols** [comment]
@padms - not sure how to test this, but I trust your solution and approve :smile:
