### ISSUE TITLE
Migrate to Swift banner - Cookiebot

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#2563]

**Comment by padms** [comment]
@meols The "powered by Cookiebot" logo is hidden from the dialog now.

**Comment by meols** [comment]
@padms - great that the logo is hidden. Can you please make the change in the cookie banners to not have preferences, statistics or marketing pre-ticked from **1 January**, we will not wait for confirmation from legal for this.

**Comment by padms** [comment]
@meols It must be done manually from cookiebot console .. on Jan 1

**Comment by meols** [comment]
@padms - OK :smile: If you're not working 1 Jan, please do the cookie banner update 31. Dec (or 30 Dec if you're off 31.)
