### ISSUE TITLE
Investigate publish action in Sanity

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2587]
Given the recent issues when editors have published norwegian news and the publish action has hung and when editor has refreshed page, changes was not published.

Investigate if something times out or fails silent that causes the suspense

**Comment by padms** [comment]
@meols Found that the publish action never publishes when new/localNews article is published for the first time. This has been fixed. You can test in staging

**Comment by meols** [comment]
Thanks @padms, publishing worked well - approved :thumbsup:
(I found an issue with language for local news and created [#2638](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/gh/equinor/energyvision/2638) )
