### ISSUE TITLE
As a user I want to see when a news article was last modified so that I can know if the article has been updated

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#259]
## Acceptance criteria
1. [x] news article shows the last modified date alongside the publish date

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/91390977-42d1-4b16-88ae-a4305405df9f)

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by wenche** [comment]
Testing, testing, testing, this is the QA department speaking!

We are sorry to inform you @SvSven  that this did not, repeat DID NOT, pass the QA department with regard to small devices.

![Skjermbilde 2021-04-15 kl. 12.27.42.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/aab161b0-9f54-4ecf-8ff9-ba45f498024b)

We know you can do better than this! ✺◟( ͡° ͜ʖ ͡°)◞✺

**Comment by SvSven** [comment]
Good to see that my test of the QA process was a success! (☞ﾟヮﾟ)☞

**Comment by petterwildhagen** [comment]
I have included 'This is a testing page' into the visual tests. The tests include screen width 375 and 1920.
