### ISSUE TITLE
Change deprecated methods in sanity config

### ISSUE THREAD

**Issue by BorghildSelle** [equinor/energyvision#2607]
`sanity.config.tsx `

```
'deskTool' is deprecated.ts(6385)
desk.d.ts(1682, 4): The declaration was marked as deprecated here.
(alias) deskTool(options: void | StructureToolOptions): PluginOptions
import deskTool
@deprecated — Import structureTool from sanity/structure instead!
```

`export const customTheme = buildLegacyTheme(partialStudioTheme)`

`The signature '(partialLegacyTheme: Partial<LegacyThemeProps>): StudioTheme' of 'buildLegacyTheme' is deprecated.`

**Comment by millianapia** [comment]
we have to use the deprecated theming solution due to our custom button colors [ref](https://equinor.slack.com/archives/C01A4BGNRMJ/p1718698175719169?thread_ts=1718698175.719169&cid=C01A4BGNRMJ)
