### ISSUE TITLE
Evaluate the pattern with helper texts as tooltip for long descriptions

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#264]
Suggestion from Sanity

![Skjermbilde 2021-04-20 kl. 14.11.23.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/9f28054e-8166-43bb-b022-978b0ace1320)

My screenshot: 
![Skjermbilde 2021-04-20 kl. 11.15.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/e08a93ee-ef9a-47ab-91e5-c220351680f7)

**Comment by nilsml** [comment]
This is not the suggested solution Birte says
