### ISSUE TITLE
Move the CSS from the AEM solution to the envis repository

### ISSUE THREAD

**Issue by vnys** [equinor/energyvision#265]
The css for the current version of equinor.com is based on 1rem being equal to 10px, so that needs to be changed so it works with the new css. Since the legacy css is based on scss, we should move the source files and the gulpfile over til envis and publish it as an npm module that can be imported into nextjs for the archived pages.

- [x] Move the scss files and gulpfile to `/legacy/css`
- [x] Create a package.json with a style field that points to the build
- [x] Use `@equinor/energyvision-legacy-css` as the name of the package
- [x] Add `/legacy/css` to the pnpm workspace file
- [x] Import the module in the relevant pages in nextjs
- [ ] Update the Dockerfile and verify that it builds correctly

We don’t need to publish the package to npm at this point as pnpm will take care of the symlinking between dependencies

Related to #243

**Comment by kalyanvaranasi** [comment]
Fixing font sizing issues and looking into how node_module fonts can be loaded to nextjs application

**Comment by kalyanvaranasi** [comment]
Fixed issues with the font-awesome by adding files to public folder of next js application
