### ISSUE TITLE
As an editor I want the hotspot and crop features to be disabled for images that don't use them in the frontend to avoid confusion

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#267]

**Comment by wenche** [comment]
I might even make sense to have only the crop features and not the hotspot in some situations? Does Sanity supports this?

**Comment by wenche** [comment]
Update: No, Sanity does not support to have only the crop features out of the box, but it's logged as a feature request on their end. But if we want this, we should be able to make a workaround for this ourselves according to Simeon.

**Comment by nilsml** [comment]
The problem here is that crop is not already working. Handled by #775
