### ISSUE TITLE
As an editor I want to be able to crop images that don't have aspect ratio so that I don't have to use Photoshop

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#268]
See #256

This is not the easiest thing to achieve while not hurting performance.
## Acceptance criteria
1. The crop features are used
2. The image has reserved space to avoid CLS in the web
3. The image is not stretched
4. The image is not smaller than the available space

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Test for accessibility
- [ ] Perform performance and load test

**Comment by nilsml** [comment]
Related to #775

**Comment by NickHaggerty1** [comment]
Im pretty sure this isnt relevant I suggest closing @meols
