### ISSUE TITLE
Sitemap.xml and Robots.txt are broken

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#2682]
🐛 🗺 🤖 🚨

**Comment by BorghildSelle** [comment]
@fernandolucchesi  An update to the robot.txt is on its way as I could see that sitemap uses url search params and we disallowed robot to crawl pages with search params, which i think is what you mean by broken files.
But in the future, please specify :)

**Comment by fernandolucchesi** [comment]
Ah, I see. I didn't look much into it nor in the code. I was running an SEO check on another site and I also ran it on equinor.com to compare results. I like using equinor.com as a reference hehe. That is how I found out it was "broken". I'll try to improve the description next time! :)

**Comment by BorghildSelle** [comment]
@fernandolucchesi  Aha, thank you anyway for the headsup :) All the best!
