### ISSUE TITLE
Workshop 4 December - points to discuss

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#2700]
- MVP for brand walls (full video, full image, clock/share price/TRIF number

- What happens when features that are implemented suddenly "disappears"?
- Forms -  request for Søknadsportalen?
- Video - could we have a direct screen9 integration?
- Could we have several languages for one page - how would it look in Studio?
- Open pdfs in a new tab
- Anything we should/could do for editors in the Studio - e.g. smart folder structure etc.?
- CTAs have different looks - should we move away from the button look?
- New components to develop?
- Template for reports?
- Front page template
- Org chart solve
- Image + expand (e.g. for careers) - [example](https://www.bp.com/en/global/corporate/what-we-do/our-transformation.html#modal-the-electric-evolution)
- Numbers/text/icon/years with several tabs component
- Newsroom and traffic

**Comment by NickHaggerty1** [comment]
**Numbers/text/icon/years with several tabs component**

Integrating data (Years / Topics) into a component where users can potentially compare previous years or toggle between topics

https://www.swisscom.ch/en/about/company.html#tabs-9c6686af39%5Bselected%5D=tab_1701870296420

https://www.eni.com/en-IT/investors/strategy/long-term-strategic-plan.html

https://investor.apple.com/investor-relations/default.aspx

**Comment by NickHaggerty1** [comment]
If time another topic to discuss is interactive maps. Comprend award points for simple overlay/interaction, to show for example Head office locations on a map or Countries we operate in... Assess cost/work vs reward on this.
Example of peer:
https://www.terna.it/en/about-us/introducing-terna
