### ISSUE TITLE
Investigate security concerns & use cases of uploading ZIP files

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#283]
See https://github.com/equinor/energyvision/issues/252

Rationale being that downloading random ZIP files from the internet tends to not be the best idea in terms of security.

- How often are zip files offered for download on equinor.com currently?
- What are the alternatives?
  - See for example how Google Drive handles downloading multiple items

**Comment by nilsml** [comment]
Have a discussion with the finance people that needs this feature, and look for possible alternatives.

**Comment by nilsml** [comment]
Isnt't this done @SvSven ?

**Comment by SvSven** [comment]
We did not discuss it in the end, but it is enabled yes - and also needed for some pages. So we can close this unless anyone has any serious objections (which they will need to take up with the editors in that case)
