### ISSUE TITLE
Move factbox code from serializer to component/storybook

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#285]

**Comment by wenche** [comment]
Much better now! And  it's much easier to reuse the factbox component. :thumbsup: 

As already discussed, we need to move the big fat margin from the text only version of the fact box to the serializer. That will make the storybook look good again.

I added a couple of stories to highlight the two column use case.

**Comment by wenche** [comment]
The margin issue is solved by [this commit](https://github.com/equinor/energyvision/commit/2552e49f9317ca49ad9a110f0a130a00eda8bee2)

I think this one is good to go!
