### ISSUE TITLE
News article publishing date.

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#287]
**Describe the bug**

- Published date should be automatically added when editor clicks publish. (real time date)
- Date picker should **only** apply if editor wants to schedule the publication for a specific time and date.
- Modify date should automatically be added once editor makes a change and re publishes. Currently it appears on the initial publish.
-  The modify date appears to show the "actual" date published when an article is first published. IE if editor sets to publish an hour ahead (ie schedule), the modify date displays the actual time one early than scheduled.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wenche** [comment]
@SvSven  I don't actually see how this solves the problem? We still print the Last modified date for all articles. And what was the idea behind the initial value in the schema? According to your commits, it's not used? And what about the publishing date, it's still an editable thing, the idea was to override the field if needed (for migrating articles back in time or scheduled publishing (which is yet to be solved ofc)

[We also discussed this on Slack](https://equinor.slack.com/archives/G01MJE7EL2H/p1619010956089800)

**Comment by SvSven** [comment]
Further work on this to be done in: #237
