### ISSUE TITLE
Random crashes when viewing news article

### ISSUE THREAD

**Issue by petterwildhagen** [equinor/energyvision#288]
Viewing a news page, such as this one:
https://energyvision.app.radix.equinor.com/news/petters-test-slug

random chashes occur

![image.png](https://images.zenhubusercontent.com/60376a60b424c72d28d1572f/1ef9dee7-0300-4609-875d-d57612adf1c3)

Comment from @wenche :
@petterwildhagen I have noticed the same, but I don't think it's related to the factboxes. It's something buried deep down in the image library we use, and I haven't been able to find a pattern with when it occurs.

I think we must create a separate issue for this bug, and see if we are able to find the exact reason. It is somewhat related to client side navigation because everything works fine when you refresh the page.

**Comment by nilsml** [comment]
I can see that we have pushed some code that may concern this card. Does that mean that the issue have been resolved? Ready for testing?

**Comment by wenche** [comment]
No, it's not resolved.

**Comment by wenche** [comment]
Check if this is still a problem
