### ISSUE TITLE
Set up blob storage for storing the static pages

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#296]

**Comment by kalyanvaranasi** [comment]
Working on ingesting the page and asset data to blob storage

**Comment by kalyanvaranasi** [comment]
Pushed the initial content to azure blob storage which contains

1. News pages from 2016 to 2018
2. News archive pages from 1998 to 2015
3. Search metadata from 1998 to 2018

This data needs to be tested once the nextjs app changes for archive pages is ready

**Comment by kalyanvaranasi** [comment]
New [storage](https://portal.azure.com/#blade/Microsoft_Azure_Storage/ContainerMenuBlade/overview/storageAccountId/%2Fsubscriptions%2Fa8b981a0-f92f-452c-90dc-d1226778e182%2FresourceGroups%2FEnvisRGDev%2Fproviders%2FMicrosoft.Storage%2FstorageAccounts%2Fenvisstoragedev/path/equinor-archive-content/etag/%220x8D925FB39AA194E%22/defaultEncryptionScope/%24account-encryption-key/denyEncryptionScopeOverride//defaultId//publicAccessVal/Container) is create and added static content
