### ISSUE TITLE
Investigate/Implement Azure function for running the migration script

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#297]

**Comment by kalyanvaranasi** [comment]
@nilsml Started looking in to the possibilities of using Azure function to run the web scraper utility.

**Comment by kalyanvaranasi** [comment]
@nilsml Almost implemented an initial version of the azure function which extracts and loads the newly published news page content.

We are yet to create a webhook from AEM to communicate about the news publish to azure function.
