### ISSUE TITLE
As a publisher I want a foolproof way to add slugs so that I avoid mistakes

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#308]
Technically this is now working as expected, but there's still a gap between the Figma sketches and the actual design and behaviour. We think this will be even more user friendly if we can apply the design for Figma

## Acceptance criteria
1. Add a new slug (/careers/{custom-text})
1. The design is like in Figma, with the slug field itself styled like a text and not a disabled input field
1. The slug field itself should not be focusable, like it is today

Link to Figma:
https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4599%3A81487

**Comment by wenche** [comment]
This is what we have done so far just as a start.
![Skjermbilde 2021-05-12 kl. 09.52.18.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/786679eb-f7bb-4537-b298-21e9e2e5cb63)

**Comment by wenche** [comment]
Current version

![Skjermbilde 2021-11-01 kl. 09.57.52.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/30b2bfba-4b58-4b27-a74e-be0033eb6e64)

We want to avoid that the publishers can edit the slug field and we would like to move the generate button under the actual text input field as that will make more sense when it's connected to where you add the unique part of the URL.

However, this was not that easy as the slug input type is not a part of Sanity UI.

**Comment by wenche** [comment]
In today's status meeting, we agreed to just leave this for now and revisit it later on to improve. Hopefully Sanity will make it easier to do custom things with the read only. Also see the [Slack thread ](https://equinor.slack.com/archives/C01A4BGNRMJ/p1635757512021400) for improvements, other things to take into consideration and solution proposals.

**Comment by wenche** [comment]
Related to #652

**Comment by fernandolucchesi** [comment]
Can we consider this a duplicate from #652 and close it? @wenche

**Comment by wenche** [comment]
yes, I think so since this was worked on in parallell with the other issue. :) But we need to remember to check of the design for this with Birte 👍

**Comment by wenche** [comment]
Update: We didn't finish the design according to Birte's Figma sketches due to time constraints. I'll update the acceptance criteria for this issue and we can improve the design later on. :)
