### ISSUE TITLE
Implement preview feature for topic pages

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#311]
Relates to #277

**Comment by SvSven** [comment]
Should be easy enough to combine the preview code for the news and page in a single file - but we might want to keep the news separate to provide a preview for cards and such as well?

**Comment by wenche** [comment]
This doesn't work for unpublished content. We must look more into this :thumbsup:

**Comment by wenche** [comment]
Now everything looks good :thumbsup:
