### ISSUE TITLE
Add teaser components to topic pages

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#312]

**Comment by wenche** [comment]
For SVGs we need to figure out if it's enough to just render them with `<img>` tag at this point or if we need to inline the SVG. Asked Sanity about how inlining SVGs could best be achieved.

We also need to figure out how we want the SVGs to behave in a responsive world, but we'll need some more experimenting before we see the big picture here.

**Comment by wenche** [comment]
Issue [#342](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/342) was created it we need inline SVGs.

**Comment by wenche** [comment]
As you mentioned as well @BirteThornquist , there are several a11y issues with the background colours and the read more link colour with axe.

1. 
![Skjermbilde 2021-05-25 kl. 09.47.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/e8c244da-d056-4243-8c5a-bd13a2a34c4a)
![Skjermbilde 2021-05-25 kl. 09.48.54.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/67fbb697-11cb-460b-a00f-b6fbf9963499)

2.
![Skjermbilde 2021-05-25 kl. 09.49.31.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/3c24c9d5-c16d-4867-90f8-1d284d86af21)![Skjermbilde 2021-05-25 kl. 09.49.45.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ca39177a-8c2c-435f-9e54-b85b90e5787a)

3.
![Skjermbilde 2021-05-25 kl. 09.50.36.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/984e51e0-cd75-40c4-aa57-77bac73311fa)
![Skjermbilde 2021-05-25 kl. 09.50.52.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f2879876-80c5-4fc7-9c5e-880b52391845)


4.
![Skjermbilde 2021-05-25 kl. 09.51.41.png](https://images.zenhubusercontent.com/5fb7aa9
b653d5135bb8c50f5/f719cd6e-feff-4783-9cf3-af945e39f846)
![Skjermbilde 2021-05-25 kl. 09.52.08.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/53bae126-b071-4ad7-ae1b-e715f37a743e)

**Comment by wenche** [comment]
Related to #277

**Comment by SvSven** [comment]
Notes & comments:

- Add padding to the top of the SVG when set to small on smaller screens
- Investigate color contrasts
- Investigate if we can improve link on dark background (text content is white and link is also white, does not stand out very much)

**Comment by BirteThornquist** [comment]
The color of all "Read more" links is changed to "Slate blue 100" in order to keep consistency and secure reading contrast. On slate blue background we will use the color "Mist Blue" for the links. Also for contrast reasons the "Moss green 80" background color option is changed to "Moss green 70".
