### ISSUE TITLE
Create site for Loop

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#318]
## Acceptance criteria
1. Serve from www.loop.equinor.com
1. Particular editors have access only to this site, and not to the rest of equinor.com
1. Subscription form required.
1. Menu. They display all stories.
1. Cookies/policy/acceptance on iframe (so editors need option to choose cookie type on the component eg Marketing)
1. Footer. Links back to Global site pages

## Additional requirements that we may do at a later stage
1. Image tile component used for a lot of Articles. How to solve? (image below) (#837) 
1. Needs some sort of newsroom page to display all articles (#838) 
1. Needs topic page template? Or a version of it that has additional option to add tags. Magazine template. (#839)
1. Tags/filters on the newsroom for users to select from (#840)

**Comment by nicholas-haggerty** [comment]
![image-tiles.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/f8661144-03fa-41ef-8f52-efce1603102e)

**Comment by nilsml** [comment]
Create separate stories for remaining "customization" tasks for this epic before closing

**Comment by SvSven** [comment]
Subscription form?

**Comment by nilsml** [comment]
Waiting on decision on how to proceed with this.

**Comment by SvSven** [comment]
@nilsml can this be closed then?
