### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#325]

**Comment by nicholas-haggerty** [comment]
@meols Can you add dependencies here

**Comment by meols** [comment]
Will the current Brandmaster subscription solution be used or a new one? 
This solution was made for Equinor to solve a problem when changing CMS to AEM, and is not an out of the box Brandmaster product. The email has poor quality email display, and should be emprived (compared to e.g. BP and other).

Investigation task:
Is there a better tool, API based, to use for subscriptions (where we need to retain the existing subscriber lists)

- End users register in a subscribe form ([example page](https://www.equinor.com/en/about-us/forms/subscription.html)) and the form is related to the specific tags (see below)
- End users are then registered in a Brandmaster database outside of Equinor (see overview of subscribers below)
- A process in AEM triggers a process at Brandmaster to send the tagged news to subscribers of the chosen tag.
- The email contains title, ingress (which is a specific component is in the news template only) and a link to the equinor.com news article. 
- Subscribers can unsubscribe via link in received newsletter, and will then be deleted from the database.
- If a news article is updated a new email is NOT sent to subscribers (and last modified date and time is added to the news article)
- If a news article is unpublished and republished again, a new newsletter is sent to subscribers

_Overview of options (incl. number of subscribers):_
General news, Norwegian (1624)
General news, English (6029)
Stock market announcements, Norwegian (1012)
Stock market announcements, English (3963)
Crude oil (847)
Magazine (906)
Loop stories (826) - on the Loop satellite site

**Comment by nicholas-haggerty** [comment]
We should look to continue with the Brandmaster set up for the MVP. Changing now will impact on Procurement / Legal / GDPR. Action is to set up a meeting with Brandmaster as soon as task is ready to be looked at.
