### ISSUE TITLE
Hero Banner

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#326]
Template/option 2. hero
1. 50 / 50 divide. Text placement area left. Image holder right.
1. Text: Placement left aligned Colour - Red / Green / Slate blue / White
1. Title
1. Ingress
1. Links
1. Downloads
1. Background:
Colour options: White / mist blue (%) / Spruce wood (100% & 50%)  / Lichen Green (100%) & slate blue

Image:
1. Image / illustration - option to extend behind menu? File type JPG / SVG?
1. Video - option to extend behind menu?

Menu background colour white, shows on hover

**Comment by NickHaggerty1** [comment]
Closing this as we have separate issues covering this need FI @meols @nilsml
