### ISSUE TITLE
Superhero Banner

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#327]
1. Full screen width and height?
1. Text: Placement L / C / R
1. Colour - Red / Green / Slate blue / White
1. Title
1. Statement
1. Ingress
1. Links
1. Downloads
1. Image:
  a. Image / illustration - option to extend behind menu?
  b. Video - option to extend behind menu?

**Comment by NickHaggerty1** [comment]
NIke corporate website. Nice example of looping, responsive video. https://about.nike.com/en/company

**Comment by nilsml** [comment]
We have many variations of banners for now.
