### ISSUE TITLE
Make it possible to navigate to other pages from static pages

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#330]
**In order to easily find other pages on the site, we need to make it possible to navigate to them from static pages**

## Acceptance criteria
1. When viewing a static pages, it is possible to navigate to any other page on site

## Related technical tasks
#453 Fix links with anchor element

**Comment by wenche** [comment]
Many of the links will just work out of the box when the static content is available since they are using a pattern like this:
![Skjermbilde 2021-09-06 kl. 11.37.45.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/946d33e0-d88e-4973-8890-ec7a6c932158)

**Comment by wenche** [comment]
I don't think this is an issue now @nilsml ?

**Comment by nilsml** [comment]
The way we have solved it seems to work, yes.
