### ISSUE TITLE
Create style variants/theming for the Teaser and Promotile components

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#334]
We want to try a concept where the publishers choose between a predefined, limited set of themes/style variants for the teaser. With this approach, we can ensure that the color contrasts are good enough, and make it easy and simple for publishers to add design and make it easier to update design later on.

A predefined style variant can apply to the background colour, text colour and font size and maybe some different colours for some part of a text or title like `highlight text`.

## Acceptance criteria
1. Define a set of themes with corresponding names
1. Create a custom input field for this in Sanity, possible with some corresponding icons
1. If needed, update text editor with a `highlight text `option with a corresponding icon
1. Update the component in the storybook to add the styles according to the chosen theme

**Comment by SvSven** [comment]
Related discussions: 
- https://github.com/equinor/energyvision/issues/312#issuecomment-847637957
- https://github.com/equinor/energyvision/issues/312#issuecomment-850162732

@vnys also mentioned we should strive to be as consistent with EDS as possible, for example when it comes to interactive elements.

**Comment by nilsml** [comment]
Look at the possibility of using the Sanity API for synchronizing colors. Publish NPM package with tokens could be an option.

**Comment by nilsml** [comment]
Is this still relevant? Do this for other components too? Other ways of achieving this?

**Comment by nilsml** [comment]
Revisit this card. Decide what to do. Rewrite description and acceptance criteria if necessary.

**Comment by nilsml** [comment]
Highlight text should be solved. Some UX work is needed. @BirteThornquist

**Comment by nilsml** [comment]
Decided not to do this atm as we don't know exactly what and how to solve

**Comment by SvSven** [comment]
Related issues: #741 (highlighting parts of a title)

We currently handle inverting the text color when the dark background colour has been selected; which was one of the main concerns here. EDS currently does not yet support this kind of theming, they are not done with their dark mode and are actively redoing how colours are implemented. They have made progress in terms of using CSS variables but I don't believe that is done yet either.

**Comment by nilsml** [comment]
Keeping it as reference in the archive
