### ISSUE TITLE
Scheduled publishing

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#339]

**Comment by nilsml** [comment]
Will be built in to next version of Sanity

**Comment by SvSven** [comment]
v3 of Sanity will have a basic implementation of scheduled publishing - but this may be incompatible with our current custom document actions and possibly also with the language plugin.

**Comment by jorgol** [comment]
We should also review current wording for article date on the news templates, as the current text can be misunderstood and interpreted as functionality to set future date:
"Publication date and time. Date and time of _when the article will be published_"

**Comment by SvSven** [comment]
It looks to be working out of the box and that kind of scares me, this is too easy?
We should definitely set up some test parameters and come up with a list of which documents should be allowed to be scheduled though.

**Comment by nilsml** [comment]
It should be possible to schedule publishing of any type of document
