### ISSUE TITLE
Add CTA label to Teaser links

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#340]
Part of #277 and #309

Create input component for adding a CTA label to the Teaser component
Render the CTA label in the component
Have fallback in the link component with original 'Read more' text

## Acceptance criteria
1. Can add a label for the link/download. 
2. Label is mandatory in validation.
3. ~Label text is rendered in teaser component~

**Comment by SvSven** [comment]
Duplicate of #332 (oops)

**Comment by wenche** [comment]
Works fine. Will probably be even more refined with [#332](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/332)
