### ISSUE TITLE
Add basic SEO and SoMe information for Topic pages

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#343]
## Acceptance criteria
1. Can override the page title with a `<title> field` SEO. If the title field is empty, it should fallback to using the title
1. Can add a meta description with guidelines for length in Sanity
1. Can add an image for open graph. If no image is added, a reasonable fallback is provided (most probably by the banner image? To be decided)
1. The webpage should add `<title>`, `meta description` and `og: tags` for SoMe the web page

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by wenche** [comment]
In Sanity I have added a fieldset for seo and some in the same way as with the `news articles`.
![Skjermbilde 2021-05-25 kl. 11.01.19.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8d155693-53ad-45e3-8591-58da0ae97fbc)

Note: The bug with the missing validation trigger for input fields in collapsed fieldsets is still present. Still waiting for Sanity here.

There is no fallback for missing og:image as that depends on the banner (#274) yet. 

Other than that, this is ready for testing.

Example before this task/facebook does its best
![Skjermbilde 2021-05-25 kl. 11.09.13.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/1a4939ce-2d55-4c6a-b611-1dcede0a378f)

Example after this task
![Skjermbilde 2021-05-25 kl. 11.34.13.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a4d213a6-43c1-4d7d-8cb7-9203fc3fa704)

**Comment by wenche** [comment]
@petterwildhagen @nicholas-haggerty  This is ready for testing :)

**Comment by petterwildhagen** [comment]
- [x] Can override the page title with a <title> field SEO. If the title field is empty, it should fallback to using the title
- [x] Can add a meta description with guidelines for length in Sanity
- [x] Can add an image for open graph. If no image is added, a reasonable fallback is provided (most probably by the banner image? To be decided)
- [x] The webpage should add <title>, meta description and og: tags for SoMe the web page

**Comment by nicholas-haggerty** [comment]
- [x] Can override the page title with a <title> field SEO. If the title field is empty, it should fallback to using the title
- [x] Can add a meta description with guidelines for length in Sanity
- [x] Can add an image for open graph. If no image is added, a reasonable fallback is provided (most probably by the banner image? To be decided) - @wenche Yes the top banner should be the fallback/default if an image is not placed in 'open graph'
- [x] The webpage should add <title>, meta description and og: tags for SoMe the web page
