### ISSUE TITLE
As editors we need to be able to present content in a table to communicate detailed information (Table component)

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#345]
Can we use table component from EDS?
1. Option to have header row(s)
2. Add/remove columns, rows. Merge.
3. Add Font size options to highlight
4.  Add Font colour option to highlight
5. Options to hyperlink to internal/external content

For discussion: Should we have options for background colour either behind the table content with white background on the  table content below. Or should the background in the table always be white? In turn will this effect the table frames.

Examples:
https://www.equinor.com/en/what-we-do/crude-oil-and-condensate-assays.html (version 1 on AEM)
https://www.equinor.com/en/investors/our-shareholders.html (version 2 on AEM)
https://www.equinor.com/en/about-us/annual-general-meeting.html (version 1 - with links)

**Comment by nicholas-haggerty** [comment]
@meols can you check and add additional points here

**Comment by meols** [comment]
We need standard table functionality, which I assume shouldn't be listed, but to add to your list @nicholas-haggerty we also need this:
- split cells
- padding
- set fixed table/column/cell heigth and width or adjust to the content
- link to O365 file formats and pdfs
- create mailto: and tel: links
- the table must be responsive
- standard text functionality (bold, italic, subscript, superscript etc)
- option to add border
- copy from O365 table and paste content across the whole table

**Comment by nilsml** [comment]
We should keep things simple for MVP!

**Comment by nicholas-haggerty** [comment]
@nilsml We need a table so needs to be created. Difficult to say from the list what is simple. As to be honest these are the functions required for a table?. The dev team will need to look at and define for us what is hard and what is simple.

**Comment by nilsml** [comment]
So, we decided to define a simple table-component for the MVP. Let's discuss next week and create new stories accordingly!
