### ISSUE TITLE
Provide a promotile component in Sanity

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#351]
**In order to promote certain content, we need to provide a "promotile" component**

## Acceptance criteria

**Comment by SvSven** [comment]
Things we need to discuss once @BirteThornquist is back from holiday:
- Should the promo tile component have an ingress/body text instead of only a title
- Which fields should be required
- Figma states "always a pair of tiles", does this mean the component should have a minimum and maximum of 2?

**Comment by wenche** [comment]
Add more guards for live preview while adding tiles

![Skjermbilde 2021-08-05 kl. 12.33.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f3f2a1d5-0ab8-42b1-ba1a-e35524473722)

**Comment by wenche** [comment]
On todays meeting we discussed a proposal for splitting the label field into two fields, one for a visible label and one for an aria label. By using this pattern, we can allow for catchy link texts like "Read more" while still creating usable content for all users.

`<a href="/" aria-label="Read more about our recruitment policy">Read more</a>`

![Skjermbilde 2021-08-09 kl. 12.54.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2fdd9cf8-930b-4de4-a2d1-5f7d921533aa)

**Comment by wenche** [comment]
We should fix the runtime error with preview while adding promo tiles. After that, it should be ready for testing

**Comment by wenche** [comment]
I think this is ready for your review as well @nicholas-haggerty
