### ISSUE TITLE
Create an accordion component in Sanity

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#352]
**In order to collapse content, we need to create an accordion component**
## Fields
1. Title
2. Ingress (rich text editor as in the ingress for text block)
3. Accordion list
    - Header
    - Rich text field without header levels (list, sub, sup, bold, italic, links)
4. Design options
    - Background colour

## Acceptance criteria
_To be filled in by the team (need to agree upon features we need from an accordion component)_
1 .Accessible

…

**Comment by wenche** [comment]
We have added the 1. version for the accordion component to Sanity. Birte looks into which icon to use in the list to better reflect the accordion, but EDS might not have a good fit for us here. 
![Skjermbilde 2021-06-30 kl. 15.04.04.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/73ee5354-9d5d-4daa-847f-4f2b8cbdd908)

![Skjermbilde 2021-06-30 kl. 15.04.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8595734a-1a0b-4b2c-852d-45d796b5fd2f)

**Comment by wenche** [comment]
We added an icon 

![Skjermbilde 2021-07-02 kl. 12.34.26.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8bfa1daf-3d90-4902-9bbe-751f02e3839f)

Can be seen at https://equinor.sanity.studio/desk/topicContent;838935d4-6139-48c6-b99c-4aeb4a4fb5f4.

You could probably verify in Sanity @nicholas-haggerty even if the component itself in the web is not ready. :)

**Comment by nicholas-haggerty** [comment]
@wenche great. Set up looks good. Cannot preview yet.

**Comment by wenche** [comment]
@nicholas-haggerty Yes, no preview since the web is not made yet
