### ISSUE TITLE
Create promo tile component for the web

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#353]
**In order to promote certain content, we need to provide a "promo tile" component**

We can use EDS card for this probably.

## Acceptance criteria
_To be decided by the team_

## Sub tasks
- [ ] Tailor EDS card for this project
- [ ] Implement in Storybook

**Comment by SvSven** [comment]
There are some unknowns at the time of writing, but based on what is available now this is "done".

Solving #408 would fix some issues, such as text color when using a dark background.
Similarly I'm not sure how the responsive behavior should be. It currently is a single column layout up to 750px width, where it switches to a 2 column layout. We can revisit this when @BirteThornquist is back from holidays same as the issues listed here: https://github.com/equinor/energyvision/issues/351#issuecomment-878241424

**Comment by wenche** [comment]
![Skjermbilde 2021-08-05 kl. 14.30.05.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d0e3ac16-f8e1-4e40-a8ca-665321df79a1)

We need to figure out how to solve the issue of long button texts. The problem with the EDS button is that it doesn't allow for line wrap. The height is 36px and you are supposed to [scale the width.](https://zeroheight.com/0b0c666ab/p/83185a-button/t/03eb53). Do we need a (low) maximum chars?

**Comment by wenche** [comment]
![Skjermbilde 2021-08-05 kl. 14.37.27.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b933ef54-6b21-489f-832b-f8b89b527777)

This is how the promo tiles behaves if the text of the buttons is not of the same length. Should it rather be a 50%?
In that case, the length of the link must be very restricted to avoid overflow

![Skjermbilde 2021-08-05 kl. 14.39.01.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a51c357e-4a14-4180-9ec5-36bac843ec8f)

**Comment by wenche** [comment]
Example with multiline

![Skjermbilde 2021-08-06 kl. 08.25.08.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/898f119a-d2ca-4592-9543-9ef31448e240)

**Comment by wenche** [comment]
![Skjermbilde 2021-08-09 kl. 13.15.01.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/7dc0891c-b506-4133-9d5a-bf68ecf754f3)

The result with aria label

**Comment by wenche** [comment]
The C2A button link does not have any styles for hover and more yet, will do this as a part of#363

**Comment by wenche** [comment]
@nicholas-haggerty  We tried the approach with 700px fixed height - didn't look good. This is also a bad fit technically with fluid typography. We decided to to instead aim for equal height for all promo tiles within a promo tile group, like in this image. What do you think that approach?

![Skjermbilde 2021-08-09 kl. 16.12.41.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d5910cce-31bc-48f5-8522-59867c75ce94)

**Comment by nicholas-haggerty** [comment]
@wenche Looks good. Lets go with that

**Comment by wenche** [comment]
Great @nicholas-haggerty ! It feels like this is ready for review and acceptance? :thinking_face: I mean, we could go on and on with tiny adjustments but I think it's ready for the next stage

**Comment by nicholas-haggerty** [comment]
@wenche @BirteThornquist Yup great, I think its good to move. Only issue is the Dark blue background /white text. I cant remember if this is part of a bigger task thats being worked on.![promo-dark-blue.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/201237db-26c2-47ac-8d13-8878006895b4)

**Comment by wenche** [comment]
@nicholas-haggerty Yes, part of #408, working on it as we speak, will be done in approx. 5 minutes :)

**Comment by wenche** [comment]
But still waiting for #363 for the button hover effects btw

**Comment by wenche** [comment]
@nicholas-haggerty Should be OK now, you may see it on the [careers page at the bottom](https://energyvision.app.radix.equinor.com/en/careers)

Please feel free to drag this card into "Acceptance" column if it's good enough :)

**Comment by nicholas-haggerty** [comment]
@wenche Thanks Wenche, virtual high five. Fast work :-)
