### ISSUE TITLE
Create component for displaying stock information for the web

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#354]
**In order to show information on stocks, we need to create a component that can display stock value**
https://www.equinor.com/en/investors/the-equinor-share.html

## Acceptance criteria
1. Based on information from an API show stock values
1. Adhere to figma sketches

## Sub tasks
- [ ] Create UI component
- [ ] Implement UI component in Storybook
- [ ] Connect to API for getting the stock exchange data (possibly it's own US)

![image.png](https://images.zenhubusercontent.com/5f899bfbf74e6d6928f0f80f/677a64ef-5656-4800-86ad-2df6f75066e1)

**Comment by kalyanvaranasi** [comment]
@wenche Here is the details about the end point for stock information.

Endpoint/feed url: https://tools.eurolandir.com/tools/pricefeed/xmlirmultiiso5.aspx?companyid=9053

We are polling this information every 60 seconds and parsing the xml to store it in a AEM way and we read this data in **stock importer** component.

Component has two configurations either to show Oslo stock exchange or New York stock exchange and you can see the additional configuration details in the screenshot below.

![image.png](https://images.zenhubusercontent.com/5f5018edb661c4effd092876/65e7ff70-121c-4c31-816c-32130a7a8c8b)

**Comment by nilsml** [comment]
@nicholas-haggerty to follow up with AEM team

**Comment by nicholas-haggerty** [comment]
@nilsml We discussed in this mornings meeting. Sven has gone ahead with this task and implemented the component in Sanity already. Input wasnt required. Until we see it in the web its a little hard to see if we have delivered on the task.

**Comment by nicholas-haggerty** [comment]
@SvSven @nilsml When you get a chance could you let me know if this task has been complicated?, I know we have the component in the list but I dont see the component in preview when I test.

**Comment by SvSven** [comment]
I don't believe we have the web part of this yet no, as we need to do some work to integrate with the API. We only added a placeholder component in the studio.

**Comment by SvSven** [comment]
@fernandolucchesi @wenche @padms This should be ready to be looked at. Might be some room for improvement to make the data fetching reusable but I don't think there is any other place where we use this API, so not sure if its worth it really.

**Comment by wenche** [comment]
Some comments
- The query is obviously copy'n paste -> FTFY
- Too much hardcoded text -> gives `at least 20 minutes delayed` for Norwegian. Should have been a text snippet
- As always: would have preferred uppercase letters with CSS, not capslock :)
- Minor detail: No localisation formatting for the currency

**Comment by SvSven** [comment]
Fixed text snippet and uppercase, not sure if localization for currency is a good idea or not. I would image that anyone interested in this understands that the NYSE trades in USD and the OSE trades in NOK.

Is there anything special we need to do in terms of screen readers for this content?

**Comment by SvSven** [comment]
The automatic formatting of the timezone by react-intl _might_ be a concern for stakeholders, since it shows CET for some and GMT+1 (or equivalent for whatever time of year it is) for others. We'll keep just keep it until we get any comments on it.

There's also the question of how relevant the date really is considering we don't show the actual _time_ - but then the original component on equinor.com does not show that either. We do have a timestamp in the API data so we could show it if we want to, but need to discuss with stakeholders.
