### ISSUE TITLE
As a publisher I want to add quotes so that I can create nice content

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#357]
## Acceptance criteria
1. Can add quotes to topic pages
1. Can select position of the image (left or right)

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by SvSven** [comment]
The quote component in this is the same as the one used in the news article.

New functionality introduced in this user story is that editors can add quotes in topic pages and that editors can select which the position of the image used in the quote (left or right). Other than that the quote component itself is unchanged.
