### ISSUE TITLE
Investigate synchronization of content between documents in different languages

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#360]
How to make sure changes in the English document are reflected in the Norwegian translation as well.

Talk to Rune in Sanity about different approaches

**Comment by SvSven** [comment]
In our meeting with Sanity we discussed how to handle this.
They suggested two different approaches;
- Adding the ability to copy-paste individual components between the English and Norwegian documents, which could be as simple as just using `ctrl` + `c` and `ctrl` + `v`
- Having a complete "copy document" functionality that copies all components over to the Norwegian document, similar to how it works when first creating a translation.

It should also be possible to selectively paste only certain fields - which can be used to for example always overwrite the Norwegian values for fields like the design options where a translation is not needed.
Additionally we could have some way of checking for differences between the 2 documents when copy/pasting.

Both approaches can be used together where for example we have an action to synchronize the non-translated fields in all components between the 2 documents at once (things like image position, background color, etc) and copy/paste newly created components one by one. 

Supposedly this can all be done with some simple JavaScript, they would get back to us with examples of how this works and how to do it. Parts of this functionality is supposedly still in development/beta.
