### ISSUE TITLE
As a end user I want good contrast on elements with coloured backgrounds so that it is easy to read the content

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#363]
We need to find a nice colour schema for buttons and links that will work for coloured backgrounds. We should see how we can achieve this by using EDS, and if some of these things should be done in the EDS (Currently EDS is made for white backgrounds). We need to both make it work with a11y and ensure it pops out so it's easy to see.

- Text colour
- Background colour
- Hover colour
- Focus colour

## Acceptance criteria
1. [Criteria 1]
1. [Criteria 2]

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by wenche** [comment]
Some identifiedissues

The hover colour doesn't look that good on all backgrounds
![Skjermbilde 2021-06-08 kl. 09.09.52.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/fabe6f54-6809-450f-82fd-1cd464e3acc1)
![Skjermbilde 2021-06-08 kl. 09.12.22.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/fe935f22-e2f5-4d74-801c-77ba95b96568) 

Hard to see?
![Skjermbilde 2021-06-08 kl. 09.13.11.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/6888442e-7635-4d79-9c4f-5ff8fa3ddbf5)
![Skjermbilde 2021-06-08 kl. 09.14.08.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/67e21504-3ef7-4ebb-9d3b-1536927df093)

**Comment by BirteThornquist** [comment]
Updated the color specifications for buttons and links [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=1511%3A948)

**Comment by nicholas-haggerty** [comment]
All good. Only issue is with spruce wood background with hover on button as light pink. @BirteThornquist lets chat to finalize.
