### ISSUE TITLE
Add icons for news, routes and topic pages

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#365]
## Acceptance criteria
1. Nice and easy to understand icons in Sanity for news, topic pages and routes.

**Comment by BirteThornquist** [comment]
I have created the icons for Route, News, and Topic Page [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=1754%3A187)

**Comment by wenche** [comment]
Icons are added, but is 48 too large @BirteThornquist ?
48
![Skjermbilde 2021-06-16 kl. 10.32.34.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/e53cee3c-0a17-459e-92e9-55675df05f6e)
24 (as an example)
![Skjermbilde 2021-06-16 kl. 10.32.12.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f3238039-7b43-4cd3-91da-aedb292e62a5)

**Comment by BirteThornquist** [comment]
Feel they are a bit too large, yes. Let's do 40x40.

**Comment by wenche** [comment]
Done. :thumbsup:

When Radix is up and running again, this can be tested Sanity
