### ISSUE TITLE
Create a separate application for the archive pages

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#374]
The News archive consists of almost 20.000 static pages from AEM. In order to not have to rebuild the news archive every time we deploy the web application, we should extract that into it’s own application. If we build the menu so that’s it can render in the client, then we would only have to deploy the news archive application once and unless there are problems it could run for years without being touched. This also makes sense from a Next perspective, since we could then identify the most popular archive pages based on page views, build and deploy those, and have the rest of the pages be built on demand. The number of built pages would then increase over time, which means the longer it runs the less pages need to be built.

**WIP**

| Pros                                                | Cons                                                                     |
|-----------------------------------------------------|--------------------------------------------------------------------------|
| We dont have to give up nextjs built in CSS support | Manage new nextjs application server with additional cost                |
| Doesn't pollute envis repo                          | Introducing one more reverse proxy layer                                 |
|                                                     | Additional Header and footer components management which could be tricky |

**Comment by kalyanvaranasi** [comment]
@nilsml I have added WIP pro's and con's going with this approach. I think we should collectively discuss this and come to conclusion whether it's the right to implement this.

**Comment by kalyanvaranasi** [comment]
Moving this back to the backlog as the developer team has decided to take this once the hosting service(Vercel/Radix) is decided.

**Comment by nilsml** [comment]
This issue is talking about archived news articles, but what about other static content. In a situation where we will need to make static pages of everything in AEM, this will probably also be an issue.

**Comment by SvSven** [comment]
In the current setup we are hosting static topic pages from AEM in the same application as the news archive and Sanity content. I'm not sure if it makes sense to do this at this point in time as we need the legacy-css styles used by the news archive for these static topic pages as well.

In addition there is the question of how to handle the new Sanity-based menu and footer if we choose to switch the news archive to its own Next application.
