### ISSUE TITLE
update TypeScript past 4.2.4

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#377]
Updating TypeScript past v4.2.4 causes Storybook v6.2.9 to fail due to a problem with `react-docgen-typescript`
This has [since been fixed](https://github.com/styleguidist/react-docgen-typescript/issues/356) in v2.0.0 of `react-docgen-typescript` but Storybook has not yet updated its dependency version.

A solution could be to switch to `react-docgen`, which would make sense as the aim is to have that be the default in Storybook v7 as described here: https://gist.github.com/shilman/036313ffa3af52ca986b375d90ea46b0
However due to `react-docgen` still not supporting imported types properly, this is not a good/easy solution.

**Comment by wenche** [comment]
With the use of rc 9 we see a lot of runtime errors. We opened an issue in [the Storybook repository](https://github.com/storybookjs/storybook/issues/15282) In the meantime we _could_ stop the use of <code>Code blocks in text</code> but let's see if it's an easy fix on their side first

**Comment by wenche** [comment]
Let's wait and see for a couple of days. Since this was added in the `package.json` file, the action didn't trigger a build on Radix so production Storybook is still running fine on the old version.

**Comment by vnys** [comment]
…but now that I’ve fixed the Github action that prevented the Storybook to be deployed we have [blank stories](https://envis-storybook.azureedge.net/?path=/docs/components-card--default) 😎  

The storybook runs in Azure btw, it’s uploaded to an Azure Blob Storage (https://envisstoragedev.z16.web.core.windows.net) which is served through Azure CDN (https://envis-storybook.azureedge.net).
