### ISSUE TITLE
As an editor I need an easy way to link new content to a route

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#380]
Look more into the incoming references. Simeon  suggested a workflow like this:

- If a route has a reference to this content, list it in the pane (the way the incoming references plugin works out of the box). If you click on the reference, it will take you to the Route document.
- If no routes have references to this content, provide a button like "Use in a Route" . If the editor clicks on this button, he or she will we taken to a new Route document where the referenced content is predefined.

Questions:
- How should this work with multiple languages
- What if the content is `careers for a student campaign` and `careers main version` and the editor wants to change the content of a route to the new  `careers for a student campaign`. In that case the "Use in a Route" will not be want you want even if that will be the content of the pane. How can this be as easy as possible to understand?

**Comment by wenche** [comment]
The plugin out of the box
![Skjermbilde 2021-06-16 kl. 10.32.12.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/21e30cc7-5755-472d-a468-b9956edafe4a)

**Comment by nilsml** [comment]
When does it make sense to look at this? @wenche; inputs?

**Comment by wenche** [comment]
If we had an epic for "Make Sanity as user friendly as possible for editors" it would belong there. @nilsml That might actually be a good idea, since we are focusing heavily on the web and not that much on sanity as a good tool for publishers

**Comment by SvSven** [comment]
If we don't have that epic already then we should make that. There are a couple of issues that relate to it, like for example #368 
It's also something that will become more and more important/relevant as we approach a release.

**Comment by nilsml** [comment]
Ok, we can create a new epic at standup.

**Comment by nilsml** [comment]
@SvSven to initiate a discussion

**Comment by wenche** [comment]
Let's keep this as a future reference, but v3 of the studio might change the suggested workflow we initially got from Simeon.

**Comment by fernandolucchesi** [comment]
I would say editors are very familiarised with the current way of doing this. I'd propose we close this @equinor/envis-devs

**Comment by SvSven** [comment]
Agreed, making major changes now would just make things more confusing
