### ISSUE TITLE
Automate cleanup of blob storage

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#382]

**Comment by SvSven** [comment]
The storybook is currently built and uploaded to blob storage from GitHub Actions. The way it is set up right now is that it just pushes a new build to blob storage without deleting previous versions.

**Comment by nilsml** [comment]
We should have a separate action for the cleanup I suppose. That must run after deploying a new version.

**Comment by fernandolucchesi** [comment]
@nilsml is this still relevant?

**Comment by nilsml** [comment]
This was probably cleaned up during rebuilding of our Azure setup
