### ISSUE TITLE
Support for different characters in the URLs

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#384]
Does it makes sense to support both 
`/no/karriere/hva-vi-gjør` and `/no/karriere/hva-vi-gjoer`?

Probably, by the use of canonicals in the web. Figure out who's responsibility this should be (Sanity, the web) [The slugify library](https://www.npmjs.com/package/slugify) supports a locale parameter, can be an idea to look into as well.

## Acceptance criteria
1. [Criteria 1]
1. [Criteria 2]

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nilsml** [comment]
Did we make a decision about this. Document the decision at least.

**Comment by wenche** [comment]
No decisions yet, it's in the backlog as a question after all.

The SEO agency did recommend us to do this though and I think we should. Can be looked into as a part of the redirects as well depending on how we solve it (if we do)

**Comment by wenche** [comment]
### Decision
-We don't want to support æøå in the Norwegian URLs
- The "generate slug" button should change to
-- æ -> ae
-- ø -> o
-- å -> a

**Comment by SvSven** [comment]
Looks to be converting æ ø å correctly 👍
