### ISSUE TITLE
synchronize next.js locale with react-intl provider

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#396]

**Comment by wenche** [comment]
![Skjermbilde 2021-08-09 kl. 08.27.22.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/3b9d2502-a5e1-4466-80af-fbaf214e82b3)

I don't think all the necessary things are done here to make this work?

**Comment by wenche** [comment]
https://github.com/formatjs/formatjs/issues/1776

**Comment by wenche** [comment]
It seems to be an issue with Chrome 92 and the Norwegian Date format. It works with other browsers (or engines, same with Edge) including Chrome Canary (v95)

Canary
![Skjermbilde 2021-08-16 kl. 10.46.42.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ea02d835-5776-41a3-9d77-89bbacff6b19)

Production Chrome
![Skjermbilde 2021-08-16 kl. 11.08.41.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/1c97deb8-63e5-4a37-8b5a-279faf783eff)
