### ISSUE TITLE
Remove empty paragraph tags from rich text editor

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#398]
Line breaks in the rich text editor generate an empty `<p>` on the web. We should filter these empty tags out so as to not clutter the rendered web with them.

**Comment by wenche** [comment]
We [discussed this with Sanity](https://equinor.slack.com/archives/C01A4BGNRMJ/p1620069362044400) a couple of months ago.

**Comment by SvSven** [comment]
Looks good, though this should really be something that we can configure from Sanity's end
