### ISSUE TITLE
(news) preview does not work until article has been published

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#401]
Steps to reproduce:

1. Create a new news article
2. Add a slug
3. Click the preview tab
4. Next.js returns a 404 error due to `news` in `getStaticProps` being `null`
5. Go back to editor tab, click "Publish"
6. Click preview tab again, preview is now working

Have checked the full query with the same param (unpublished slug) in Vision, and there it does return results.
Might be related to not being able to fetch drafts, but that shouldn't be an issue when using the preview inside the studio.

**Comment by wenche** [comment]
This goes for previews in general. Both news, topic content and landing pages share the same issue
- When a document is published, previewing draft works
- Before a document is published, preview is just 404

**Comment by SvSven** [comment]
This issue came up when we were using the inline preview hook, which we currently are not using anymore. The current setup we have with cookies is supposed to be a temporary solution until the performance issues with the inline preview hook are fixed, so we can revisit this once we decide to move back to that setup.

For the time being; if the cookies are set properly after clicking the "Open preview", then the inline panel for preview should work. The preview in the new tab won't currently work properly for news because the URL is incorrect, we have a separate issues with that button: #630
