### ISSUE TITLE
@sanity/form-builder v2.12.2 does not work with pnpm

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#404]
Upgrading `@sanity/form-builder` to 2.12.2 causes the desk tool to crash

**Comment by SvSven** [comment]
After a discussion with Sanity, it seems that having `@sanity/ui` as a direct dependency is causing the desk tool to crash.
We no longer need `@sanity/ui` as a listed dependency because it is included in `@sanity/base`.

However trying to run the studio after removing `@sanity/ui` and reinstalling, our imports from `@sanity/ui` cannot be resolved. The problem seems to be with PNPM - when installing dependencies and running it with yarn the problem does not occur.

**Comment by SvSven** [comment]
Seems like the problem runs a little deeper than just the `@sanity/ui` dependency.

Installing the dependencies with either `yarn` or `npm` (both with and without `@sanity/ui`) makes the problem magically go away.
Similarly, using `pnpm` to build and run the studio, but using dependencies installed by `yarn`, makes the problem go away.

Attempted to fix the problem by using the `shamefully-hoist` option, however that did not fix the problem either.

When trying to install and run it with `npm` there are some other problems

```bash
$ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^16.9 || ^17" from @sanity/base@2.12.2
npm ERR!   node_modules/@sanity/base
npm ERR!     @sanity/base@"^2.12.2" from the root project
npm ERR!     @sanity/base@"2.12.2" from @sanity/default-layout@2.12.2
npm ERR!     node_modules/@sanity/default-layout
npm ERR!       @sanity/default-layout@"^2.12.2" from the root project
npm ERR!     4 more (@sanity/desk-tool, @sanity/form-builder, ...)
npm ERR!   22 more (react-dom, @sanity/default-layout, @sanity/desk-tool, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-sortable-hoc@1.11.0
npm ERR! node_modules/@sanity/base/node_modules/react-sortable-hoc
npm ERR!   react-sortable-hoc@"^1.11.0" from @sanity/base@2.12.2
npm ERR!   node_modules/@sanity/base
npm ERR!     @sanity/base@"^2.12.2" from the root project
npm ERR!     5 more (@sanity/default-layout, @sanity/desk-tool, ...)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

ignoring this issue and installing with `--force` and running `$ npm run start` presents us with a missing dependency, which also shows up when building the studio with `yarn`:

```bash
Error in ./node_modules/@sanity/desk-tool/lib/components/BrokenReferences.js
Module not found: Error: Can't resolve 'react-props-stream'
```

attempting to install `react-props-stream` then brings us another problem, which looks to be related to the React version problem above. This problem only showed up for `npm`

```bash
npm install react-props-stream
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: energy-vision-studio@1.0.0
npm ERR! Found: rxjs@7.1.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"^7.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6" from react-props-stream@1.0.1
npm ERR! node_modules/react-props-stream
npm ERR!   react-props-stream@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Once again using `--force` fixes this problem. After that, building and running the studio with `$ npm run start` now builds it successfully, and the initial problem we see with `pnpm` is not present.

Should be noted that adding `react-props-stream` as a dependency and trying to install & run with `pnpm` does not fix the problem either.

**Comment by SvSven** [comment]
For the sake of not wasting more time on this during holidays, we will put this on hold and postpone the update until people are back from vacation when we have more eyes and brains to look into it.

**Comment by wenche** [comment]
Related conversation https://equinor.slack.com/archives/C01A4BGNRMJ/p1625141094119900

**Comment by vnys** [comment]
I made a pull request a year ago about missing dependencies in Studio → https://github.com/sanity-io/sanity/pull/1965

**Comment by vnys** [comment]
I think the sad conclusion after spending most of the day wrestling with Sanity Studio, is that it does not work with pnpm. Another thing is as long as we don’t host Sanity Studio ourselves, it doesn’t really make sense to have a lock-file from a different package manager than the one that’s used in production. 

I suggest we do the following: Install `@sanity/cli` as a dependency in Studio, and then change the dev script to `yarn ./node_modules/.bin/sanity start`. Then it can be run from the root with `pnpm studio dev` the same way we do now. We would also have to remove `studio` from `pnpm-workspaces.yaml`, and lastly to install dependencies we would have to create an npm script in `./studio` called `yarn` that just has `yarn` in it (since just yarn is a shortcut for `yarn install`) – and then run `pnpm studio yarn` from root to install dependencies. 

I would have made a pull request but I ran out of time.

**Comment by wenche** [comment]
Nils Magne and I _think_ this works now. Let's have the final test when Sven is back from his vacation! 

We did what @vnys  suggested, with a few additional steps.

**Comment by SvSven** [comment]
Following these steps:

```bash
    $ git clone git@github.com:equinor/energyvision.git
    $ cd energyvision
    $ pnpm m i
    $ pnpm studio yarn
    $ pnpm start:studio
```

and everything works for me - so looks good?
