### ISSUE TITLE
Filter pages in internal link list to only those that has a reference

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#406]
When the publisher select an item in the internal link reference list, it is possible to select a page that has not yet been connected to a route because type is of type `page` and not `route`. The actual reference has to be to a route, and we should make the preview as good as possible to make it easy for publishers to understand what they are referencing.

**Comment by SvSven** [comment]
Switching to `route` instead of `page` was fairly straightforward, and the preview for editors is actually better than what we had out of the box.

There is however a problem with the slugs for internal links as described in #413
