### ISSUE TITLE
Refactor Card component to support BackgroundContainer

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#408]
The EDS Card component has a background color applied from EDS.
We should refactor the Card component to support our BackgroundContainer component so that we can set different background colors and support the "inverted" option for darker backgrounds.

**Comment by wenche** [comment]
This is more of a technical issue, let's wait for Sven's approval

**Comment by SvSven** [comment]
Looks good 👍
Just wondering if this is something we should fix upstream in the EDS as well?
