### ISSUE TITLE
Archive News Pages: Iframe component does not load video/url as cookiebot integration is pending

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#416]
Until cookiebot has been implemented in new solution, video through iFrame will not work.
Revisit this issue once cookie handling is working.

Related to #407

**Comment by padms** [comment]
Works with test implementation

**Comment by nicholas-haggerty** [comment]
@padms We notice the archive news is 2016 to 2018. Where is 2019 to 21?
Could you supply an example link news page from 2016 - 2018 that contains a video?

**Comment by padms** [comment]
@nicholas-haggerty  We have all the pages in azure. Here is a link to a recent news article having a video.
https://energyvision.app.radix.equinor.com/news/archive/20210806-giving-vigdis-boost
