### ISSUE TITLE
Build example pages in Sanity to use for testing

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#417]
**In order to have a stable environment for testing, we need to set up one or more example pages in Sanity**

- [ ] Identify what kind of pages are needed
- [ ] Build the pages
- [ ] Document the pages

Related to #419 and to some degree #418.

**Comment by wenche** [comment]
Is this still relevant @nilsml

**Comment by nilsml** [comment]
A test dataset could be used for this
