### ISSUE TITLE
Follow up on fix for array field validation from Sanity

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#422]
Related: #332

Array fields where the items are removed have the value `[]` instead of `undefined`, breaking the `required()` validation

**Comment by wenche** [comment]
This works as expected now. 

Add a link: action array is of length 1
![Skjermbilde 2021-09-22 kl. 08.24.36.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/975e6a54-a6c8-4f3d-91fc-3199fd50f9ec)

Remove the link: action is no longer an empty array, but undefined
![Skjermbilde 2021-09-22 kl. 08.23.58.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c35f379e-c233-4dfd-9bb5-e999ed5a72d1)
