### ISSUE TITLE
As a editor we would like have an event template to provide users with a standardized page to view events both as upcoming and passed events

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#440]
## Acceptance criteria
1. New EVENT template based on NEWS template setup

1. Title
1. Date
1. Add to calendar button (remove/disable button post event date)
1. Ingress
1. Text
1. Iframe - (optional, doesn't display until link is added)
1. People promo - providing contacting details of stakeholder(s)
1. Basic table component 
1. Links & Downloads

**Comment by nilsml** [comment]
This one can be converted to an Epic US and sub-tasks added to this
