### ISSUE TITLE
Investigate solutions to solve certain pages that previously used the PANEL template

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#442]
As we will move forward WITHOUT the PANEL template, some will be easy to replace as either: NEWS  /  EVENTS / TOPICS, but there are some pages that may cause issues
https://www.equinor.com/en/how-and-why/impact-assessments.html
https://www.equinor.com/en/about-us/corporate-executive-committee.html
https://www.equinor.com/en/what-we-do/fields-and-platforms.html

Should we build these pages using topics, but is there are solution to clean up/structure the TOPIC Routes? Perhaps using smart folders or tagging filtering. EG tag a topic fields&platforms so it is added to a smart folder.

**Comment by nilsml** [comment]
Hasn't some work been done on this already?

**Comment by nicholas-haggerty** [comment]
@nilsml This will largely be solved editorially. 
Either they have: 
Already been removed in AEM
Use topic or Event template to resolve
Combine content onto existing topics

Could still be a need for the overlay component that has been discussed already, but I think this should be backlogged and see if there is still a need as pages are built.
