### ISSUE TITLE
Follow up on brandmaster web plugin issue

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#443]
Relates to #337

The Brandmaster web plugin used for the custom asset source in Sanity does not load properly. It gets stuck in an infinite redirect loop when trying to authenticate with AD.

We need to check with Brandmaster on how to fix this.

**Comment by nilsml** [comment]
Talk to @meols about this one

**Comment by SvSven** [comment]
This has been relayed to Brandmaster and we are waiting for a fix/further feedback.

**Comment by meols** [comment]
@SvSven I have received an update from a brandmaster IT guy (Torbjørn) - see attached email. Can you please answer him directly (feel free to add me on cc)
[https://app.zenhub.com/files/224120954/8fdd5a16-570b-4b89-bae2-3efe8bd47fda/download](https://app.zenhub.com/files/224120954/8fdd5a16-570b-4b89-bae2-3efe8bd47fda/download)

**Comment by SvSven** [comment]
Have reached out to Brandmaster tech people directly.
Looking into it a bit deeper it seems like the problem might be caused by the SSO with Azure AD - the iframe that loads the Brandmaster web plugin can't seem to properly parse the SSO session and gets stuck in an infinite reloading/redirecting loop.

Waiting to hear back from Brandmaster for advice/solutions

**Comment by SvSven** [comment]
Have heard back from Brandmaster, they can reproduce and confirm the issue. They are working on figuring out what the problem is and how to fix.

**Comment by SvSven** [comment]
The problem with the SSO is strange. We had a walkthrough with the person responsible for SSO integrations in Equinor who could not find anything wrong on our end, pointing the problem back at a callback hook in Brandmaster.

However Brandmaster in turn can't pin down the problem either, and have stated that they have not heard of similar problems from other customers.

In discussion with Brandmaster we came up with an alternative solution which seems to avoid this problem, by using a child window popup that loads the DAM in web plugin mode but outside of an iframe. Initial testing with this is promising, shows that things are working as intended.
