### ISSUE TITLE
Make migration script work with topic pages - careers into blob storage

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#444]
**In order to serve AEM pages as static pages in Next.js solution, we need to make migration script work with topic pages**

Focus on careers

## Acceptance criteria
1. Json-content for topic pages available in blob storage

## Sub-tasks
- [ ] Add new rewrite Next.js config file

**Comment by padms** [comment]
New containers for non-news pages are created. 
Azure function app updated to store non-news pages to new container.

**Comment by nilsml** [comment]
Need to also do the top level pages

**Comment by wenche** [comment]
The top level pages are available. Looking mostly good. Some comments @padms 
- About us has only an image and doesn't look like in production
- Some images are missing, for example at Where we are
