### ISSUE TITLE
Split on language in the navigation structure for Routes and Menu

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#445]
Add a navigation structure level for "Norwegian" and "English" at top level for routes and menu.

![Skjermbilde 2021-08-27 kl. 12.59.24.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8bd7f79b-3f73-416f-91f1-c6f27156fe98)

Relates to #437

Acceptance criteria
- English and Norwegian routes and menus are created separate
- Use previews corresponding to the actual language (Norwegian route names for Norwegian, English for English)
- The publisher should only be able to reference content from the chosen language
- Is it possible to limit the number of documents to one for English, one for Norwegian? Aka a singleton (this depends on how we solve the actual document creation)

**Comment by wenche** [comment]
**Status**
- Added the language level in Sanity
- Updated the internal links and references accordingly
- Updated some previews
- Updated the topic page query in the web
- Updated the menu query in the web, we now have the first version of the menu running for both /careers and for /no/karriere

**Some details are still work in progress**
- Get the language switch to work with the new content structure
- Probably some bugs and quirks

**Comment by wenche** [comment]
@nicholas-haggerty  I'm moving this to review. Not everything is 100% polished yet, but more things will come in the near future while we are working on  the Plan B part.

To test/verify this you can try the features that was demoed during yesterday's status meeting: The language should now be the first thing you need to select when you add routes and menu items in Sanity. You should be able to create references to documents in the same language. 

As we talked about yesterday, we'll need to figure out at some point if we need to loosen up on the validation/filters for language or not depending on how the publishers will work with language.

**Comment by nicholas-haggerty** [comment]
@wenche Good, been through it. Works well. I will close this card.
