### ISSUE TITLE
upgrade to node v16

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#447]
upgrade Dockerfile and volta config from node v14 to node v16

**Comment by nilsml** [comment]
Isn't this something we can just do? @wenche @SvSven

**Comment by wenche** [comment]
Probably? I don't remember why we created a separate issue for this one. But didn't you struggle with something yourself about node versions? Let's try.

**Comment by nilsml** [comment]
Yeah, it didn't work when I tested several months ago, but that should not prevent us from trying again.

**Comment by wenche** [comment]
@nilsml  I don't remember the exact issue from last time we tried? Do you? It seems to work OK on CI and locally when I upgraded now

**Comment by nilsml** [comment]
I was not able to run at all last time. Some dependency issue I believe.

**Comment by wenche** [comment]
Sooo... I'm moving this to review then. Please test and see if everything is OK beyond OSX land @SvSven

**Comment by SvSven** [comment]
Looks to be working on my end as well, so... LGTM 👍
