### ISSUE TITLE
As an end user I want a good way of navigating the news archive

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#449]
Let's not make too much effort out of it, but we need an improved version of the [news archive landing page](https://energyvision.app.radix.equinor.com/news/archive). Is it possible to fetch the title for each page as well?

How about search/filtering? tbd

## Acceptance criteria
1.  It is possible to navigate to each of the static pages
2. It is possible to switch language

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nilsml** [comment]
Is this also related to sitemap?

**Comment by wenche** [comment]
No, it's not. It's for the news archive landing page.

**Comment by nilsml** [comment]
Could be solved (partly) by search
