### ISSUE TITLE
As an editor I want to easily find the page I want to edit

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#452]
## TODO
- Discuss different solutions to this.

## Acceptance criteria (to be updated)
- It is possible to group pages based on
  - template
  - title

Related (almost duplicate of) to #541 
----

While work is being carried out on the production environment could be good to look at smart folders. Particularly in the TOPIC CONTENT lane. Be good to have editorial control to set up/name the folders and allocate topic under the relevant one. This would follow the logic of the site structure. 
FOLDER NAME Sections

1. Energy
1. Sustainability 
etc

FOLDER NAME energy
1. Natural gas
1. fields and platforms
etc

**Comment by nilsml** [comment]
How should we deal with this one. Is it captured in other stories? Nice to have?
