### ISSUE TITLE
Fix links with anchor element

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#453]
AEM has a lot of links using the anchor element to jump directly to an id of a page. This doesn't work in the Next.js solution because of the added `.html` part. Example from wind:
`<a href="/en/what-we-do/wind.html#uk-wind" target="_self"> <span>UK Wind</span> </a>`

Ideally, the url should just be `href="#uk-wind"` if it is on the same page, and without the .html `<a href="/en/what-we-do/exploration#uk-wind" target="_self"> <span>UK Wind</span> </a>` if it's on another page.

**Comment by padms** [comment]
Fixed in the migration script.
