### ISSUE TITLE
The height of the "main" element is wrong with static pages

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#454]
![Skjermbilde 2021-09-06 kl. 11.49.23.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/23fb0769-55e8-4ea5-b689-527eb94e9a7c)![Skjermbilde 2021-09-06 kl. 11.49.06.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/63f1ed18-7f8f-4fce-980c-031fd3e24e31)

The height of the `main` element is wrong, and this causes the `footer` element to be positioned at the wrong place.

**Comment by wenche** [comment]
Since we have multiple `main` element, I don't think we can reuse the Layout directly for static AEM pages.

**Comment by wenche** [comment]
Production equinor already has two levels of nested `<header>` landmark regions. When we do the menu, we'll figure out the 100% best way of doing the landmark regions.

**Comment by wenche** [comment]
Devs: Solved this by moving the main landmark region into the template itself, this gives us more flexibility later on as well. I also added a clear float for the footer component, because the static pages have some `float: left` attached to some of the top level containers. I don't see exactly why, and while this may cause some issues later on, it's OK atm

**Comment by SvSven** [comment]
I guess the `float: left` on the top level `main` for the legacy content might be because of the sidebar menu on the current site? _Should_ be safe to remove that if it causes any issues.

Other than that, looks fine 👍
