### ISSUE TITLE
Fix icon issues

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#455]
We are still seeing some issues with icons on the static topic pages.

![Skjermbilde 2021-09-06 kl. 11.53.20.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/12e4b23b-f5f3-4575-9377-8b2995b65cac)

**Comment by wenche** [comment]
![Skjermbilde 2021-09-20 kl. 09.15.47.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/edb94bce-7bf6-4ea2-bf9a-18a04fb28198)
Looks good. :)

@padms It would be nice with a comment describing what you did beyond the linked commit.

**Comment by padms** [comment]
This a [bug](https://github.com/vercel/styled-jsx/issues/589) in styled jsx, as a workaround , converted the equinor-icons.css to scss and then used unquote to set the glyph like[ here](https://github.com/vercel/styled-jsx/issues/589#issuecomment-579113530)
