### ISSUE TITLE
Highlighted, big number is "0"

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#456]
In the arrays with text and svg, we probably miss some Javascript as the highlighted  numbers are showing "0". Example URL [/what-we-do/exploration](https://energyvision.app.radix.equinor.com/what-we-do/exploration)

![Skjermbilde 2021-09-06 kl. 12.06.28.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/902da635-c395-4a54-b52c-2949a0a3ee38)

**Comment by nilsml** [comment]
First step at enabling javascript for the archived pages
