### ISSUE TITLE
Text wrapping issue with "Read more" button

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#457]
The "Read more" button doesn't look too good at breakpoints between 750px and 1650px as the text wraps on two lines

![Skjermbilde 2021-09-06 kl. 12.19.50.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2d0e75ce-0a4a-4d4d-af9c-39b3ecc9cf7e)

**Comment by padms** [comment]
Reduced padding left and right for the button in list component.

**Comment by wenche** [comment]
LGTM :thumbsup:
