### ISSUE TITLE
SVG icons in text/icon arrays are too big

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#458]
Static version
![Skjermbilde 2021-09-06 kl. 12.28.25.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/4d626191-e3e2-4bf2-a4d6-846acc0008bb)

In production
![Skjermbilde 2021-09-06 kl. 12.29.29.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/15ad0d2e-f2a5-4170-8b65-f50491fb02ec)

**Comment by wenche** [comment]
@padms  It would be nice if you could add a comment to explain what you did to solve the issues for future references. :) 

As for this issue, the icons are still too big compared to production but I guess that's because of the fluid typography and the size of `rem` in the new solution? Doesn't look to bad, so I think it's OK.

**Comment by padms** [comment]
To reduce the size, we are just dividing the existing value by 1.6 ( as that looks good in all screen sizes). We chose to end up diving with a constant value of 1.6 because we would end up modifying a lot.
