### ISSUE TITLE
Find a way to populate getStaticPath for the static AEM pages

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#459]
WIth Next.js and static content with dynamic routes, we'll need a way to fetch the URLs that should be generated. See [Next.js documentation](https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation).

For Sanity served pages, we have [a query that fetches every slug ](https://github.com/equinor/energyvision/blob/db7c35852ae31bf0d1af813828b1ffa464e63417/web/pages/%5B%5B...slug%5D%5D.tsx#L144)for the available locales.

With the archived 2016-2018 news, we [read the list of urls from file](https://github.com/equinor/energyvision/blob/db7c35852ae31bf0d1af813828b1ffa464e63417/web/pages/news/archive/%5B...pagePath%5D.tsx#L97), the same list that is used for the `/index.tsx` route. 

We need a way to solve this for the pages with static AEM content as well.

**Comment by SvSven** [comment]
We may be able to get this directly from the blob storage - otherwise we could maybe make an azure function that takes a top-level route (for example /careers) and then returns all entries that are in the storage with that path.

That may be useful to have for other stuff as well.

**Comment by wenche** [comment]
We will also need to see how many of the pages we should generate at build time. Are some of them more important than other? Like the ones in the menu og the most popular one according to analytics

**Comment by wenche** [comment]
We need to figure out what exactly we want to do here and find the sweet spot. We will probably know more after the workshop of Thursday.

**Comment by nilsml** [comment]
Keep on hold for now. Performance enhancement that could be worth while doing at some later point.
