### ISSUE TITLE
Make  3. level urls work

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#460]
![Skjermbilde 2021-09-06 kl. 12.50.47.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/98db5534-1bf8-4ea9-9abf-176ba9261d8e)

Url's on the 3. level doesn't work yet

Example https://energyvision.app.radix.equinor.com/what-we-do/partner-operated-fields-in-norway/marulk

**Comment by wenche** [comment]
Probably mostly related to overlay pages

**Comment by SvSven** [comment]
Third level pages are only used for the purpose of panel pages as far as I know, and won't be used in the future.
If we can't get the old javascript to run without any issues then another option is to just have the links/buttons to open these panel pages link to the URL and have it be a normal content page.

**Comment by padms** [comment]
Removed the magnific-popup styles out the 'legacyStyles' scope, because of which the css styles were not applied properly.

**Comment by wenche** [comment]
Maybe you can take a look at this @nicholas-haggerty ?

**Comment by nicholas-haggerty** [comment]
Seems to be working as expected on the links I tested with. Both from buttons on a topic page and the horizontal menu.
