### ISSUE TITLE
Scope global CSS element rules from legacy css

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#462]
CSS rules on element level affect the menu (and footer)
 ![Skjermbilde 2021-09-07 kl. 12.53.30.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/07e72ce9-b034-4ff8-bd4d-1372079bdcc5)

**Comment by SvSven** [comment]
@wenche this is ready for review

Legacy CSS rules are now nested under the `.legacyStyles` class - which has been added to the container div for the static topic pages and news archive.

**Comment by wenche** [comment]
Looking good!

For the record, I'm not a fan of camel casing naming convention for CSS class names, but I'll let it go. For this time. :p

**Comment by SvSven** [comment]
🐫

**Comment by wenche** [comment]
The version of the CSS legacy styles in radix is wrong/too old. Why? Should be solved by #477

**Comment by wenche** [comment]
Because the github action was not triggered by changes in `package.json`.

Wenche, on behalf of Sven van ProblemSolver Steenis.

**Comment by vnys** [comment]
> Looking good!
> 
> For the record, I'm not a fan of camel casing naming convention for CSS class names, but I'll let it go. For this time. :p

I think camelCasing PascalCasing and hyphens all have their purpose in classnames to denote meaning. `.ComponentClass ` `.descendantClass` `.descencantClass-someModifier` etc. Underscores on the other hand 🤮

**Comment by SvSven** [comment]
I admit to not have put much thought into it 😬
Personally don't really like hyphens as it doesn't play nice with double clicking the class name to for example change or see all occurrences. Granted, not needed often but eh 🤷‍♀️
