### ISSUE TITLE
Implement a caching policy for DAM content

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#464]
![Skjermbilde 2021-09-07 kl. 14.07.18.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/98f0e5d0-9165-4fca-ac49-0e24b6479a70)

Currently not enabled for images in blob storage. Either set up CDN or run script to enable caching for each file.

**Comment by SvSven** [comment]
The AEM assets are copied to and hosted by the azure blob storage, same as the JSON content.
We'll need to set a caching policy for the entire blob storage, however this is not something that is easy to do at the moment. We could solve this by adding a CDN however.

**Comment by nilsml** [comment]
We have added a CDN for the static content. Could you check if the issue has been resolved by this @wenche?

**Comment by fernandolucchesi** [comment]
I believe we can close this
