### ISSUE TITLE
Test performance

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#470]
We should run some tests and see how the static pages affect performance

**Comment by wenche** [comment]
Desktop 2 AEM, 2 Sanity

![Skjermbilde 2021-09-09 kl. 10.59.33.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/122801d7-789f-4a0c-9cad-8710c9699ce0)
![Skjermbilde 2021-09-09 kl. 11.00.35.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/144b1080-b882-4ed4-8f65-6a16531f2f1d)
![Skjermbilde 2021-09-09 kl. 11.07.34.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2b5f1be2-0d5d-483b-a474-dc1b6ff9f3e7)
![Skjermbilde 2021-09-09 kl. 11.10.23.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d183f0b6-8534-4f46-ba6e-e6d67d44139b)

**Comment by wenche** [comment]
Mobile

![Skjermbilde 2021-09-09 kl. 11.20.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f3252c2f-34c2-4687-b882-9e33d3ee80fb)
![Skjermbilde 2021-09-09 kl. 11.23.19.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d02375cd-2ca9-4ff1-b9f3-e3d1affa65dd)![Skjermbilde 2021-09-09 kl. 11.25.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f97f43e6-61c6-4055-90a6-0e09ff748d43)
![Skjermbilde 2021-09-09 kl. 11.25.35.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b7b3d487-fcd6-4cb3-831b-9b2dbc2ace7f)

**Comment by wenche** [comment]
Bundle analyze

server
![Skjermbilde 2021-09-09 kl. 11.28.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/de153921-1944-4102-a0e4-bb8c3603f561)
client
![Skjermbilde 2021-09-09 kl. 11.28.24.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/4fb6d63c-87f6-44b4-96c1-9396f4fb5118)

**Comment by wenche** [comment]
To summarise,  yes the new setup with static pages does impact performance (as expected). Especially the main thread work

**Comment by nilsml** [comment]
@nilsml to bring this up with the Radix team

**Comment by wenche** [comment]
Top 3 performance issues (critical) atm flagged by Sitebulb:

- Lack of cache from the DAM image archive (#464)
- Some pages (10 in this audit) are huge (>5Mb)
![Skjermbilde 2021-09-16 kl. 14.11.55.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/0e46e86d-7d91-44d9-bd5a-cb4c24f1c0d2)
- https://energyvision.app.radix.equinor.com/en/what-we-do/exploration is flagged with a render blocking issue

**Comment by wenche** [comment]
Latest audit (for future reference)
### Grafana
![Skjermbilde 2021-09-16 kl. 15.19.17.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/4ecfda20-5e6f-434b-9c64-130b83c1b3d2)
### Sitebulb
![Skjermbilde 2021-09-16 kl. 15.20.42.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/103b8525-3804-49e7-b21c-e5220e77cd13)

**Comment by wenche** [comment]
The EDS packages have a huge impact on the client side bundle size. We have done some testing and summarised our finding in the corresponding EDS issues https://github.com/equinor/design-system/issues/1539 and https://github.com/equinor/design-system/issues/1043
