### ISSUE TITLE
Find a better way to include Azure analytics 

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#472]
[This commit](https://github.com/equinor/energyvision/commit/881c43f06cdf6d102fd6d3551bc5c2c31a2b19ab) removed the MS application insight because it had such a high impact on first JS shared by all

See the difference using Next.js's CLI
![Skjermbilde 2021-09-14 kl. 21.40.48.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/29ca4dab-36c2-4f84-87bf-d72dc4f88466)
![Skjermbilde 2021-09-14 kl. 21.40.26.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/0a6749bc-4c67-45b8-8f7a-a12e49b11cff)

Look into a better way to include this.

**Comment by SvSven** [comment]
Relevant issue on the application insights repo: https://github.com/microsoft/ApplicationInsights-JS/issues/1076

**Comment by nilsml** [comment]
Related to #711

**Comment by wenche** [comment]
We need to discuss what we need here

**Comment by wenche** [comment]
Had to remove the previous work due to pnpm v7 peer deps issues. Adding [a link to the commit](https://github.com/equinor/energyvision/commit/7c895f34c490e857d39df3a7e478b7896334f77e) here for future reference. #bekindtofutureself 

We need to investigate this furter, and it might not even make sense to use Azure analytics

**Comment by SvSven** [comment]
Do we still need/want Azure Insights? Especially now that we are working on enabling Dynatrace

**Comment by fernandolucchesi** [comment]
#1309 Decide on what to do monitoring-wise
