### ISSUE TITLE
Fix missing images

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#473]
Some pages are missing some of the images, like https://energyvision.app.radix.equinor.com/where-we-are

![Skjermbilde 2021-09-17 kl. 07.27.36.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/87e2df0f-b8e9-462e-bec8-3ca89e1c66ec)

**Comment by padms** [comment]
These images had % in their path. https://envisstoragedev.blob.core.windows.net/equinor-archive-content/content/dam/statoil/image/where-we-are---carousel-16-9/Angola%20landscape.jpg.transform/large/image.jpg

So % is replaced with %25 in the page.

**Comment by wenche** [comment]
Looking good :thumbsup:
