### ISSUE TITLE
As editors we need to use Sanitys DAM to host PDF/EXCEL and certain illustration files (JPG/SVG)

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#475]
## Acceptance criteria
1. Editors can easily upload files to use in templates
1. Need to have a way to structure the assets to make it easy to find for editors when they are bot saving/uploading and navigating to the relevant file(s)
1. Sanity has smart folders. How does this work in practice? Tagging? Editors should have ability to fine grain 'file structure'

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nilsml** [comment]
Set up a meeting with Sanity to figure out what is possible

**Comment by nilsml** [comment]
Try out media plugin

**Comment by meols** [comment]
@adneforslund @wenche 
Comments from further testing:
- No warning when uploading a new file with the same file name as an existing file – should be able to replace with a new updated file, or choose to keep both, or as version
- File name on hover in preview doesn’t show the uploaded pdf's filename e.g. sustainability-report-2020-pdf https://cdn.sanity.io/files/h61q9gi9/production/ef021e175cd8561245314bf1fcf264d4e8a57bd3.pdf
- Seems like file name isn’t what’s unique, but Sanity gives a new “internal url” per upload no matter what the file name is. Can we then replace a file?
- Uploading in an article you don’t choose where to upload to (smart folder) and can’t see other files when uploading (e.g. editors wouldn't know if the file already exists, leading to duplication)
- No version history or upload version
- Drag and drop not working – even if it seems to be possible
- No pdf preview – which is useful both for adding description and confirming it’s the correct file
- No published time, only Last updated
- No info on which user that has uploaded/published
- No options to publish a file from Media view (nice to have, useful when replacing a file that is in use on several pages)

**Comment by nicholas-haggerty** [comment]
closing and created #536
