### ISSUE TITLE
Pull meta data from images on Brandmaster

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#478]
When images are uploaded to Brandmaster, the editors add some meta information. In #337, the fields we can pull where identified to be

- title
- description
- credit line

1. Which of these fields are relevant for us?
2. How can we attach them in Sanity
3. How could we access the in the web
4. Update image fields (caption/attribution/??) accordingly

**Comment by SvSven** [comment]
The brandmaster plugin is currently set up to pass along the following fields from Brandmaster:
- title
- description
- credit (photographer)

These are, to my knowledge, the only such meta fields that Sanity supports/accepts for a custom asset source.

See: https://github.com/equinor/energyvision/blob/main/studio/plugins/asset-source-brandmaster/src/BrandmasterAssetSource.tsx#L40-L55

These fields can be accessed in GROQ from the asset document, but need to be explicitly referenced.
Example:

```
heroFigure.image.asset-> {
    title,
    description,
    creditLine
  },
```

Both the description and the photographer can definitely be useful, as we currently have our own fields for a caption and image credit. So the question is how can we use these values from Brandmaster as there are some questions and potential problems still:

1. The fields are not localized, only available in English. Having an English caption on the Norwegian language site would be weird and out of place.
2. Not every image will be selected from Brandmaster, so we can't just remove our own input fields
3. Similarly, can we trust that every image from Brandmaster has these values?
4. I'm not sure if we can automatically populate our input fields for caption and credit when selecting an image. If we can though, then that would probably be the best option.
5. What do we do if for example the description on an image gets updated in Brandmaster? There is no "link" between the asset on Brandmaster and the one in Sanity, as we just upload a copy of it into Sanity.

**Comment by SvSven** [comment]
Re point 4: should be possible with a custom input component according to feedback, waiting to hear back from Sanity with an example.

**Comment by SvSven** [comment]
With #443 likely being solved, this can be worked on again.

**Comment by nicholas-haggerty** [comment]
@nilsml Should see where we can fit this in to forthcoming sprints. If editors are to start working on live pages, be good to have this in place.

**Comment by SvSven** [comment]
It might involve a bit of investigation and development work to get it right, because apparently pre-filling fields when you for example select an image is not something Sanity supports out of the box. We have a dialog going with some potential solutions, but we haven't spent more time trying them out yet.

That being said; might be useful functionality to have for other integrations as well.
