### ISSUE TITLE
Supply sitemap

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#483]
**In order to comply with SEO best practice, we need to supply a sitemap** 

## Questions
1. Is it needed
1. If yes; when is it needed
1. Cleanup when replacing static pages with dynamic

## Acceptance criteria
1. [Criteria 1]
1. [Criteria 2]

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by nilsml** [comment]
@nicholas-haggerty to check if this is needed for going live

**Comment by nilsml** [comment]
Related to #459

**Comment by wenche** [comment]
Closed, duplicate
