### ISSUE TITLE
Create "add to calendar" functionality for events

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#484]
Create a button for events that downloads an .ICS file based on the event details to allow users to add that event to their calendars.

**Comment by SvSven** [comment]
Current add-to-calendar button on production site downloads a .ICS file with event information for adding it to the calendar. Not sure if these files are created on-demand by AEM or if they are created when a new event is created.

Feedback from PO is that this type of functionality is good enough for the new site as well.

**Comment by adneforslund** [comment]
https://github.com/nwcell/ics.js

**Comment by BirteThornquist** [comment]
When a specific time is not yet specified for an event, it should still be possible to add it to the calendar as a full day event. When the time at a later stage is specified, the calendar event is updated.

**Comment by nicholas-haggerty** [comment]
@BirteThornquist @SvSven Looking good Sven, nice work One comment relating to date. For Timezone, is it possible to set Europe/Oslo as default? It will be 90% of times I guess, and editor has to manually scroll down to select it, which added at least 7 seconds to my day!

On preview, the spacing for the text in the top banner looked a little off compared to the Figma sketch. The date seems too tight to the header (and further away from the time). 
We also had date/time/event type in Green. Maybe these are for another issue through?

**Comment by SvSven** [comment]
> @BirteThornquist @SvSven Looking good Sven, nice work One comment relating to date. For Timezone, is it possible to set Europe/Oslo as default? It will be 90% of times I guess, and editor has to manually scroll down to select it, which added at least 7 seconds to my day!
> 
> On preview, the spacing for the text in the top banner looked a little off compared to the Figma sketch. The date seems too tight to the header (and further away from the time). We also had date/time/event type in Green. Maybe these are for another issue through?

This technically relates to #599 (but the issues are a bit confusing at the moment)
Tagging @fernandolucchesi since he is working on the actual date and time implementation

**Comment by SvSven** [comment]
@nicholas-haggerty @meols 

For this issue specifically (the "add to calendar" button); the button will only show if the event has a date (which should be required in Sanity) and will only show if it is an upcoming event (end date and time is in the future from this moment). It wont show if the event is in the past, which is an improvement over the current equinor.com solution.

Clicking the button prompts the download of an .ICS file.
The name of this file is the title of the event. Opening it with for example Outlook opens a window to create a new calendar event. The day and time _should_ be correct based on the user's timezone - I've tested it a couple times and it works for me, but timezones are notoriously annoying to work with 😅

Currently the imported event just has the title of the event and the date, nothing more. Does it need a description or anything like that as well?

**Comment by nicholas-haggerty** [comment]
@SvSven I dont think we need description. This is good (enough) how it is. I tested with a couple of different time zones set and it worked correctly for me. Not sure how time we should put into testing this but maybe @meols wants to go through when she back on Monday
