### ISSUE TITLE
Investigate how to cache static generated pages

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#487]

**Comment by wenche** [comment]
See e.g. https://www.smashingmagazine.com/2021/04/incremental-static-regeneration-nextjs/#isr-not-just-caching

**Comment by wenche** [comment]
https://nascentdigital.com/thoughts/how-to-deploy-next-js-without-vercel <-- Features a paragraph on CDN near the bottom

**Comment by wenche** [comment]
I don't think I'm able to do so much more here :woman-shrugging: Have read through the Internet, didn't find that much of interest beyond ^ . Next (pun intended) step will probably be to test this out with a CDN on Azure/Radix. 

It's the content of the .next/server/pages that would somehow be nice to persist between builds and for horizontal scaling at k8s. But how will this affect revaildate? It might be possible to map this folder to some storage in Azure somehow in k8s, but which consequences will it have...? If we somehow find a sweet spot between the number of prebuilt pages during build process, and ISR pages that would probably be 1. thing. Shouldn't do too much premature optimisation either, especially prefetch a lot of the pages in the background as well...
