### ISSUE TITLE
As an administrator I want to set access controls for the studio so that I can control who has rights to view/edit specific content

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#493]
Not every user needs/should have access to everything inside the studio. Some options should be restricted to specific users, like for example the routing, menu, or content with specific tags (investor content, careers, etc). Similarly editors for the satellite sites do not need access to the global site and vice versa.

Investigate whether AD groups can play a role in this as well.

## Acceptance criteria
1. Can create and manage groups with different levels of access
1. Can add/remove users from different access groups
1. Can set read, write, delete access for specific menu items and content in the studio

**Comment by nilsml** [comment]
This will be handled within the Sanity admin dashboard.

**Comment by nilsml** [comment]
But also we need some way of mapping roles to content!!

**Comment by nilsml** [comment]
Not sure if this is relevant anymore. We should discuss this and see if what we have through Sanity management console is enough.

**Comment by fernandolucchesi** [comment]
This was handled by https://github.com/equinor/energyvision/issues/939
