### ISSUE TITLE
Trigger rebuild of web when menu or footer data is created/updated

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#497]
## Acceptance criteria
1. When menu or footer documents are updated (published), the menu/footer data is updated on all pages in the web as well.
2. Should not trigger a rebuild for drafts

**Comment by SvSven** [comment]
Using hidden tokens in the webhook system is something that is on their radar, but not likely to be implemented soon. Suggestion for fixing this is to, for example, use a webhook in Azure functions that stores the secret and acts as a middleman between Sanity and GitHub.

**Comment by nilsml** [comment]
Wait until Azure function for search is up and running. Use that as a template.

**Comment by fernandolucchesi** [comment]
Do we need this at all? Why should we rebuild after updates? @equinor/envis-devs

**Comment by SvSven** [comment]
Updating the menu or footer in Sanity did not trigger an update in the web, meaning there could be discrepancies between pages where the menu/footer is outdated or wrong, especially when navigating between pages.

Not sure if this is still the case.

**Comment by nilsml** [comment]
A lot of things have bee reworked after this issues was created. Close this one and create new issue if this is still the case.
