### ISSUE TITLE
Correct TableV2 styles ,Accordion and Basic Accordion animation  and styles.

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#511]
https://www.equinor.com/en/where-we-are/russia.html : Basic Accordion
https://energyvision.app.radix.equinor.com/careers/frequently-asked-questions : Accordion 
https://energyvision.app.radix.equinor.com/investors/events-and-presentations : TableV2

**Comment by padms** [comment]
Pending css publish to npm.

**Comment by nicholas-haggerty** [comment]
@padms looks like this one is fixed now. Closing
