### ISSUE TITLE
Implement cookie policy for iframe component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#516]
- The iframe component needs to have an input field to select the cookie policy to load the iframe like in AEM.
  - None (default): load the iframe regardless of accepted cookies
  - Marketing: only load iframe if marketing option is accepted
  - Statistics: only load iframe if statistics is accepted
- The iframe component should not be loaded until the relevant cookie policy has been accepted by the user.

**Comment by nicholas-haggerty** [comment]
@SvSven is this blocked as we waiting for cookie bot to be implemented? Just wondering if we will start building pages and using the iframe/YT route to solve video (until MUX is working) it would be good for editors to choose the cookie user consent. Currently we have:
NONE
Marketing
Statistics

With NONE as the default.

**Comment by nicholas-haggerty** [comment]
With that route in mind, we should also add a (optional) Description/caption field to appear under the iframe to for example introduce the video to the audience...

**Comment by SvSven** [comment]
This is blocked by the cookie bot integration yes, that currently only works for the static pages.

**Comment by nilsml** [comment]
Needs design. We may copy what we have today.

**Comment by Toetsed** [comment]
Hi guys, I see you are making adjustments to the Cookiebot template design. 
We created some custom designs for Cookiebot. Perhaps these are of help for you? 

Thanks!

Ed

[https://www.cookieinfo.net/en/cookiebot-custom-banner/](https://www.cookieinfo.net/en/cookiebot-custom-banner/)

**Comment by wenche** [comment]
We need to improve the design for the enable cookies component used by iframes.
Before:
![Skjermbilde 2022-01-17 kl. 09.46.44.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b4192564-fcd5-4531-a6f4-b8b5ae88a3e4)
Work in progress version
![Skjermbilde 2022-01-17 kl. 09.47.20.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/e0e9ef8d-6fcf-493c-a8a6-3d796ab0f0f1)

@BirteThornquist  Let me know when you are ready for implementing the final version

**Comment by wenche** [comment]
Updated according to the design
![Skjermbilde 2022-01-18 kl. 14.48.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/cd8cc05c-ca1a-45f3-89ef-f965bef9ca4a)

**Comment by wenche** [comment]
Atm we don't have a natural place for where this consent text and corresponding translations should live. Waiting for #359

**Comment by BirteThornquist** [comment]
Good job @wenche! LGTM!

**Comment by padms** [comment]
Let the value for cookie policy option in iframe be default none. ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/fc30f71a-98c6-46a4-8a27-8eb00368d852)

**Comment by padms** [comment]
Also the iframe is hidden even if all the cookies are accepted when navigating from one page to other.

**Comment by SvSven** [comment]
I've been testing with this here: https://energyvision.app.radix.equinor.com/sustainability/mettes-testpage
However I can't reproduce the problem, I've tried all 3 of the different options (none, statistics, and marketing) and they all seem to work as expected.

Not really sure where the `null` value is coming from here, it should default to `none` in the component if the value isn't set; and I also added `none` as an initialValue in Sanity when creating a new iframe 🤔

**Comment by wenche** [comment]
@padms  Can you retest?

**Comment by SvSven** [comment]
I've wrapped the iframe's cookie policy value in a coalesce function to default it to `none` - in theory we don't need this since the component handles that, but doesn't hurt to have just in case.

**Comment by padms** [comment]
https://energyvision.app.radix.equinor.com/careers/apprentices this page has multiple Iframes , which his hidden when we navigating from another page to this one ...

**Comment by SvSven** [comment]
I see, I think I found the problem. The consent is all fine, but the cookiebot sets the display property to "initial" when the content should be shown - which conflicts with the iframe container as that requires it to be "block".

Have added a wrapping div dedicated to the cookiebot class, which should solve it

**Comment by padms** [comment]
Now its solved :)

**Comment by wenche** [comment]
@SvSven Did you fix the FF issue with the svg?

**Comment by SvSven** [comment]
Looking into it, seems to be a problem with the SVG element having its width and height set to auto instead of a fixed value.
Trying to find a bug report or similar to find some more info.

**Comment by wenche** [comment]
@SvSven Just pushed a fix

**Comment by SvSven** [comment]
Looks good on Edgium:

![image](https://user-images.githubusercontent.com/7661362/150750389-10d63294-9cb6-4c18-b3fc-6a56e8343198.png)

Looks good on Firefox:

![image](https://user-images.githubusercontent.com/7661362/150750478-5b40cb08-c8d2-47d2-91a8-b778b746626d.png)

Can't test Safari

**Comment by wenche** [comment]
I have already verified it in Safari np 👍
