### ISSUE TITLE
Verify tag information in news articles.

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#522]

**Comment by padms** [comment]
Tag information is available in the page content as well as the search-metadata.json in the azure container.

**Comment by nicholas-haggerty** [comment]
@padms Not sure how to test or approve this? Can you supply link? Or happy to have a short meeting/demo too.

**Comment by nicholas-haggerty** [comment]
@padms ok I have gone through several articles now and seems to be fine so closing
