### ISSUE TITLE
Minimize flicking because of scrollbars

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#524]
See if it's possible to minimise the jumping/flicking effect caused by the scrollbar when the menu is opened/closed.

E.g. DNB does something here to smoothen things out

**Comment by SvSven** [comment]
The problem was because our dropdown/modal was using `position: fixed` with `right: 0`

Fixed by using provided classname from the `react-remove-scroll` package: https://github.com/theKashey/react-remove-scroll#positionfixed-elements

**Comment by wenche** [comment]
Works pretty well, expect for when we have a scroll inside the menu container. But that should be less of a problem for most screen sizes when the menu restructuring is done.

![Skjermbilde 2021-10-15 kl. 09.36.37.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/de4c7de8-9ff9-40ef-b332-454e5b87ad9c)
