### ISSUE TITLE
As a editor I want to be able to choose the type of articles to promote in a fixed list component

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#535]
Link lists/Cards

**Fixed list:**
Traditionally the amount is 3. Should we expand to up to 4 to accommodate wider screens?
On Mobile should component be swipeable as today? Optional?
Editor selects link internal link they wish to promote per item
Display is pulled from the page linked to (image / title / ingress - limit character count? Where is this pulled from? / Animated red arrow) 
Fixed size for desktop and mobile? With the Ingress character limitation?
Whole card is clickable
Component available on TOPIC template

**Comment by BirteThornquist** [comment]
Covered by #559
