### ISSUE TITLE
As a publisher I want it to be easy to find the Topic content to edit

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#541]
The list of Topic content documents in Sanity Studio will be long. One way to make it easier for publishers to find the right document could be to add different ways of sorting the list using the [`orderings` functionality from Sanity.](https://www.sanity.io/docs/sort-orders) Another way is to make the preview used in the document list as good as possible. We should probably use both.

1. Discuss and identify which field are candidates for a custom ordering
1. Currently it's just the title and image that is used as preview. What else makes sense here?
1. Do we want tags here as well? Like `energy` `careers`. 
1. What about smart folders/grouping? Like `All topic content` `Drafts` (the one that's not assigned to a route) , based on tags +++

Ordering on title, created and updated
Not much content to preview except Title and image

**Comment by BirteThornquist** [comment]
Is this good to go for now @nicholas-haggerty without the tags?

**Comment by nicholas-haggerty** [comment]
Yup. I think we have two good ways into the topic content. 
1. Search
2. Topic routes

Closing
