### ISSUE TITLE
Investigate Brandmaster REST API for Sanity integration

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#543]
We want to use the Brandmaster web plugin iframe for the integration into Sanity, and Brandmaster also recommends this approach - however we have a SSO issue that is preventing us from using this at the moment.

Brandmaster will look into fixing it but they are not sure what the problem is, so we should look into the REST API documentation to get an idea of how much time/effort it would be to create a custom asset source plugin from the ground up using their API so that we have a plan B.

According to Brandmaster the main challenge here would be to replicate the search and filter functionality you get "for free" with the web plugin - but the API does provide far more options and is a more powerful tool.

**Comment by nicholas-haggerty** [comment]
@SvSven OK to close this now right?

**Comment by SvSven** [comment]
Depends on the outcome of the DAM project I suppose?

**Comment by SvSven** [comment]
This is no longer relevant
