### ISSUE TITLE
As a publisher I need consistent validation messages to make it easy to avoid mistakes

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#549]
1. Align tone of voice in the validation messages and make them as descriptive as possible
1. Add missing validations
1. We use the char counter concept some places, should this be used more?
1. Make a good separation of warnings/errors which one should be used where/combination of both

Example of bad and inconsistent validations
![Skjermbilde 2021-10-25 kl. 09.13.24.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ea322e78-1ce2-429a-bb9f-f098745aaebb)

**Comment by nilsml** [comment]
Related #750

**Comment by nilsml** [comment]
Careful to make fields madatory as that could cause problems for existing content

**Comment by nilsml** [comment]
Create sub-tasks that can be prioritized

**Comment by fernandolucchesi** [comment]
Not relevant anymore
