### ISSUE TITLE
Use a simple rich text editors for titles instead of the plain text input

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#550]
At some point we need the option to do things like highlighting parts of the text by colour (or add hard line breaks :grimacing: ). To be able to do this, we need to swap the simple text input by a really basic rich text editor for titles

1. Which titles should use this
1. It will probably make sense to not actually add style options at this point, but just prepare the ground for that (we talked about theming way back)
1. 

The needs are yet to be discovered, but without the rich text editor we can't do things like this.

**Comment by SvSven** [comment]
@wenche ready for checking 🕵️‍♀️

**Comment by wenche** [comment]
@SvSven  What about the news title?

**Comment by wenche** [comment]
This was a huge one! :sweat_smile:

### Titles with rich text editor
- Topic page banner title
- Text block
- Teaser
- Accordion
- Iframe

### Still plain text inputs
- Icon & Text
- Promo tile
- Quote (has no title)
- News title
- Full width image (has no title)
- Image (has no title)

**Comment by wenche** [comment]
And to clarify, this change is about the future feature of highlighting text parts in titles. Like for example ![Skjermbilde 2021-11-01 kl. 10.41.35.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f6fb2a49-b33c-4c01-a086-51a3e105631c)
