### ISSUE TITLE
Create REMIT table component

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#558]
## To do
- [ ] Create the REMIT TABLE in the web and studio.
- [ ]  Contact REMIT UMM TEAM to set up test job to push json to azure container.
- [ ] UI/UX corrections.

**Comment by nicholas-haggerty** [comment]
@padms Reach out to @meols if you need any assistance or contact names on this task

**Comment by padms** [comment]
Pending confirmation, whether we need REMIT after January or not.

**Comment by nicholas-haggerty** [comment]
@padms Hi. Sorry I have heard back and unfortunately they would still like to have REMIT as a feed on equinor.com. Could you continue on with this task please

**Comment by nilsml** [comment]
Waiting for #590

**Comment by padms** [comment]
@wenche Should the [table component](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/345) be ready for this?

**Comment by padms** [comment]
@BirteThornquist  [this](https://www.equinor.com/en/what-we-do/remit.html) is the page in equinor.com for the REMIT table. There are two buttons at the top of the table, to filter the content. Let me know if you would provide a sketch for this.

**Comment by padms** [comment]
Yet to get WBS code for REMIT UMM team to start the work.

**Comment by nicholas-haggerty** [comment]
@pradeepvenurao I asked about this a week ago? Any news?

**Comment by pradeepvenurao** [comment]
@padms please let me know the name of the person in UMM team.

**Comment by padms** [comment]
RITM2347346  created for the task.

**Comment by nilsml** [comment]
Waiting for this issue to be verified when the REMIT team has done their job.

**Comment by padms** [comment]
Production remit data is automatically updated in Azure container. Remit table shows production data

**Comment by padms** [comment]
Created #726  for UI corrections.

**Comment by padms** [comment]
@meols Could you please review this? You could verify this component in preview mode without publishing. Or I can help you verify this in my local.

**Comment by meols** [comment]
Thanks @padms - I have added a few comments to the screenshot below. The same comments apply for both Unplanned and planned events. Please let me know if you have any questions. ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/4b224b2e-2493-4071-b2a0-988bf0772ba2)

**Comment by padms** [comment]
@meols I created a separate issue #726 for address UI.

**Comment by padms** [comment]
To test here : The REMIT data is same as in production.  @meols

**Comment by meols** [comment]
@padms @nilsml - the data I see are the same as in production. Do we have a way to test if updates are showing up? (if we are using the real data and not test data)

**Comment by nilsml** [comment]
Create card for follow-up and test when Remit data is updated. Then close this issue.

**Comment by padms** [comment]
Created #796 to follow up. So closing this
