### ISSUE TITLE
As a editor I want to be able to choose the type of articles to promote in a NEWS list component

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#559]
**News list:**
Traditionally the amount is 3. Should we expand to up to 4 to accommodate wider screens?
On mobile should component be swipeable as today? Optional?
Editor links to news? And the component automatically displays the latest 3/4?
Editor can define tags to display (EG News list on UK page, editor could select 'UK' tag, so latest UK news is always displayed)
Display is pulled from each news article (image / date / title / ingress - limit character count? Where is this pulled from? / Animated red arrow)
Fixed size for desktop and mobile? With the Ingress character limitation?
Whole card is clickable

**Comment by nicholas-haggerty** [comment]
@wenche Testing on this page: https://equinor.sanity.studio/desk/topicContent;1a8d1ece-0252-410f-9d86-4774852d2be6

Adding coloured background. When previewing, the colour show for a second but disappears.

**Comment by wenche** [comment]
With this promotion? 

![Skjermbilde 2021-11-16 kl. 10.49.22.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/1f6908ce-43f8-40ef-9919-93757ff7ddc4)

**Comment by nicholas-haggerty** [comment]
No news one

**Comment by SvSven** [comment]
Seems to work fine when I test it locally, but for the hosted studio I can see it as well; it's either very slow to change or doesn't change at all.

Looks to be happening with other components as well, so this seems like an issue with the background colour component and/or preview in general.

**Comment by nicholas-haggerty** [comment]
@SvSven Should we just close this one and create an issue for that specific problem? Everything else seems #amazing

**Comment by wenche** [comment]
Yes, we probably should and address this issue with Sanity at some point, just need to do some digging and figure out what/where. To me it seems like the preview has some issues, it's also super duper slow locally. 

We found another one we should address as well, the text is inverted for the darkest background even if the card remains white. Could create an issue for that one as well
