### ISSUE TITLE
As a editor I want to be able to promote people in a list/card component

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#560]
A type of the promotion component available on TOPIC and EVENT template.
The component has a title and can be styled with a background color.
One or more cards can be added to the component.
If only one card added, the web presentation of the card will be in landscape style, for more than one, the card will be  presented in portrait style as specified in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3290%3A70695).
The cards will be stacked in the web according to screen size.

The people card:
Editor can add image of person
Editor can add Name
Editor can add Title
Editor chooses between:
1. Adding an internal or external link
OR
2. Adding contact details (email address on first row. Tif on second) Content should be clickable so user can email or call (if on mobile)

**Comment by wenche** [comment]
We have done quite a lot of work for the portrait version and started on the landscape version. Need to figure out how spacings should behave when there are so many variations of the content (lot of optional information). The anchor links for CVs need to wait until that is solved by #346
![Skjermbilde 2021-11-19 kl. 16.52.45.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a604ad32-095b-4962-9760-2005c7e1de8e)

Remaining tasks
- Add link label/aria-label for CV button
- Finish the landscape version for one people
- Update storybook...
- Final adjustments

**Comment by nicholas-haggerty** [comment]
@wenche great work so far!

**Comment by wenche** [comment]
This doesn't feel 100% right, maybe we can take a last refactoring and simplifying round after we have done the event card. Might be a good idea to refactor the list of the Promotions itself to another component, to make it easier to reuse some logic in the event template for @SvSven ? And the landscape version is not optimal yet, but the event card is so different

**Comment by wenche** [comment]
@BirteThornquist Let's look at this tomorrow/when you are working on Envis

**Comment by wenche** [comment]
TODO
- Smaller images on mobile (~120-150)
- Add width restrictions for title and ingress (leftover from promotion web issue)
- Left align text on portrait
- Only center on the y axis for portrait
- Bonus: Single line for title and department for portrait

cc @BirteThornquist

**Comment by wenche** [comment]
@BirteThornquist  Let's take another look at this tomorrow morning :thumbsup:

**Comment by wenche** [comment]
/careers/professionals for examples (bottom) @nicholas-haggerty
