### ISSUE TITLE
As an editor I want to be able to promote EVENTS in a list/card component

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#561]
A type of promotion component available on Topic pages.
List of event cards will depend on events added in the event template. All events added in the event template where the date/time has not passed will show up in the list as default and will automatically disappear as soon as the event is over. It shall also be possible to manually pick events to promote from the event template list. It could be the editor wants to promote one event on the front page for instance. A nice to have will be the possibility to promote one event in the menu as well.

The event card will have to different styles; portrait and landscape. If only one event, the card will show in landscape style.

Content for the event promotion component
Editor can add a title
Editor can add an ingress
Editor can style the component with a background color

### The publisher can select
- All upcoming events, (like news, but all events not limited to 3)
- All upcoming events by selected tag/s (like tagged news, but all events and not limited to 3)
- Select one or a random number of events to promote (like topic pages, but without min/max)

**Comment by wenche** [comment]
The thing we have left to do with this issue is the filter for events in the past. That's because it's so convenient to have a couple of the test events from the past to test the even card. :)

But the cards are almost there, so let's add this tomorrow morning.

**Comment by wenche** [comment]
@nicholas-haggerty  As demoed on the meeting today https://energyvision.app.radix.equinor.com/careers/dont-touch-this-sven

We can go on for ever and ever on this, but I think this is good enough for now. :)

**Comment by nicholas-haggerty** [comment]
@meols Its an 'approved' from me. Had a chance to test?
