### ISSUE TITLE
As an editor I want to have a clear understanding of the content menu in Sanity, so that I can be able to quickly find what I need.

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#563]

**Comment by wenche** [comment]
Confirmed by Sanity that there's no way to do this now unless we want to drill down. :)
![Skjermbilde 2021-11-11 kl. 09.24.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/e910cc12-0d47-4261-9a3f-f8422742c6fb)

**Comment by nicholas-haggerty** [comment]
@wenche Should we just close this? Or keep it open in case the feature becomes available from Sanity? Low priority.

**Comment by wenche** [comment]
If it's not that important, I guess we could as well close this.
