### ISSUE TITLE
Make icons in footer as SVGa

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#564]
Conclusion from meeting was that we would rather like the SoMe icons as inlined SVGs as this will solve the lack of hover effects. The original approach was by using an image upload in Sanity and images in the web. The pros of this is that publishers can upload SoMe icons themselves. 

New decision
- Don't upload this as images in Sanity
- If a new SoMe platform is needed, this will involve a developer if an icon is needed. It's not a complicated task though.

**Comment by wenche** [comment]
Had several warnings with the images in the console during testing. While that was removed by adding the `unoptimized` flag, we could as well just do this now.

**Comment by wenche** [comment]
@BirteThornquist  The icons have different width and height inside the svgs, I have edited the SVG sources slightly but if we want to go all in one day, we could adjust them even more. :) This is nitty gritty details though

**Comment by wenche** [comment]
@nicholas-haggerty Added two different types of links inside the footer component, one for "ordinary" links and one for SoMe links. Hopefully the workflow is pretty self explanatory. I have updated the English version of the footer, but not the Norwegian one.

**Comment by nicholas-haggerty** [comment]
@wenche Great, this is looking really good.
