### ISSUE TITLE
As a publisher I want the latest news to instantly be available after publishing so that important time related articles are available at the right time

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#566]
Some articles are time sensitive and have to be published and available to the public at a certain time. This could for example be quarterly results or content that is agreed to be published at a certain time together with partners.

This means that we cannot/should not have any delay between when an article is published and when it is actually available on the website - for example delay by the build process.

## Acceptance criteria
1. TBD
1. TBD

**Comment by SvSven** [comment]
Need to verify how fast the newly published content on AEM is pushed to Azure, and how to handle the caching to ensure it's available as fast as possible.

**Comment by fernandolucchesi** [comment]
Not only happening to the latest news, but also other types of documents

**Comment by fernandolucchesi** [comment]
Set revalidate time to 60 seconds

**Comment by SvSven** [comment]
Based on a discussion on the Sanity slack channel, the problem looks like it might be related to the use of the Sanity CDN in combination with static page generation - which is causing is to fetch stale data.

One solution is to just disable the use of the CDN, but this might cause slower queries and higher data usage - which is not ideal. I think the best approach for the latest news component (and any other component that relies on 100% up to date data) is to look into a strategy with SWR, where we then use the non-cdn API https://swr.vercel.app/

**Comment by fernandolucchesi** [comment]
Tried to get it fixed #1286. Improvements were seen but not working as it should. Possibly fixed when migration to Next 13 app dir is done.

**Comment by nilsml** [comment]
Editors happy with current solution.
