### ISSUE TITLE
Equinor fonts load every time viewport resizes

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#570]
Step 1: open network console
Step 2: resize browser window
Step 3: see lots of requests for /fonts/equinor/EquinorVariable-VF.woff2
Step 4: ??
Step 5: profit

**Comment by wenche** [comment]
This seems to happen at exactly 1285px. But whyyyyyyyyyyy

**Comment by SvSven** [comment]
Using: Edge version 95.0.1020.40 (Official build) (64-bit) on Windows 10 with a 1920x1080p monitor.

Seems to happen at these sizes for me:
- 1282px
- 733px
- 683px
- 583px

Which makes it even weirder.
I cannot reproduce this on Firefox, which indicates it might be a Chromium related issue?

We can live with the font loading several times when people resize their browser, it's really not that common a scenario and the font file isn't particularly large - but it might be indicative of a larger problem with global styles from styled-components 🤔

**Comment by SvSven** [comment]
Cannot figure out what is causing this at the moment. It's a small enough issue to ignore for the time being, and we cannot waste more time on it. Moving to backlog so we have it in case we have more time to look at it later.

**Comment by SvSven** [comment]
I can't reproduce this anymore so this somehow got fixed along the way. Not sure why it happened or how it got fixed which bothers me, but at least it's fixed 🤷‍♂️
