### ISSUE TITLE
Broken internal URLS on Raddix / static pages

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#571]
We notice that there are a lot of issues with broken internal URLs. E.g. on the annual general meeting page. If you click on the PDF link to one of the previous annual general meetings, the PDF does not exist. Here is the complete list from this audit below. PDFs are ok on the AEM page.

Padmaja could you and the AEM team take a look into this, and maybe take a broader look to see if this issues effects on other pages? Is it an issue with PDFS contained within an table?

https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting

"URL","URL Rank","Scheme","HTTP Status Code","HTTP Status","HTTP Error Message","Indexable Status","First Parent URL","Crawl Depth","Crawl Source","No. Internal Linking URLs",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2011/statoil-agm-minutes-2011.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2013/statoil-agm-notice-2013.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2017/statoil-annual-general-meeting-2017-english.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2016/statoil-annual-general-meeting-2016.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2012/statoil-agm-minutes-2012.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2012/statoil-annual-general-meeting-2012.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2019/equinor-agm-15-may-2019-en.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2013/statoil-annual-general-meeting-2013.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2015/statoil-agm-minutes-2015.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2013/statoil-agm-minutes-2013.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2014/statoil-agm-minutes-2014.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2018/statoil-annual-general-meeting-2018-eng.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2011/statoil-agm-notice-2011.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2014/statoil-agm-presentations-2014.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2015/statoil-agm-presentation-2015.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2012/statoil-agm-notice-2012.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2014/statoil-annual-general-meeting-2014.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2014/statoil-agm-notice-2014.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2015/statoil-annual-general-meeting-2015.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2009/statoil-agm-minutes-2009.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2006/statoil-annual-general-meeting-2006.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2009/statoil-annual-general-meeting-2009.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2005/statoil-agm-minutes-2005.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2010/statoil-agm-minutes-2010.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2006/statoil-agm-notice-2006.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2007/statoil-annual-general-meeting-2007.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2007-egm/statoil-extra-ordinary-general-meeting-2007.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2007-egm/statoil-egm-presenstation-2007.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2007/statoil-agm-notice-2007.pdf","7","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","3",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2005/statoil-agm-notice-2005.pdf","5","https","404","Not Found","404 Not Found","Not Found","https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting","2","Crawler","2",
"https://energyvision.app.radix.equinor.com/content/dam/statoil/documents/annual-general-meeting/english/2011/statoil-annual-general-meeting-2011.pdf","5","https","404","Not Found",...

**Comment by wenche** [comment]
There's also a ton of urls containing white space, that's never a good thing but probably not that much to do about  it for the old content? Like all the xls files from the crude oil  and condensate assays. Let us not permit this in the new solution at least.

**Comment by padms** [comment]
Assets that were there in other components other than download were not pushed. Made changes in the migration tool to push them.

**Comment by wenche** [comment]
I just did another audit and I still see a lot of issues with broken URLs, 693 issues and that's an improvement of 41 since the last audit. I manually checked two links https://energyvision.app.radix.equinor.com/where-we-are/algeria and https://energyvision.app.radix.equinor.com/investors/events-and-presentations and neither of them worked. 

When did you push the changes? It might be some cache issues with the blog storage...? cc @nicholas-haggerty

**Comment by padms** [comment]
Pushed all the pages in the list.  Also I found that few assets were missing in current system. @wenche Could you run  the audit again?

**Comment by wenche** [comment]
The last fix had a huge impact @padms  :thumbsup:

![Skjermbilde 2021-11-11 kl. 13.01.42.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/0b7e9d9f-b812-4cea-b55a-6e90c065d136)

Only 15 left to go, I'll share it on Slack

**Comment by wenche** [comment]
@nicholas-haggerty 12 of these URLs are not available in the current solution. To close this issue, we should probably fix that?

1. The high resolution images at the bottom of this page https://energyvision.app.radix.equinor.com/news/archive/fourth-quarter-2017-results-and-capital-markets-update-2018
2. The images from Danske Bank at the bottom of this page https://energyvision.app.radix.equinor.com/news/archive/2019-02-01-danske-commodities
3. The first "Konsekvensutredgnings"-pdf at this pag https://energyvision.app.radix.equinor.com/how-and-why/impact-assessments/nsgi
4. The photo from the press conference, bottom https://energyvision.app.radix.equinor.com/news/archive/14dec2017-long-term-subsea-contracts-ncs

Then we have 3 left: The first two do work in the solution, might be a mistake from the tool? Let's see it they keep showing. I created a new issue #587 for the 3. one, but this should be of low prioritisation.

**Comment by nicholas-haggerty** [comment]
@wenche I have fixed (deleted) the elements on the 4 pages referenced above and re published on both the EN and NO versions for each

**Comment by nicholas-haggerty** [comment]
@wenche Not sure if you need to test further? If ok please close.
