### ISSUE TITLE
Create a component for News promotion list

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#574]
### To do

- Create a new component in Sanity for promotions
- Find a way to query for tags inside the promotion form
- See design in Figma
- It might make sense to do both news and topic page promotions at the same time? (Event is yet to be started)

### Acceptance criteria
- Can promote news and topic page cards by adding a promotion component in Sanity
- Can choose a maximum and minimum of 3 cards to promote
- The cards must be of the same type (can't mix news and topic page)
- The publisher selects the type of card by a dropdown
- All added tags in the "Tags" menu item are available as tags inside the form for news
- No duplication of tags or topic pages to be promoted
- The publisher could also add a title, ingress and select a background colour

**Comment by wenche** [comment]
@nicholas-haggerty  Please take a look at my acceptance criteria list and see if you agree. I'm not sure about whether we should limit the number of tags added, what do you think?

**Comment by nicholas-haggerty** [comment]
@wenche Ref tags. Depends a bit on the setup for tags. Are we splitting them in some way ie TOPIC tags (General news/Wind/oil etc) and COUNTRY tags. We discussed this a little bit  when Ådne presented (though not concluded) So in the News card is the editor selecting from two drop downs? 
In terms of used cases I cant see a need for the ability to select alot of _tags_. I think It would at most be 1 to 2 TOPICS and a COUNTRY.

**Comment by wenche** [comment]
@BirteThornquist and I have identified 2 different approaches for selecting the correct type to promote

1. Use "Promotion" in the component list and choose the correct type in the next dialog
![Skjermbilde 2021-11-09 kl. 09.10.45.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/68a2b2e6-22e0-44b4-8db6-a4b3e76f661b)

2. Choose between
- Promote news
- Promote topic pages
- Promote events
- Promote people in the component list. We decided to test the first version to avoid making the component list too long.

**Comment by wenche** [comment]
@nicholas-haggerty We added both the `news` and the `topic page` promotion types as that made it easier to test different approaches. This issue is just for the Sanity part. :)

**Comment by wenche** [comment]
We decided to add an intro text for the topic page

**Comment by wenche** [comment]
We have added the intro text for the topic so this one should be good to go @nicholas-haggerty

**Comment by BirteThornquist** [comment]
Looking good! Closing this @nicholas-haggerty - since we did the review the other day.
