### ISSUE TITLE
404 doesn't work for archived news

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#576]
When I visit urls like https://energyvision.app.radix.equinor.com/news/archive/sdlkfjlsdkfj (which does not exist) no 404 is returned. The response code is 200 and the page is empty.

![Skjermbilde 2021-11-03 kl. 09.38.39.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/4ab9d8c0-629c-467a-b0f0-94bb5ac72468)

**Comment by wenche** [comment]
Returning `notFound` fixed this

**Comment by SvSven** [comment]
Can confirm, I now see a 404 in the network tab and the nice new custom 404 page 👍
