### ISSUE TITLE
Cookie policy page contains a Source Code table that is not displaying correctly in radix

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#578]
Is there something that can be done in with the issue? Alternatively should we look to build this page in Sanity instead of having as a static page rather than spend too much solving. 

Which also means we need to look at how to solve source code displays? Not sure if this could be solve using an iframe or can it only be solved with Source code component?

https://www.equinor.com/en/cookie-policy.html

https://energyvision.app.radix.equinor.com/cookie-policy

Interactive element from from Cookie policy:
https://consent.cookiebot.com/f1327b03-7951-45da-a2fd-9181babc783f/cd.js" type="text/javascript" async></script>

**Comment by padms** [comment]
@nicholas-haggerty The cookie declaration script tag should be inserted as is at the exact location where we want to show the declaration. So, we need a component to load this cookie declaration in order to load the cookie declaration on other satellite sites too.

**Comment by nicholas-haggerty** [comment]
@wenche Hey, see Padmajas comment above. Should we just create a new card for a specific component to host the script code?

**Comment by wenche** [comment]
Yes, that would probably make sense @nicholas-haggerty

**Comment by wenche** [comment]
On a side note, @BirteThornquist  and I briefly discussed if we should group these single-use, odd components in a separate component list item like "Special components" and choose the component in the popover to avoid to bloat the list with components like "REMIT (if needed)", "Stock information"

**Comment by nicholas-haggerty** [comment]
@wenche Great idea. Ill make a card and lets discuss

**Comment by nicholas-haggerty** [comment]
Closing the bug and have opened a new issue in backlog to solve this and other special/unique components that have limited use
