### ISSUE TITLE
add type checking to Sanity studio build

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#579]
Sanity currently doesn't do any type checking when building, mainly due to TS being added later on and their types were incomplete.

We can (should) add manual type checking like so:

```json
// tsconfig.json
{
  "compilerOptions": {
    // 👇👇👇
    "noEmit": true
    // other options...
  },
  "include": [
    "./node_modules/@sanity/base/types/**/*.ts",
    "./**/*.ts",
    "./**/*.tsx"
  ]
```

```json
// package.json
{
  "name": "mysanityproject",
  "devDependencies": {
    // 👇👇👇 ensure typescript is a dev dependency
    "typescript": "^4.4.4"
  },
  "scripts": {
    // 👇👇👇
    "build": "tsc && sanity build"
  }
}
```

**Comment by nilsml** [comment]
Also worth mentioning that we are using type names for components in the code. Would be better to use proper types or at least have the names as constants somewhere to avoid typos and make changing these easier.

**Comment by SvSven** [comment]
Supposedly v3 of Sanity Studio will have much better TypeScript support - so maybe this will be added by default

**Comment by fernandolucchesi** [comment]
I'll close this since upgrading to sanity v3 will get this solved
