### ISSUE TITLE
As a publisher I want to publish a news article with the same slugs across transations 

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#580]
Current situation is that it the slug is the same in the English and Norwegian news article, Sanity will throw an error message.

![Skjermbilde 2021-11-04 kl. 14.38.17.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/445fdd71-c78a-491c-94e6-c02edca1c8f8)

**Comment by adneforslund** [comment]
As a translation of an article is another document, and Sanity enforces uniqueness across a documentType, we need to override Sanitys default isUnique method

**Comment by adneforslund** [comment]
Waiting for Sanity

**Comment by adneforslund** [comment]
Works on existing documents, but language is set on publish, so it blocks creating new documents

**Comment by wenche** [comment]
LGTM :thumbsup:

![Skjermbilde 2021-11-24 kl. 13.19.41.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8835426f-a066-4eff-8035-e6f47b8a969e)
![Skjermbilde 2021-11-24 kl. 13.20.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/9cffba29-2a5f-4118-97df-d5ec56b9e035)
