### ISSUE TITLE
Wrong placement of close menu button on mobile

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#581]

**Comment by BirteThornquist** [comment]
On mobile (safari) the close menu icon is placed to the left instead to the right. 

iPhone 12 Pro - version 14.7.1

![IMG_2284.PNG](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/269d6888-bb95-47e1-a4fc-79afe226aca8)


![IMG_2285.PNG](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/0b93f5c9-3b5b-4ee6-9acf-c59573ae9c54)

**Comment by SvSven** [comment]
Can't reproduce on Chrome or Firefox on Android. Looks to be Safari/iOS specific bug.

**Comment by SvSven** [comment]
@BirteThornquist can you double check if this is still an issue? We checked with 3 different devices and it all looked as expected there, with the close button on the right.

**Comment by fernandolucchesi** [comment]
Works as intended now
