### ISSUE TITLE
Create subscribe form component in sanity

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#589]
The component has two fields : 
1) Heading ( the heading for the form)

**Comment by padms** [comment]
Created a simple component in sanity, called Subscription form with the same fields as in AEM.

**Comment by padms** [comment]
We might need to remove the type field for subscription form.. if there is going to be a single form.

**Comment by padms** [comment]
@nicholas-haggerty @meols If we are going to have only one form for all categories, then shall I remove the type field in this component?

**Comment by meols** [comment]
@padms - if the "type field" let you choose what kind of news you can subscribe to we will need it. We still need to be able to choose between the same options as today General news, Stock market announcements, Crude oil assays, Magazine stories (skipping People as a magazine story option going forward) and Loop. New subscribers will need to be added to the corresponding subscribers list in the Brandmaster end.
@nicholas-haggerty

**Comment by nicholas-haggerty** [comment]
@padms Hi. Yes, we remove it. There will be only one subscription form for all types. The user chooses on or more from the tick list. This determines which mail group they will be assigned to at the brandmaster end. We have spoken to Yngve at Brandmaster and its possible to set up this way their end.

**Comment by padms** [comment]
Removed form type field in the component

**Comment by padms** [comment]
@meols @nicholas-haggerty  The component is working as expected. Could you please review this again?

**Comment by nicholas-haggerty** [comment]
@padms Great work Padmaja. Closing. WE can create a new issue reflecting the changes towards Brandmaster
