### ISSUE TITLE
Recaptcha for forms

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#591]

**Comment by nilsml** [comment]
Perhaps you @padms can have a look at this when you are done with your current tasks?

**Comment by nilsml** [comment]
Waiting for us to make a decision on alternative to Google

**Comment by padms** [comment]
Came across this one https://friendlycaptcha.com/
https://friendlycaptcha.com/insights/recaptcha-alternatives-compared-recaptcha-vs-hcaptcha-vs-friendly-captcha/

**Comment by nilsml** [comment]
Looking more into Friendlycaptcha as that seems to be the best solution. Issues with url being blocked by policy though. @pradeepvenurao is looking into it.

**Comment by nilsml** [comment]
Friendlycaptcha is approved by legal.
