### ISSUE TITLE
Investigation task. Integrating with Fotoware DAM

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#592]
In addition to API integration there are some further options with Fotoware solution,

https://learn.fotoware.com/Integrations_and_APIs/01_Creating_Integrations_using_Embeddable_Widgets

**Comment by fernandolucchesi** [comment]
https://github.com/equinor/energyvision-internal/discussions/49

**Comment by meols** [comment]
@fernandolucchesi - I learned this afternoon that from 30 June Fotoware will be the Equinor image archive. All new images will only be uploaded there from that date, and images will only be available in Fotoware (excluding the historical archive from 2018 and older, that will continue to be in Brandmaster until moved to https://www.arkivverket.no/ later) 
This means that integrating Fotoware DAM will need to be prioritized.
Please raise any questions you/the team may have with some of those attending the meeting you and @nilsml were in 13 May (assuming those are the most relevant contacts), and let me know if there is anything I can do to contribute to speeding things up with Fotoware/the DAM 2.0 project.

**Comment by fernandolucchesi** [comment]
@meols, thank you for following up, I will prioritise this

**Comment by fernandolucchesi** [comment]
Closing this since this was an investigation task, another issue has been created for implementation purposes
