### ISSUE TITLE
Create basic Sanity schema for event document

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#598]
See: #440

- [x] Add translation 

- [x] Preview

- [x] Route tabs

**Comment by wenche** [comment]
@SvSven What about preview and connected route tabs. Translations?

**Comment by SvSven** [comment]
Translation & preview has been added, let's discuss tomorrow regarding the slug/routes

**Comment by SvSven** [comment]
We agreed to switch over to using the routing system similar to topic pages as it adds more flexibility in the long run. Option will still be there to switch back should we need to.
