### ISSUE TITLE
Investigate how to handle date & time input for events

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#599]
Events can be any of the following:
- Single day
- Multiple days
- No specified time
- With specified time

We need to figure out a good way of handling the date & time input here to avoid confusion. One option could be to just have it be a simple text input where the editors write it out, but this can (will) cause inconsistencies and can (will) cause problems with converting that text to a usable date format for the web and .ICS file.

**Comment by adneforslund** [comment]
Could represent events as an array of days with 2 dates on each element

**Comment by fernandolucchesi** [comment]
Proposed solution: https://github.com/equinor/energyvision/pull/616

**Comment by SvSven** [comment]
Copied from #484:

> @BirteThornquist @SvSven Looking good Sven, nice work One comment relating to date. For Timezone, is it possible to set Europe/Oslo as default? It will be 90% of times I guess, and editor has to manually scroll down to select it, which added at least 7 seconds to my day!
> 
> On preview, the spacing for the text in the top banner looked a little off compared to the Figma sketch. The date seems too tight to the header (and further away from the time).
> We also had date/time/event type in Green. Maybe these are for another issue through?

**Comment by fernandolucchesi** [comment]
The UI is still a WIP. Will get them updated today when I am done with all the security tutorials and tests :P. The timezone is already being set to the user's timezone, I believe she edited an already existing event instead of creating a new one, and that is why Europe/Oslo wasn't pre-selected.

**Comment by fernandolucchesi** [comment]
Hi @BirteThornquist, can you double check this one? :)

**Comment by BirteThornquist** [comment]
Looking good @fernandolucchesi ! I got the Europe/Oslo timezone as default. When a specific time is not set, we should have a text saying "Time to be announced " also for the event template, right @nicholas-haggerty ?

**Comment by nicholas-haggerty** [comment]
@fernandolucchesi @BirteThornquist Yes we would need this in the event template too (and on the event promo)

**Comment by fernandolucchesi** [comment]
I have just updated it @BirteThornquist

**Comment by BirteThornquist** [comment]
Great @fernandolucchesi !
