### ISSUE TITLE
Implement press contact list component for events

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#602]
https://energyvision.app.radix.equinor.com/event
On some events, editors add a list with contact information for press contacts.

**Comment by SvSven** [comment]
Design availabe on Figma, located below people promotion on event template

**Comment by adneforslund** [comment]
https://energyvision.app.radix.equinor.com/event

**Comment by padms** [comment]
@nicholas-haggerty  @meols  Could you please have a look at this?

**Comment by nicholas-haggerty** [comment]
@adneforslund  @padms 
Looking good thanks. Question, is it possible to have the numbers clickable/active, Especially on Mobile. This is automatically added in the PEOPLE promo card so would be good if this is the same.

**Comment by adneforslund** [comment]
@nicholas-haggerty Will fix
