### ISSUE TITLE
Trigger webhook to brandmaster when article is published in sanity

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#604]

**Comment by nilsml** [comment]
Is this done @padms ?

**Comment by nilsml** [comment]
Any comments on this one @padms? Shouldn't it be part of the subscription delivery?

**Comment by padms** [comment]
Currently set up webhook to trigger when news are is published with the subscription type selected.

**Comment by padms** [comment]
Webhook is not triggered when a news article is published in both English and Norwegian at the same time.

**Comment by padms** [comment]
Issue : When a news article is published at the same time in both Norwegian and English, the webhook is triggered for only one of them. 
[Webhook attempt list](https://api.sanity.io/v2021-10-04/hooks/projects/h61q9gi9/F5qvLiqKEZMwuqEd/attempts?limit=50&offset=45) shows only norwegian version of https://energyvision.app.radix.equinor.com/no/news/test-jan-11 

GROQ results shows below result for the test-jan-11 article ( See the English version has drafts but its published ) 
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/8a1633a6-143c-4b85-98f0-6b3448c2474a)
![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/c6a810eb-6e84-4f39-81a8-cf5b7a33f21e)

**Comment by padms** [comment]
To test: 
Create a news article with subscription type selected, and publish it. The newsletter distribution can be verified by going to the webhook requests or contacting brandmaster.
@meols

**Comment by meols** [comment]
@padmaja - thanks for checking that this worked as expected for both languages. Please close this ticket after attaching the email/screenshot from Yngve.

**Comment by nilsml** [comment]
Waiting for Yngve to reply

**Comment by padms** [comment]
Confirmation received from Yngve... 

`{"id":"atm-249ARGSVLq9zLid3tWDPh4GnS2J","projectId":"h61q9gi9","inProgress":false,"duration":809,"createdAt":"2022-01-24T13:53:37.842Z","updatedAt":"2022-01-24T13:53:37.842Z","messageId":"msg-249ARCdnJvill8jWLHYdnqHkGQw","hookId":"F5qvLiqKEZMwuqEd","isFailure":false,"failureReason":null,"resultCode":200,"resultBody":"{\"msg\":\"Successfully distributed https://energyvision.app.radix.equinor.com/no/news/2022-01-21-equinor-test-nyhet\"}"},{"id":"atm-240iI5HsoJCRWODpYidwZkczPr3","projectId":"h61q9gi9","inProgress":false,"duration":1240,"createdAt":"2022-01-21T14:03:39.823Z","updatedAt":"2022-01-21T14:03:39.823Z","messageId":"msg-240iHt69Ty5JxTgu4EAM4plD09w","hookId":"F5qvLiqKEZMwuqEd","isFailure":false,"failureReason":null,"resultCode":200,"resultBody":"{\"msg\":\"Successfully distributed https://energyvision.app.radix.equinor.com/en/news/2022-01-21\"}"}`

Yngve's Confirmation :
can confirm that I have received both these news. 
One english on 21.01 at 15:03. Type of news: "Company"
One Norwegian on 24.01 at 14:53. Type of news: Company.
