### ISSUE TITLE
Some content will be in one language only but this content needs to be reflected in both menu structures

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#605]
We agreed upon that the best option is to add a separate field for linking to a different language. This one is added in the rich text editor's internal link by #912

Do we need this option for other internal references as well, and if yes: Exactly where?

-

Investigate need for linking to different languages from different components and list pros and cons

**Comment by wenche** [comment]
See issue #912

**Comment by wenche** [comment]
In the meetings in Oslo we agreed upon using external links in these cases (mostly related to Investors and Careers)

Fernando suggested to create a new type of internal link: Link to content in another language to make it easier for publishers and for safety reasons. This is done for rich text editors by #912.

We should probaby add this to C2A buttons as well

**Comment by wenche** [comment]
@meols  Are you satisfied with the option to reference content in other languages from a rich text field, or should we at least add it to the call to action button styled links as well?

**Comment by meols** [comment]
@wenche - please add to CTA buttons as well :thumbsup: Thanks! We would like this option for all links.

**Comment by nilsml** [comment]
Have a discussion on this issue to set up acceptence criteria
