### ISSUE TITLE
Create the event card

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#608]
The event card will have two styles, portrait and landscape, specified in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3290%3A70695). If only one event is promoted it will show in landscape style, else in portrait style. Editors will not be able to style the card (background color).

**Comment by nilsml** [comment]
@nicholas-haggerty

**Comment by nicholas-haggerty** [comment]
@meols same. Ok for me, but take a look
