### ISSUE TITLE
Handle .html issue

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#609]
In AEM `.html` suffix is used for the pages. In Sanity/Next.js we are not using it, so need to handle redirects.

**Comment by nilsml** [comment]
Maybe you can describe this problem a little bit more @wenche?

**Comment by nilsml** [comment]
Some kind of middleware perhaps. The editors should not have to deal with this.

**Comment by fernandolucchesi** [comment]
@SvSven can you take a look at this solution?

**Comment by SvSven** [comment]
I have no experience with handling redirects or middleware in Next, but this looks pretty straight forward?
I tried going to some pages with .html added at the end and it does redirect the request to the same page without .html - so it seems to work.

Will this approach be good enough for web crawlers and SEO? I see it's set up as a 301 redirect which is good at least.

**Comment by wenche** [comment]
What does it take to be able to close this?

**Comment by fernandolucchesi** [comment]
I am improving this solution

**Comment by fernandolucchesi** [comment]
> What does it take to be able to close this?

closing it :)
