### ISSUE TITLE
Set up/map access groups

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#610]
Relevant comments in #619

**Comment by nilsml** [comment]
Will be handled automatically when Sanity has implemented feature, but for now we need to do it ourselves.

**Comment by nilsml** [comment]
Manual work for now. Will keep this in the backlog as a reminder for pushing Sanity on a better solution.

**Comment by fernandolucchesi** [comment]
https://equinor.service-now.com/selfservice?id=ticket&table=sc_req_item&sys_id=2b6823b5871ed590a9faa9383cbb3575

**Comment by nilsml** [comment]
Dis Sanity release this feature @SvSven ?

**Comment by SvSven** [comment]
https://www.sanity.io/blog/saml-sso-project-role-mapping-enterprise

**Comment by fernandolucchesi** [comment]
@meols @NickHaggerty1 everything should be working through accessIT from now on..

**Comment by meols** [comment]
@fernandolucchesi - the requests I have received have worked as they should, so this one is good/approved :smile:
