### ISSUE TITLE
Workflow for the news (do you really want to publish?)

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#611]
## Acceptance criteria
- Editor has to confirm that he/she wants to publish a news article or publish updates to an existing one
- Should be added for news and local news, but not the rest of the templates

### Testing
 **Dialog for news article**
1. Create a new news article 
1. Click `publish`
Expected outcome: Can't publish since the mandatory content is not yet added. The publish button is disabled
1. Add the mandatory content
1. Click `publish`
Expected outcome: A dialog asking you to confirm that you want to publish

1. Edit the news article
1. Click `publish`
Expected outcome: Prompted by the dialog again asking for verification

**Dialog for local news article**
1. Create a new local news article
1. Add the mandatory content
1. Click `publish`
Expected outcome: A dialog asking you to confirm that you want to publish

1. Edit the local news article
1. Click `publish`
Expected outcome: Prompted by the dialog again asking for verification

**No dialog for topic content/other content than news and local news**
1. Create a new topic content
1. Add the mandatory content
1. Click `publish`
Expected outcome: No dialog

**Comment by SvSven** [comment]
@wenche @fernandolucchesi @padms  
I have pushed a custom document action that replaces the built in Publish action: https://github.com/equinor/energyvision/commit/54b30fa79e360851605c686d92818113f37fddd9

This action will pop up a confirmation dialog for the `news` and `localNews` document types, for the rest it should act like before (with the exception that the label on the button isn't updated by state as the built in one).

The code and comments are I think pretty self explanatory, but a few comments:

We need to use the publish action from the `useDocumentOperation` hook to manually publish the document. This command does not care about drafts or validation, so we need to manually check the validation status before running that. To that end I made a function that checks the validation markers passed by the `useValidationStatus` hook for any errors.

Similarly we check for the existence of a `draft` document (see: https://www.sanity.io/docs/document-actions-api#draft-f1269efe5ab2) which is used to conditionally disable/enable the publish button along with the validation check.

What is important to check here is whether the validation stuff works; users should not be able to publish a document if there are validation errors, nor should they be able to publish if there are no changes made to the document (no draft). We also need to check that the confirm dialog works for news and local news, and does not appear for other documents.

**Comment by wenche** [comment]
LGTM :thumbsup:

**Comment by wenche** [comment]
@meols Please take a look at what Sven did. I have added some suggestions for testing in the issue description

**Comment by meols** [comment]
@SvSven - works perfectly :thumbsup:
@wenche - thanks for great test cases :smile:
