### ISSUE TITLE
As an editor I want to select the correct subscription options for news articles

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#613]
## Acceptance criteria
1. Tick of either general news, stock market announcements or crude oil assays
1. Linked to the correct subscriber list
1. Differentiate on language

**Comment by nilsml** [comment]
Do we have news articles that are only published in one language? Then what happens for people that have signed up for a different language? @nicholas-haggerty @meols

**Comment by nilsml** [comment]
Waiting for Brandmaster to be able to test this

**Comment by padms** [comment]
This can be verified while testing #604.  @meols

**Comment by meols** [comment]
@padms - I can choose between the three subscription tags in a news article. This is OK.
