### ISSUE TITLE
focus-visible with EDS core react

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#615]
The EDS team has updated eds-core-react to use esm modules. This is good, as tree-shaking now works as expected and and bundle size in reduced. However, Next.js does some clever optimisation for the production bundle and the polyfill library for :focus-visible didn't work anymore.

The solution for Envis is to 
a) Make the focus-visible library an explicit dependency for the web.
b) Import the library in _app.tsx

Since we use this library in our code beyond in the EDS component, this is the right thing to do as it's not optimal to implicit use a library from a library :)

**Comment by wenche** [comment]
See https://github.com/equinor/energyvision/commit/39e61429872ac80f3ad1547f59bfba530527abbc

**Comment by wenche** [comment]
@SvSven  I guess you have already verified this? Close?

**Comment by SvSven** [comment]
Can confirm that I see the focus state again both locally and in production
