### ISSUE TITLE
Add legacy pages to Algolia index

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#617]
**In order to make legacy (static) pages searchable, we need to add them to the Algolia index**

## Acceptance criteria

1. All text content from static pages are added to index
1. Index is updated at regular intervals

**Comment by nilsml** [comment]
Waiting to see the outcome of the next backlog refinement meeting.

**Comment by nilsml** [comment]
Putting this back in the backlog as I do not have time working on it atm 😬

**Comment by nilsml** [comment]
This does not need to be a scheduled task like the indexer for Sanity pages as we don't expect the archive to be changed anytime soon. Will create a tool that can read a json-file with all archived news and massage these data and put into Algolia.

**Comment by nilsml** [comment]
Is dependent on #964 and #965

**Comment by SvSven** [comment]
Investigate removing markup from json content

**Comment by SvSven** [comment]
I can confirm that we are getting archived news from Algolia in both the search results and newsroom, and I can also see them in Algolia.

So.... looks good to me 👍
