### ISSUE TITLE
Specify the needs for satellite pages

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#618]

**Comment by fernandolucchesi** [comment]
If we decide to go with the multiple instances approach, we need to make all languages dynamic in both our web app and studio. Languages could be added from either the Studio itself (sounds more complicated but editors could add support to new languages themselves), or as an environment variable (sounds less complicated to start with but requires a dev to add/remove new languages)

I could list the following files as containing any sort of reference to hardcoded langs that would need refactoring:

Web app
![image](https://user-images.githubusercontent.com/23337266/145365406-d882249c-596d-45ad-86ad-66259ccb3dc2.png)

Studio
![image](https://user-images.githubusercontent.com/23337266/145365779-7f7d4d22-0db0-4a07-b268-b307d8d743d0.png)

**Comment by nilsml** [comment]
I've been promised a document 😄 Where can I find it? Perhaps link to this issue @adneforslund @fernandolucchesi

**Comment by adneforslund** [comment]
https://github.com/equinor/energyvision/blob/main/multisite.md
