### ISSUE TITLE
Specify access control needs to Sanity

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#619]

**Comment by adneforslund** [comment]
Should be able to manage access on specific documents?

**Comment by nilsml** [comment]
We had a meeting with Sanity where our needs were presented. They had solutions for the access control on the Sanity side. What we need in addition is a way to connect Azure AD roles to Sanity roles. Perhaps we can live without that for some time?

**Comment by nilsml** [comment]
Customising desk structure based on user role:

https://gist.github.com/SimeonGriggs/f4954ced2b1313278eaef5feab5ce4c4

**Comment by meols** [comment]
**SSO – access groups**
•	Author – access to create, edit, publish on all sites (editorial team, on duty personell)
•	Loop Author - access to create, edit, publish on the Loop site only
•	Brazil Author - access to create, edit, publish on the Brazil site only
•	Techstar Author - access to create, edit, publish on the Loop site only 
•	Equinor Storage Author - access to create, edit, publish on the Equinor Storage site only
•	Equinor Fondene Author - access to create, edit, publish on the Equinor Fondene site only 
•	Poland Author - access to create, edit, publish on the Poland site only
•	German Author - access to create, edit, publish on the German site only
•	Japan Author - access to create, edit, publish on the Japan site only
•	Korea Author - access to create, edit, publish on the Korea site only
•	“Any new satellite site” Author

**Questions:**
•	How to restrict access (per person) for an article, not showing the article (and related assets) for anybody else? Also excluding support system? (Different accesses for different articles - ref. quarterly results)
•	Specific author access for specific pages on the global site – e.g. Careers people updating and publishing their pages.
•	Access handling for the DAM/separate DAMs pr. site/access to one DAM “folder”?
•	How to handle local news (and possibly Loop) publishing accesses in global site? Different options available for the news template, or specific Local news template?
•	How to give access to someone from an agency, without xx@equinor.com email?
•	Should be possible to have more than one access group (e.g. Japan and Korea)

**Comment by nilsml** [comment]
> Questions:
• How to restrict access (per person) for an article, not showing the article (and related assets) for anybody else? Also excluding support system? (Different accesses for different articles - ref. quarterly results)

This is more related to authorization, but I believe for articles it should be possible to solve after what Sanity told us in the meeting. For assets I am not sure. Apparently all assets are public once in Sanity. We need to further investigate that.

> • Specific author access for specific pages on the global site – e.g. Careers people updating and publishing their pages.

This should be easy to solve

>• Access handling for the DAM/separate DAMs pr. site/access to one DAM “folder”?

Also authorization related. Will need further investigation, ref answer above.

> • How to handle local news (and possibly Loop) publishing accesses in global site? Different options available for the news template, or specific Local news template?

Authorization. Will be possible to only give access to certain content for certain people.

> • How to give access to someone from an agency, without xx@equinor.com email?

They need to get a (restricted) Equinor account

> • Should be possible to have more than one access group (e.g. Japan and Korea)

So, you mean belonging to more than one group? That should be possible, yes.

**Comment by meols** [comment]
@nilsml - sounds promising :-)

**Comment by nilsml** [comment]
Groups applied for in AccessIT 👍🏻
