### ISSUE TITLE
Client Secret + password hardcoded in repo

### ISSUE THREAD

**Issue by circa10a** [equinor/energyvision#622]
Assuming it's not intentional to have these here?
https://github.com/equinor/energyvision/blob/main/web/components/utils/subscription.tsx#L9

**Comment by nilsml** [comment]
@SvSven Is this what we already discussed?

**Comment by SvSven** [comment]
@nilsml Nope, this is something different. Looks to be the subscription form which should _probably_ be in an `env` file.

**Comment by nilsml** [comment]
Thank you so much for letting us know about this @circa10a!
This is definitely not intentional, and we will fix it asap!
