### ISSUE TITLE
Fix latest news in the news article template

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#629]
There are some issues (with the query?) for the latest news list.

It doesn't seem to list 3 news articles and it should not list draft news

 ![Skjermbilde 2021-12-01 kl. 10.12.16.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d2c26e33-6e9d-4fa2-ad7c-e9796429e2a1)

**Comment by adneforslund** [comment]
Are we not filtering out drafts in the querues?

**Comment by wenche** [comment]
Probably a couple of things since this was made ages ago and way before we added the read token :)

**Comment by wenche** [comment]
Also this one, do we not filter correctly on languages 
![Skjermbilde 2022-01-04 kl. 14.44.39.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/bdff5793-2815-4936-b54b-f5d9890883cc)

news/20211201-stepping-up-fusion-investment

**Comment by SvSven** [comment]
Should we also filter out articles that don't have all the content (like image and ingress)?

**Comment by fernandolucchesi** [comment]
Hint for reviewing this, use this url slug locally: `news/news-testing`, dataset `production`.

Without the heroImage query: 
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/23337266/153016010-75b2d7e6-b7c7-4710-8d15-c499c5ba2df2.png">

without the languages' query:
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/23337266/153016186-8094414c-cf12-4b0f-8e32-e86756069c22.png">

after the fix:
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/23337266/153016324-c3027ad6-7197-40ee-abe0-ede83fb5a83a.png">

**Comment by wenche** [comment]
Using the preview inside Sanity, lists the English latest news in the Norwegian page

![Skjermbilde 2022-02-09 kl. 10.31.09.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/192d863b-0665-492d-a0cb-8e41d758da2a)

**Comment by fernandolucchesi** [comment]
Hi @wenche, I fixed the news in norwegian but it doesn't work when previewing inside the studio. I couldn't figure out why but seems to be working fine otherwise. If this is a "must" requirement I can do some more investigation. I will also add this as a point for the next sanity discussion
