### ISSUE TITLE
Improve "open preview" button

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#630]
If we will continue to use the approach with cookies and token for preview, we need to fix the redirect here. The location in  /pages/api currently does not set the hostName.

![Skjermbilde 2021-12-01 kl. 15.02.22.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8583f7f3-ea03-45e3-aa67-5c49c2f7cd0c)

## Acceptance criteria
- When clicking the "Open preview" button, we are taken to the correct web page

**Comment by nilsml** [comment]
This is making the editors confused. I think this one should be prioritized.

**Comment by SvSven** [comment]
Added the protocol and hostname to the preview redirect. Looks to be working both locally and on radix with global-dev.

**Comment by SvSven** [comment]
@wenche @fernandolucchesi have a look 🙏

**Comment by wenche** [comment]
Seems to be working as expected :thumbsup: We should do a full regression test for this when we move to the new cluster
