### ISSUE TITLE
Upgrade Sanity

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#632]

**Comment by wenche** [comment]
I upgraded the studio and added the performance fix Simeon gave us. That removed the endless loading spinner for me. Are you able to verify this @SvSven  ?

**Comment by SvSven** [comment]
At first glance it looks like everything is working as it should
I can load news, topic content, top level routes and child routes, events, menu. No real lag, no loading spinners being stuck. Seems to be okay?
