### ISSUE TITLE
As an editor I would like to have option to format titles in both the templates and components

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#633]
![formating titles.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/76fe9d8b-45d6-4408-8c16-cb3bccc84036)

### Acceptance criteria
- Can use sub script in titles
- Can use sup script in titles

NB: Not all titles have rich text, so this feature will only affect the rich text titles in Sanity

**Comment by nilsml** [comment]
Needs further discussion. This could be a bigger task.

**Comment by nilsml** [comment]
Related to #334

**Comment by wenche** [comment]
Related to #741

**Comment by nilsml** [comment]
@nicholas-haggerty Can you add more details to this card? What kind of format options are needed? Is it covered by #741?

**Comment by nicholas-haggerty** [comment]
@nilsml If you look at the example attached. You will see an editor cannot format the CO2 in the text block component title (compared to having the option in the ingress and body to do so) It could be course be consolidated with 741. (As long as its captured there) an editor may need this option in the templates title also. Although this could backlog as I suspect it would mostly impact news titles that tend to be longer and stakeholder controlled @meols thoughts?

**Comment by meols** [comment]
@nilsml  - agree with Nick. We would like to have the options, but it's not critical at this point (for some reason I can't tag Nick)

**Comment by wenche** [comment]
This card is mainly complaining about the formatting for sub and sup script so we will focus on that. Other options for rich text titles is covered by #741

**Comment by wenche** [comment]
Added this to the branch too @SvSven

**Comment by wenche** [comment]
@meols  It's not easy to change the input component to a rich text editor at this point, so no it's not a low hanging fruit to add this to the accordion item title unfortunately :sweat_smile:

**Comment by meols** [comment]
Thanks @wenche - then I just close this one :smile:
