### ISSUE TITLE
As an editor I need to be able to add a colour background to the QUOTE component to display the quote as part as of a module. 

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#634]
![this-background-should-be-green.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/8ca78a39-6cd7-410a-aa76-ac37478f91e5)

## Acceptance criteria
- Can choose a background colour for a quote component in Topic pages
- The chosen background colour is visible in the web
- All texts and icons are inverted for the darkest background colour
- These changes does not affect the news article's version of the quote

**Comment by nilsml** [comment]
This component was tailered for news articles, so needs to be changed for other pages.

**Comment by wenche** [comment]
One way of solving this (if we know that the only thing that should differ between the news's quote and the topic page's quote is the background colour) could be by using the pattern filter Sven originally introduced for the iframe component, [removed later by this commit](https://github.com/equinor/energyvision/commit/81fa3e459f64ea502147faad3a3582a167b52aaa)

**Comment by adneforslund** [comment]
@BirteThornquist

**Comment by BirteThornquist** [comment]
@adneforslund For news articles there shall not be a background color for the Quote component. For news we don't use background colors in general, except for the Fact Box.

**Comment by wenche** [comment]
Fix the quote symbol for dark bg
![Skjermbilde 2022-02-04 kl. 11.37.29.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/eb2207a8-a6ed-4206-a0a5-6447c54ca7d1)

**Comment by wenche** [comment]
@meols Could you please take a look at this?

For news articles: No background colour options in Sanity and no colour on the web
![screencapture-localhost-3000-drafts-db2dc966-c86a-428c-80ec-f654061d42c7-2022-02-04-12_36_34.jpg](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/34e135cf-4cb0-40cc-9469-f27ba88753c7)

On topic pages: Able to choose a colour and create a module using for instance text block and quote. 
![screencapture-localhost-3000-drafts-db2dc966-c86a-428c-80ec-f654061d42c7-2022-02-04-12_36_34.jpg](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/81cd5d75-dbcd-402c-ac8e-18c762f2af03)

**Comment by nicholas-haggerty** [comment]
@meols @wenche Approved. Nice work!
