### ISSUE TITLE
As an editor it makes more sense to change 'ATTRIBUTION' to 'Credit' when adding photographers name to Image component

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#635]
Change Attribution field to Credit

**Comment by nilsml** [comment]
Change of lable. Should be a quicky!

**Comment by fernandolucchesi** [comment]
@wenche can you check changes?

**Comment by wenche** [comment]
Looks good to me! As long at @meols agrees, we are good to go :thumbsup:

**Comment by meols** [comment]
@wenche @fernandolucchesi - yes - great and thank you! :clap: 
(not sure where I can check it, but agree to the change)

**Comment by BirteThornquist** [comment]
LGTM @fernandolucchesi
