### ISSUE TITLE
Pre-select parent for new child routes

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#638]
**As an editor trying to create a child route, I want my selected parent route to be pre-selected in dropdown because I want to save time**

## Acceptance criteria
1. The parent route selected under "All parents" is pre-selected in "Parent" dropdown

![Screenshot 2021-12-07 at 09.13.08.png](https://images.zenhubusercontent.com/5f899bfbf74e6d6928f0f80f/89a7daba-d380-4676-a5e4-23fdf6fdfca8)

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform user testing

**Comment by adneforslund** [comment]
In the file `parentChild.js` there is a reference to a initial value template that doesnt exist. 
But the solution to this would probably to make a template that takes in the id of the parent and populates the reference field with the if of the parent

**Comment by adneforslund** [comment]
Note: not able to set any kind of initial value on this document

**Comment by fernandolucchesi** [comment]
Found a good workaround for this, looks like it worked :)

**Comment by wenche** [comment]
@fernandolucchesi Does seem to work as expected for child pages, both English and Norwegian. It does however _not_ work when I want to create a new top level (parent) page, then it seems like it preselect the first children in the list as its parent? New top level pages should not have a parent. Are you able to do this magic for child pages only?

**Comment by nilsml** [comment]
New issue #641 created for parent/child problem

**Comment by nilsml** [comment]
Tested and verified!
