### ISSUE TITLE
Investigate issue with parent/child routes

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#641]
Creating a new top level route reloads the studio with the first item in the list of top level routes selected and the child routes pane open:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/9b234359-4954-4549-bae2-a7f5e4ec1a80)

**Comment by nilsml** [comment]
Please add more details to this card for the issue @fernandolucchesi

**Comment by SvSven** [comment]
This was introduced when we upgraded Sanity from v2.21.7 to v2.22.3
Based on the release log by Sanity this was specifically introduced in version 2.21.10, where they fixed some things related to the documentPane and new document creation editor: https://github.com/sanity-io/sanity/releases/tag/v2.21.10

**Comment by nilsml** [comment]
Did you find a solution to this @SvSven?

**Comment by SvSven** [comment]
Got some feedback from Sanity with a potential solution, running tests to see if it works

**Comment by SvSven** [comment]
This should be fixed now. We need to be explicit in setting the intent in the desk structure: https://github.com/equinor/energyvision/commit/dc2507780cc5502bf99050baa0a5c288a8600ac6

**Comment by wenche** [comment]
LGTM! :thumbsup:
