### ISSUE TITLE
Set up production environment

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#649]
- [ ] Set up prod environment in Radix

- [ ] Set up new dataset in Sanity for production

**Comment by nilsml** [comment]
Figure out how to use the studio for multiple environments. Same studio or new studio?

**Comment by wenche** [comment]
Doing some initial tests with spaces.

With spaces the publishers and other can select the dataset they want to edit by using a dropdown from the top menu inside the studio.

![Skjermbilde 2021-12-13 kl. 14.58.53.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/48b9d75a-513b-4667-bcfe-e2185eedd503)
![Skjermbilde 2021-12-13 kl. 14.59.05.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/70f730a6-fb56-44ea-af24-142525a3e016)

I added two dummy datasets just for testing the functionality inside the studio. The first is a copy from the original dataset we've been using so far but without the history `test with no history` (development). The second is an empty  dataset called `global production`.
 
We need to discuss the naming patterns for global datasets vs satellite pages.

We also need to look into exactly how this should work when previewing, on radix and the workflow in general.

Sanity is working on figuring out why copy with history doesn't work for our production dataset.

**Comment by wenche** [comment]
Need to catch up with the global satellite pages and an overall strategy for the workflow. Putting this on hold.

**Comment by wenche** [comment]
Covered by satellites pages
