### ISSUE TITLE
Define simple table

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#650]
Screenshot from current solution:

**Comment by adneforslund** [comment]
Where is the screenshot?

**Comment by wenche** [comment]
**MVP**

- Let's focus on the end user's experience
- The complex thing is the Sanity part
- The plugin that was showed during a meeting is not very good. It lacks semantic and, even worse, it's based on a simple text input. That makes it hard to add references (for links) and more structured data without a massive rewrite. This is an unknown cost. I would argue that this is a no-go for a MVP. 
- So what if we don't use a table in sanity... I would rather suggest that the data is collected in Sanity using an array structure. This might not be 100% editor super-duper user friendly, but it is closer to structured content and we can still improve with a more advanced table-like plugin at a later stage.

**Comment by wenche** [comment]
**Content in cells**

- External links
- Internal links (references)
- PDF
- Excel (or the files we support)
- Date
- Simple rich text

**Comment by wenche** [comment]
We went through the list of tables from Mette and tried to group them based on content and purpose. See Figjam.

Identified different scenarios and will create new issues for each of them.
1. Data heavy tables without links -> Import from CSV?
2. List with downloads and links -> Use the array structure with options for references
3. Descriptions list (like FAQs) -> Create a new key-value pair (<dl>) component?
4. Contact information -> Use the contact list developed for the event template. Consider if we need some additional information
5. Hard to organise, like time tables for conferences -> Look into how we can solve this.

We also need an issue for the web part of the table.
