### ISSUE TITLE
How can we handle /news/archive with  the globale pages?

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#651]
The original approach from way back was to have the /news/archive routes for the old news. The old news should be static generated pages from a blob storage somewhere, and they should not be updated. How does this fit with the global on code base to rule them all approach?

**Comment by fernandolucchesi** [comment]
Proposed solution is returning 404 for satellites that do not contain /news. We can also hide the menu item in sanity studio for these satellites to avoid confusion.

Drawback is the /news and /news/archive will always returning 404, even if you create a topic page with the slug /news for example.
