### ISSUE TITLE
Issues with EDS button and fixed height

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#653]
The EDS button component has a fixed height, and this causes some issues with long texts. The icon within a button also has a lot of space and a with of 24px, that's why we had to remove the + symbol for the Add to calendar button. Look into how we can improve this.

![Skjermbilde 2021-12-10 kl. 14.10.49.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/631498e1-7e12-4562-b7e7-15ca745f484b)

**Comment by nilsml** [comment]
@vnys

**Comment by vnys** [comment]
Hello, shiny happy people ❤️  Can you install `@equinor/eds-core-react@0.18.0-envis.1` and see how the button works for you?

**Comment by vnys** [comment]
Added css variables and feature flags so it’s possible to test locally or on a staging server if you add the feature flag _but_ you have to remove the padding that you’ve added to the EDS button in Envis, as that overrides what I’ve done in EDS.

**Comment by padms** [comment]
@vnys  Is it done?

**Comment by wenche** [comment]
Duplicate? https://github.com/equinor/energyvision/issues/843

**Comment by vnys** [comment]
> @vnys Is it done?

Yes, this can be closed. Same with #843.

**Comment by wenche** [comment]
@meols Is this working as expected now?
