### ISSUE TITLE
As an editor I need the option to define small text on type to cover needs for a small info text

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#655]
issue in Icon component

![sanity-icon-text.jpg](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/8ab5d5c7-3f49-4aad-aa46-b84d79ef2b75)

![aem icon-text.jpg](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/b4f44681-6e22-4c00-81f8-06f1983c184d)

**Comment by nicholas-haggerty** [comment]
@BirteThornquist We need to look into which components should have this, my feeling is any with Text but maybe there are exceptions?

**Comment by nilsml** [comment]
Requires investigation

**Comment by SvSven** [comment]
If this is limited to components with a rich text editor (like the Text component), it could be a "Footnote" component that can be inserted inside the rich text editor - similar to how we did the Quote, Factbox, and Image in the news article template.

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/bef4d8ca-5815-4afa-9ee2-c11388f8a537)

**Comment by meols** [comment]
@nilsml - do you need any input from Nick on this? This is an important one that editors will have to revisit a lot of pages to update.

**Comment by nilsml** [comment]
I am guessing @BirteThornquist and Nick will or have discussed this?

**Comment by nicholas-haggerty** [comment]
@nilsml We havent, but can of course. Doesnt seem like a particularly big one and as Sven pointed out above, the solution is there to place in the rich text editors for the components that feature that. Just need to define the font scale. Guess this isnt captured as part of the Dynamic font task that's going on?

**Comment by nicholas-haggerty** [comment]
Or even just add in here as 'small text' option?![icon rich text.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/c8db6f37-75dc-45c6-8896-6cd667855e5f)

**Comment by BirteThornquist** [comment]
I created a different issue for Footnote #898, as the small text style and footnote are to separate things.

**Comment by BirteThornquist** [comment]
![Skjermbilde 2022-03-01 kl. 15.14.37.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/e8026679-17d0-405b-a6f5-afa86132b7f7)
Add a new small text style in the font style drop down. By choosing/marking text the font size will be set to x-small (typescale 00). This font style shall be available in text component ingress and text content, short text with icon, fact box in news. @meols (I can not tag Nick) - are there other places you see the need for small text?

**Comment by adneforslund** [comment]
What is missing: figure out a way to make text small in editor as well

**Comment by BirteThornquist** [comment]
@adneforslund LGTM! Over to you @meols .

**Comment by adneforslund** [comment]
Note: Small text is available on all rich text fields, ingress, teaser etc

**Comment by meols** [comment]
@adneforslund - thanks! The small text looks good :smile: 
(both Nick and I have tested)
