### ISSUE TITLE
As editors we need a button that displays correctly or have a restriction in place for characters in the PROMO card

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#656]
![button length in promo tile.jpg](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/1d4200f2-d0ee-4fd4-a76c-841c3a78212e)

**Comment by wenche** [comment]
Duplicate #653

**Comment by vnys** [comment]
closing, duplicate of #653
