### ISSUE TITLE
As an editor I would expect to see correct spacing after using the bullet point setting in text component

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#657]
After defining bullet point settings, there is a spacing issue for either continuing on with normal (non bulleted text) or placing a CTA straight after.

The same spacing between the heading and the bullets should apply in the example below....

![spacing after bullests.jpg](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/81d18d23-05fb-4b83-8056-a00b5353bd81)

**Comment by nilsml** [comment]
Fixed!
