### ISSUE TITLE
Skip to content link uses router.push instead of replace

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#658]
If you click the skip to content link, it will add a hash link to the url, but is seems like it is using `router.push` and not `router.replace`. This is annoying with browser back.
![Skjermbilde 2021-12-13 kl. 09.29.35.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d05e2d60-963c-49a5-9e9d-8bd97f4d6a2a)

## Todo
Use replace instead of push

**Comment by SvSven** [comment]
This is using the @reach/skip-nav library: https://reach.tech/skip-nav

**Comment by adneforslund** [comment]
It opens up a new tab
