### ISSUE TITLE
Make languages in webapp dynamic

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#659]

**Comment by wenche** [comment]
Seems like something has broken with internal links and linking to routes? Ref. slack

**Comment by fernandolucchesi** [comment]
> Seems like something has broken with internal links and linking to routes? Ref. slack

Upgraded studio and seems to work again. Could you please double check?

**Comment by SvSven** [comment]
I can link to both news and topic page routes with the `linkSelector` component now, so looks like it's fixed?

**Comment by wenche** [comment]
Yes it is, verified yesterday. But we don't like things that suddenly works :grimacing:
