### ISSUE TITLE
how to handle frontpage / homepage

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#664]
We need a proper way to handle the front page inside the route structure in Sanity Studio. The current route builder feature are created for level one (top level / equinor.com/**careers**) and level two (child / equinor.com/careers/**students**) and not for the root level (equinor.com) We want to support to add the front page without changing the existing functionality. 

(If the PR #724 is merged: The current approach for adding the home page is just a temporarily version and not the best approach since we manipulate the slug field. This is even more important to avoid with #308.)

The suggested approach is to add a route to the home page as a singleton with a separate menu item inside the route structure. We need to discuss exactly how this can be done. :)
![Skjermbilde 2022-01-17 kl. 10.02.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2b2a918d-c984-4a02-88c8-14e914293d5a)

Also remember to make the dynamic home page have priority over the static home page in the web app

Related to #308

**Comment by nilsml** [comment]
@BirteThornquist and @wenche will look into this one
