### ISSUE TITLE
Improve background colour for promo tiles

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#667]
The way we select background colour for the promo tiles is inconsistent with the rest of the components, as it's selected on the tiles itself and not the container. 

I will add a fix with the no background class name for the promo container and turn off the class name for the tiles as a workaround, but this might be improved at some point.

**Comment by nilsml** [comment]
To be discussed before it is being worked on

**Comment by nilsml** [comment]
Decided to close this and fix this whenever the component is refactored or worked upon
