### ISSUE TITLE
As a publisher I need to be able to "unpublish" assets from the Sanity CDN

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#669]
Problem: 

1. Editor uploads a PDF that contains an error
2. User(s) have a direct link to the PDF on the Sanity CDN (for example in an email)
3. Editor notices error, uploads a revised version of the PDF
4. Since the content of this new file is different to the original, Sanity creates a new unique hash and URL for this file, while the old file and link remains.
5. Editor deletes asset in Sanity DAM, but because it was published to the CDN the file is still accessible
6. Users can still access old file since link is still intact.

How do we solve this to ensure that certain files become inaccessible on the CDN, as this could be a data integrity and/or security issue

**Comment by meols** [comment]
@fernandolucchesi - if this is possible, and we just need to send a request over slack channel with projectId / dataset / doc id, please do so :smile:

**Comment by meols** [comment]
And also request to replace display of «cryptic» file URLs on sanity server with «equinor.com»

**Comment by SvSven** [comment]
@meols We had a short discussion with Sanity about the URL structure, and it is definitely possible to use something like `https://cdn.equinor.com/123blabla` for assets - we wouldn't be the first client to request/do that.

**Comment by fernandolucchesi** [comment]
Closing this :)
