### ISSUE TITLE
Convert components with file links to new file management structure

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#671]
Depends on #670

For downloadable files we currently have an editor select/upload a file directly. With the new custom DAM for files this will instead be a document reference.

**Comment by SvSven** [comment]
Have updated `downloadableFile` to use the document reference system instead of direct file upload

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/c0d400a4-bbd3-4561-b538-5a7a19a33d4d)

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/2ca8b686-ef42-4259-9d5b-5a5fd10374aa)

I believe that is the only component we are actually using for files, could not find any other reference using `type: 'file'`

**Comment by SvSven** [comment]
This task is part of #670 so can be reviewed at the same time. In particular this is about selecting files on pages/articles.
Issue #670 is about the asset library in general (handling file uploads)

**Comment by SvSven** [comment]
@meols @nicholas-haggerty can you have a look at this? This is for selecting assets in news articles and on pages.
Can be tested by adding a downloadable file to the "More on this topic" list of links on a news article for example.

**Comment by adneforslund** [comment]
Bump this @meols

**Comment by nilsml** [comment]
Can we close this @meols @nicholas-haggerty? If something is still missing we can create new issues

**Comment by meols** [comment]
@nilsml  - there are still issues to clarify/discuss with this. Suggest to move this one to another lane

**Comment by nilsml** [comment]
Call for meeting next week to discuss asset library and outstanding issues/questions

**Comment by nicholas-haggerty** [comment]
I will close this one and keep the other assets related one. Will call for a meeting with Sven to go through the remaining concerns, and depending on outcome will create new issues to reflect.
