### ISSUE TITLE
Create c4 diagram for satellite sites

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#676]

**Comment by fernandolucchesi** [comment]
![c4](https://user-images.githubusercontent.com/23337266/146373734-d61eaf81-da7e-4fd8-ba86-a29be5c95d86.jpeg)

I will add to the documentation once the diagram is reviewed

**Comment by wenche** [comment]
LGTM :thumbsup: Asked Nils Magne the c4 expert Lunde wether we need to include the existing DAM in this diagram, but I guess that's not necessary?

**Comment by SvSven** [comment]
So this has probably been covered in discussions/meetings about the satellite sites, but just to confirm the way I understand this is as follows:

- Global (EN/NO) has its own dataset and is hosted on Sanity servers
- Satellite sites each get their own dataset (one per site) and these studios are hosted on their own Radix instance (one per site)
  - So there is a Brazil dataset with a Brazil studio hosted on Radix and a Brazil Next.js instance on Radix
  - Then there is a UK dataset with a UK studio hosted on Radix and a UK Next.js instance on Radix
  - etc
- Codebase is the same across the global and satellite sites, same code same repo
- We use env variables in the CI setup to deploy to each individual site accordingly

**Comment by nilsml** [comment]
This has now been incorporated in the existing drawings. May use as reference for the architecture contract though.
