### ISSUE TITLE
As a developer I want to read and find out how to create a new satellite site from the documentation

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#677]
## Acceptance criteria
1. [Criteria 1]
1. [Criteria 2]

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Extra focus on usability
- [ ] Test for portability
- [ ] Test for accessibility
- [ ] Create automated acceptance test/smoke test
- [ ] Perform performance and load test
- [ ] Perform user testing
- [ ] Perform security testing

**Comment by wenche** [comment]
Duplicated by #712
