### ISSUE TITLE
Create switch logic for languages based on sanity datasets

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#678]

**Comment by wenche** [comment]
@fernandolucchesi  Do you mind to describe what I should do to verify this? I'm not sure if I understood 100% the workflow and the current limitations

**Comment by wenche** [comment]
What I did (by reading the code)
- Remove `production` as the key for NEXT_PUBLIC_SANITY_DATASET in  .env.local
- Added some console.logs.
Result
![Skjermbilde 2021-12-22 kl. 11.44.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/9afcd53c-8196-4bfc-9615-b302a7440d31)

- Removed `production` from .env
Result
![Skjermbilde 2021-12-22 kl. 11.46.17.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/cc36354d-108d-42c1-9e15-cc089023f538)
and 404 for the front page on localhost:3000 :thumbsup:

So the web part seems to work as expected, if you know how [env variables work in Next](https://nextjs.org/docs/basic-features/environment-variables#default-environment-variables). Do you think it will be easier to understand for everybody if we remove the default .env file? If we are using the variables to control the  global satellites, it might make less sense to use default env variables? Should we rather just use the env.local?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Do you mind to describe what I should do to verify this? I'm not sure if I understood 100% the workflow and the current limitations

Sure! For the studio, check that modifying supported languages on the (studio/language.js) file affects the supported languages on the studio: 
![image](https://user-images.githubusercontent.com/23337266/147079392-f4a87e91-8170-47b5-946c-55224bf3e5ed.png)
![image](https://user-images.githubusercontent.com/23337266/147079442-07dc3207-63a6-448d-ab02-1a9bd8730807.png)

For the web, similar behaviour should exist (web/languages.js), you can test the /test page:
![image](https://user-images.githubusercontent.com/23337266/147079862-4fdd736e-e81d-44a6-9184-cd2dce5404d8.png)
![image](https://user-images.githubusercontent.com/23337266/147081167-6f5fe208-83c6-400f-a772-fff7a2b5f40c.png)
![image](https://user-images.githubusercontent.com/23337266/147081311-cfa5bbee-7d96-4f34-96cc-d54eb255420c.png)

**Comment by wenche** [comment]
![Skjermbilde 2021-12-22 kl. 11.54.11.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/52e7b129-d56f-4d38-86ac-a401868480f4)

(This is probably a new issue) Are we able to create an escape hatch for the satellite pages before we check AEM?

**Comment by fernandolucchesi** [comment]
> ![Skjermbilde 2021-12-22 kl. 11.54.11.png](https://camo.githubusercontent.com/7b53a497b217b5c43680c27ec2d1d54bd771b794af8f8a67ba129014d49577c8/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566623761613962363533643531333562623863353066352f35326537623132392d643536662d346433382d383661632d613430313836383438306634)
> 
> (This is probably a new issue) Are we able to create an escape hatch for the satellite pages before we check AEM?

Yes, in the same way that we will handle news/archive in #651

**Comment by fernandolucchesi** [comment]
Remember to restart the server after modifying languages.ts file in the web folder, since it is used during the build

**Comment by wenche** [comment]
LGTM :thumbsup: 

One note about the env.template, please add a better description to be kind to future self :)
