### ISSUE TITLE
As an editor I want to create data-heavy tables based on Excel to minimise work

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#682]
These tables are mostly related to investors and are tables without links that are received as Excel sheets from different sources. Time is a factor here, there might be a tight schedule from where the table data is received to publishing time.

https://www.equinor.com/en/investors/our-dividend/analysts-following-statoil.html
https://www.equinor.com/en/investors/our-dividend.html
https://www.equinor.com/en/investors/our-dividend/consensus.html
https://www.equinor.com/en/investors/our-dividend/internal-gas-price.html
https://www.equinor.com/en/what-we-do/floating-wind/how-hywind-works.html

### Challenges with current solution
The tables are not accessible since there is no indication of the headers (all the cells are adjacent cells in the table body tag). We need to find a way to improve this.

### Suggested solution
To be decided when we start to work on this issue. Suggestion atm is to upload a CSV file and look into how we can use that as a basis for semantically correct table markup

## Acceptance criteria
- Tabular data can be imported into Sanity
- Data can be shown on the web in a semantically correct format

**Comment by meols** [comment]
@nilsml @fernandolucchesi - we'll have a discussion in the editorial team if we can live without this component for go-live, and put it in the backlog instead. Please don't spend any time on it until we have confirmed.

**Comment by nilsml** [comment]
Ok @meols, we'll put this back in the backlog for now
