### ISSUE TITLE
As an editor I want to create tabular data with internal references and links to present information in a structured way

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#683]
Some of the tables in the current solution have a lot of internal links and attachment. It's important for the long run that the links use the same referencing as the rest of the page and not just are external links. 

### Suggested solution
Since Sanity is headless, a table in the web does not have to be a table in Sanity. It can be whatever sort of structured content. 

Suggested solution is to create an array like structure with options to add 
- Internal references
- External links
- Files
- Date
- Text
- Number

**Comment by nicholas-haggerty** [comment]
Refinement issue @adneforslund If ingress isnt used, the title sits too close to the top of the table![spacing of title on table component.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/058da335-1b40-44a9-819d-ba0e78ae679c)

**Comment by nicholas-haggerty** [comment]
@adneforslund @wenche @meols Question on the input fields for the table. There are issues with Date and Number (as flagged by Mette) Do we actually need different fields for this? The text field allows full flexibility to add characters with no restrictions. Do we even need the Date and Number field? Or can we just use Text field for all with Download and Link in addition. For example I cannot add % to a number in the Number field, but can in the Title

**Comment by nicholas-haggerty** [comment]
Refinement issue @adneforslund The table does not display 100% width. Should it? Seems odd especially if we would have tables with differencing columns following on page example here and screen grabbed![table width not 100%.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/73271a92-5dbf-4452-8232-5775a5ce04b8)

https://studio-argentina-energyvision-dev.radix.equinor.com/desk/topicContent;4ed6ff04-7452-4190-bf84-15ffb0e29671%2Cview%3Dpreview

**Comment by wenche** [comment]
@nicholas-haggerty  I haven't been involved in the final requirements for this topic, but when Birte and I did some initial sketching for this before Christmas, we talked about a date field to make the date format consistent across tables and a number field (that was actually for pure numbers) to be able to use `monospace` font for that (that's something the EDS table provides, an "is number" option)

**Comment by adneforslund** [comment]
@nicholas-haggerty When it comes to dates, editors will of course be able to use the text field to create dates instead of the date field, but having a date field give some advantages as well. For example a semantic representation of date in HTML plus  special styling, as Wenche mentioned

**Comment by adneforslund** [comment]
@nicholas-haggerty I agree that the number field is not very practical as it is today, and should probably be changed, but not removed, as it can also be used to give numbers special formating and styling

**Comment by meols** [comment]
@adneforslund - is this a sign to stop using numbers? :smile: - (link to example page](https://equinor.sanity.studio/desk/topicContent;b59ddfae-d382-4ffa-b46a-b0c59de2126d)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/f3cf141d-0c9d-4b9a-9a3e-920b48fc613b)

**Comment by adneforslund** [comment]
@meols I just changed the type, they can be used again

**Comment by nicholas-haggerty** [comment]
Refinement issues @adneforslund @meols 
1. I have given two separate tables the same background as they belong in the same module, first we have the usual spacing issue, but also now I have a white strip between the two tables which is unexpected.
2. If I do not include a Table header (which in the example below it might not be needed as we have year in title) I don't get a warning that I cant do this, but when I preview I get a 500 error message. Should either be allowed to not include a table header or be a requirement.

https://equinor.sanity.studio/desk/topicContent;9d717af4-7950-4e91-a395-9d1c60f9fe51%2Cview%3Dpreview

**Comment by nilsml** [comment]
@nicholas-haggerty can you retest this one?

**Comment by nicholas-haggerty** [comment]
@nilsml
1. If a table header is not used/required the component allows it but shows a 500 error message on preview. This is now solved and editor is able to not feature table headers and component works as expected.
2. Date should be displayed as British format on the date field option. This is **not** fixed. Should be Date Month Year 22 February 2022. Now it displays Month, date year.
3. Tables show in different widths. Should be 100% full column width. This is **not** fixed
4. White stripe shows between same coloured background. Fixed (not an issue on the published page)

**Comment by adneforslund** [comment]
should be fixed now @meols

**Comment by fernandolucchesi** [comment]
@nicholas-haggerty

**Comment by meols** [comment]
Checked as well and closing :smile: @nilsml @adneforslund  (not able to tag Nick)
