### ISSUE TITLE
As an editor I need a way to present an agenda

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#686]
Some of the tables were hard to categorise and that was mainly related to some events where an agenda was added. Look into different solutions for this. It's not heavily used, can a simple approach be to use the text field? (to maximise return of investment)

https://www.equinor.com/en/what-we-do/autumn-conference-2018.html
https://www.equinor.com/en/what-we-do/autumn-conference-2019.html
https://www.equinor.com/en/what-we-do/calendar/autumn-conference-ir-seminar-2018.html
https://www.equinor.com/en/what-we-do/calendar/Equinor-Virtual-Supplier-Day-2020.html
https://www.equinor.com/en/what-we-do/calendar/etv-technology-showcase-2018.html

**Comment by fernandolucchesi** [comment]
We can live without it
