### ISSUE TITLE
Create CI/CD for deploying multiple instances of Sanity Studio

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#690]
We need to setup a job to deploy multiple instances of the studio in our pipeline. Each studio instance should connected to a different dataset, representing a satellite.

Connected to #649

**Comment by nilsml** [comment]
We have found a good way of solving the CI/CD part of this now, so adding new satellite sites is a simple task. What is lacking for the Sanity part is the Brandmaster setup. Perhaps create a new issue for that @fernandolucchesi and close this?
