### ISSUE TITLE
Implement cookiebot consent manager for dynamic pages

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#696]

**Comment by padms** [comment]
Everytime when the router.asPath changes, Cookiebot.runScripts() should be called in in order to hide/show the components that are said to set cookies based on users consent. This is the optimal solution. But this does not work when shown in preview mode inside sanity iframe. ( Because cookiebot loads another script in an iframe which is blocked). I could not find a solution to make cookiebot work in the preview mode. 
So conditionally called the Cookiebot.runScripts(), this would show both the Component and consent request Container, in preview mode (iframe). As a work around editor can view the page in new window.

**Comment by wenche** [comment]
But what about the errors on the console? Do we have to live with them?
![Skjermbilde 2022-01-13 kl. 16.09.19.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ff238ba6-5504-4992-86b2-9e94a8b04339)

**Comment by fernandolucchesi** [comment]
Hi @vnysm, have you investigated how to load the script tags dynamically? Any inputs on this issue?

**Comment by nilsml** [comment]
@vnys Maybe you can give some hints and tips about this one?

**Comment by vnys** [comment]
https://github.com/equinor/energyvision/blob/main/web/pages/_app.tsx#L70-L79

That was just to solve my problem with Cookiebot and Gitpod, not sure how robust that is for other scenarios.

**Comment by adneforslund** [comment]
to be closed?

**Comment by nilsml** [comment]
The consent dialog looks a little bit of on Firefox:
![image](https://user-images.githubusercontent.com/1836295/150989690-4707d7ea-ecd4-49ed-8648-eeb064654426.png)
