### ISSUE TITLE
Add Siteimprove analytics script

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#699]

**Comment by meols** [comment]
@nilsml - at some point we need to add  the Siteimprove analytics script.
Link to article: https://help.siteimprove.com/support/solutions/articles/80000448448
Our account code: <script async src="https://siteimproveanalytics.com/js/siteanalyze_6003171.js"></script>

**Comment by nilsml** [comment]
Could Tag Manager be used?

**Comment by meols** [comment]
@nilsml  - is this a question to me? This is developer things to me. (We would need to have both Goggle analytics/tag manager and Siteimprove implemented.)

**Comment by wenche** [comment]
@meols  No, just something to investigate when we do this issue

**Comment by nilsml** [comment]
Dependent on recent discussions on Google Analytics and GDPR. Do not prioritise this task until we know what to do.

**Comment by meols** [comment]
@nilsml - please add this to the priorities. We will not continue using google analytics. We will have Siteimprove as our main source for analytics, accessibility etc., and it needs to be implemented on all sites.

**Comment by nilsml** [comment]
Let's discuss this in the next sprint planning meeting. Could be a good candidate @meols

**Comment by nilsml** [comment]
Google Tag Manager actually can be used.

**Comment by nilsml** [comment]
Need to figure out if we should add Google Search Console. @meols to check this

**Comment by adneforslund** [comment]
SiteImprove is added, splitting GTM to new card

**Comment by meols** [comment]
@nilsml - yes, we will continue using Google search console, so please implement that as well

**Comment by nilsml** [comment]
@fernandolucchesi assess and close

**Comment by fernandolucchesi** [comment]
@nilsml, waiting for access so I can test it properly (finished my account setup/requested access today). From what I see in the code it looks like the same script is used for all sites. I want to check if SiteImprove splits the data in their panel by domain, in this case it will be fine. If not I will need to do some changes to this boy here.

**Comment by meols** [comment]
@fernandolucchesi - let me know if access to GTM and search console isn't in place. I gave you access to Siteimprove yesterday and you should have received an invitation email.

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi - let me know if access to GTM and search console isn't in place. I gave you access to Siteimprove yesterday and you should have received an invitation email.

all good with the access, thank you
