### ISSUE TITLE
Use cache when deploying web instances

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#700]
We can use similar approach to what has been done with the CI/CD for studios

**Comment by fernandolucchesi** [comment]
![image](https://user-images.githubusercontent.com/23337266/147939298-52cf7865-a8c8-4304-8970-793b53b9860c.png)

Trick here was building the global instance prior to the satellites instead of in parallel. By doing this we guarantee that a cached version of the node_modules will exist for all other satellites instances.

**Comment by nilsml** [comment]
Like discussed I think we should use `setup-node` also for web to be consistent.

**Comment by nilsml** [comment]
Has this been merged now @fernandolucchesi ?
