### ISSUE TITLE
Document satellite site configuration

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#712]
- [ ] Technical documentation
- [ ] What is needed in terms of authorization
- [ ] Cookie handling
- [ ] Analytics

Note to self: Remember to document the environment variables and secrets like `SANITY_STUDIO_PREVIEW_SECRET`, `SANITY_PREVIEW_SECRET`

**Comment by wenche** [comment]
### FAQ
Q: I get a warning about "missing template" when I try to preview on localhost:3333
A: There's a mismatch between the defined dataset in the Sanity studio and in the web
![Skjermbilde 2022-01-12 kl. 19.54.46.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/fd8aaee6-919b-4c50-a871-68531d58b08d)

**Comment by wenche** [comment]
@fernandolucchesi 
When I have added the secrets on Radix, I'm stuck here. Do you remember if the Restart button was enabled or did you click Stop then Start?
![Skjermbilde 2022-01-20 kl. 14.01.51.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/df1ff05b-4351-43de-a1a3-60860e69cf8f)

**Comment by wenche** [comment]
@fernandolucchesi  I followed your guide and was able to create the Argentine version. One issue with the web and that the pipeline to deploy the web wasn't run when I changed the config files on the root level. That one should now be solved by adding these two files to the files/folder that trigger the action
