### ISSUE TITLE
Make sure that the Preview for each satellite sites points to correct web

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#713]
**As an editor I want to have a preview showing data for the satellite site I am currently editing in Sanity Studio**

## Acceptance criteria
1. Preview for a satellite site is pointing to corresponding web

## In order to ensure good quality we should
- [ ] Perform functional testing

**Comment by wenche** [comment]
On my localhost this work as expected. 
Steps for testing
1. Use dataset `german` in my studio
2. Use dataset `german` in my .env.local file 
3. Start sanity on localhost:3333
4. Open a document
5. Split pane -> preview
6. Click "Open preview" -> cookie is set
7. Verify that preview works, including for drafts. In my example, only Güten tag is published.
![Skjermbilde 2022-01-12 kl. 20.00.23.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/7c58c7d1-f814-43b3-b03c-ace4cb0fd072)
