### ISSUE TITLE
Cannot add new Brandmaster image after removing first

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#719]
Reported in by editors

Steps to reproduce:

1. Select image from Brandmaster on image component
2. Remove image using the "Remove" button on the image
3. Select another image via Brandmaster
4. Seemingly nothing happens, or it takes a very long time to update

**Comment by wenche** [comment]
@SvSven Did Sanity reply?

**Comment by SvSven** [comment]
I had forgotten about this one; I recall we had several issues with it at the time and this may have been a symptom of something else.
Need to investigate if this is still actually a problem or not.

**Comment by SvSven** [comment]
Have tried it a couple of times now but can't reproduce it anymore.
@nicholas-haggerty @meols have you or any of the other editors noticed this recently? Might be it resolved itself, or we fixed it when we did something else.

**Comment by nicholas-haggerty** [comment]
@SvSven bit hard to test this one as right now I cant even seem to add an image from BM. Links through fine, but when I select the image it doesnt load into the studio!

**Comment by nicholas-haggerty** [comment]
Ill close, and just monitor if it pops up again
