### ISSUE TITLE
Uploading asset from Brandmaster sometimes fails

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#720]
Occasionally when selecting an image from Brandmaster, an error will show on Sanity stating that the upload could not be completed.

Have not been able to find a pattern to find out what/when/why

**Comment by SvSven** [comment]
Have reached out to Sanity to see if there is a way for us to see the error logs or debug these uploads

@meols @nicholas-haggerty can you try to take a screenshot/recording/copy the error text when this happens so that we have the exact error?

**Comment by SvSven** [comment]
For some SVG files it seems to fail when the file does not have a description in Brandmaster, which is also what the error in the console says. Not sure if this is a new way Sanity handles `null` values for these fields, but can confirm that we can fix this easily on our end by conditionally passing these meta fields. This may also be the cause for the non-SVG images that are failing.

**Comment by SvSven** [comment]
@meols @nicholas-haggerty 

The fix for this has been pushed and should be in production now.
If you could test with a couple of images that were giving you problems before to see if this fixes it that would be great.

**Comment by nicholas-haggerty** [comment]
@SvSven Tested with image and SVG that didnt work previously (no description) Now working as expected. Nice work
