### ISSUE TITLE
Update media library used in Brandmaster integration

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#721]
We are currently linking to the wrong media library in Brandmaster with our integration.
This should be updated to the one the editors are used to using for dotcom

**Comment by SvSven** [comment]
@meols / @nicholas-haggerty to check with Brandmaster for the correct link we should use

**Comment by meols** [comment]
@SvSven @nicholas-haggerty - I have talked to Yngve, who said that it shouldn't matter which archive we link to. Users should only see images they have access to, e.g. meaning that I will see historical images and images with a red warning triangle for missing consent forms, but a user without specific access wont see those.

**Comment by wenche** [comment]
Is the conclusion then that this is not needed?

**Comment by SvSven** [comment]
I think we can close this one yes
