### ISSUE TITLE
Add asset source fields & filters to Media plugin

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#722]
For GDPR reasons, the editors need to be able to see which images were uploaded from Brandmaster as well as have a way of finding specific Brandmaster images

For this we need to fork and edit the Media plugin ourselves, as these changes were not deemed relevant enough to be added to the plugin itself:

Asset source information: https://github.com/SvSven/sanity-plugin-media/commit/ebdecbc799fe29e38a3a7019081f09c2c041d3ae

Asset source filters: https://github.com/SvSven/sanity-plugin-media/commit/638c991f0f706de3d15399713865dcc097a15361

**Comment by SvSven** [comment]
Having the ability to manually edit these fields might be very useful as well, in cases where editors have to download an image from Brandmaster and upload them manually. For example due to #720

**Comment by SvSven** [comment]
Need to discuss how to handle this for long(er) term as well; do we use the workspace or publish it as a package? If as workspace, do we keep the code in the plugins folder or do we use a dedicated folder in this repo?

If not workspace, do we fork it into a dedicated repository within the Equinor org, or keep it as part of our monorepo?

It's important to make sure that maintaining this, being able to pull in upstream changes, and potentially switching back to the upstream plugin is as painless as possible

**Comment by nilsml** [comment]
I think we should put this separate from the project and manage it in its own package, either in GitHub or npmjs.

**Comment by SvSven** [comment]
Hosting it as a GitHub package is an option, but would cause conflicts with using multiple package sources as per experience from WellX. Though maybe that has since been fixed given that Microsoft now owns both GitHub and NPM 🤷‍♂️

**Comment by nilsml** [comment]
@meols Is this still needed?

**Comment by fernandolucchesi** [comment]
I believe this was fixed on #1859.
@meols what do you think? Can we close this?

**Comment by meols** [comment]
Yes, agree @fernandolucchesi - closing it :smile:
