### ISSUE TITLE
Investigate how to hide files (pdf, xlsx, etc) in Media plugin

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#723]
Since these files are handled by the asset library, they should ideally not show up in the media plugin; keeping the media plugin view for images only.

Relates to #722 if we need to do any code changes in the media plugin for this

**Comment by nilsml** [comment]
Sync with Sanity since they are doing changes to the plugin these days.

**Comment by SvSven** [comment]
Last news from Sanity is that the original author of the plugin now works for Sanity and that they have "big plans" to improve this plugin, however they did not have a timeline or roadmap for this - so I think we should work on the assumption that this is not coming soon and we should look into possibilities of solving this ourselves.
