### ISSUE TITLE
Use a fallback for reference filters for unpublished content

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#725]
### Description
Since the intl plugin for whatever reason adds the intl fields (_intl: en_GB) on publishing for the base language, we need a fallback to be able to filter references for unpublished content. Could we just use the base language as the fallback if there's no _lang value? (We will then need a more robust way to define the base language)

![Skjermbilde 2022-01-11 kl. 14.19.08.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b0190b62-4a8a-4fd8-9f8b-5fc688f0f3e8)![Skjermbilde 2022-01-11 kl. 14.20.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/7fcd2840-9266-4938-be45-cf66ead36a7b)

### Examples of the errors I see
Runtime error (will add a guard here)
![Skjermbilde 2022-01-11 kl. 14.23.30.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/4520f978-840b-4f53-bc23-562491a02f69)
Mix of Norwegian and English references
![Skjermbilde 2022-01-11 kl. 14.24.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/91801aca-eb5b-4cba-aa1c-fae0f88db83d)

**Comment by nilsml** [comment]
Ask Simeon in the weekly meeting about this

**Comment by wenche** [comment]
We made a fallback in the landingPage.ts, I think we might just do it as simple as this...? Because the translated document will have the language information added when it's created, and not when it's published as with the base language :(
![Skjermbilde 2022-02-09 kl. 09.07.03.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/be0dc06a-fc8c-4422-8cfc-11de22e107aa)
![Skjermbilde 2022-02-09 kl. 09.15.07.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/04e6dc12-1828-4ae3-bdc2-4bb9d610d2b1)

**Comment by fernandolucchesi** [comment]
@wenche, can you take a look at this? :)

**Comment by wenche** [comment]
### Test
 News
- [ ] Internal link News EN -> reference to EN route and EN news
- [ ] Internal link News NO -> reference to NO route and NO news
- [ ] More on this topic link News NO -> reference to NO route and NO news
- [ ] More on this topic News EN -> reference to EN route and EN news

- [ ] Internal link Text block Topic EN -> reference to EN route and EN news
- [ ] C2a link Text block Topic EN -> reference to EN route and EN news
- [ ] Teaser link  Topic EN -> reference to EN route and EN news
- [ ] Accordion internal link  Topic EN -> reference to EN route and EN news
- [ ] Internal link Text block Topic NO -> reference to NO route and NO news
- [ ] C2a link Text block Topic NO -> reference to NO route and NO news
- [ ] Teaser link  Topic NO -> reference to NO route and NO news
- [ ] Accordion internal link  Topic NO-> reference to NO route and NO news


Except for the gotcha with the translated document that does not respect the filters, this look really good :thumbsup:
