### ISSUE TITLE
UI corrections for REMIT TABLE component

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#726]
The Remit table does not look as it in production today. The production Remit table uses list and not table. Need to improve UI. ![image.jpg](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/4b224b2e-2493-4071-b2a0-988bf0772ba2)

**Comment by BirteThornquist** [comment]
To get this Remit information to be presented in a readable way will require a bigger restructuring of the information. Our table component does not support accordion for instance (View history links). We would also have to make a wider table and possible pagination as the scrolling is not a good solution. I had a quick chat with @meols and she shall find out if this remit table/list really is something we need, or if linking to https://umm.gassco.no/ could be sufficient.

**Comment by nilsml** [comment]
Waiting for confirmation on the need of this page

**Comment by nilsml** [comment]
Waiting for FINAL final approval for removing REMIT table

**Comment by meols** [comment]
@nilsml - then it's official :smile: It is confirmed that we will **not** continue with the REMIT table on equinor.com, so I'm closing this card!
