### ISSUE TITLE
Italic display in preview and published

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#728]

**Comment by meols** [comment]
We have used italic font under Telecom worker on this page:
https://energyvision.app.radix.equinor.com/careers/apprentice-disciplines
Doesn't display Italic either in preview or published in Chrome. Nick was able to see in his Edge, Mette didn't see it in Edge either.

**Comment by nilsml** [comment]
Need to investigate this one

**Comment by wenche** [comment]
We don't actually do much beyond the default Sanity behaviour for this. Screenshot from my Chrome and Edge respectively

![Skjermbilde 2022-01-17 kl. 13.38.25.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/5b408bfe-73bb-4860-b60a-87af9e58b9e9)
![Skjermbilde 2022-01-17 kl. 13.42.13.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f444a740-8703-4323-b2c0-5c743b3a99ca)

I don't know why it's not displayed properly for some users, but we should probably set this style ourself explicitly if there's different browser defaults.

`<strong> and <em> are semantic - they specify that the enclosed text should be "strong" or "emphasised" in some way, usually bold and italic, but allow for the actual styling to be controlled via CSS. Hence these are preferred in modern web pages.` [Source](https://stackoverflow.com/questions/271743/whats-the-difference-between-b-and-strong-i-and-em)

**Comment by wenche** [comment]
@meols I can't reproduce this is my browsers, so I fix things blindly here :sweat_smile: 

Can you test and see if my change worked or not?
