### ISSUE TITLE
Iframe adjustments

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#730]
### Acceptance criteria

- Publisher can add an optional description for the iframe
- Publisher can add an optional call to action for the iframe (one link)
- Publisher can add an optional ingress for the iframe 

### Note
 The new options should only be applied for the Topic page template

**Comment by meols** [comment]
Due to layout requirements we would need to add a (optional) descriptive/caption text field under iframe, to provide a description of the content to appear below the video/iframe component
We also need a (optional) call to action placed in iframe component to appear below the video/iframe component. See this page: 
 https://energyvision.app.radix.equinor.com/careers/apprentices

**Comment by wenche** [comment]
@BirteThornquist  I can add the fields in Sanity, but let's see how it should look like in the web tomorrow aka Envis day

**Comment by wenche** [comment]
Need to align with @BirteThornquist for this one.

**Comment by wenche** [comment]
We want to test the [last alternative design in Figjam](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4104%3A79229) for this.

**Comment by BirteThornquist** [comment]
I added an ingress, a capture text and a CTA for the iFrame component, find the design [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4104%3A79269)
![Skjermbilde 2022-01-24 kl. 10.11.47.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/f83c45ed-dca3-4c7f-ae58-8450c5dd8a79)
All the fields will be optional.

**Comment by SvSven** [comment]
Keep in mind that the iframe is used on the news article and event templates as well as the topic pages.

**Comment by wenche** [comment]
@BirteThornquist  Let's fine tune the spacings tomorrow
![Skjermbilde 2022-01-26 kl. 14.54.27.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c7ec64a5-1f13-4d82-ae65-dc2a93a3d821)

**Comment by BirteThornquist** [comment]
@wenche LGTM! Please review @nicholas-haggerty @meols

**Comment by nicholas-haggerty** [comment]
@BirteThornquist looks good to me.
