### ISSUE TITLE
Image component credits

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#733]
### TODO
- Figure out how this should look like (UX)
- See if we should improve the label/description/placeholder for the related fields in Sanity to make it easier to use for the publishers

**Comment by meols** [comment]
Credit should be on second line, an/or have a different text treatment on the Credit text

**Comment by wenche** [comment]
Related to #705

**Comment by BirteThornquist** [comment]
The image credit will have a slightly different color (grey60, grey40 on slate blue background) than the caption text. I don't think it should be on a separate line as a rule, though. I have set the text line length to max 560px long. Design example [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4193%3A82380)![Skjermbilde 2022-01-28 kl. 16.58.55.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/35577d0b-c805-4d48-9ad8-cebc35113400)

**Comment by adneforslund** [comment]
@BirteThornquist Is the design on this good to go?

**Comment by BirteThornquist** [comment]
@adneforslund Yes it is.

**Comment by fernandolucchesi** [comment]
@BirteThornquist, can you check?

**Comment by fernandolucchesi** [comment]
@wenche, can you please take a look at the refactored component?

**Comment by BirteThornquist** [comment]
@fernandolucchesi I think the difference between the caption and credit is too small, unfortunately. We cannot go lighter on the text color, so we need to test using font weight or size.

**Comment by wenche** [comment]
From a technical perspective, this is good to go :thumbsup:

@BirteThornquist  Do you want to postpone the credit text style? Or do we have a plan?

**Comment by BirteThornquist** [comment]
@fernandolucchesi @wenche After some testing I do think it is best to have the photo credit on a separate line instead of mixing different text styles. Design is updated in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4193%3A82354) Agree?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi @wenche After some testing I do think it is best to have the photo credit on a separate line instead of mixing different text styles. Design is updated in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4193%3A82354) Agree?

Sounds good to me!

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi @wenche After some testing I do think it is best to have the photo credit on a separate line instead of mixing different text styles. Design is updated in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4193%3A82354) Agree?

This is ready to be re-re-reviewed @wenche @BirteThornquist

**Comment by wenche** [comment]
![Skjermbilde 2022-02-08 kl. 16.25.04.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/9ed75c8c-6d60-46fa-9cef-efe13250b86c) LGTM :thumbsup: My heart is crying for your deleted code tho :sweat_smile:

**Comment by BirteThornquist** [comment]
LGTM @fernandolucchesi Moving to review by @meols

**Comment by nicholas-haggerty** [comment]
![photo credit.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/5d042cc6-deec-4eec-b551-0a2ea3c0472e)

**Comment by nicholas-haggerty** [comment]
@BirteThornquist @meols not seeing the change on the website. This page: https://energyvision.app.radix.equinor.com/careers

**Comment by fernandolucchesi** [comment]
@nicholas-haggerty, the change is only the Credits going to a new line. It used to be in the same line.

**Comment by nicholas-haggerty** [comment]
@fernandolucchesi @BirteThornquist,  so no text treatment (size/font variant)? Just moving Credit to a new line?

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi @BirteThornquist, so no text treatment (size/font variant)? Just moving Credit to a new line?

Yes... after a lot of back and forth...

**Comment by nicholas-haggerty** [comment]
cool, thanks..... @meols I can confirm the credit is on a second-next line and long caption doesn't extend full image width.... You will have to close as I merely a guest!
