### ISSUE TITLE
Quote component - If no image placed, text should expand to full width.

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#734]

**Comment by meols** [comment]
For the quote component: If no image placed, text should expand to full width.

**Comment by wenche** [comment]
Pay attention to that the Quote component is used for both the News and the Topic Page templates. Might be worth to check out #634 as well if we changes behaviour across the two occurrences

**Comment by BirteThornquist** [comment]
Hi @adneforslund The quote text should follow the main column right for both news and topic if no image is added. You will see the design for quotes in topics [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4210%3A82918) with a contextual example to the left, and [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=1174%3A4291) for the news article with contextual example below. 

![Skjermbilde 2022-02-01 kl. 11.13.17.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/f917137c-f92f-4d4e-be49-53db338cadf1)

**Comment by wenche** [comment]
@BirteThornquist @adneforslund  One thing: In the topic page, the quote follows the margins for the Text block component

![81cd5d75-dbcd-402c-ac8e-18c762f2af03.jpeg](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/cca31cae-4bdf-4c6c-98a9-32223ed9dfe6)
```
padding: var(--space-3xLarge) var(--layout-paddingHorizontal-large);
max-width: var(--maxViewportWidth);
```
According to Figma, it should drop to the left like in the news article? Is that correct and if so we should change this in the code :)

**Comment by adneforslund** [comment]
@meols @BirteThornquist

**Comment by adneforslund** [comment]
Name does not show if title is missing

**Comment by BirteThornquist** [comment]
@adneforslund I have outlined all the variations of the quote component [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4379%3A81138)  I have also placed the different variation in a topic template [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4379%3A81751) Please take a look and let me know if anything is missing or unclear.

**Comment by adneforslund** [comment]
New review @BirteThornquist por favor

**Comment by BirteThornquist** [comment]
hi @adneforslund Looks like the quote still drops out to the right from the main column? In the example below for the quote with image, the text drops right:  ![Skjermbilde 2022-02-21 kl. 10.15.44.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/d6b6aa15-c7a3-4db6-afe6-bf84884f296d)
And for the short quote text, the name should be right aligned to the quote text
 ![Skjermbilde 2022-02-21 kl. 10.24.40.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/ba1fa553-e676-4a43-bb2d-2d1f236a966a)

**Comment by adneforslund** [comment]
@BirteThornquist Can you look again?

**Comment by nilsml** [comment]
@meols and @nicholas-haggerty to verify

**Comment by meols** [comment]
Thanks - Nick has checked and confirmed that this is good now, so closing
