### ISSUE TITLE
Add brandmaster envs to the satellites studios and automate secrets

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#736]
The secrets for brandmaster to work with the satellites studios are missing:

`SANITY_STUDIO_BRANDMASTER_URL,  SANITY_STUDIO_BRANDMASTER_PLUGIN_SOURCE`

These secrets might need to be passed as arguments to the docker file, following the same approach used for the `sanityPreviewToken` (check if needed during build or not)

**Comment by wenche** [comment]
Labeled this with on hold since we do not actually need news letters for the satellites. We need to figure out how to proceed with this task.

**Comment by nilsml** [comment]
This is actually needed

**Comment by fernandolucchesi** [comment]
Hi @nilsml, can you review this one? The approach used was fetching the secrets from github, passing as arguments to the dockerfile, and converting to an environment variable - as we did during xmas.

The only secrets that now needs to be manually added are:
```
        - BRANDMASTER_EMAIL_CLIENT_SECRET
        - BRANDMASTER_EMAIL_PASSWORD
```

For the global web instance

**Comment by nilsml** [comment]
I will have a look

**Comment by nilsml** [comment]
Seems to be working. Closing!
