### ISSUE TITLE
Spacing issue between components

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#738]

**Comment by nilsml** [comment]
Need to have a second look at this, and test with different spacings between components with the same background colour.

**Comment by BirteThornquist** [comment]
@meols  I see that some pictures used have a white space under which causes a big space between the image and credit text. Think you should fix/change these ![Skjermbilde 2022-03-18 kl. 15.15.46.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/a047f2c2-9e25-44e5-8761-d1a4fa794711)

![Skjermbilde 2022-03-18 kl. 15.15.30.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/905e9ebf-8c3d-4d86-8846-a64f2af53f2e)

**Comment by wenche** [comment]
Related #1009

**Comment by fernandolucchesi** [comment]
@BirteThornquist to check if something needed for news article template.

Also check differences between h3 in topic / news pages

**Comment by wenche** [comment]
If the remaining for this issue is mainly for the event template, we have a separate issue for that #794. This issue can't live forever. @BirteThornquist to conclude
