### ISSUE TITLE
Teaser component does not display small icon when size is selected

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#740]

**Comment by adneforslund** [comment]
@nicholas-haggerty I have been playing around with the teaser component for a while, but I cant seem to see the issue. Can you take some screenshots/describe it more?

**Comment by nicholas-haggerty** [comment]
@adneforslund @SvSven you can see example here: https://energyvision.app.radix.equinor.com/sustainability  https://equinor.sanity.studio/desk/topicContent;1b08e4d3-17a7-46d2-bba9-f16de70579d2

Teaser component has been set to display small. May be connected to file type #739?

**Comment by SvSven** [comment]
It might be related since I recall we did some magic if the image is an SVG (since Sanity's image pipeline doesn't handle SVGs very well).

It's been a while since I looked at the code for the teaser though, but in this case that is indeed a JPG while it should be an SVG

**Comment by nicholas-haggerty** [comment]
Yup, It absolutely should be an SVG file.

**Comment by nicholas-haggerty** [comment]
@adneforslund @SvSven This seems be be working now as expected. Maybe it was just the file causing the issue. Now with a different icon in place it works as expected and I can change the display from large to small... CLosing
