### ISSUE TITLE
Option to have rich text options in the text block titles

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#741]

**Comment by nicholas-haggerty** [comment]
Should we allow for weight change in the Titles (H2) to emphasize word or statement.
Potentially also allowing for colour option on font? Moss Green 100% only?

https://www.equinor.com/en/sustainability.html

**Comment by wenche** [comment]
Related to #633

**Comment by SvSven** [comment]
Needs UX discussion with @BirteThornquist

**Comment by nilsml** [comment]
This has to do with #633 and #334, and doing this card may make it more difficult to solve it properly later on. AND it is not crucial for going live.

**Comment by fernandolucchesi** [comment]
Waiting for the design of the title

**Comment by meols** [comment]
@fernandolucchesi - we'd like to start with adding bold, italic and strikethrough. We'll discuss further on color options in the future.

**Comment by SvSven** [comment]
Looks good to me ✅

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/79e11e0d-964d-49f1-8aa8-4e310edf1793)

@meols @NickHaggerty1 strikethrough is a new formatting option that we haven't used before - is it needed anywhere else as well?

**Comment by meols** [comment]
Thanks @SvSven :thumbsup: Can we add this to the header title (H1) and also to all components where we have rich text titles (incl. hero title for 50-50 banner)? @NickHaggerty1 - any comments, or is this OK as per our discussion?

**Comment by NickHaggerty1** [comment]
@meols @SvSven no additional comments from me

**Comment by padms** [comment]
@SvSven Small changes to allow these new options for all rich text titles.

**Comment by SvSven** [comment]
@padms Looks good to me!

**Comment by padms** [comment]
@meols New options enabled for all titles with rich text options.

**Comment by NickHaggerty1** [comment]
@meols @SvSven @padms One issue I notice is that we dont have a rich text title on the PROMO Tile component. I know this is set up a little differently but it would be good to have the same options there too. I suggest we capture that in a separate card.

**Comment by padms** [comment]
Created #1377 for promo tile.
