### ISSUE TITLE
Should we show the language options even if there's not a one-to-one translation of the current page?

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#743]
It there's a translation to another language for a page, we show the language switch component in the header. When no translations exist, we show nothing. What would be the optimal behaviour for this? Does it make sense to not show language options at all just because the current page does not have a translation? 

@BirteThornquist The "jump" of the menu button you complained about the other day does actually seems to be related to the missing language switch.

Example with switch: https://energyvision.app.radix.equinor.com/
Without: https://energyvision.app.radix.equinor.com/careers/professionals

**Comment by wenche** [comment]
Conclusion:
If a page is available in English only, show EN (non-clickable)
If a page is available in Norwegian only, show NO (non-clickable

**Comment by fernandolucchesi** [comment]
Find ways to handle the language switch when page has only one page.

- dropdown?
- always display + tooltips?

**Comment by fernandolucchesi** [comment]
We will keep it as it is, everybody is happy :)
