### ISSUE TITLE
Github Actions is reporting SUCCESS when job fails

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#747]
Slack bot is reporting success when job fails. This is a bug
![image](https://user-images.githubusercontent.com/23337266/149965396-466d2b20-4e2a-4de9-b0f0-f8250b4a3606.png)
https://github.com/equinor/energyvision/compare/99ea8827816a...9d05e0d02cd2

## Action

- [ ] Make sure that we bring the status from each task along for final status

PS: Need to investigate how we can accumulate status with parallel tasks

**Comment by nilsml** [comment]
It is because of the way the actions are configured. We are not taking the status with us when running multiple tasks in the same action.

**Comment by nilsml** [comment]
So right now if a task fails in an action you still might get SUCCESS for the tasks that do not fail. This is not ideal, but at least we should get all failures. Might want to create an issue to improve on this.

**Comment by wenche** [comment]
@nilsml  Yes, I also feel that we should create an issue to improve this, but not of top 10 priority rather nice to solve. :thumbsup:

**Comment by nilsml** [comment]
Perhaps we should just log the latest task as it is dependent on the others

**Comment by nilsml** [comment]
Created new task for improving on this #790
