### ISSUE TITLE
Add "all sites" link to global menu on mobile

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#748]
How should "all sites" be presented to end user?
Automatic based on dataset? Topic content?

This card only takes presentation of the link, and not presentation of the content. 

To be tested. 

- [x] All sites link shows on the menu

**Comment by adneforslund** [comment]
How should "all sites" be presented to end user?
Automatic based on dataset? Topic content?

**Comment by adneforslund** [comment]
related to #797

**Comment by adneforslund** [comment]
@BirteThornquist Can you test this?

**Comment by adneforslund** [comment]
updated description in card

**Comment by BirteThornquist** [comment]
hi @adneforslund Looking good! I miss the hover effect, though.  Can you pls add the same grey hover background color as for the other menu items?

**Comment by adneforslund** [comment]
@BirteThornquist

**Comment by adneforslund** [comment]
@BirteThornquist pushed up, but might take a couple of minutes to take effect + hard reload

**Comment by wenche** [comment]
LGTM :thumbsup:
