### ISSUE TITLE
Improve validation messages for SEO & metadata fields

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#750]
The validation labels used for the `SEO & metadata` fields can be made more clear and consistent.

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/ee644b21-e290-4fae-97fd-860fec26e28f)

For example the use of `The document title is very important for SEO` alongside `Meta description is important for SEO` is a bit strange.

Similarly `Please pay attention to SEO` could be written better, for example something along the lines of `It is recommended to fill out the SEO fields whenever possible.`

Needs input from @BirteThornquist 

Easy to fix if we can agree on better texts

**Comment by meols** [comment]
I see the "yellow triangle" with explanatory text on news and magazine templates, and the texts are OK. But we don't have the "yellow triangles on topic pages. Topic pages are where focus the most on SEO.

**Comment by millianapia** [comment]
as text is ok, i will move this forward but have created a bug for the warning not being in the top for topic pages #2442
