### ISSUE TITLE
Update validation of Text Block component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#752]
We currently have a warning `Should we warn for missing title` when the editor has not filled out a title in the text block component. That's a good question, let's decide on that and fix it.

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/12f2344d-6c62-47ba-8699-55784232e004)

**Comment by nilsml** [comment]
Decision: Use warning text. Write a good text to make the editors want to put it in

**Comment by satyendra900** [comment]
**Acceptance criteria**:

- We should just replace the warning message with something like "A title is recommended" or something else and 
  title should not be mandatory.

**Comment by wenche** [comment]
LGTM :thumbsup:

**Comment by wenche** [comment]
@meols  New and hopefully improved warning message for components without a title
![Skjermbilde 2022-05-30 kl. 15.37.48.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ed29cfe6-9a8d-4138-9567-0d0745dc2e70)

**Comment by meols** [comment]
@wenche - for the text block component I see the text "A title is recommended"  and not "In most cases you should add a title" (in preprod). Is that correct?
I also see "In most cases you should add a title" for Table and Promotion and "Should we warn for missing title" for Accordion. But those are perhaps handled separately, and only text block for this card?

**Comment by wenche** [comment]
@meols  That's why I added the screenshot - it's just available in the dev environment atm. :) Should have mentioned that explicitly. We where supposed to release it to preprod today, but just need to sort one thing out first

**Comment by meols** [comment]
@wenche - the screenshot is great :smile:
