### ISSUE TITLE
Custom text editor size for Title field is broken

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#753]
The rich text editor we added for the Title field in #550 had a smaller size than for example the ingress and content fields, this was done because the title should ideally be short and concise. For some reason this is no longer working, resulting in the text editor being the same size as the other ones. This should be fixed.

**Comment by nilsml** [comment]
Connected to Sanity update

**Comment by SvSven** [comment]
Can be looked at at the same time as #741

**Comment by fernandolucchesi** [comment]
Can you review this one @SvSven ?

**Comment by SvSven** [comment]
Looks good to me 👍
I like the comment in the code, something tells me that this won't be the last time we look at this.

**Comment by wenche** [comment]
@meols I believe you mentioned this at some point as well? The title editors are now lower than the rest of the text editors, as they used to be before a Sanity upgrade. :)

 ![Skjermbilde 2022-02-15 kl. 14.14.43.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c7cafeef-c664-45d8-b360-0f908cf7d757)

**Comment by meols** [comment]
:thumbsup: Great that this is fixed! :clap:
