### ISSUE TITLE
Missing span in div on Language Switch

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#756]
**Describe the bug**
Giving error message.![Screenshot 2022-01-19 at 10.57.44.png](https://images.zenhubusercontent.com/61482e3b2cb1bada8cadcc42/eb99a271-9bd8-4dfc-91fe-7b4bfbc9d553)

**To Reproduce**
1. Go to any page and click on console

**Desktop ):**
 - OS: IOS
 - Browser Chrome

**Comment by wenche** [comment]
Looking into this since it is such an annoying thing in the console on localhost

**Comment by wenche** [comment]
### Mobile 
Not translated: Hide language info
Translated: Show only the opposite language

### Desktop
Not translated: Show the current language only
Translated: Show the complete language switch

**Comment by wenche** [comment]
@SvSven  Do you mind to take a look, since this component is pretty confusing :sweat_smile:

**Comment by SvSven** [comment]
Warning is gone ✅
Not really sure why we decided on using the window breakpoint in the first place, but doing this with CSS seems like a better approach 👍
