### ISSUE TITLE
Fix typing in Menu.tsx

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#757]
Reach/accordion is expecting something else

![Screenshot 2022-01-19 at 11.09.51.png](https://images.zenhubusercontent.com/61482e3b2cb1bada8cadcc42/58f0382c-0401-4cab-b26d-b897bb121ecc)

**Comment by wenche** [comment]
As far as I remember we checked this way back because your are allowed to send in whatever you want. But there's probably a way to express this in typescript that haven't found?
