### ISSUE TITLE
Wrong status codes for pages that are not found (404)

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#758]
**Describe the bug**
Wrong status codes are returned for pages that doesn't exist

**To Reproduce**
1. Open the network panel
1. Go to e.g. https://energyvision.app.radix.equinor.com/this_page_does_not_exist.html and  https://energyvision.app.radix.equinor.com/this_page_does_not_exist
2. Check the status codes

**Expected behavior**
404 status code in the Network tab when a page doesn't exist

**Actual behavior**
304 is returned for .html suffix and 200 without server side. Client side it shows the 404 page

**Screenshots**
![Skjermbilde 2022-01-19 kl. 11.52.36.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/5eebcd2d-12b6-4917-8a56-f5a603703895)
![Skjermbilde 2022-01-19 kl. 11.57.05.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c10ca49d-7bbc-49d4-ae8c-e88f953ff06a)

Correct behaviour from Next js homepage
![Skjermbilde 2022-01-19 kl. 12.01.17.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/7a06edb8-76a2-43bb-bf7a-0674682f7d15)

**Desktop (please complete the following information):**
 - OSX/Chrome

**Comment by wenche** [comment]
By returning `notFound` this should now be fixed
![Skjermbilde 2022-03-15 kl. 09.43.58.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f68f5f4c-fa88-4fc8-925c-9f715585f30c)
![Skjermbilde 2022-03-15 kl. 09.44.19.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/d36f35d9-cb95-4acd-ad6c-07815b58117f)

**Comment by SvSven** [comment]
I'm seeing a 404 in the network tab for https://energyvision.app.radix.equinor.com/this_page_does_not_exist
The .html version successfully redirects to the non-html version now so that is no longer a concern.
