### ISSUE TITLE
Missing header in articles

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#765]
**Describe the bug**
There is no header inside article tag

**To Reproduce**
1. Go to https://energyvision.app.radix.equinor.com/how-and-why/sustainability

**Expected behavior**
Articles hsould have h2-h6 header

**Comment by nilsml** [comment]
Static content. Lets check if this works in AEM

**Comment by SvSven** [comment]
We no longer use static topic pages; only the news archive - so I'm assuming this is no longer an issue
