### ISSUE TITLE
Add descriptions to hero image fields for news article

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#766]
The `attribution` and `image caption` fields should have a short description to state what these fields are and how to use them in order to prevent the editors from using them the wrong way (like omitting "photo by" or similar in the attribution field)

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/a64c8b02-0bb8-410a-b6ef-fffc2cd59a3c)

**Comment by wenche** [comment]
And perhaps also a placeholder

**Comment by fernandolucchesi** [comment]
Already done
