### ISSUE TITLE
Remove text style option in rich text editor if no alternative styles are available

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#767]
Having a dropdown where editors can select a text style, without any alternative styles (only "normal") can be confusing. We should disable this dropdown when there are no alternative styles available.

Example from news article Ingress field:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/7fb87458-838d-46e8-8cac-1ca37038426e)

**Comment by wenche** [comment]
And if we are not able to figure out how, we should ask Sanity.

**Comment by wenche** [comment]
This might no longer be needed if we introduce a "small" text type to be able to create end notes

**Comment by fernandolucchesi** [comment]
Check if we have rich text fields without more than one option.

**Comment by SvSven** [comment]
I agree with closing it in that case 👍
