### ISSUE TITLE
Events and News are triggering a warning in the console

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#768]
![image](https://user-images.githubusercontent.com/23337266/150146362-fec16707-2bdc-4a7e-8704-e9990c72fe3a.png)

**Comment by SvSven** [comment]
Might be related to the character count custom input at `studio/schemas/components/CharCounterEditor.tsx` as that is not using `forwardRef`

**Comment by wenche** [comment]
[See discussion with Sanity](https://equinor.slack.com/archives/C01A4BGNRMJ/p1647000712462629?thread_ts=1646902139.444429&cid=C01A4BGNRMJ). This is probably related to the collapsed SEO fields at the beginning of the document.

**Comment by wenche** [comment]
Things like this are probably fixed in v3 of Sanity studio, so let's wait and see.

**Comment by fernandolucchesi** [comment]
Warning is gone on v3
