### ISSUE TITLE
Year in the footer is not updated automatically

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#770]
How should we actually go ahead to keep this up to date? 

![Skjermbilde 2022-01-19 kl. 15.04.07.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f966e8ae-a6cd-459b-bcd5-f49826b5e5ad)

**Comment by nilsml** [comment]
You fixed this @adneforslund ?

**Comment by adneforslund** [comment]
Hotfixed it at least, Im not sure if this should be handled in Sanity, Javascript, or wheter it should be hardcoded, but at least it says 2022 now

**Comment by fernandolucchesi** [comment]
Finally time to prioritize this 😂

**Comment by padms** [comment]
This is editorial task now. Copyright can be changed from text snippets.

**Comment by fernandolucchesi** [comment]
Remove text snippet and hardcode the value

**Comment by fernandolucchesi** [comment]
@millianapia, looks good! Just a minor comment.

When removing the feature flag also remember to delete the text snippet on studio/schemas/textSnippets.ts

**Comment by meols** [comment]
@millianapia @fernandolucchesi - any test criteria for this one?

**Comment by fernandolucchesi** [comment]
> @millianapia @fernandolucchesi - any test criteria for this one?

Value is now hardcoded, meaning the text snippet will be useless from now on, so we will remove it. A way to test it is to change the Copyright text snippet to a random string, and seeing that it still shows Copyright 2023 Equinor

**Comment by millianapia** [comment]
@NickHaggerty1 @meols

**Comment by meols** [comment]
Great! Thanks :smile:
