### ISSUE TITLE
Jumping fonts

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#771]
**Describe the bug**
Fonts "jump" after som seconds

**To Reproduce**
1. Navigate to  https://energyvision.app.radix.equinor.com/sustainability/energy-perspectives through menu
2. Scroll down to "Previous years’ Energy Perspectives reports" on bottom of page

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome

**Comment by SvSven** [comment]
Fixed/improved in #971
