### ISSUE TITLE
Include api version when fetching within sanity

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#772]
Reproduce by navigating to 'News'

![image](https://user-images.githubusercontent.com/23337266/150150445-464b6931-591b-4a23-9855-c26a5322b1ee.png)

**Comment by SvSven** [comment]
Need to review how we use the sanity client for fetching in general, I see we are not consistent with it.
This should probably be handled by `web/lib/config.ts`, which we use for the preview hook and PortableText in `web/lib/sanity.ts` - maybe make a reusable wrapper for the client where this config is passed?

**Comment by padms** [comment]
Added api version isuniqueWithinLocale.js where its missing

**Comment by wenche** [comment]
We should at some point add the api version to a shared config or something
