### ISSUE TITLE
Looks like hero image is required

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#773]
**Describe the bug**
Image selector is red

**To Reproduce**
1. Go to sanity studio, make a news article
2. Scroll down to image

Image selector is red, which makes it look like the image is required

**Comment by SvSven** [comment]
Confirm if this is still an issue after #1055 is fixed
This particular issue might be solved after Sanity redesigned the image selection field.

**Comment by fernandolucchesi** [comment]
Investigate further / try to replicate
