### ISSUE TITLE
Text block and accordion: can't se internal page name when creating a hyperlink to an internal page in the text

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#776]

**Comment by meols** [comment]
When adding a hyperlink to an internal page in the text content in the text block and in the accordion item in the accordion, I can't see the name and url of the page to link to - as I do when adding a link item below the text block (maybe the search/list field could be broader?)
Link item: 
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/eab2cf42-7c71-4aac-95a1-92194ba78488)
Accordion item:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/66a4a60e-6dd0-4e99-b616-fb5892640b3a)
Text block:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/3b8c4d1e-8bcc-429b-917a-c9d1b8e5eca1)

**Comment by wenche** [comment]
According to Sanity, the width can be customised in the text editor. It's a new feature, so just not documented yet
```
{
  type: 'object',
  name: 'link',
  fields: [{type: 'url', name: 'url'}],
  options: {
    modal: {
      width: 'medium', // defaults to 'small' for annotation objects
    },
  },
},
```
![Screenshot 2022-01-24 at 10.48.32.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a9b6ce14-51dc-43a8-a48b-d83cc1b9164b)

**Comment by wenche** [comment]
@meols  Please check if it's better now :thumbsup:

**Comment by meols** [comment]
@wenche - brilliant! :ok_hand:
