### ISSUE TITLE
As an Argentine editor I want to add content to build the page

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#778]
### TODO

Follow the [description in the wiki](https://github.com/equinor/energyvision/wiki/satellite-sites) to create the Argentine satellite page

### Acceptance criteria

- An Argentine version of Sanity studio is available including preview
-- Language: English and Spanish
-- Main language is Spanish (the language of equinor.ar)
- An Argentine version of the web page is available

**Comment by wenche** [comment]
We need to disable fetching of static pages for satellites if they share language (en in my case) as I see English static content. Will create an issue

**Comment by wenche** [comment]
**Web**
https://web-argentina-energyvision-dev.radix.equinor.com/

**Studio**
https://studio-argentina-energyvision-dev.radix.equinor.com/

**Comment by wenche** [comment]
We didn't find the best way to use a flag icon for translations in this case. We might look at this on a more general level and perhaps get some inspiration from the translation plugin?
![Skjermbilde 2022-01-20 kl. 14.55.26.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/82c38d0c-f324-4aa8-8127-05171b677d28)

**Comment by wenche** [comment]
Let's create (yet another issue) for this :)

**Comment by wenche** [comment]
@nicholas-haggerty @meols  The Argentine version should be up and running :thumbsup:

Web
https://web-argentina-energyvision-dev.radix.equinor.com/

Studio
https://studio-argentina-energyvision-dev.radix.equinor.com/

**Comment by nicholas-haggerty** [comment]
Great stuff Thanks for this.. Looking forward to get into this if I can escape INVESTORS

**Comment by SvSven** [comment]
They use emojis for the flags and have some png fallbacks if I'm not mistaken. Had a short discussion about it with Sanity a while ago since there was no emoji flag for `nb_NO` with the initial implementation.

https://www.npmjs.com/package/a11y-react-emoji is used for implementation

**Comment by SvSven** [comment]
We should probably have something in the studio indicating which version it is. I know you can look at the URL to figure it out, but the dashboard for this one looks the same as the dashboard for the global studio.

Could be something as simple as instead of having it say "Equinor" in the top left, it says "Equinor Argentine" for example?

**Comment by nicholas-haggerty** [comment]
@wenche @adneforslund Not sure if this should be a separate issues (in order to close this one) I have add some pages to the solution (in En) When I went to route they could not be found in the EN route structure but the pages were not displayed. I notice that Spanish is first, so on checking the page route under Spain, I can see pages. Is this easy to change the hierarchy on? So EN if first? as per the global?

**Comment by adneforslund** [comment]
@nicholas-haggerty as in you want English to be the main language of the Argentien site?

**Comment by nicholas-haggerty** [comment]
Yes please. In all cases where English is one of two languages in the site it should come first.

**Comment by nilsml** [comment]
So we want to change it from todays solution? ES is first in the Argentine site today.

**Comment by nicholas-haggerty** [comment]
@nilsml Yes!

**Comment by nicholas-haggerty** [comment]
@nilsml Hey any update on when this will be in place? Then we are able to route the pages and test the menu

**Comment by fernandolucchesi** [comment]
@nicholas-haggerty starting on it right now!

**Comment by fernandolucchesi** [comment]
https://web-argentina-energyvision-dev.radix.equinor.com/
https://studio-argentina-energyvision-dev.radix.equinor.com/

**Comment by meols** [comment]
Tested cookie declaration and a few components
