### ISSUE TITLE
As an editor for Equinorfondene I want to add content to be able to build my page

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#779]
### TODO
Follow [the description in the wiki](https://github.com/equinor/energyvision/wiki/satellite-sites) to create the Equinorfondene satellite page

### Acceptance criteria
- An Equinorfondene version of Sanity studio is available including preview
- An Equinorfondene version of the web page is available

**Comment by adneforslund** [comment]
@meols @nicholas-haggerty ready to add content at https://studio-equinorfunds-energyvision-dev.radix.equinor.com/ now

**Comment by meols** [comment]
@adneforslund @fernandolucchesi - I can't see a Create new button to create the menu for Equinorfondene. Can you please take a look?

**Comment by adneforslund** [comment]
@meols Yes, pushing up a fix now

**Comment by meols** [comment]
Created with relevant content, menu, cookie declaration, text, iframe, image etc.
