### ISSUE TITLE
As an editor for Techstars Energy I want to add content to be able to build my page

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#781]
### TODO
Follow [the description in the wiki](https://github.com/equinor/energyvision/wiki/satellite-sites) to create the Techstars energy  satellite page

### Acceptance criteria
- A Techstars energy version of Sanity studio is available including preview
- A Techstars energy version of the web page is available

**Comment by fernandolucchesi** [comment]
https://web-techstars-energyvision-dev.radix.equinor.com/
https://studio-techstars-energyvision-dev.radix.equinor.com/

**Comment by meols** [comment]
Tested with cookie declaration, text, iframe, image
