### ISSUE TITLE
As an editor for Equinor storage I want to add content to be able to build my page

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#782]
### TODO
Follow [the description in the wiki](https://github.com/equinor/energyvision/wiki/satellite-sites) to create the Equinor storage  satellite page

### Acceptance criteria
- An Equinor storage version of Sanity studio is available including preview
- A Equinor storage version of the web page is available

**Comment by fernandolucchesi** [comment]
https://web-storage-energyvision-dev.radix.equinor.com/
https://studio-storage-energyvision-dev.radix.equinor.com/

**Comment by meols** [comment]
Tested with cookie declaration, text, image

**Comment by meols** [comment]
Closed
