### ISSUE TITLE
As a Polish editor I want to add content to be able to build my page

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#784]
### TODO
Follow [the description in the wiki](https://github.com/equinor/energyvision/wiki/satellite-sites) to create the Polish  satellite page

### Acceptance criteria
- A Polish version of Sanity studio is available including preview
- A Polish version of the web page is available

**Comment by fernandolucchesi** [comment]
https://web-poland-energyvision-dev.radix.equinor.com/
https://studio-poland-energyvision-dev.radix.equinor.com/

**Comment by meols** [comment]
Tested with cookie declaration and a few components
