### ISSUE TITLE
As a Brazilian editor I want to add content to be able to build my page

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#785]
### TODO
I think this should only be a matter of cleaning the dataset?

### Acceptance criteria
- A Brazilian version of Sanity studio is available including preview
- A Brazilian version of the web page is available

**Comment by fernandolucchesi** [comment]
https://web-brazil-energyvision-dev.radix.equinor.com/
https://studio-brazil-energyvision-dev.radix.equinor.com/

**Comment by meols** [comment]
Tested cookie declaration and a few components
