### ISSUE TITLE
As a German editor I want to add content to be able to build my page

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#786]
### TODO
I think this should only be a matter of cleaning the dataset?

### Acceptance criteria
- A German version of Sanity studio is available including preview
- A German version of the web page is available

**Comment by fernandolucchesi** [comment]
https://web-germany-energyvision-dev.radix.equinor.com/
https://studio-germany-energyvision-dev.radix.equinor.com/

**Comment by meols** [comment]
Tested with few components. Will add a comment on cookie on [#808](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/808)
