### ISSUE TITLE
Image component: As an editor I need to be able to search in uploaded images within the component

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#787]

**Comment by meols** [comment]
When choosing Select -> uploaded images in the Image component, I should see the title/file name for all images and also be able to search for a file name to find one that's already uploaded. 
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/ccdebae0-b08e-4925-b719-32e8030e0364)

**Comment by nilsml** [comment]
If using the media plugin search is available
