### ISSUE TITLE
Prevent menu button from "jumping"

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#789]

**Comment by wenche** [comment]
Sorry, but these kind of greedy selectors in a  styled components world to me feels like a serious gotcha and anti pattern? Like it's the opposite of a scoped, component style. Am I wrong? Please challenge me if you disagree

**Comment by fernandolucchesi** [comment]
I must confess that I haven't worked much with styled component so I am not aware about the patterns. 

I am very familiar with tailwind and this selector is widely used there through a class `space-x-{value}` or `space-y-{value}`, which adds margins to every child of the component except the last one. So since I am used to it this comes very natural to me.

The same result can be achieved with gap, but until last year safari didn't accept gap with flexbox and that is why I always used the css selectors over gap. But I have just checked it now and seems like they've been accepting it since april 2021 😃  https://css-tricks.com/safari-14-1-adds-support-for-flexbox-gaps/

I'll update the code!

**Comment by wenche** [comment]
This one was ready to be retested right @fernandolucchesi ? 
If yes => LGTM :thumbsup: We can close this issue
If no => please do the last nitty gritty and then tag me :sweat_smile:

**Comment by fernandolucchesi** [comment]
> This one was ready to be retested right @fernandolucchesi ? If yes => LGTM 👍 We can close this issue If no => please do the last nitty gritty and then tag me 😅

Yes! :P I will close it then
