### ISSUE TITLE
Improve flags for language and country

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#792]
With satellite pages we have multiple variants of languages and country. Like British english for global and Argentine english for the Argentine pages. We should find a way to improve the icons we use for the editors that can handle this. 

Sanity's language plugin solves this by showing multiple flags, one for the country and one for the language. Might be an idea to replicate?
![Skjermbilde 2022-01-21 kl. 08.56.04.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/1057b91f-eb75-4818-a4ed-67d63b3acd6e)

**Comment by wenche** [comment]
https://www.npmjs.com/package/a11y-react-emoji

**Comment by fernandolucchesi** [comment]
Fixed already
