### ISSUE TITLE
Spacing issues on event template

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#794]
Spacing between components on the event template is too big. seems like its accounting for the background colours but we dont have this option on the events. Example here: https://energyvision.app.radix.equinor.com/investors/testing

**Comment by adneforslund** [comment]
related to #738

**Comment by fernandolucchesi** [comment]
Probably this has been changed already, but we are rendering an empty div on the page still, so we can use this issue to fix it instead:
![image](https://user-images.githubusercontent.com/23337266/209573674-ec82a9fd-5cdb-4664-b385-37dfe8910316.png)

**Comment by fernandolucchesi** [comment]
I did not use a feature flag for this since it is such a tiny change.

**Comment by millianapia** [comment]
lgtm!
