### ISSUE TITLE
People promotion card display issues.

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#799]
When displaying several people promotions together, on an average screen to large the component displays as 5 column. This Looks very narrow, especially with text heavy descriptions which we will need and on buttons, so one improvement should be to set a maximum width to display 4? 

Examples: 
https://energyvision.app.radix.equinor.com/about-us/corporate-executive-committee
https://energyvision.app.radix.equinor.com/about-us/board-of-directors

This also highlights the issue with button text if it is required to add something longer. In the example obviously RELINK will not be there but some names are very long. Due to google analytics we would/should need to add the full name to the button in order to see which has been clicked (IE the buttons shouldn't only say 'CV'). Or would we be able to distinguish which had been clicked based on the promo itself rather than specifically the button?

**Comment by wenche** [comment]
We need to look into exactly how we should do things in general with GA, but the people card was designed to use "CV" as the label and for example "CV for Kari Nordmann" as the screen reader label :) Let's figure out how this works with GA.
![Skjermbilde 2022-01-27 kl. 11.28.54.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/580dc73b-d387-4b95-a1f2-f752dd2d0db9)

**Comment by SvSven** [comment]
Screenshot to illustrate in case the page changes: 

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/cf842737-2edb-402e-80f8-7011bffbcd7d)

This is in part also related to the problem with the EDS button being worked on in #653

**Comment by nilsml** [comment]
@nicholas-haggerty @meols Is this one solved by the changes done to the button recently? Please confirm!

**Comment by nicholas-haggerty** [comment]
@nilsml still looks the problem is there if you look at the links above.... 5 column. Super narrow. Here is another one.... https://energyvision.app.radix.equinor.com/investors/contacts-investor-relations

**Comment by meols** [comment]
@nilsml - the button part of this is solved, but the people promo should be three in a row (not 5 column). This will further help with the button text as well. Both the news promo and the topic promo are three column, but the people currently are five column.

**Comment by meols** [comment]
@nilsml @BirteThornquist - after an update in the corp. exc. committee today (Elisabeth Birkeland Kvalheim), the issue with having the people promo displaying five side by side instead of three is even more visible.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/9a66782b-279e-4ec1-97c8-e3ec0cb44416)

**Comment by BirteThornquist** [comment]
Yes, absolutely @meols This does not look good. We have to fix it - will see when it can be done.

**Comment by wenche** [comment]
@meols  Birte and I have made some tweaks to the grid for these cards. It's not easy to make something that works well for both 2 and 12 cards. :) It should look better now - but these cards doesn't look good if they are as wide as the news cards. It's also a matter of making the design look less dull than if every cards container looks the same, 3 cards in the same rows. :)

We think this is good enough for now, and as a backlog issue we can look into the cards in general; both events, news, local news,people and landing page.

**Comment by meols** [comment]
Thanks @wenche - looks much better now :smile:
Agree that further improvements of cards is something for the backlog :thumbsup:
