### ISSUE TITLE
Access to Brand master not working as expected in Argentina site

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#802]
When selecting to add image from the brandmaster button a new window is launched but displays the same site, not the brans master image archive.![linking to brandmaster.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/f392fbcd-f0f0-481d-a241-f486d8972dda)

**Comment by SvSven** [comment]
This is because of some missing secrets for loading the Brandmaster plugin, which should be solved by #736

**Comment by fernandolucchesi** [comment]
Solved by #736
