### ISSUE TITLE
Get rid of Cookiebot error messages while in Sanity preview

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#805]
When in Sanity Preview, Cookiebot is giving error messages in the console and it doesn't really work as expected on the web page. Ref #696 for more details.

**Comment by fernandolucchesi** [comment]
I believe this is done already right @padms ?

**Comment by padms** [comment]
@fernandolucchesi This loads the iframe and hides the consent dialog in preview. But the errors in the console is same. ![image.png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/98cc7146-6c9d-40d8-ad29-d0340493b721)

**Comment by fernandolucchesi** [comment]
@meols @NickHaggerty1 this is a small improvement when previewing iframes. The difference is that the cookie bot banner is not shown anymore while in preview mode (both when using tabs or another window).

**Comment by meols** [comment]
Thanks @fernandolucchesi - this is great :smile:
