### ISSUE TITLE
add missing file types to asset library

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#806]
The custom asset library system currently support PDFs and excel sheets. Some additional file types should be added

List of file types to be supported:
- .pdf
- .xls
- .xlsx
- .csv
- .doc
- .docx
- .pptx
- .txt
- .zip
- .asc
- .ics

Related: #283 and #670

**Comment by SvSven** [comment]
@meols I have added the file types listed above and as mentioned on Slack also added additional filters in the asset library to hopefully make it more easy to find assets.

![image (6).png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/273ab56a-09e8-415a-b1f0-bdd85469e4f8)

**Comment by meols** [comment]
@sven - perfect! :+1:
