### ISSUE TITLE
Cookie Policy page for global and satellite sites

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#808]
Cookie policy page should contain the script from cookiebot which loads a table of cookies with their purpose. See https://www.equinor.com/en/cookie-policy.html

### Decisions to be made
- How should the editors create the content for this
-- Should it be a component in the topic page list
--Separate template

**Comment by padms** [comment]
@meols  Created a new component called " Cookie Declaration", which can be used on the cookie policy page to show the cookies list.

**Comment by meols** [comment]
@padms - I get the error message below (in preview) when adding the component to a new test page. 
If the test task is to confirm that I can drag the component to a page, it works. If it should display the list and the text above it (current state, id, etc.) correctly, it doesn't work.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/88ad25f9-8d2c-428a-bc7c-8fef247a3a88)

**Comment by padms** [comment]
@meols I added the domain web-energyvision-dev.radix.equinor.com to the cookie bot console. Now the table is shown on the page. https://web-energyvision-dev.radix.equinor.com/b4f5bd88-a9c0-467a-a53a-f3f79d5fc54e

**Comment by padms** [comment]
@meols All the satellites have been added to the Cookiebot console now.

**Comment by fernandolucchesi** [comment]
@padms can you also update the [wiki](https://github.com/equinor/energyvision/wiki/satellite-sites) and add the cookiebot configuration as a new step?

**Comment by padms** [comment]
@fernandolucchesi I updated the wiki.

**Comment by meols** [comment]
@padms - on the German site I get this message (meaning "Under construction: The website is currently being scanned for cookies for the first time. ") Is this expected? (haven't seen it on any of the other sites)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/e2e5c641-b8f8-4396-a3ef-b5067cf32950)

**Comment by padms** [comment]
@meols  I could see the same in production. There is a scan scheduled today. I will check it and contact Cookiebot support, if there is no change. The test version will be automatically reflect correctly if the production is corrected.

**Comment by padms** [comment]
@meols The cookies are now reflecting in production. It reflects in test too.

**Comment by meols** [comment]
Thanks @padms
