### ISSUE TITLE
Initial investigation for search tasks

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#810]
Define technical tasks for search
Conceptual drawing in Figjam

**Comment by nilsml** [comment]
Link to figjam: https://www.figma.com/file/Gsp2my8TxoDhZ3zsZJnhKO/Search

**Comment by wenche** [comment]
As a start, we have created the following issues: #817, #816, #815, #814 and #818. It's always hard to make every issue in advance. We decided to go with an approach where we will do A-Z for a limited number of the fields for the event document, suggesting title, description and date as a start. This will act as a MVP.

Moving this into QA, let's take a brief discussion in the technical standup tomorrow morning
