### ISSUE TITLE
Menu refinements on satellite sites

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#813]
1. The menu is justified left even with a bigger screen/display/browser window. Looks a little strange when he logo and menu remain centralized.
2. Should we make an additional visual distinction on the menu points when we have two identical titles, One unclickable without an arrow, one clickable with. @BirteThornquist ![menu.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/525e5c09-5e15-4f2b-bb41-3713b160cb0b)

**Comment by nicholas-haggerty** [comment]
![menu-1.JPG](https://images.zenhubusercontent.com/5fb7bd9b956d0a1c1ed319e1/7faebb5d-83cd-425c-8b7c-502debf2e027)

**Comment by BirteThornquist** [comment]
The left padding is responsive and increases only up until screensize 1920px it seems... @adneforslund?
The expanded menu item should be bold as done in the mobile menu. Design updated [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3765%3A74563)
