### ISSUE TITLE
Push data to Algolia

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#817]
Create function for updating an index in Algolia with data (from Sanity).
The function should be idempotent.

**Comment by wenche** [comment]
Dear board, we have sinned. Multiple issues in progress at the same time :scream:

This issue was too closely connected to #816. Working on those in parallell

**Comment by nilsml** [comment]
Pushing data and index settings now. Lets discuss what is needed for us to close this issue @wenche

**Comment by wenche** [comment]
Not much to say about this issue, let's demo it in tomorrow's standup
