### ISSUE TITLE
Make home pages in sanity a singleton

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#819]
We should not allow editors to create more than one home page item, therefore it should not be a list:
![image](https://user-images.githubusercontent.com/23337266/152115328-cc94e384-ccb3-403a-802e-a2918ec9c121.png)

Look at how the menu is implemented for inspiration:
![image](https://user-images.githubusercontent.com/23337266/152115428-440a5412-7635-4e68-95f9-4344f6a88159.png)

**Comment by padms** [comment]
@fernandolucchesi  For your review

**Comment by fernandolucchesi** [comment]
Looks good! 👍
