### ISSUE TITLE
Algolia: Support for multiple indexes for events

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#823]
We need multiple indexes for events.
- For each language (en-GB and nb-NO)
- One for each dataset (global and global_development)
- ( tmp dataset for copying?) - To decide!

### Acceptance criteria
- One index for the global English events
- One index for the global Norwegian events
- One index for the global development English events (production dataset is deprecated)
- One index for the global development Norwegian events (production dataset is deprecated)
(- tmp)

**Comment by nilsml** [comment]
Support for using multiple indexes added in code.
Adding the actual indexes is remaining.

**Comment by nilsml** [comment]
Added indexes for dev and prod:
dev_EVENTS_en-GB (dev)
dev_EVENTS_nb-NO (dev)
EVENTS_en-GB (prod)
EVENTS_nb-NO (prod)

For now I think this is ok. Rename at later stage if we want a different convention.
