### ISSUE TITLE
As an end user I want to search for events so that can find the relevant ones

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#825]
## Acceptance criteria
1. Events has a tab in the search overlay
1. The hits are formatted in an easy and intuitive way for events
-- Event date
-- Title
-- Ingress 
-- Event description
-- URL
1. When you select a hit with the mouse or keyboard, the search overlay is closed and you are navigated to the selected page
1. On mouse hover, the title is underlined
1. On keyboard navigation, the title is outlined

## Test
**Search for an even**
1. Open the search overlay by pressing the search button
1. Type in something in the search box
1. Select the even tab (by pressing with the mouse or use the arrow keys on the keyboard)
1. The result list is populated with corresponding hits
1. Matching characters are highlighted in the hits
1. Longer texts are truncated
1. The URLs for the hit pages are correct

**Can navigate to an event**
1. Open the search overlay by pressing the search button
1. Type in something in the search box
1. Click on the even tab
1. Click on one of the hits
Expected result: You are navigated to the page and the search overlay is closed

**Can navigate to an event page by keyboard**
1. Open the search overlay by pressing the search button
1. Use tab to navigate to the search box 
1. Type in something in the search box
1. Navigate to the event tab by tab and arrow keys
1. Use tab to navigate to one of the hits
1. Ensure that focus is visible all the time (dotted border around the titles in the hits)
1. Select one of the hits by pressing `enter`
Expected result: You are navigated to the page and the search overlay is closed

### Notes
- Initially we wanted to set autofocus on the search box input field, but it's not advised to do so due to a11y. We will investigate this further
- When navigating with the keyboard, you'll notice that the whole tab (the list of hits) received focus between the search input field and the individual hits. This is due to the tab library we use, we'll investigate this further as well. They probably do it for a reason, but its nevertheless annoying. :) UPDATE: These to issues are now covered by #895

**Comment by wenche** [comment]
We don't actually have the complete design here yet, but we have created it like this and will discuss the final details with Birte.

![Skjermbilde 2022-02-15 kl. 14.05.25.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c9154d05-c1ba-4bc6-af0b-ac62f0b71497)

**Comment by wenche** [comment]
@meols  I know that we don't have that much to search for here (3 events are indexed in Algolia), but I still think you should be able to do some testing here. :)

**Comment by meols** [comment]
Thanks @wenche - neither file names (CTA titles, as commented on another card as well), date or name in People and contacts are found when searching - is that expected?

**Comment by wenche** [comment]
@meols  Yes, this is as expected, for events this is the searchable attributes
![Skjermbilde 2022-02-28 kl. 17.06.23.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/a2848be0-0a37-4092-8177-b96caef7fa23)

Se my comments on https://github.com/equinor/energyvision/issues/824 for complementary information about indexing and some screenshots

**Comment by meols** [comment]
Thanks @wenche - closing this one then :-)
