### ISSUE TITLE
Create the search input field

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#826]
We have some design for this in Figma.

We need to discuss if we should use react-instantsearch components (the SearchBox) or the hooks library. Update: We used the hook variant, so we have created a component.

## Acceptance criteria
- Can type text into the field
- Has a search icon to the left (see updated Figma sketches)
- Native behaviour for the clear search X
- Has a hidden label for accessibility
- Design according ti Figma

**Comment by wenche** [comment]
I need to discuss some smaller details with @BirteThornquist, but this might have to wait a couple of days since Birte will be working on EDS for some days. :thumbsup: It shouldn't matter too much, since the search box is just one part of the search design.

We decided to go with as much native functionality as possible, that means using the type "search". We styled the native clear button that most browsers renders except Firefox. But it now works the way you will expect a search input field to work on your platform, so I think this is a good solution. We can always change this later on it we want to. 

For the outline, we removed the outline completely as the way we do it with focus-visible will actually, according to the spec, add an outline border even when I use a mouse as the input device. We might add another focus style here for the text input.

To use auto focus is not actually recommended due to a11y - so I didn't add that. I don't know if I agree in this case as it is in an overlay, but hard to say.

**Comment by BirteThornquist** [comment]
@wenche To distinguish the placeholder text from the search text I changed the placeholder color to grey 40.

**Comment by wenche** [comment]
Agree, that looks better. Will commit :thumbsup: @BirteThornquist 

![Skjermbilde 2022-02-23 kl. 12.32.02.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/b7edc0ca-c076-4325-b596-2869f499983e)

**Comment by wenche** [comment]
@BirteThornquist I also added one more px to the border when it's focused. Test it in production, should be available in about 10 minutes

**Comment by wenche** [comment]
@BirteThornquist If you think this is OK you may close this?
