### ISSUE TITLE
Create tab component

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#827]
We need a tab component to display the search results and for the news archive. We already have some design sketches in Figma. 

## Acceptance criteria
- The tabs must be accessible
- The tabs should be styled according to Figma
- Examples in storybook
- Relevant tests

**Comment by adneforslund** [comment]
Should this be a pageComponent?

**Comment by wenche** [comment]
We use reach tabs, since we already are using a couple of components from that library with great success

**Comment by wenche** [comment]
This is a start, let expand with more functionality and design tweaks if needed when we use it for search. Need to discuss some details with @BirteThornquist

**Comment by wenche** [comment]
@BirteThornquist Just updated the focus for the tab headers with the same as for the hits, EDS + mist-blue-100.

Other than that, this should be OK, and we can test it as a part of the search
