### ISSUE TITLE
As an end user I want to be informed that my query had no relevant hits so that I can rephrase

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#830]
## Acceptance criteria
1. If a search query yields no results, users are shown a text stating that there were no results
2. [Design in Figma ](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4542%3A81213)

## Testing
1. Type for example "a long text that will give no resultzzzz" into the search box

### Expected outcome
- Text explaining that no hits where found for each of the tabs (currently topics and events). The text is the one that is defined in text snippets: `Search, no results, category` and the corresponding title, `Search, no results title `.

**Comment by SvSven** [comment]
I have added a sentence telling users there were no results for their search query using the new text snippets functionality: https://github.com/equinor/energyvision/commit/7c9c384e0fcead44367a6e7997bcd3691ab8940e

The default text is `No results were found in {category} for your search query. Please try again.` where the `{category}` is dynamic and changes based on which tab you have open (for example, Topic or Event. This text can be changed in the studio.

We need to write some documentation on how to use dynamic text snippets with parameters like in this case with `{category}` so the editors know how this works.

**Comment by SvSven** [comment]
This is ready to be looked at @BirteThornquist

**Comment by BirteThornquist** [comment]
hi @SvSven Looks good. I just added a"header" that stands out a bit more. Design [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4542%3A81213) When we have the "All" category in, this will be the default result I guess? And the text here will be generic.

**Comment by SvSven** [comment]
@BirteThornquist Have just pushed an update and added the header 👍

**Comment by BirteThornquist** [comment]
I see the text change, but no header @SvSven Maybe it just takes a while...?

**Comment by SvSven** [comment]
Works for me in production? But maybe it wasn't updated yet 🤷‍♂️

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/33cca2b7-4b50-43db-a64b-6507c03df1e5)

**Comment by wenche** [comment]
@meols  I don't know if Sven already has showed you the text snippets for this. But here we go:

In Sanity, click the "Text Snippets" menu item. The text for this consists of several pieces. 
1. The `Nothing found` title is the "Search: No results title". 
2. The text for the "Sorry, no results..." is the "Search: no results, category". As you can see, this text translation has some curly brackets inside it `{category}`. This is a template, and it will be changed to the actual value in the web. DO NOT CHANGE THIS OR TRANSLATE IT :) In my screenshot, it's "Topic". 
3. The actual texts for the {category} template are "Search, no results, category event" and "Search, no results, category topic" 

The Norwegian translations are just a suggestion, you will probably like to update it. :) 

English
![Skjermbilde 2022-02-25 kl. 14.12.30.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/f10e86dc-7c63-4209-8b3b-eddd45097cbd)
Norwegian
![Skjermbilde 2022-02-25 kl. 14.21.33.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ff6d29b0-833c-4f4b-8a2e-7ed5f62587b9)

**Comment by wenche** [comment]
@meols  This should be ready for testing.

**Comment by BirteThornquist** [comment]
I think we can just skip the category in the empty state text all over. We discussed this on Friday @SvSven @wenche, and we also mentioned it in todays status meeting @meols I think the default search shall be on the "All" generic when we get that in, showing the tabs even with no hits. The text can be the same, generic for all the tabs. I think it is intuitive enough to show the #hits in parenthesis.

**Comment by meols** [comment]
@wenche - looks good to me :thumbsup: and agree with the last comment above from @BirteThornquist. Is it then captured somewhere that the texts should be updated? What about the Local news in search (potentially with a separate template #143), how will they be shown?

**Comment by wenche** [comment]
@meols  I'm removing the separate topic texts  as we speak.

**Comment by wenche** [comment]
@meols  The code is now updated to show the generic text and the different variants of this text is removed from the text snippets in Sanity :thumbsup:

I don't know about the local news, this will be one of the things to look into as we start working on that.

**Comment by meols** [comment]
@wenche - thanks, and closing this one :smile:
