### ISSUE TITLE
As an end user I want to search for topic content so that I can find relevant content

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#831]
## Acceptance criteria
- Topic content has a tab in the search overlay
- The hits are formatted in an easy and intuitive way for topic content
  -- The page title
  -- Snippets from the matching text (text block title + text block  ingress + text block content OR accordion title + accordion ingress)
  -- The URL of the page
- When you select a hit with the mouse or keyboard, the search overlay is closed and you are navigated to the selected page
- On mouse hover, the title is underlined
- On keyboard navigation, the title is outlined

## Test
**Search for a topic content**
1. Open the search overlay by pressing the search button
2. Topic content tab is preselected
3. Type in something in the search box
4. The result list is populated with corresponding hits
5. Matching characters are highlighted in the hits
6. Longer texts are truncated
7. The URLs for the hit pages are correct

**Can navigate to a topic content page**
1. Open the search overlay by pressing the search button
2. Topic content tab is preselected
3. Type in something in the search box
4. Click on one of the hits
Expected result: You are navigated to the page and the search overlay is closed

**Can navigate to a topic content page by keyboard**
1. Open the search overlay by pressing the search button
2. Topic content tab is preselected
3. Use tab to navigate to the search box 
4. Type in something in the search box
5. Use tab to navigate to one of the hits
6. Ensure that focus is visible all the time (dotted border around the titles in the hits)
7. Select one of the hits by pressing `enter`
Expected result: You are navigated to the page and the search overlay is closed

### Notes
- Initially we wanted to set autofocus on the search box input field, but it's not advised to do so due to a11y. We will investigate this further
- When navigating with the keyboard, you'll notice that the whole tab (the list of hits) received focus between the search input field and the individual hits. This is due to the tab library we use, we'll investigate this further as well. They probably do it for a reason, but its nevertheless annoying. :) UPDATE: These to issues are now covered by #895

**Comment by wenche** [comment]
@meols  I tried to add some suggestions for some tests in the issue description ^^

This issue is just related to the topic content. Don't worry too much about the ranking of the hits yet, we haven't paid that much attention to this yet. This will also be a task for after we go live, as the real business metrics like number of visitors, the date for the last update of a page ++ are not available yet and we haven't even discussed things like this. But I did update the pageTitle to rank above a text block title so in the sustainability example the sustainability page is now number 1 :)

**Comment by meols** [comment]
Thanks for adding a detailed testing description @wenche :thumbsup: Much easier for me :smile:
"Search for a topic content" and "Can navigate to a topic content page" work perfectly.
For the navigating by keyboard part, I have a comment:
When the search result (investors, 11 topics 1 event) is on three pages and I have tabbed through the five items on page 1 and then tab to page 2 and click enter, page 2 is activated, but the tabbing continues to the page 3 pagination, the arrow, the logo, the close x, the search field, the topics tab, all five items outlined (as mentioned in Notes above) and then the topic/item at the top of page 2. How should the tabbing through work? I would expect after tabbing through the five items on page 1, tabbing to page 2 and going to the first of the page 2 items on the next tab?
Also I never go to the Events search results tab by tabbing through.
