### ISSUE TITLE
As a publisher I want my topic pages to be added to Algolia so that the end users can easily find them

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#832]
Topic page data must be added to Algolia

## To do
- [x] Ground work for pulling out topic data from Sanity and make them ready to be mapped to records in Algolia
- [x] We need to figure out exactly which components in the component array  we should add to Algolia. Discuss with UX
- [x] Define index settings for the field (searchable, snippets ++)

## Acceptance criteria
- Indexes for topic pages are added, both English/Norwegian and test/production
- [List of fields to add to Algolia] are added in Algolia. Verify in the Algolia GUI
- The settings are correct (Verify in Algolia GUI)

## In order to ensure good quality we should (Keep the ones we need for this US)
- [ ] Perform integration testing
- [ ] Perform functional testing
- [ ] Perform performance and load test
- [ ] Perform user testing

**Comment by nilsml** [comment]
TODO: Make list of data to index in first iteration

**Comment by wenche** [comment]
2. step: Create one record for each text block within a document-> If a topic page has 10 text block sections this will be 10 records in Algolia.
https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/indexing-long-documents/

**Comment by wenche** [comment]
@meols  I tried to add some screen shots to better explain the indexing for topic pages, but bottom line is: We need to tune the search as we go along. But feel free to test it out in the web, but remember that the design is not 100% done yet :)

**Comment by wenche** [comment]
Closing this for now. We can evaluate the hits, and add more content to be indexed later if needed.
