### ISSUE TITLE
When and how should the data in Algolia be updated

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#833]
We need to discuss this as it's a matter of both cost, time, data accuracy and usability. If we push content immediately on each and every publish, data in Algolia is fresh but this will cost more than if we push at regular intervals or at certain timeouts after publishing (like time X after the last publish and reset if more content is published before the time liimit)

If we replace all content in an index, this is probably safer. One document in Sanity will not be equal to one record in Algolia, making it harder to replace the actual changed content.

It might also depend on the type of content:
- Archived news
- News
- Events
- Topic pages

**Comment by wenche** [comment]
This is the initial discussion for this topic, and will probably result in a couple of new issues
- Something for listening to changes in Sanity, like 'publish' event and 'unpublish' events
- Look into if we need to use `copyIndex` and `moveIndex` to make the update more robust since Algolia doesn't delete records.

**Comment by nilsml** [comment]
Set up a timer trigger now with 5 minutes intervals, but this should be replaced something more sophisticated.

**Comment by nilsml** [comment]
Inform @meols and @jojog007 about the process right now.

**Comment by fernandolucchesi** [comment]
Investigate if it impacts price with our current solution.  If it does, this can become an urgent issue.

**Comment by fernandolucchesi** [comment]
We can trigger Algolia update with a webhook when creating/updating/deleting documents

**Comment by padms** [comment]
@nilsml ready to be reviewed.

**Comment by nilsml** [comment]
Reviewed and commented on the commit itself

**Comment by padms** [comment]
@nilsml Refactored :)

**Comment by nilsml** [comment]
Really nice @padms! You are close to being a certified Functional Developer 🤓 Great work!

**Comment by padms** [comment]
Safe to deploy as webhook for prod is not set up yet.

**Comment by padms** [comment]
@Mette This can be tested now. Upon publishing ( new content or updates) news, local news, magazine, topic content, events or routes should be immediately visible on search, newsroom and magazine. 
This can be tested on dev. 

This also fixes the problem of dev content not visible on search unless some one from dev team manually update it.

**Comment by meols** [comment]
@padms - this doesn't seem to work as expected. ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/15960bc7-0b2f-4e66-b8a1-7939297cc077)

**Comment by meols** [comment]
@padms - when testing updates on the title of a topic page the English was visible in search immediately, but the Norwegian is still not visible after 24 minutes![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/c3b85935-f955-4684-b5fc-32c970611459)

**Comment by meols** [comment]
For English event, title update wasn't visible in search after 6 minutes ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/4ba30b0c-f8b5-41e8-94d1-7f635bc4fb2c)

**Comment by padms** [comment]
@meols Please test now.

**Comment by nilsml** [comment]
Let's have a small workshop do make sure we are covering all scenarios

**Comment by padms** [comment]
@meols This can be tested

**Comment by meols** [comment]
Thanks @padms - this is great :thumbsup:
