### ISSUE TITLE
iFrame component - fullscreen button missing

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#835]

**Comment by meols** [comment]
I just noticed that the Vimeo fullscreen button isn't visible in the iFrame. Is that expected?
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/f0d9f9d7-c2b6-4cf3-b9c4-2cf8ccf11f2c)
https://energyvision.app.radix.equinor.com/sustainability/mettes-testpage
https://www.equinor.com/en/what-we-do/calendar/press-conference-q1-2020.html

**Comment by fernandolucchesi** [comment]
Closing since we will migrate to MUX
