### ISSUE TITLE
As a user I want my query to be highlighted in the search results so that I can see why these results match my query

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#844]
As a result of using the new hooks library from Algolia, we need to manually implement the results highlighting.

https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/react-hooks

https://www.algolia.com/doc/guides/building-search-ui/getting-started/react-hooks/#highlight-matches

Design: https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3812%3A76529 
## Acceptance criteria
- [ ] Query text is highlighted in each search result
- [ ] Ingress and text (when available) are truncated to only show the relevant part of the text (snippet functionality)

## Testing
- Type something in the search box
### Expected result
- The relevant matches are highlighted

**Comment by SvSven** [comment]
This is ready to be looked at @wenche @BirteThornquist

**Comment by nicholas-haggerty** [comment]
@SvSven Just opened the search. Not sure if its been noted or fed back anywhere else (so ignore if so!) but Equinor logo when opening the search should be white version.

**Comment by BirteThornquist** [comment]
Looking good @wenche!  The only thing is that the moss green color does not give good enough contrast to be a highlight, I think. Lets try spruce wood 100 instead. Design updated [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3812%3A76529)

**Comment by BirteThornquist** [comment]
@SvSven I think it's a good idea to add the URL to the search result. I think it might be better to add it under the text, though - floats better. Updated design [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3812%3A76529)

**Comment by SvSven** [comment]
I have updated the color to spruce-wood-100; I agree, it looks a lot better with that.
Have also moved the URL to below the text and updated the color from slate-blue-70 to mist-blue-100 like in Figma

Might take a while before the web is updated 😅

**Comment by wenche** [comment]
@meols This is ready to be testet.

**Comment by fernandolucchesi** [comment]
Hi @wenche. How are the results prioritised in the search result list? In this example the sustainability page is the 3rd result instead of 1st.
<img width="716" alt="image" src="https://user-images.githubusercontent.com/23337266/155962710-e0afec07-31e3-4e18-8146-fa52069ca3ee.png">

**Comment by wenche** [comment]
@fernandolucchesi  It's a complex algorithm, and we haven't done much with ranking and sorting yet. It's easier to see when you query inside Algolia because then you can see the why a hit was ranked the way it was. :)

The exact reason for sustainability is probably that Nils Magne introduced the concept of `pageTitle`  as the h1 and that's probably at the bottom of the list, while `title` the h2 is above atm.

To look more into this is on the list of remaining things to do.

**Comment by meols** [comment]
@wenche - looks good to me, and improved with the last ranking update (checked again with searching for Sustainability) One question: will texts on CTAs not give a result - both a question for the web and in sanity (which I understand is something else). We have added relink as part of the link text on several pages, without them showing in the search result (on the web and in Sanity)

**Comment by wenche** [comment]
@meols Yes, that's correct: texts on CTA will not give a result (in the web at least, cannot speak for the Sanity search here as we don't control that). We only index the page title, ingress and event description for events, and text blocks and accordion title + ingress for topics at the moment. We can adjust or add more later on, if we find that adding more texts will give a more accurate search result.

**Comment by meols** [comment]
Thanks for explaining @wenche 
Would be good to look into adding CTA texts later. F.ex. on the impact assessments page
https://energyvision.app.radix.equinor.com/sustainability/impact-assessments
we have simplified by removing AEM pages and only having separate pages for those with many pdfs. The typical setup is a project description text and the words impact assessment/konsekvensutredning on the CTAs, which means that a search for "aasta hansteen konsekvensutredning" doesn't give a hit on the page with this information:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/22a5d055-c3c8-4903-a8bf-8753117a417c)
Can I ask you to create a card on this for the backlog to give a better description than me :wink:? Then this card can be closed.

**Comment by wenche** [comment]
Created #919
