### ISSUE TITLE
Improve preview text for Full width image as decorative

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#847]
We should probably write decorative image or something like that instead of `undefined`

Same for Image component

![Skjermbilde 2022-02-10 kl. 09.54.34.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/ca379a50-00c9-421c-9a0e-bb0c3ffcd144)

![Skjermbilde 2022-02-10 kl. 10.10.57.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/23cfb821-1223-4d5d-95bd-719c9ae6f4b2)

**Comment by fernandolucchesi** [comment]
Looks good!

When committing try to remember the "#" in the issue number, you can read more here: https://github.com/equinor/energyvision/wiki/how-we-work:-using-github#commit-messages.
