### ISSUE TITLE
Teaser component: Two links added in editor, but only one link showing in preview and web

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#848]

**Comment by meols** [comment]
When we add two links in the teaser component (Editor), only one of them is showing. [Example page](https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/saml2?SAMLRequest=nZJBj9MwEIX%2fSuS749hJuo3VdlW2QlRaoNoWDlzQxHV2LRw7eJzC%2fvtNUyLKpQeu4%2bf5Zt68xf3v1iYnHdB4tyQ8zcj9aoHQ2k6u%2b%2fjinvTPXmNMBplDOT4sSR%2bc9IAGpYNWo4xK7tcfH6VIM9kFH73yliTbzZJ8V1AXSs0Er%2bYgGjGfHaEiydcJOPwYhIi93jqM4OJQyoSgmaCcH3ghRSEzkeZl%2fo0kuz%2bt3xl3NO759hz1RYTyw%2bGwo7vP%2bwNJNsMmxkEc0S8xdigZs%2f7ZuLQ1Knj0TfTOGqdT5VuWAxQg8pLWMy1oMT%2bWtOJVSe8a1WRlXZRVnbGzJYIka0Qdzo0fvMO%2b1WGvw8ko%2feXp8S8KOpMiOBNfU%2bPZadiUU57RjDMYvB5bMQXW1qB%2bsLKsgd%2flilzuIUeXwtUhbu8P00BkNeER%2fRV%2bpE2QBbtiTAH4NDTdbnbeGvX6PwF470ML8bb6XDFH2oxS2Z1zgVG7ODhqrf%2f1EDREvSQx9Jqw1WXMf6O5egM%3d&RelayState=https%3a%2f%2fequinor.sanity.studio%2fdesk%2ftopicContent%3b6a575c87-b446-401f-b594-a4e688279361&sso_nonce=AwABAAAAAAACAOz_BAD0_8xOEAMLdV9t_SBWn0kqt9c1yFbaM41jN2BbjBTB7vkOCRKdPMUN-LV81kmeP7Gjdn36sWXc_dfbB-uwxpgKhmEgAA&client-request-id=dc7ee84e-346c-4456-8f79-7c63abd4f644&mscrid=dc7ee84e-346c-4456-8f79-7c63abd4f644) ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/ed67539a-7a5e-49ef-9087-6c808cd668c6)

**Comment by wenche** [comment]
The issue here is actually that the max(1) from Sanity was removed when we said that the link should be optional. You should only be able to add one link for a teaser component. We should fix this in Sanity. :thumbsup:
