### ISSUE TITLE
Error page template

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#851]
A general 500 error page with the same design options as the 404 page.

**Comment by meols** [comment]
@nilsml  Do we need a separate template for error pages? If yes, is it captured somewhere (I couldn't find it)?
I found #769, #576, #500, #758 on the 404 topic

**Comment by wenche** [comment]
We think we should, and I've made it to be the same as the 404 page in terms of design and editor's options in Sanity

**Comment by wenche** [comment]
Same as #500, final look tomorrow

**Comment by meols** [comment]
The issue with Equinor Storage error pages is fixed :smile: Closing this.
