### ISSUE TITLE
Update the language plugin

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#852]
[Sanity has released the beta of the `document-internationalization` plugin](https://github.com/sanity-io/document-internationalization). We should update our code to use this plugin instead of the community version. The new version also offers an improved side by side interface for working with the translations.
 
[See Slack for release announcement ](https://equinor.slack.com/archives/C01A4BGNRMJ/p1643709984878879)

### Acceptance criteria
- Update to use the new translation plugin by using the migration path
- Nothing should break.
- +++

**Comment by fernandolucchesi** [comment]
Hi @SvSven, can you review this one?

**Comment by SvSven** [comment]
From what I can see everything still works. Did you have to run the "translation maintenance" they mentioned in the guide?

I could have sworn that my test page had a Norwegian translation, but that seems to have disappeared. Might be I never published it and the migration got rid of drafts somehow? Either way not a big problem.

**Comment by nilsml** [comment]
Discuss with Sanity if there is anything we missed here.

**Comment by adneforslund** [comment]
Waiting for Sanity, some issues with conversion of fields

**Comment by nilsml** [comment]
Let's wait until we have updated Sanity

**Comment by wenche** [comment]
**One notable different**
When you create a new document the language dropdown is not visible before you have added some text into the editor. This means that if we want to create like a Norwegian only topic content, we'll need to add some dummy text to the English version to be able to switch to Norwegian :/

![Skjermbilde 2022-05-18 kl. 13.45.04.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c8ed94b6-80a2-4a45-aeda-d935a758c536)
![Skjermbilde 2022-05-18 kl. 13.45.15.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8c874066-2454-4430-bd7b-d0e78c1e9614)

**Comment by wenche** [comment]
**Testing the _lang attribute**
This seems to be working as expected
English version, not published
![Skjermbilde 2022-05-18 kl. 13.51.08.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/cc0eb4e7-9c9b-4c7b-8b70-2bd45ecc587f)
English version, published
![Skjermbilde 2022-05-18 kl. 13.51.55.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/37b0c62d-8419-4682-90f9-8ecfa4e2bbf4)
Norwegian version, not published
![Skjermbilde 2022-05-18 kl. 13.52.36.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c7cbf30f-277b-4c2b-bec1-a1ecfd7762f7)
Norwegian version, published
![Skjermbilde 2022-05-18 kl. 13.53.20.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/dcc32749-6b5d-4bd8-8287-fdec3af18933)

**Comment by fernandolucchesi** [comment]
LGTM!

But before we forget, the upgrade adds new fields to referenced translations:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/23337266/169278095-77356201-c458-4815-9927-47b8e3428d56.png">

<img width="670" alt="image" src="https://user-images.githubusercontent.com/23337266/169278320-dd238f00-ae0d-4455-a540-17072c678b5a.png">

Ideally we also need to use the "Translation Maintenance Plugin" to have all old documents updated accordingly https://github.com/sanity-io/document-internationalization/blob/main/docs/translation-maintenance.md. (For each dataset). 
Maybe we should evaluate this in a different issue? How risky can it be?

**Comment by wenche** [comment]
Created #1101 to address the private field changes
