### ISSUE TITLE
Make preview easier and less error prone to use

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#853]
By watching the records of the publisher's workflow, if seems like there is some confusion related to the temporarily fix for the lack of live preview. Can we improve this somehow? 

(Pay attention to the return of investment, since the preview experience will be improved when groq-store is back in business. But we don't know how long that will take)

### Suggestions
- Sven did some experiments with setting the cookie when the publisher choose the `preview` tab
- Nils Magne suggested to highlight wether the cookie is set or not in the UI somewhere
- Should we add a banner to the top/bottom of a page if the page is in preview mode? Like "You are watching a preview of this page"

**Comment by nilsml** [comment]
We should upgrade Sanity and try using the live preview again. If it doesn't solve our issues we should take that up with Sanity.
