### ISSUE TITLE
update styled-jsx to v5

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#857]
We are currently using v4 of `styled-jsx` but a new v5 is available.
We should check if any of the changes are a concern to us as we are doing things slightly different in `_document.tsx`

https://github.com/vercel/styled-jsx/releases/tag/v5.0.0

**Comment by wenche** [comment]
![Skjermbilde 2022-05-19 kl. 10.38.50.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/8c78879e-7490-4f5e-84a8-6680a075efd6)

This is already done. But another question is: Do we actually use this? I think no @SvSven

**Comment by wenche** [comment]
I removed the package all together @SvSven

**Comment by SvSven** [comment]
Sounds good 👍
