### ISSUE TITLE
en-GB as part of the url causing issues

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#859]

**Comment by meols** [comment]
Yesterday the editorial team noticed that **en-GB** was part of the url, today it isn't. But it seems like internal text links we have created while this was an issue, still contains en-GB as part of the link, and that is causing a 404: example on this page https://energyvision.app.radix.equinor.com/about-us/privacy-policy-and-data-protection  ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/5e773a6b-d1c7-49d9-aca5-c9e0f02d54a0)

**Comment by wenche** [comment]
[Technical explanation coming up] The internal link renderer component used to handle links from the rich text editors has a bug. We add `locale` as getIsoFromLocale which gives en-GB. I have no idea why we do this? We should fix this, but also try to figure out why we added locale to NextLink in the first place

**Comment by meols** [comment]
Also: can this be fixed by a script and/or relevant pages with this issue be identified.
We also discussed in todays meeting that /en/ or /no/ will be part of the url. Currently /en/ isn't part of the url.
Please confirm if /en/ will be part of the url or if /en/ is missing and potentially will cause similar issues for internal links.![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/dfa7c669-e3b4-446f-834c-10563e8b80f6)

**Comment by fernandolucchesi** [comment]
Hi @wenche, can you review this one? :)

**Comment by wenche** [comment]
Lot's of issues in the console?
![Skjermbilde 2022-02-21 kl. 15.19.36.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/db319a78-62d4-46ac-9b99-2a64e1c1eb36)

**Comment by wenche** [comment]
And by the way @meols  , please don't use 'here' as the link text. :thumbsup:

**Comment by meols** [comment]
@wenche - the links are now working - thanks :smile: Re. to /en/ or not to /en/, from the editorial end we are expecting this to be as today - with /en/ - and I don't think I completely understand the answer/issue. What kind of redirect will the next.js redirect be (for our already redirected pages)? On using "here" as link text, we do avoid that - except for this page with a text that's been delivered from Legal :sweat_smile:
