### ISSUE TITLE
Investigate indexing of archived news articles

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#874]

**Comment by nilsml** [comment]
Things to consider:

- Should not index all articles all the time
- How to do it in a smart way parallelising the task, and at the same time stay under thresholds from Algolia?
- Proper encoding (utf-8?)

**Comment by wenche** [comment]
We need to align the keys as much as possible with the Sanity news article. 
- We need a publishing date.
- Is it possible to get the real page title, and not just the meta title? Now it's just in the content. Or is the page title so equal to the <title> that we will have decent hits anyway?
- Two arrays for the tags

**Comment by nilsml** [comment]
Covered by #617
