### ISSUE TITLE
Limit access to content based on role

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#879]
**In order to control who gets access to what, we need to limit content in Sanity Studio based on Sanity role**

## Acceptance criteria

1.  If content is available to role x, a user with role x should be able to access the content
2.  If user with role x is removed from that role, she should no longer be able to access content only available to this role

**Comment by adneforslund** [comment]
https://www.sanity.io/docs/roles

**Comment by SvSven** [comment]
One thing of note here is that we need to be clear that we cannot limit access to uploaded images and files per Sanity's answer on that. Once a file has been uploaded to the library, it's available to everyone in the studio as well as in the API

**Comment by nilsml** [comment]
@fernandolucchesi will make the dataset private and refactor code accordingly
