### ISSUE TITLE
Handle HTML special characters like ampersand in search hits

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#880]
React doesn't render special characters like ' and & in the search hits, we need to fix this.

 ![Skjermbilde 2022-02-18 kl. 13.53.10.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/dc200392-1bd4-4c5e-a18d-3f9fabc129cf)

**Comment by fernandolucchesi** [comment]
Hi @wenche, can you review this one please?

**Comment by wenche** [comment]
LGTM :thumbsup:

Closing this issue, since it's just a little building block for the search
