### ISSUE TITLE
Issues with focus, focus-visible and Safari

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#881]
We use a library to polyfill focus-visible. We want the focus to only be applied for keyboard users, not it you use a mouse. 
I Safari, I see the native focus style for several elements. I can't see exactly why this is happening, but it seems to be related to attached screenshot of styles

![Skjermbilde 2022-02-21 kl. 09.22.25.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/412b3b94-4783-454f-bd8a-07b9d0a42f35)

![Skjermbilde 2022-02-21 kl. 09.19.15.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/7de7210a-7cc7-4899-8eec-28772db0a1cc) 

Example URL https://energyvision.app.radix.equinor.com/careers/faq

**Comment by millianapia** [comment]
This might not be relevant anymore due to the move from reachUI to ChakraUI

**Comment by nilsml** [comment]
@millianapia to see if possible to replicate

**Comment by millianapia** [comment]
not a problem after we started using another library for accordions
