### ISSUE TITLE
Always display locale in the url

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#883]

**Comment by fernandolucchesi** [comment]
We need to discuss if we really want this feature

**Comment by nilsml** [comment]
To be discussed in Oslo

**Comment by wenche** [comment]
Related discussion from Next.js: https://github.com/vercel/next.js/discussions/18419

The updated docs: https://nextjs.org/docs/advanced-features/i18n-routing#prefixing-the-default-locale
