### ISSUE TITLE
Icon and text component: svg from Brandmaster Icon and illustration archove isn't uploaded after being selected.

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#885]

**Comment by meols** [comment]
This one has been on and off a few times. Icons work in the teaser component, but not in the Icon and text.

**Comment by wenche** [comment]
`https://web-energyvision-dev.radix.equinor.com/_next/image?url=https%3A%2F%2Fcdn.sanity.io%2Fimages%2Fh61q9gi9%2Fglobal%2Fa838ba616f9f11afb6ba24c1893c402045be4737-125x125.svg%3Fw%3D150%26h%3D150%26auto%3Dformat&w=384&q=75`

 ![Skjermbilde 2022-03-08 kl. 12.31.14.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c301158f-3317-4444-bdcf-be6759f18612)

400 status code for the image in the web

**Comment by meols** [comment]
Also the animated icons doesn't work correctly, as Nick showed in the workshop at Fornebu. Both errors can be viewed on this page: https://energyvision.app.radix.equinor.com/energy/renewable-energy-and-low-carbon-solutions

**Comment by SvSven** [comment]
I am able to reproduce the problem with uploading the icons (this is good) but I am so far not able to figure out _why_ this is happening (not good).
Have reached out to Sanity to see if they can help.

**Comment by SvSven** [comment]
@meols could you and the editors see if this is still an issue?
it seems to be working fine on my end now when trying to select images from the icons and illustrations bank - so I'm wondering if the network policy changes we did to try and solve the slowness in the studio may have fixed this as well.

**Comment by meols** [comment]
@SvSven - seems to still be an issue. Some examples:
- United states page: animated icons showing, "other" icons not showing
https://energyvision.app.radix.equinor.com/where-we-are/united-states
- EU page - icons not showing (in two components)
https://energyvision.app.radix.equinor.com/where-we-are/eu
- CCS page - icons not showing
https://energyvision.app.radix.equinor.com/energy/carbon-capture-utilisation-and-storage
- I also tested with fetching from Brandmaster, Media and uploading from desktop on mettes testpage, and none were showing
https://energyvision.app.radix.equinor.com/news-and-media/mettes-test-page

**Comment by SvSven** [comment]
Ah yeah I haven't looked into the animated icons or the broken images on the web - I was mostly referring to the icons not being uploaded to Sanity when you select them in Brandmaster 😅

**Comment by meols** [comment]
:smile: @SvSven - didn't manage to upload to sanity when selecting in Brandmaster either

**Comment by meols** [comment]
@SvSven - is this issue dependent on Brandmaster, what's the status?

**Comment by SvSven** [comment]
@meols I'm not sure yet, but I suspect it's an issue on Sanity's end. I've contacted Sanity about it and they are looking into it. It's not something we can easily debug from our end since there are no errors or any indication of what might be wrong.

**Comment by meols** [comment]
:thumbsup: Thanks @SvSven

**Comment by SvSven** [comment]
@meols It looks like we managed to fix the rendering of the icons now

**Comment by meols** [comment]
Thanks @SvSven - I see that already added icons are showing on the Natural gas page, Carbon capture page, EU page - great! But I am still not able to add icons - tested on the Natural gas page https://equinor.sanity.studio/desk/topicContent;1ef36c61-4589-4864-86a0-1ba5cce4b89c by both Trude and me, with and without VPN, in chrome and edge. After selecting an icon, it never is added to the component.

**Comment by SvSven** [comment]
@meols Yep, I'm seeing the same thing on the link you provided - but at least we managed to solve one part of it. Now for the next 😅

**Comment by meols** [comment]
@SvSven - :smile: a very good start :thumbsup:

**Comment by SvSven** [comment]
@meols Okay I have pushed a change that should hopefully fix this issue - it fixed it for me locally at least (for now 😬)
