### ISSUE TITLE
Add Azure functions to CI and Azure

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#887]
**In order to run the indexers in Azure, we need to set up CI for deploying the Azure functions**

## Acceptance criteria
- Config settings in app config
- Secrets in key vault
- Functions to be triggered by hooks
- First version, update indexes every five minutes
- Possible to set which environment to update dynamically

## Note
It should be "hard" to make mistakes so that an index will always contain data from the corresponding dataset

Relates to #820 and #497

**Comment by nilsml** [comment]
This was not easy. Using a hack now to include all dependencies in searc/node_modules/.pnpm but that is several thousand files we don't need. Have to find a better solution! For now we could at least consider zip-ing the files before upload to Azure, but the best solution would be to only include needed files.

References:

- https://github.com/pnpm/pnpm/issues/4378
- https://github.com/pnpm/pnpm/issues/2198
- https://www.shanebart.com/deploy-az-func-with-github-actions/

**Comment by nilsml** [comment]
Could also look into pnpm 7

**Comment by SvSven** [comment]
We should probably do a walk through of this sometime next week

**Comment by nilsml** [comment]
Yes, we can set up a walk-through. I guess that goes for several things I have worked on in the project...
