### ISSUE TITLE
Initial load of Sanity Studio hangs forever

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#889]
**Describe the bug**
Sanity Studio hangs loading the first time the page is visited for some users. Spinners keep spinning to eternal time.

**To Reproduce**
1. Go to 'equinor.sanity.studio'
2. Wait for studio to load
3. Keep wating…
4. When tired, stop waiting. Reload to get studio up.

**Expected behavior**
Studio should load the first time

**API calls pending (no answer)**
- https://h61q9gi9.api.sanity.io/v1/data/query/global?query=%5B*%5B_id%20in%20%5B%22drafts.1d30382d-607a-4242-8496-00505cee467d%22%2C%221d30382d-607a-4242-8496-00505cee467d%22%5D%5D%5B0...2%5D%7B_id%2C_rev%2C_type%2C_type%7D%5D%5B0...1%5D&tag=sanity.studio.preview.document-paths
- https://h61q9gi9.api.sanity.io/v1/data/query/global?query=*%5B_type%20%3D%3D%20%22page%22%20%26%26%20(!defined(_lang)%20%7C%7C%20_lang%20%3D%3D%20%24baseLang)%5D%7Corder(_createdAt%20desc)%5B0...100%5D%7B_id%2C_type%7D&%24baseLang=%22en_GB%22&tag=sanity.studio.desk.document-list
- https://h61q9gi9.api.sanity.io/v1/data/doc/global/drafts.1d30382d-607a-4242-8496-00505cee467d,1d30382d-607a-4242-8496-00505cee467d?tag=sanity.studio.document.snapshots

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Edge
 - Version evergreen

**Comment by SvSven** [comment]
This has since been fixed - the problem was corporate network policy not playing nice with Sanity if I recall correctly.
