### ISSUE TITLE
SVGs not displaying in preview or web 

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#890]

**Comment by nicholas-haggerty** [comment]
Added SVG icons on Brazil site.
1. The same issue as the global. When using Brandmaster link, the icons do not load into Sanity. So alternatively....
2. Download the icons needed from Brandmaster to desktop and then UPLOAD to media in Sanity. The icons then show and are accessible for the icon component. However in preview and and when published the icons do not display.

Examples can be (not) seen here:
https://web-brazil-energyvision-dev.radix.equinor.com/
https://studio-brazil-energyvision-dev.radix.equinor.com/desk/topicContent;6cf2adf0-8e19-49c5-aeba-1668d11c4c70%2Cview%3Dpreview
@meols I cannot add labels, so when oyu get a chance, add BUG please!

**Comment by wenche** [comment]
@SvSven @meols   This one should be sorted out by now right?

**Comment by meols** [comment]
@wenche - regarding the full width one on the United Kingdom page looks like there still is an issue: https://equinor.sanity.studio/desk/topicContent;0e2bc501-1474-4e40-ac81-148fc1931ec4
https://www.equinor.com/where-we-are/united-kingdom

**Comment by fernandolucchesi** [comment]
This was fixed on #885
