### ISSUE TITLE
Search hit link is causing a full page load

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#892]
Should be a client side navigation, but is not since the refactoring of the link component.

**Comment by wenche** [comment]
The introduction of the `forwardRef` was because of a [warning with Next.js](https://github.com/vercel/next.js/issues/7915). This approach seems to break client-side navigation, so I'll try a less elegant approach

**Comment by wenche** [comment]
Will leave this as an exercise for @SvSven when he's back :)

**Comment by SvSven** [comment]
I don't understand why the forwardRef breaks it here, but the change and the reason for the change has been noted 👍
