### ISSUE TITLE
Anchor link on text link

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#894]

**Comment by meols** [comment]
How to solve this legally required page: https://energyvision.app.radix.equinor.com/about-us/privacy-policy-and-data-protection
Is there a way to add anchor link to an internal text link, to jump down to anchor on the page?
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/84b29b80-e864-4a51-946f-6c45dc6457af)

**Comment by meols** [comment]
@nilsml - can this issue be prioritized, adding anchor option to internal link in text. We have received a request from Legal to prioritize this - due to it being of a complaint from Datatilsynet, that Equinor has a deadline to handle before mid-May.

**Comment by meols** [comment]
[https://app.zenhub.com/files/224120954/46f605f2-45af-490c-9f52-3c43b0530e3d/download](https://app.zenhub.com/files/224120954/46f605f2-45af-490c-9f52-3c43b0530e3d/download)

**Comment by SvSven** [comment]
@wenche @fernandolucchesi Added a quick fix solution, but we should probably make a proper table of content component at some point

**Comment by wenche** [comment]
You should be able to test this shiny new feature in https://studio-global-energyvision-preprod.radix.equinor.com/desk @meols :)

**Comment by SvSven** [comment]
In the long run we should probably make a proper table of content component that can automatically generate the links based on the headings used - but for now this should work to fix the immediate problem.

**Comment by meols** [comment]
@SvSven - I saw that I can create an anchor link, but when clicking on it in preview I jump to the top of the page and created anchor links disappeared. As mentioned in the meeting I really don't understand the preprod vs prod preview - I thought I couldn't test it because it was mentioned that it is prod data and preview, but I see the links in preview. If the test is that I can create an anchor link its OK, but if preview should work, it didn't work as expected

**Comment by fernandolucchesi** [comment]
Please test it on https://studio-global-development-energyvision-dev.radix.equinor.com/desk
