### ISSUE TITLE
Persist search state in the URL

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#896]
For an improved user experience we should use the URL to persist the search state. We need 
- the selected tab (tab=x)
- the query (q/query=x)
- the selected page for the pagination (p/page=x)

The ultimate goal is be to restore the complete search state on browser back to achieve something like this flow:

1. User searches for `sustainab`, selects the events tab, navigates to hits page number 2 by using the pagination
1. The user clicks on the hit number 1 on that page, an imagined event called "Sustainability goals for 2024"
1. The user is navigated to that page, but quickly realises that this is not the event she was looking for
1. The user clicks on the back button in the browser or on her mobile
1. The search overlay is opened and the search state is restored to where she left if, making it easy to select hit number 2 instead, the one called "Sustainability goals for 2023"

### Acceptance criteria
- URL has attached query params like `?tab=topic&query=sustain&page=2`
- If the query param for at least query exists, the search overlay state should be `open`
- The pagination component must select the corresponding page from the url (controlled component)
- The search box must be controlled by the query content
- The routes must be updated once (use` router.push` when the user open the search overlay and `router.replace` to update the query params when the user interacts with the search)

**Comment by wenche** [comment]
Some back and forth on this one as this is one of the things that has changed with the hooks implementation.

### Use the routing param
- The idea from Algolia's side is that if we pass the routing param we don't manually need to listen for changes as everything should happen behind the scenes. 
- This sounds very promising
- However, some issues
1. Hard to add our `tab` query param, since it's not a part of the UiState type from Algolia. 
2. Changing tabs cause a rerender and you loose the keyboard state
3. If you click a hit and use browser back, the first item in history is not the url with the query params, but a version without and then the next has query params
4. If we enable the Next.js `router` key on the routing param, the app will freeze on browser back
5. The tab query param is not removed when the search is closed/unmounted
5. Some other issues as well
- Bottom line: It doesn't seem to play very well with custom query parameters and router history

### Use UI state and change handler
- This is also updated from the original version, the `searchState` is deprecated in favour of UiState. The ui state object has one key with a complete state object for each index name
- This is more complex to keep track of
- We get warnings in the console about missing widgets for like query, even if we have implementet a search box
- Hard to keep in sync
- Doesn't feel right/too complex

### Combination with router for the Algolia state queryparams and manuallly adding tab query param for tab using Next router
- When we update the router with the tab state on tab change, it's removed
- Seems like the two URL state mechanism are fighting against each other
- Seems buggy

**Comment by wenche** [comment]
Let's see if Algolia can clarify some of the issues

**Comment by wenche** [comment]
I will move this to the backlog for now. In order to improve the current implementation, we should take a step back and look into how we would like this to work. We also need to see it in the context of the newsroom which are currently a MVP. One of the main challenges will be to make this scale across several tabs, pagination components, search input, filters and more.

Algolia has updated the Next.js example and it run both in the Sandbox and locally. We should look into this, and see if some of the bugs in the discussion is fixed (see link in the issue description)

Currently we have implemented the tab and the query in the URL for search only by using approach number 3 (combination) from the issue description. This kind of works, but it's a little bit buggy when you open the search overlay.

**Comment by fernandolucchesi** [comment]
This is almost finished - missing only the pagination part. We should also include this to magazine and newsroom

**Comment by fernandolucchesi** [comment]
Closing this since we already have #915
