### ISSUE TITLE
As an editor I need the option to add footnotes in the text editor

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#898]
## Acceptance criteria
- [ ] A footnote function is available in the rich text editor
- [ ] By clicking "Add footnote" a modal input field is shown where the footnote text is added
- [ ] A number will be added where the marker is placed in the text
- [ ] The footnote will be placed in numbered order at the end of the text components paragraph text

**Comment by BirteThornquist** [comment]
A new footnote icon in the toolbar:
![Skjermbilde 2022-03-01 kl. 14.37.27.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/bb80917f-2e85-455b-ab2d-db053a0773d3)

The footnote will have font size x-small, type Scale 00 and  will be added at the bottom of the paragraph text left aligned as designed in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4592%3A81386)


![Skjermbilde 2022-03-01 kl. 14.53.39.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/bcf10d98-dd90-46ee-8761-28cfd4d07688)

**Comment by BirteThornquist** [comment]
Footnote is different from the small text styling and is not used much on the site. It will be possible to solve footnote with the small text styling which is prioritized in the todo, so this will be a backlog issue for now.

**Comment by fernandolucchesi** [comment]
This problem was solved with the `Small text`
