### ISSUE TITLE
Find a way to map between translated Norwegian urls and existing one in English

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#899]
Existing URL in AEM
`https://www.equinor.com/no/careers/summer-intern.html`

We want to translate the URL into Norwegian, like
`https://www.equinor.com/no/karriere/sommerjobb.html`

We need a way to link those two versions to avoid 404 for all Norwegian URLs in the wild
### Some suggested approaches
- Add them to a general route document? +Simple -Hard to ensure that all are captured?
- Create a separate field in the Norwegian route document "Pre-translated version of this URL" +Easier to cover every new route. Can use validation to ensure that each new route has this field -More complicated to develop?

### Acceptance criteria
TODO Update when we have figured out how to do this.

**Comment by wenche** [comment]
Also see #384 for addressing characters

**Comment by nilsml** [comment]
Update this issue with our preferred solution and get Mettes blessing

**Comment by nilsml** [comment]
Doable with the approach we currently use in Sanity
