### ISSUE TITLE
Which satellite pages should have translated URLs

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#900]
Look into the actual needs here.  Like the need for Spanish URL in the Argentine satellite

**Comment by nilsml** [comment]
This could be done by the editors?

**Comment by nilsml** [comment]
@wenche to add description in Figjam for this case to make it clear

**Comment by wenche** [comment]
Yes, it should be done by the editors, but when we discussed this we didn't know if the translated URLs approach should be used for satellites as well. 

https://www.figma.com/file/xm1aNey7RrP4llwou1t8OX/Envis-content-Figjam?node-id=1245%3A16151 shows the potential issues if we have a satellite pages with non-translated urls and news articles.
