### ISSUE TITLE
Ensure news or magazine article link in the news letter does not give 404 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#901]
If the news is published from AEM and newsletter sent from AEM.. and its seen from energyvision, we need to make sure that the link in the newsletter mail does not give 404.![image (1).png](https://images.zenhubusercontent.com/60ec03bee99549a0e2a093b7/261c8013-9674-4e54-8372-89babb9f64ac)

**Comment by nilsml** [comment]
Will publish news articles from Sanity now
