### ISSUE TITLE
Define first version of the newsroom

### ISSUE THREAD

**Issue by nilsml** [equinor/energyvision#904]
- Focus on the news (not Magazine and Events in MVP)
- Postpone URL state -> Create separate issue to imprve
- No mobile filter overlay -> create separate issue to improve
- All old news in the year filter (2022-1998)

**Comment by wenche** [comment]
@BirteThornquist  to update Figma

**Comment by BirteThornquist** [comment]
@meols a MVP version of the Newsroom added in Figma here[https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=5229%3A83194](url)
![Skjermbilde 2022-03-25 kl. 11.03.39.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/f57f39ba-8504-458b-a62b-35ce31f3c352)

**Comment by meols** [comment]
@wenche @BirteThornquist - we are happy with this as the newsroom MVP :smile:
