### ISSUE TITLE
Query params when the search panel is opened

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#907]
**Describe the bug**
When the search is opened, the tab state is initialised with either the tab from the URL or the default (topic atm) and add at `tab=topic `in the URL. Immediately after the query param will be added (`query=""`) and the tab query param is removed. Plot twist: This only happens in production, not at localhost. 

The resulting query history is that both `url?query=""` and `url?tab="topic"` are added and if you look at the URL it is switching. It _think_ it might have something to do with the `refine` in the SearchBox, so some internal states in Algolia overrides the tab? Or some race conditions, but I would assume that Next.js router shouldn't behave like this.

**To Reproduce**
1. Go to some page in production
2. Click on the search icon
3. Look at the URL, notice that tab=topic is swapped with query=""
4. Click browser back, notice that both states are pushed to history

**Expected behavior**
The URL should be `url?tab=topic&query=""`

**Comment by fernandolucchesi** [comment]
Look into it once algolia has finished the work on hooks

**Comment by fernandolucchesi** [comment]
This has been fixed
