### ISSUE TITLE
Add gtm

### ISSUE THREAD

**Issue by adneforslund** [equinor/energyvision#908]
Code is added and GTM is configured, Missing env variables in radix

**Comment by adneforslund** [comment]
Blocked til Radix envs are working again

**Comment by fernandolucchesi** [comment]
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/23337266/160026271-280f73e3-b2bd-43a7-803a-f2a64fe1737e.png">
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/23337266/160026295-5ab168f5-1b29-4d2e-9f36-e9e8f4be6fa6.png">

**Comment by wenche** [comment]
@fernandolucchesi  Are we able to avoid this message in the console somehow?
![Skjermbilde 2022-03-25 kl. 15.15.14.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/80443a95-3888-43d8-9c79-99d638be0e35)

**Comment by fernandolucchesi** [comment]
> @fernandolucchesi Are we able to avoid this message in the console somehow? ![Skjermbilde 2022-03-25 kl. 15.15.14.png](https://camo.githubusercontent.com/232fd0a7c395ea2769f33245ceec5a8eb06eb44591ccb080e51d2e07057d0e1b/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566623761613962363533643531333562623863353066352f38303434336139352d333838382d343364382d396337392d393964363338626530653335)

which url did you get this error?

**Comment by wenche** [comment]
@fernandolucchesi  It's on localhost
