### ISSUE TITLE
As an end user I want the most important pages to be pre build to make the site blazingly fast

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#909]
### Questions to discuss and experiment with
- Which pages are most important? Both topic pages and news pages
- How many pages can we pre build? (using `getStaticPaths`) What is the sweet spot of performance (lot of pre build pages) and build time on CI (takes more time to pre build a lot of pages)
- Do we need to pre build some of the pages from the old AEM (news pages)?
- What about the satellite pages? The solution must work for them as well

(Bonus question: Does the new features of Next.js somehow affect this?)

**Comment by fernandolucchesi** [comment]
Duplicate #1566
