### ISSUE TITLE
Create contact form 

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#910]
## Acceptance criteria
- Be able to add 'Contact Equinor Form' in topic page, with title and ingress ( optional) 
- Be able to add or modify the translations for the form  field labels, text  and error messages.
- Be able to successfully submit the form and verify that RITM is created in service now ( https://equinortest.service-now.com/nav_to.do?uri=%2Ftask_list.do%3Fsysparm_query%3Dactive%253Dtrue%255EstateNOT%2520IN6%252C5%255Ecmdb_ci%253D66f0ff89db2e2644ff6272dabf961945%26sysparm_first_row%3D1%26sysparm_view%3D )
- Validations are done properly.

**Comment by padms** [comment]
@BirteThornquist  I need some inputs to continue on this task. 

1) Currently ( in AEM ) all the forms have optional title field. Do we need this title? 
2) Design for this form https://www.equinor.com/en/about-us/forms/how-to-order-our-annual-report.html, ( we  discussed to avoid adding download link in the form ) 
3) Form component design in sanity.

**Comment by BirteThornquist** [comment]
@padms @fernandolucchesi @meols 
Since there will be just a few types of forms, and to make a cost-effective solution, we will have a set of predefined forms that the editor can choose from. The interaction will be similar to the promotion, where you first choose to add a form and on the next step you choose between the different forms available in Sanity. I have outlined the interaction design in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3309%3A71064)
I have also added ingress text. We have to look into what we shall call the different forms.

**Comment by BirteThornquist** [comment]
To answer your first question about title field @padms - I have kept the optional title for the forms.

**Comment by BirteThornquist** [comment]
@padms All I get when selecting type of form is this msg: ![Skjermbilde 2022-03-17 kl. 13.37.16.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/7156d019-775c-4744-b8d0-b5b651305d12)

**Comment by padms** [comment]
@BirteThornquist  All other forms except order reports do not have any fields. So there is nothing to configure for other forms.

**Comment by BirteThornquist** [comment]
@padms Can the add downloadable file show up for the order form - and for the rest we do not need to show a msg? it looks a bit like an error msg to me.

**Comment by meols** [comment]
@padms @BirteThornquist - thanks, and some questions:
- Could the component be called **Forms** instead of **Form**, to indicate that it contains more than one form?
- How/when will the translation to Norwegian be handled
- Can we test that questions to the different options goes to the correct assignment groups in s@e? (Is the form linked to s@e stage or prod?)
- Can the form component be hidden from the satellite sites?

**Comment by meols** [comment]
@padms - also the submit button should be called "Submit form" with a lowercase F.

**Comment by padms** [comment]
@meols 
- Could the component be called Forms instead of Form, to indicate that it contains more than one form? **Corrected it** 
- How/when will the translation to Norwegian be handled 
 **Translations can be added under text snippets against each form's text** 
- Can we test that questions to the different options goes to the correct assignment groups in s@e? (Is the form linked to s@e stage or prod?) 
**Currently linked to stage ( see the url in acceptance criteria )**

**Comment by meols** [comment]
@BirteThornquist - Is the "guiding text/field names" (Name, email etc.) an OK font size? Looks a bit small to me.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/1ff8f855-01ff-4ab2-9cf6-5f4f71872ffc)

**Comment by BirteThornquist** [comment]
@meols The form fields is from EDS and use these text styles. I absolutely agree the text should be bigger. Padmaja is looking into if we can change the size without taking too much effort.

**Comment by BirteThornquist** [comment]
@meols @padmsI think the components should be named in singular in the Add menu in Sanity (except Promo tiles that must be a pair). That is how we have done it for the other components. Promotion for instance, also exists in different types. The name also shows up as a title for the edit modals - and here "Edit Form" is better than "Edit Forms". ![Skjermbilde 2022-03-22 kl. 12.01.36.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/1115e22a-eebf-443f-b521-fc9a81010096)

**Comment by padms** [comment]
@BirteThornquist  @meols  I have increased the font-size of label ..

**Comment by meols** [comment]
@padms - for some reason the text in text snippets for "Contact form: How can we help you?" and "Contact form: Who are you trying to reach?" are shown as "Name" in the form - even if they have the correct text in English and Norwegian.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/623a9600-9904-4c00-9fa7-c7989818d86b)

**Comment by padms** [comment]
@meols : I found the one ticket for this form in service now from you.

**Comment by meols** [comment]
Thanks @padms

**Comment by BirteThornquist** [comment]
Same comment about the font size as written in issue #921
