### ISSUE TITLE
Fix preview for news

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#911]

**Comment by fernandolucchesi** [comment]
@wenche can you check this one?

**Comment by wenche** [comment]
Still some issues
1. Doesn't work for Norwegian, seems to be some issues with the locale
![Skjermbilde 2022-03-16 kl. 11.05.00.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/2af8b054-4028-4e36-b94e-76ed2b687b1a)
2. Difference between server and client
![Skjermbilde 2022-03-16 kl. 11.10.07.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/5259f330-57f4-47c0-915b-d617483d2ccb)

@fernandolucchesi

**Comment by wenche** [comment]
@fernandolucchesi  I dunno about the client/server mismatch, seems to be only for that url so I didn't bother to spend time on it. But the Norwegian preview should work now, please verify :thumbsup:

**Comment by fernandolucchesi** [comment]
Seems to work fine, warning is related to the already known issue with the localization switch. Closing this.
