### ISSUE TITLE
Allow Internal Links to link to different languages inside text editor

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#912]
Currently editors have to use an external link, this is not ideal.

**Comment by SvSven** [comment]
Looks good! But I would maybe add a helper description below the toggle if possible - something along the lines of "Use this if you want to create a link to a page of a different language"

**Comment by wenche** [comment]
@BirteThornquist @SvSven Happy?

**Comment by BirteThornquist** [comment]
@fernandolucchesi Agree with Sven -we should have a help text to this toggle. ![Skjermbilde 2022-03-17 kl. 14.31.19.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/426b5a2f-e57f-414b-a60d-4e5359dd7d1e)

**Comment by SvSven** [comment]
I believe the "Select this if you want to link to  a page that is in another language." is the description - which is already an improvement to what there was initially.

Do you think this is not good enough @BirteThornquist ?
