### ISSUE TITLE
Create schema for local news

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#917]
Related to #143

Set up the schema and desk structure for local news. This is largely the same as the regular news schema, but without the subscription field. We will need a hard-coded system for local news tags, where the editor can select a specific market.

## Subtasks
- [x] Create local news tags, add to schema as dropdown select. This field should be mandatory and has to be filled before a slug can be generated.
- [x] Update slug field to prefix slug based on selected local news tag

## Acceptance criteria
- Local news template is accessible in the main Sanity menu
- Can filter local news by market tag
- Can create local new documents
- Local news template does not have subscription field
- Local news market tag is mandatory field
- Local news slug is prefixed with value of the selected local news market tag
- Creation/editing of local news market tags should be restricted to administrators

**Comment by SvSven** [comment]
@wenche @fernandolucchesi there is some creative coding here to share the news fields between 2 document types, so if you could have a look and see if we're all on the same page that would be great 👍

we also still need to come up with a good way of handling the access control for the local news and local news tags

**Comment by wenche** [comment]
Testing highlighted several issues, @SvSven  to the rescue

**Comment by SvSven** [comment]
@meols This issue is for creating local news. The template for local news is the same as the regular news template, but without the subscription field and with a newly added "local news tag" field.

We have added a new menu item called "Local news" which is where the local news is created. This is using a similar structure as the asset library, where there are pre-defined filters/smart folders to order the local news based on the market. Creating a new local news article after you have clicked on one of these filters will automatically pre-fill the local news tag for the article.

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/7fd9a7df-b0e3-4fa2-a797-41b2bc948307)

These filters are generated automatically based on the newly made `local news tags` - these tags are meant to organize the local news to a specific market, and are also used to generate the URL for local news.
These local news tags can be managed under "Settings > Local news tags".

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/999ed888-98f8-4464-a1a5-fbc7e478a744)

These local news tags are currently restricted to users with the administrator role in Sanity, since editing/deleting them can have bad consequences to already created local news.

The local news tags have 3 fields; a title used internally on the studio, and an English and Norwegian "tag name" field. These tag name fields are used to add a prefix to the URL when generating the slug for the local news, and works like this:

Using the "Netherlands news" tag in the screenshot below, when you have a local news article that uses this tag and click to generate the article's slug - the slug it generates will look like this: 

- English: `/news/netherlands/blablabla`
- Norwegian: `/nyheter/nederland/blablabla`

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/fcb1fd81-c06b-457f-ad30-b33d09a97d8f)

You can give these whatever value you want, it could just be `netherlands` or it could be `netherlands-news` or whatever. You can then create a topic page where you add the new "news list" component to display this news, and give that topic page the same URL.

So for example, in summary:

- "Netherlands news tag" has tag name "netherlands"
- Local news article tagged with the "Netherlands news" tag has a slug `/news/netherlands/blablabla`
- Topic page called "Netherlands news" has a "news list" component for the tag "Netherlands news" and a route `/news/netherlands`

Lot's of information here, I hope I managed to make sense of it 😅

**Comment by meols** [comment]
@SvSven - this looks very good :clap: I'll discuss with the editorial team tomorrow, and will close this if there are no comments :smile:

**Comment by meols** [comment]
@SvSven - we are very happy with this :smile:
Questions (not critical):
- Is it possible to also hide Topic tag and Country tag in the local news template
- Is it possible to have the date picker starting the week with Monday (for both Local news and Global news )

**Comment by SvSven** [comment]
Yes, should be no problem to hide the Topic and Country tags for the local news template - but I thought we wanted to have those?

Have also made a new issue for the date picker: #955

**Comment by meols** [comment]
Thanks @SvSven - We don't need to be able to tag in the local news template with topic or country (at least for now), so great if those can be hidden. 
(but are very happy that we can add country or topic tag in the **newslist**, to fetch global news by these tags, together with the local news in the list)

**Comment by SvSven** [comment]
Have removed the topic and country tags from the local news schema ✅

**Comment by meols** [comment]
@SvSven - I can still see the options for Topic tag and Country tag and add them to a local news article. It should't be visible - right?

**Comment by SvSven** [comment]
It looks like the changes haven't been deployed to the global studio yet. A little bit hesitant to do so _at this moment_ since we are doing some experimental stuff for the studio that we need to make sure works first

**Comment by SvSven** [comment]
@meols should be available in the global production studio now

**Comment by meols** [comment]
Great! Thanks @SvSven :clap:
