### ISSUE TITLE
Slug validation doesn't work properly

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#918]
The is unique validation is buggy.

**Comment by wenche** [comment]
[Here's the issue from last time we worked on this](https://app.zenhub.com/workspaces/energy-vision-5fb6386c578f1200222dd6c2/issues/equinor/energyvision/580)

**Comment by wenche** [comment]
Remove the option to have the same url slug for both translations of a document

**Comment by fernandolucchesi** [comment]
@wenche, updated

**Comment by wenche** [comment]
Removed the is unique across documentation so now the publisher will have to translate the URLs and they will see a validation error in the slug field for duplicate slugs when the create a translation. LGTM, closing
