### ISSUE TITLE
Create local news list component

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#920]
Related to #143

We need a basic news list component for the local news.

Link to design in Figma: https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=4802%3A82891

## Acceptance criteria

- [ ] Local news article is readable on the web
- [ ] Can add a new "news list" component to a topic page
- [ ] Can select a local news tag to display local news in the "news list" component, this should be a mandatory field
- [ ] News list component renders a list of local news on the web
- [ ] News list component matches design

**Comment by SvSven** [comment]
Handling of large amount of articles via pagination to be handled in separate issue #942

**Comment by SvSven** [comment]
The component is very straightforward in Sanity, simply select any number of topic, country, and/or local news tags and it will use those tags to generate a list of news

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/e5147491-fdc1-44c6-ae16-e8a38dfbc5e1)

This is reusing the "news promotion" schema - have reached out to Sanity asking how we can customize the component description for different use cases (note the "Feed in the latest 3 news that satisfies the tags" from the news promotion). Editors can also add an optional title which will be displayed above the list if they wish.

In the web it reuses the news cards - so this is _basically_ just a news promotion without the 3 article limit; instead this currently just loads all news articles that match the tags (we will later limit this by introducing a "load more" button, see #942)

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/f2dbbc69-fa6d-46fb-90a4-27583d92faad)

**Comment by SvSven** [comment]
@wenche @BirteThornquist This is ready to be looked at.

The web part doesn't 100% match the design; in Figma the cards lack the ingress, but it's still being shown here now.
If we want we could modify it to hide the ingress (and/or any other fields on the cards) but I didn't want to complicate things further.

**Comment by wenche** [comment]
Been testing a bit
English: https://web-global-development-energyvision-dev.radix.equinor.com/about-us/the-netherlands
Norwegian: https://web-global-development-energyvision-dev.radix.equinor.com/no/om-oss/nederland

**Comment by nilsml** [comment]
@SvSven to update padding according to suggestion from Birte

**Comment by SvSven** [comment]
Have updated the padding to match that of the promotion component, and added a warning/description text to the component inside Sanity:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/d96c1f3c-4ee1-41c0-b02e-0c8f8eca4d9b)

**Comment by SvSven** [comment]
@BirteThornquist done ✅

**Comment by BirteThornquist** [comment]
@SvSven if you add a space after the icon before the text it will be perfect! (sorry for being picky) 😄

**Comment by SvSven** [comment]
Have added some breathing space between the emoji and the text 👍

**Comment by SvSven** [comment]
@meols I believe you and the rest of the editors have already looked at this, correct?

**Comment by meols** [comment]
Yes @SvSven - that's right :thumbsup: There has been some issues with preview, but Tor (our news guy) has tested and confirmed today that it works at it should. Closing this one then :smile:
