### ISSUE TITLE
Create Order Annual Report form

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#921]
We need a form so that users can order annual reports by post.

## Acceptance criteria
- Be able to add 'Order reports' in topic page, with title and ingress ( optional) 
- Be able to add or modify the translations for the form  field labels, text  and error messages.
- Be able to successfully submit the form and verify that RITM is created in service now ( https://equinortest.service-now.com/nav_to.do?uri=%2Ftask_list.do%3Fsysparm_query%3Dactive%253Dtrue%255EstateNOT%2520IN6%252C5%255Ecmdb_ci%253Dd1872741db26ea40977079e9bf961949%26sysparm_first_row%3D1%26sysparm_view%3D )
- Validations are done properly.

**Comment by BirteThornquist** [comment]
For the Order Report form it must be possible to add a downloadable file. I have outlined the Sanity navigation for that  in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=3309%3A71064)
In the same frame I have done the design of this form: Order Annual Report Form. Here you will see a couple of different solutions when it comes to the text order. I prefer alternative c - any input @padms ?
@meols can you pls check the naming of the different form types in Sanity? And have we covered the different forms needed? ![Skjermbilde 2022-03-18 kl. 08.02.36.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/ab9654cb-26c8-4620-a088-675700eadf4d)
Also @padms we should check that the form name is the same in ServiceNow.

**Comment by padms** [comment]
@meols @BirteThornquist For your review

**Comment by BirteThornquist** [comment]
@padms Pls add some space after the link list above the form as shown in Figma


 ![Skjermbilde 2022-03-22 kl. 12.23.56.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/76256815-1a82-4bb2-ba61-467973d221bb)

**Comment by padms** [comment]
@BirteThornquist I added more space now.

**Comment by meols** [comment]
@padms @BirteThornquist - some comments:
- The option for "Årsrapport for norske myndigheter" should be named that in the information going to serviceNow as well (and not be called Statutory Report)
- The validation text is very big for choosing at least one report, and very small below the different text fields: ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/06bb5157-af03-41e1-842a-4b1a1e4c2bb4)
- should mandatory text fields be marked with * (even if all are mandatory)?
- translations are working fine
- I found my RITM in ServiceNow
- Users should see a submit button state change or something to indicate that their form is submitted, which is captured in #951

**Comment by meols** [comment]
@nilsml - we also need a recapthcha alternative for forms #591

**Comment by nilsml** [comment]
@meols Yes. Will look into that when we start working on #591 👍

**Comment by BirteThornquist** [comment]
@padms @meols I have updated the design for feedback in Forms in Figma [here](https://www.figma.com/file/F2OnKFEoMwFaANMgeGRGqE/CMS?node-id=5353%3A91102)
The form is substituted with a feedback information box, with a button to reload the form. 
The CTA button in the form will also change to "Sending ..." on press. 
What do you think?


![Skjermbilde 2022-03-29 kl. 09.37.41.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/fa83e74c-453f-4c43-8c3a-84eda6300580)


![Skjermbilde 2022-03-29 kl. 09.39.03.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/a6d71a84-8387-442b-b555-4f90c1cbd317)

I think instead of marking the mandatory fields, we mark the optional with the text "(Optional)" behind the field name.
I see your point about the big validation text for the check boxes @meols.

**Comment by padms** [comment]
@meols @BirteThornquist I modified the look for the checkbox error as suggested.. 
Sending... text on submit button. 
And the success/failure after the form is submitted... 
The (Optional) text for optional fields can be done editorially by changing label text under text snippets

**Comment by padms** [comment]
@meols I found the ticket in service now.

**Comment by meols** [comment]
Thanks @padms :thumbsup:
Any comments from you @BirteThornquist (if not, just close it)

**Comment by padms** [comment]
@BirteThornquist  Fixed the font size

**Comment by nilsml** [comment]
@BirteThornquist to confirm this

**Comment by meols** [comment]
@padms - I just tested the Order annual report form, which worked :thumbsup: But can you please update the information going to serviceNow to be "**Årsrapport**" and not "Statutory Report" when you order the Norwegian report (it was like that in AEM as well, but it should be corrected)

**Comment by padms** [comment]
@meols The "Statutory Report - Yes" in the description of RITM is coming from service-now. I will create a ticket with service-now team to fix that.

**Comment by SvSven** [comment]
@BirteThornquist checking again

**Comment by BirteThornquist** [comment]
@padms  Looks better with the increase in font size for the form labels. Good job - lets go for that. I would also like the selection control labels to follow the rest of the size, now they are set to 16px.

![Skjermbilde 2022-05-13 kl. 10.39.11.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/a2d4175d-1cc4-4d39-99c8-fd63d8240cc8)

**Comment by BirteThornquist** [comment]
Great @padms - looking good! @meols can you pls take a look, accept and close?

**Comment by meols** [comment]
Looks great! Thanks @padms and @BirteThornquist
