### ISSUE TITLE
Create Redirects in Sanity

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#922]
This should allow editors to add news redirects and create vanity urls.

- If a redirect exists in sanity, we should permanent redirect to the new page
- If it is the global dataset and the pathname contains /magazine/, we should temporarily redirect to a landing page /magazine
- If slug ends with .html, we should crop it out of the url
- redirects logic are handled in the `_middleware.ts` file

**Comment by wenche** [comment]
Do we need a switch for temp redirect vs permanent redirect

**Comment by SvSven** [comment]
We also need to make sure we have it documented how to handle redirects, when redirects should be used (and for which use cases)

**Comment by wenche** [comment]
@fernandolucchesi  to make this issue ready for review by Mette

**Comment by fernandolucchesi** [comment]
Added some documentation at: https://github.com/equinor/energyvision/wiki/Redirects
