### ISSUE TITLE
Create Career fair and events form

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#929]
## Acceptance criteria
- Be able to add 'Contact Equinor Form' in topic page, with title and ingress ( optional) 
- Be able to add or modify the translations for the form  field labels, text  and error messages.
- Be able to successfully submit the form and verify that RITM is created in service now ( https://equinortest.service-now.com/nav_to.do?uri=%2Ftask_list.do%3Fsysparm_first_row%3D1%26sysparm_query%3Dactive%253Dtrue%255EstateNOT%2BIN6%252C5%255Ecmdb_ci%253D848f447ddb692600ff6272dabf961948%26sysparm_view%3D)
- Validations are done properly.

**Comment by padms** [comment]
@BirteThornquist For your review

**Comment by BirteThornquist** [comment]
@padms I hope we can change the text size, it is far too small. Also, we need a success msg after submitting the form. Now I can't tell if I submitted or not... Can we  replace the form with a success msg after submitting? If so I can outline a design for it.

**Comment by padms** [comment]
@BirteThornquist  I changed the label size to typescale-05 now. I also agree that we have a success message after successfully submitting a form. We also need to handle failure and actions after a failure in form submission.

**Comment by padms** [comment]
Created a separate issue #951 for showing message after form is submitted.

**Comment by meols** [comment]
Thanks @padms 
- I have submitted two tests, and can't see either of them in ServiceNow (link in acceptance criteria). Can you please check and confirm if you can see them?
- Thanks for adding the additional text for "Visit Equinor facility..." I couldn't find the new "Please be aware..." text in text snippets. What's it called?
- I leave the font size commenting to @BirteThornquist (looks good to me)

**Comment by padms** [comment]
@meols  Yes, I could see two RITMs in service-now. 
The text snippet title is like this - 'Career fair form: We offer visits to a few locations'

**Comment by meols** [comment]
@padms - thanks for confirming the RITMs.
I still don't see the text snippet
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/5944a384-31d1-46d5-b7af-ed8fd1927579)

**Comment by meols** [comment]
@padms - now the text snippet is showing :smile:
