### ISSUE TITLE
Add option to add a custom publishing date time for news and display it accordingly

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#930]
Acceptance criteria:

[ ] Editors can choose a custom publication date
[ ] Editors can choose not to use a custom a publication date
[ ] The actual publication time will be used if no custom date is chosen
[ ] News should display correct dates in the website
[ ] Latest news should work properly

**Comment by wenche** [comment]
LGTM :thumbsup: You will probably want to take a look as well @meols

**Comment by meols** [comment]
Thanks @fernandolucchesi - looks good :smile: 
We would like the date picker to start the week on Mondays, it's captured in #955
