### ISSUE TITLE
Wrong font size in simple menu

### ISSUE THREAD

**Issue by BirteThornquist** [equinor/energyvision#932]
The font size for simple menu is too small. Seems it is set to 16 px without using the type scale. ![Skjermbilde 2022-03-18 kl. 08.05.04.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/63b7c8e0-bb04-4eec-becd-caf3cc681d0b)

**Comment by SvSven** [comment]
@BirteThornquist This should be fixed now and can be reviewed for example here: https://web-brazil-energyvision-dev.radix.equinor.com/

**Comment by BirteThornquist** [comment]
@SvSven The menu item links looks good, but the accordion links are too small (set to 16px). The accordion links must have the same font size as the menu links.

![Skjermbilde 2022-03-27 kl. 14.54.30.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/88ac7c7b-7b5b-432d-bd80-82e3e2bb041a)

**Comment by SvSven** [comment]
Turns out it wasn't using the correct font weight when the accordion was expanded either. Both the font size and weight should be fixed now.

**Comment by BirteThornquist** [comment]
LGTM @SvSven Closing Issue.
