### ISSUE TITLE
Index local news articles

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#933]
The local news is a separate document from the regular news, and will thus need to be set up to be indexed by Algolia.
We can use the same setup as #882 - just need to change the document type to `localNews` instead of `news`

Related to #917

- [x] Update documentation

**Comment by nilsml** [comment]
Let's do this some other time :)

**Comment by fernandolucchesi** [comment]
Should be indexed together with "News", and tags/country tags should be used for filtering.
Ex: https://www.equinor.com/where-we-are/uk-news

**Comment by fernandolucchesi** [comment]
Hi @padms, left a couple of comment in your commits

**Comment by padms** [comment]
Changes done as per suggestions

**Comment by fernandolucchesi** [comment]
@padms just one minor comment, otherwise looks good

**Comment by fernandolucchesi** [comment]
@padms Looking good! You can move to Acceptance :)

**Comment by padms** [comment]
@meols Local news article are now searchable from dev. Currently any local news article published in production are searchable from global search and newsroom. [ dev ](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news).
Please also find the local market filter in the newsroom.

**Comment by fernandolucchesi** [comment]
@padms, quote from mette on slack:

> I am looking into the card for Local news, and when testing on dev, for some strange reason, every time I write "vent" (to search for ventures) I get an error message. Searching for "ven" and other letters (even æ) works as usual. Not exactly critical, but very strange

I just found a bug and believe it is related to that. The ingress is not being parsed correctly when indexing in algolia:

<img width="639" alt="image" src="https://user-images.githubusercontent.com/23337266/186908509-39f012ef-8ef9-4aaa-b7d7-9ef9aea6db7f.png">

**Comment by padms** [comment]
Ingress is not indexed properly both for news and local news .

**Comment by fernandolucchesi** [comment]
Hi @padms, now we are displaying the whole ingress in the search results... I don't think this is correct, it should display only the part of it that contains the text:

<img width="694" alt="image" src="https://user-images.githubusercontent.com/23337266/187663706-a5a12da6-698e-404c-a023-ba1bd7d8b816.png">

and this has been deployed to prod already, we should be extra careful when doing changes to /search

**Comment by padms** [comment]
Missed to add ingress in the attributes to snippet property.

**Comment by fernandolucchesi** [comment]
@padms, looks good to me

**Comment by meols** [comment]
@fernandolucchesi @padms - in addition to having the local news indexed - which looks good  now :thumbsup: - we would like to list them in a separate tab in the search result, and not have them showing on the newsroom page. I assume you want that on a new card, and that this card should be moved, since the indexing task is OK?

**Comment by fernandolucchesi** [comment]
Hi @meols, this was done together with news due to a decision made on the sprint planning from 9.8.2022.

> Should be indexed together with "News", and tags/country tags should be used for filtering. Ex: https://www.equinor.com/where-we-are/uk-news

If the logic is to be changed we should use this same card before going into prod

**Comment by padms** [comment]
@meols Just to confirm,

- Local news should be indexed separately. 
- It should not be searchable from the newsroom. 
- It should be searchable from global search, and have a separate tab "Local news"

**Comment by meols** [comment]
@padms - we'll have a small discussion on some of this in our editorial meeting tomorrow. I'll update after that.

**Comment by padms** [comment]
Pretty simple :) Please test in dev now. Local news and news with crude oil assays tag will not be shown in newsroom , but can be searchable from global search under the tab ' News'

**Comment by meols** [comment]
Great! @padms :clap: 
For the local news this looks great - visible in search, not visible on the Newsroom page. But still some questions on crude oil.
I published[ this news](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/visible-test) tagged with crude oil 25 minutes ago, and it isn't visible in search (should be) or in newsroom (very good).
I also tagged[ this news](https://web-global-development-equinor-web-sites-dev.c2.radix.equinor.com/news/crude-oil-assay-update-2-28-04-2022) with topic crude oil (it was only tagged with subscription option crude oil) 2 hours ago, but it still shows on the newsroom page.
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/6f67cc72-14d9-418d-b65e-a3850a809eee)
Can you please look into the crude oil issue again?
Local news is perfect :smile:

**Comment by padms** [comment]
@meols I triggered indexing for dev manually. Now you should be able to test the news with crude oil assays. 

> I also tagged this news with topic crude oil (it was only tagged with subscription option crude oil) 2 hours ago, but it still shows on the newsroom page.

This news is already indexed, so it will be visible in newsroom unless it is deleted from the index. 
Also, the news is excluded from newsroom only based on the topicTag. So setting subscription type to crude oil assays will not have any effect.

**Comment by fernandolucchesi** [comment]
@meols pinging you just in case you forgot about this one

**Comment by meols** [comment]
Thanks @padms - all good :smile:
@fernandolucchesi
