### ISSUE TITLE
How are translations in text snippets handled

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#936]

**Comment by meols** [comment]
@nilsml - can you please clarify how translations for items found in text snippets will be covered and by who? (dev or editors) 
Editors have not handled adding translations to e.g. forms in AEM. We have handled ordering the translations (from translations service) and using it the correct ways and places have not been done by editors for these things.

**Comment by wenche** [comment]
@meols  Does it work the way it is handled now?
