### ISSUE TITLE
The Techstars site will not be continued in Sanity 

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#940]

**Comment by meols** [comment]
@fernandolucchesi @nilsml It has been decided that the [Techstars site](https://studio-techstars-energyvision-dev.radix.equinor.com/) (that we have filled with content) will be discontinued.
So this site will not need to be part of any go-live planning, it will just live in AEM until AEM is shut down
Finally a comment from me that doesn't bring more work :smile:

**Comment by nilsml** [comment]
Removed from radix and CI, but the dataset will need to be deleted from Sanity.

**Comment by wenche** [comment]
It's deleted from Sanity.

FYI: We have a backup of the added content for techstars if this will ever be relevant in the future.

**Comment by wenche** [comment]
@meols Techstars is no longer available
