### ISSUE TITLE
Migrate text blocks components from block-content-to-react to portable-text

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#941]
Sanity's `block-content-to-react ` package is deprecated. They have realised a new version called [portable-text](https://github.com/portabletext/react-portabletext) and we need to migrate. The new version offers better Typescript support, so we could also clean up our block content related types. :thumbsup:

The 404 and 500 templates use the new version, so some of the serializers are already migrated . 

- [x] FactRenderer
- [x] FigureRendererWithLayout
- [x] PaddedBlockRenderer
- [x] QuoteRenderer
- [x] BlockRenderer
- [x] ExternalLinkRenderer
- [x] IngressBlockRenderer
- [x] InternalLinkRenderer
- [x] ListItemRenderer
- [x] ListRenderer
- [x] SubRenderer
- [x] SupRenderer
- [x] TitleBlockRenderer

**Comment by wenche** [comment]
@SvSven This should be done now, and all the old code should be deleted (hopefully) Do you mind to take the final look before we merge?

**Comment by SvSven** [comment]
Seeeeeeems to all be fine - we'll fix the typescript stuff at a later point ✅

**Comment by wenche** [comment]
This is now merged to main
