### ISSUE TITLE
create "pagination" component for news in stallites

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#942]
Related to #920

For the news list component, and potentially in other places as well, we will need a "load more" button that dynamically loads in additional news articles in the list to prevent the component from rendering a very large amount of articles in one go - since there is currently no limit on the amount of articles being fetched yet.

**Comment by fernandolucchesi** [comment]
https://www.equinor.pl/aktualnosci

**Comment by millianapia** [comment]
@NickHaggerty1 does it exist a design for this?

**Comment by NickHaggerty1** [comment]
Hey @millianapia 
Isn't it better to use the pagination design as per search and Corporate news? Currently the local news is set up using NEWS LIST component with tags. Example page below:
https://www.equinor.com/where-we-are/uk-news
Pagination example at the bottom here:
https://www.equinor.com/news
Perhaps just display say 12 or 15 on page one and have numbers below?

**Comment by NickHaggerty1** [comment]
Looks good. Approved.
