### ISSUE TITLE
Refactor the news room to allow for a Norwegian version

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#946]
Split up code into reusable components for both 
/news and /nyheter

### Acceptance criteria
`/news `-> Return the English newsroom
`/en/news` ->  Return the English newsroom
`/no/news` -> Return 404
`/en/nyheter` -> Return 404
`/nyheter` -> Return 404
`/no/nyheter` -> Return the Norwegian newsroom

**Comment by wenche** [comment]
So this one was a little tricky. What we want for the URLs:
`/news `-> Return the English newsroom
`/en/news` ->  Return the English newsroom
`/no/news` -> Return 404
`/en/nyheter` -> Return 404
`/nyheter` -> Return 404
`/no/nyheter` -> Return the Norwegian newsroom

I have solved it by using a non-optimal approach for the time being, sorry @fernandolucchesi  :grimacing: At some point we should take a closer look at this. Also see comment in the code

**Comment by wenche** [comment]
@SvSven  We might want to add more component or split up even more, but should be fine for now. Do you mind to just verify according to my list of urls in the acceptance criteria

**Comment by SvSven** [comment]
Can confirm that the URLs work as expected according to what you listed, haven't looked into the code itself yet
