### ISSUE TITLE
Add a news room schema for Sanity

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#947]
We need a way to set 
- Page title
- Ingress text
- Meta title
- Meta description
- Some image
 
for both the English and Norwegian version.

### Acceptance criteria
- Can add the texts needed for the news room
- The texts are visible on the news room page in the web
- Both English and Norwegian

**Comment by wenche** [comment]
This should be a singleton, and we faced some issues with the translation plugin and singleton, [see the documentation](https://github.com/sanity-io/document-internationalization/blob/main/docs/known-caveats.md)

Tried the suggested approach for the error pages, and it's a though one to love :/ Shouldn't spent to much time on this though as it should be improved by the plugin

**Comment by wenche** [comment]
![Skjermbilde 2022-03-31 kl. 14.24.47.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/fff4c81e-c86e-44a9-b12b-2346773fbfda)

@meols  FYI: I have added the document for the newsroom to the `Misc` folder since it is a singleton (can only have one newsroom document). It might be an idea to improve the structure of the content in the studio at some point, but I think this is OK for now. It's supposed to be kind of an "add once and forget" piece of content.

It has the same shortcomings as for the 404 and 500 pages, that is remember to use "Create new" when you create this document.

**Comment by SvSven** [comment]
Given the problems with the language plugin with regards to singletons, this is probably as good as we are going to get - so looks good to me 👍

**Comment by wenche** [comment]
@meols You have already created a news room document for the global site, but do you mind to just verify this anyway

**Comment by wenche** [comment]
It wasn't initially when we created the landing page :) But Birte and I talked about it the other day and that was our suggestion as well. It's on my list to add it :)

**Comment by meols** [comment]
Thanks @wenche - closing this one then :smile:
