### ISSUE TITLE
Make shared components work for both light and dark mode

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#948]
The shared components, like the pagination (and the search box, but the uncontrolled one are not actually used for the site search), must work for both light backgrounds (news room) and dark (site search)

**Comment by wenche** [comment]
@BirteThornquist  Let's just go through the colours for the pagination component on light background

**Comment by BirteThornquist** [comment]
@wenche @SvSven Let's use "Moss Green 70" for active state color when pagination is used on light color.

 ![Skjermbilde 2022-04-08 kl. 10.12.44.png](https://images.zenhubusercontent.com/5fb7acdfad906a977e792e56/363b4018-fd7a-463e-bfc5-8c0eb56e4164)

**Comment by wenche** [comment]
@SvSven  Removed your console.log

**Comment by SvSven** [comment]
Oops, good catch.
