### ISSUE TITLE
Checkboxes for filtering

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#949]
Fingers crossed that we can use EDS here?

**Comment by wenche** [comment]
Speaking of markup: Should we have a fieldset with a (hidden?) legend to connect the checkboxes even if they are within an accordion as well? How is this for screen readers?

**Comment by SvSven** [comment]
The issue name and description are a bit lacking. Where are these checkboxes exactly? Is it for the newsroom?

**Comment by wenche** [comment]
Yes, it's in the newsroom centre epic after all

**Comment by SvSven** [comment]
Which is not visible outside of Zenhub, and I came here via Github notifications 😅

**Comment by SvSven** [comment]
Checkboxes seem fine, works with keyboard within the accordion as well.
I guess it's good that we can use the EDS here, though I feel like there are some improvements that could be made; like the behaviour when hovering over the label - but that's up to EDS 😬
