### ISSUE TITLE
Add suffix "Equinor" to meta title

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#950]
Add a suffix to titles using <NextSEO> plugin. `<title>This is my page - Equinor<title>` (or  `<title>This is my page | Equinor</title>`)

### Question:
This should be the same for all satellites right?

### Acceptance criteria
- All meta titles end with "- Equinor"

**Comment by wenche** [comment]
@meols  To figure out if the satellites should have this or not

**Comment by meols** [comment]
@wenche - satellite sites should have the site's domain name as suffix in the meta title. Japan site example:
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/a7b821e2-52a0-4ca7-a774-0ca8c3b2e13e)

**Comment by wenche** [comment]
For flexibility we should probably just add a meta title suffix config in the satellites config

**Comment by wenche** [comment]
@padms  I think we should use the `isGlobal` helper and not just test for `dataset === 'global'` because we want to avoid to hard code dataset names as much as possible and we also want Equinor for global-test and global-development datasets

**Comment by fernandolucchesi** [comment]
I'd argue that a best approach is to merge this logic with the already existing websiteDomains:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/23337266/169016984-d16abd06-84af-42d9-975f-6231146acbe6.png">

**Comment by fernandolucchesi** [comment]
This is also breaking the build. I will revert it temporarily since we need to deploy soon. 
<img width="874" alt="image" src="https://user-images.githubusercontent.com/23337266/169029387-db30ef9e-79ee-411e-b5e1-857c5982cbaa.png">

**Comment by wenche** [comment]
LGTM :thumbsup: Even if we add more config it think this solution is more flexible. :)

We should perhaps handle the (not likely) case of `websiteDomains[dataset] ` being `undefined`

**Comment by fernandolucchesi** [comment]
> LGTM 👍 Even if we add more config it think this solution is more flexible. :)
> 
> We should perhaps handle the (not likely) case of `websiteDomains[dataset] ` being `undefined`

we actually should handle it because we have an undefined url for the secret project, (it is needed for preview). I didn't want to list it to not expose it in a public repo. but we should handle the undefined case otherwise build won't work.

`websiteDomains[dataset]?.url || 'Equinor'`

**Comment by padms** [comment]
done

**Comment by wenche** [comment]
LGTM :thumbsup:

**Comment by wenche** [comment]
@meols  You should be able to test this in the preprod environments now, like https://web-brazil-equinor-web-sites-preprod.c2.radix.equinor.com/

Here is the complete list of the added meta suffixes:
```
 global: 'Equinor',
 poland:  'equinor.pl',
 brazil:  'equinor.com.br',
 germany: 'equinor.de',
 storage: 'equinorstorage.de',
 argentina: 'equinor.ar',
 equinorfunds: 'equinorfondene.no',
 japan: 'equinor.jp',
 
```

**Comment by meols** [comment]
Thanks @wenche - looks good :thumbsup:
