### ISSUE TITLE
Feedback message on form submit

### ISSUE THREAD

**Issue by padms** [equinor/energyvision#951]
## Acceptance Criteria

- Verify that after form is successfully submitted, thank you message shows up. Upon clicking 'Reopen the form', the form should appear for submitting again,.
- Verify that if there are any errors after submit ( server error ), failure message shows up. Upon clicking 'Try again, the form should appear with entered values before submitting. 
- Translations for the form success/ failure message and the button works

**Comment by meols** [comment]
@padms - I get the "Sorry, something went wrong" for all five forms on your page

**Comment by padms** [comment]
@meols You can test now.

**Comment by meols** [comment]
Thanks @padms - now it worked :smile: Error message for subscribe form and Thanks you message for the other four.
@BirteThornquist - any comments from you?

**Comment by BirteThornquist** [comment]
The feedback messages looks good @padms
