### ISSUE TITLE
Use canonicals for pages with query params

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#959]
We need to set up some canonical URLs for the pages where we use query params, so that these pages don't get indexed with every combination of query params known to mankind.

https://rishimohan.me/blog/nextjs-canonical-tag

We don't want google to treat them as separate URL. But we should align with Mette & co about how this should ideally be listed in Siteimprove.

We should avoid things like `equinor.com/search?query=` , equinor.com/search?query=e` `equinor.com/search?query=eq`. Also accordions add params to the URL [like with the Fact page](https://www.equinor.com/careers/faq?11e524fd5dc3=11&11e524fd5dc3=9&37e77476d9b4=2&37e77476d9b4=6)

We also use quite a lot of query params for campaign, we should also ask Mette & co for some insight here. 

### Acceptance criteria wip
- Satisfy Google/Bing while still making SiteImprove useful

**Comment by SvSven** [comment]
@wenche to expand on this issue

**Comment by wenche** [comment]
Also pay attention to how the queries are showing in the siteimprove. Today it's bloating the Siteimprove statistics.

**Comment by fernandolucchesi** [comment]
@SvSven, isn't this fixed?

**Comment by SvSven** [comment]
Don't think we ever set up anything with canonical tags, no.
I do recall we briefly discussed whether this was needed or not, but don't remember the outcome of that.

**Comment by nilsml** [comment]
@fernandolucchesi to check if this is implemented

**Comment by nilsml** [comment]
Should be ok now
