### ISSUE TITLE
Poland cookie policy page: cookies not visible immediately

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#962]

**Comment by meols** [comment]
On the cookie policy page for Poland https://www.equinor.pl/cookie-policy you need to refresh several times before the cookie list is showing (it is "blinking" on refresh, and after 6-7 refreshes it stays) - it should always be visible. Also the distance between the Text component and the Cookie declaration component is too big.

**Comment by padms** [comment]
@meols https://web-poland-energyvision-preprod.radix.equinor.com/cookie-policy fixed in preprod

**Comment by padms** [comment]
Fixed  :)

**Comment by meols** [comment]
@padms - when testing both the Poland and the Storage site I have to refresh once to see the cookie list/declaration component
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/339f2635-852c-4fd3-9c2a-89fa96164e4f)
![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/0ac861cb-dd75-4b8f-b1ef-d819d564a182)

**Comment by padms** [comment]
@meols Could you please try one more time? It was fixed in preprod, may be it was not deployed to prod when you tested it. I could see the declaration loading immediately for all the sites in production.

**Comment by meols** [comment]
Thanks @padms - now it was there immediately (both for Storage and Poland)
