### ISSUE TITLE
Deleted news are visible in news promo 

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#963]

**Comment by meols** [comment]
News we have deleted are still visible in the news promo and news room list. Is there a "process" for deleting news (just Delete incl translation/One by one language/Unpublish first and then delete etc.)? How long does it take before a news disappear after deleting/unpublishing it?
- Also, please confirm if Unpublishing a news and then publishing it again will trigger a new newsletter being sent (which is what we need) - and that publishing updates (without unpublishing first) will not trigger a new newsletter being sent out.

**Comment by wenche** [comment]
Needs refinement and should probably be tested by a developer
