### ISSUE TITLE
Optimize SVG icons

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#969]
The SVG icons used by the Icon and text component are flagged as not optimized. We should look into if we can improve this. Example from [Storage](https://web-storage-energyvision-prod.radix.equinor.com/en)

![Skjermbilde 2022-04-05 kl. 10.15.04.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/e46e6038-8e45-4d20-9437-3027c90e9065)

**Comment by fernandolucchesi** [comment]
This is an issue with lighthouse: 
https://github.com/vercel/next.js/issues/20060
https://github.com/GoogleChrome/lighthouse/pull/12120

**Comment by fernandolucchesi** [comment]
[gif...](https://www.google.com/url?sa=i&url=https%3A%2F%2Ftenor.com%2Fsearch%2Fnothing-to-do-here-gifs&psig=AOvVaw1mlj6W1-lLkIJCvfDU8oGG&ust=1664974004947000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCJi8xdPNxvoCFQAAAAAdAAAAABAD)

**Comment by SvSven** [comment]
👍
