### ISSUE TITLE
As a user I want a good typographic scale in an established font  to make it easy to read and perceive content on the pages

### ISSUE THREAD

**Issue by nicholas-haggerty** [equinor/energyvision#97]
## Acceptance criteria
1. Typographic scales that suit multiple devices are implemented
2. Base font size/s is/are established
3. The web pages use the Equinor font

### In order to ensure good quality we should
- Extra focus on usability
- Test for accessibility
- Perform performance and load test when the font loads
- Perform user testing

## Sub-tasks
- [x] #165 Design and implement a typographic scale
- [x] #166 Add Equinor font

**Comment by vnys** [comment]
Started refactoring the news article. Also made a Power App for calculating values for the CSS clamp function. It’s in the Heap Purple teams channel in Teams.
