### ISSUE TITLE
Improve font loading and caching

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#971]
We see a lot of "flicking" with the font. Initially we wanted to use the EDS hosted font, but we ran into some issues with the TTL. See [related issue on the EDS board.](https://github.com/equinor/design-system/issues/1543)

As a work around, we added the font into our Next.js public folder, but since `expires = 0` this is not optimal either.

![Skjermbilde 2022-04-05 kl. 10.34.50.png](https://images.zenhubusercontent.com/5fb7aa9b653d5135bb8c50f5/c55c6e1a-3f4f-4a23-89db-1034fbadbc2a)

**Comment by wenche** [comment]
Now using the EDS CDN in preprod since EDS has changed the TTL. It seems to work pretty well. :thumbsup: I think we should just stick to this for now. 
- Lighthouse seems to be happy
- Using Network tab it's loaded from memory cache
- The change of font for the end user has improved significantly

@SvSven  What do you think?

**Comment by SvSven** [comment]
First hit on the page without cache still has the jump, but afterwards it's no longer doing it - so it's much better. 👍
