### ISSUE TITLE
Do not convert /news/archive urls to lowercase

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#976]
Archived news may contain uppercase urls. We should not change it to lowercase.

**Comment by SvSven** [comment]
Problem is with _old_ archive - content from AEM and Sanity are not case sensitive

**Comment by SvSven** [comment]
Looks to be working 👍
- https://www.equinor.com/en/news/archive/1999/12/28/VenezuelanInjectionStarts.html
- https://energyvision.app.radix.equinor.com/news/archive/1999/12/28/VenezuelanInjectionStarts

- https://www.equinor.com/en/news/archive/2010/12/22/22DecKristinCompressor.html
- https://energyvision.app.radix.equinor.com/news/archive/2010/12/22/22DecKristinCompressor

Should we use this same logic for the preview by ID, or stick to my hacky fix?

**Comment by fernandolucchesi** [comment]
If the preview by ID follows a logic that is easy to follow then I'd suggest we add to the middleware, less hacky stuff in the code
