### ISSUE TITLE
Fav icon missing for news

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#980]

**Comment by meols** [comment]
Currently the news don't have a fav icon ![image.png](https://images.zenhubusercontent.com/5fbbf4f2bab8ae744cb6560f/36b23e54-c474-432c-b1e0-8efde2f7be3f)

**Comment by wenche** [comment]
@meols  This should now be fixed, but you can't verify before its built to production :)

**Comment by meols** [comment]
Thanks @wenche
