### ISSUE TITLE
Event template: Add Iframe component inside Text Component

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#989]
The event template should have an (optional) text field below the iFrame, to give better options to distribute the text on the page.
E.g. the Annual general meeting event has a lot of text instructions, and the iFrame gets pushed to the bottom of the text:

Acceptance Criteria 
- [ ] Editor is able to add iframe inside the Content text area of the event page and view the same on page
- [ ] Existing iframe component is marked as 'deprecated' and document level warning is shown.
- [x] Update documentation in Runbook

**Comment by meols** [comment]
Examples (AGM):  https://energyvision.app.radix.equinor.com/about-us/annual-general-meeting-2022

**Comment by wenche** [comment]
Ideally the iframe component should probably be within the rich text editor itself

**Comment by padms** [comment]
Please review the PR

**Comment by fernandolucchesi** [comment]
Left one last suggestion but looks good to me. I will try to find out if we should modify the paddings of the deprecated document to make it look like the new one, since now old & new look different

**Comment by fernandolucchesi** [comment]
> Left one last suggestion but looks good to me. I will try to find out if we should modify the paddings of the deprecated document to make it look like the new one, since now old & new look different

We don't need since it will be deprecated, branch can be merged :) @padms

**Comment by fernandolucchesi** [comment]
@jorgol

**Comment by meols** [comment]
@fernandolucchesi - this looks good :smile:
But also adding a question; how should the approval process work? This is already in production before being approved

**Comment by meols** [comment]
@fernandolucchesi - "Feature Flags" sounds great :clap:
