### ISSUE TITLE
Featured content: should be able to promote events

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#991]

**Comment by meols** [comment]
Currently we cant promote Events in Featured content - which would be useful to promote the Quarterly results (in the Investor menu) and the Annual general meeting (in the About us menu). Is that possible to fix?

**Comment by SvSven** [comment]
@meols @BirteThornquist  what would we want to show in the menu for a featued event? Should it just be a title + ingress and a link to the event page, should it be a custom version of the event card, or the full event card?

**Comment by SvSven** [comment]
We decided to go with a simplified card for the event:

![image.png](https://images.zenhubusercontent.com/5dba9d22e2edb600015fe6c0/d2518559-d12b-41ed-8014-a0c998583766)

This is ready to be looked at @wenche @BirteThornquist

**Comment by fernandolucchesi** [comment]
@BirteThornquist @meols

**Comment by BirteThornquist** [comment]
Looking good @SvSven. I think the font size for the header in these cards is a bit big, but that is a general card issue that we need to look into separately.

**Comment by BirteThornquist** [comment]
@meols for you to accept and close

**Comment by meols** [comment]
Great! :thumbsup: Thanks :smile:
