### ISSUE TITLE
Anchor link component

### ISSUE THREAD

**Issue by meols** [equinor/energyvision#992]
Ref: https://equinor.slack.com/team/U02N7FCF3GT

### Acceptance Criteria
- [ ] Be able to add an anchor link in topic pages using the component
- [ ] The anchor link works correctly ( opens the page at the right component)

**Comment by meols** [comment]
For the backlog: we would like to explore to have a separate component for anchors, to make it easier to place them correctly.

**Comment by fernandolucchesi** [comment]
Hi @padms, left a couple of minor cleanup comments, other than that it looks rly good! well done! :)
