### ISSUE TITLE
Add news, localNews, and archived news to sitemap

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#993]

**Comment by SvSven** [comment]
Doing a CTRL+F shows news, archived news, and local news (searched for `/news/uk/` for local news) in the sitemap: https://energyvision.app.radix.equinor.com/sitemap.xml?lang=en

So looks good to me 👍

**Comment by nilsml** [comment]
@meols to have a look and confirm

**Comment by meols** [comment]
Looks good :thumbsup:
