### ISSUE TITLE
Add missing head tags

### ISSUE THREAD

**Issue by fernandolucchesi** [equinor/energyvision#994]
### HREF tags:

Here's a quick writeup on hreflang:
 
The "rules" of hreflang:

All tags are bidirectional, meaning all pages will link to each other - the code example underneath will be installed on both language-versions
	
All pages should link to itself - line 2 in code example beneath
	
X-default is recommended: this is the default when no other language matches

Example:
 
On https://www.equinor.com/ and https://www.equinor.com/no.html
```
<head>
  <link rel="alternate" hreflang="en" href="https://www.equinor.com/"/>
  <link rel="alternate" hreflang="no" href="https://www.equinor.com/no.html"/>
  <link rel="alternate" hreflang="x-default" href="https://www.equinor.com/" />
</head>
```

### Canonical tags

A canonical tag (aka "rel canonical") is a way of telling search engines that a specific URL represents the master copy of a page.

All pages should have the tag, linking to itself.

Example frontpage:
On https://www.equinor.com/ and https://www.equinor.com/no.html    

```
<head>
  <link rel=“canonical” href=“https://www.equinor.com/” />
</head>
```

**Comment by SvSven** [comment]
I can see the `rel="alternate"` tags on Sanity pages that have a translation, and can see the canonical one on both Sanity pages with and without a translations.

Can't see them on legacy news pages - do we need them there too?

**Comment by wenche** [comment]
@fernandolucchesi  Can't see them on legacy news pages - do we need them there too? ^^

**Comment by fernandolucchesi** [comment]
Implementation for archive news will be handled on #1037
