### ISSUE TITLE
Add news tab to site search

### ISSUE THREAD

**Issue by wenche** [equinor/energyvision#995]
The site search should have the option to search for news

**Comment by SvSven** [comment]
Copied some code, and updated the attribute fields, and it seems to magically work.

Have added #1006 to create a more reusable component for these hits.

**Comment by SvSven** [comment]
@wenche things magically worked so I assume I did this right 😬

**Comment by SvSven** [comment]
We can put in an easter egg, where if there are > 1000 hits and the user navigates to the last page they are shown a "Congratulations, you've won the game" thing

**Comment by SvSven** [comment]
@meols We have a tab for "News" in the search results, it works as one would expect but take note of what @wenche wrote above; we have a limit of 1000 search results, but with the vast news archive we can have more than 1000 results for news.

I have taken the liberty of adding the Norwegian translation for the _Nyheter_ tab in production already; you can find this under Settings > Text Snippets > Search: News tab name

**Comment by meols** [comment]
Thanks @SvSven - great! 
I still see English and not Norwegian texts in the Norwegian search results tabs (but see that it is correct in the text snippets).

**Comment by SvSven** [comment]
The text snippets looks to be a bigger problem with search in general, all of the snippets in search seem to be English regardless of locale. Made a separate issue to investigate #1013
