### ISSUE TITLE
Fix publish confirmation dialog

### ISSUE THREAD

**Issue by SvSven** [equinor/energyvision#996]
The hooks implementation for the confirmation dialog before publishing breaks the i18n logic, and can't be used.
Simeon has suggested a potential workaround based on: https://github.com/sanity-io/demo-content-planning/blob/main/studio/src/actions/GoLive.js

Relates to #611

**Comment by SvSven** [comment]
Instead of using the GoLive approach (which can be seen here: https://github.com/equinor/energyvision/commit/a4b68849fffd1c6fbc460d6c85302bb6dd95c3d9) we decided to go another route and copy/modify the i18n publish function from the document-internationalization plugin, see: https://github.com/equinor/energyvision/commit/d299b78b8d15460c3257aadd04a465854dd9bbff)

Most of the code is unchanged, with the only changes being that we add a confirmation dialog for the document types `news` and `localNews`.

I'm not sure if this is a sustainable way of doing it since updates to Sanity or the plugin could be missed/break things; but since most of the code is unchanged it _should_ be easy enough to adapt if they update the publish function in the future. Important part is that it works for now.

**Comment by SvSven** [comment]
@meols The confirmation dialog when publishing news and local news should be in place again now - it works the same as before (we were able to fix the issue we had), so nothing "new".

**Comment by meols** [comment]
Great @SvSven :clap: - thanks! This is very reassuring for us :smile:
